### ISSUE TITLE
footer-sociallinks not visible on iOS 14.6

### ISSUE THREAD

**Issue by inselgrafik** [benjaminkott/bootstrap_package#1021]
# Bug Report

footer social links are not visible on iPhone or iPad, even not at the demo page www.bootstrap-package.com

## Steps to Reproduce

Just open the demo side on an iPhone

### Screenshots
![IMG_C130737B6B7F-1](https://user-images.githubusercontent.com/26580829/126130569-ec0c5e62-2bb9-48aa-805b-d07775ee1248.jpeg)

**Comment by olivermeckel** [comment]
Hi inselgrafik,
i can't reproduce the bug.
Tested on iPhone SE und iPhone 12 (iOS 14.6) with Chrome and Safari.
Looks like expected:

![IMG_0512](https://user-images.githubusercontent.com/9928953/126132734-a7c82037-ccb9-464c-b2bf-dabc9e8f5707.jpg)

**Comment by inselgrafik** [comment]
I found the problem, it was AdGuard – Social on my iPhone.
