### ISSUE TITLE
Where/how to define backend logo / backend login logo

### ISSUE THREAD

**Issue by klodeckl** [benjaminkott/bootstrap_package#1022]
As the title says I would like to know where/how to define the backend logo and backend login logo. I cannot find it in the documentation. Thanks!

**Comment by olivermeckel** [comment]
You can change/ this logos just in your TYPO3-Settings:
Admin-Tools -> Settings -> Extension Configuration (Configure extensions) -> backend (Tab)
There you can override the styling of the backend and login

**Comment by klodeckl** [comment]
Thanks. I already had that settings, but when installing bootstrap package it seems the extensions overrides the settings set before.

**Comment by olivermeckel** [comment]
Thats right, Bootstrap Package "prefills" these settings.
You can find this in: bootstrap_package/Classes/Service/BrandingService.php

**Comment by klodeckl** [comment]
Maybe it would be better if bootstrap_package checks if the values are already set before it prefills them.
