### ISSUE TITLE
Frame around mp4 in Bootstrap V12.0.0

### ISSUE THREAD

**Issue by LMFC-Krisi** [benjaminkott/bootstrap_package#1040]
Yesterday I install the new Version 12.0.0 of Bootstrap Package. My System ist Typo3 10.4.19. Now i have Problems with mp4 Videos because on the right side ist missing the frame around the Video so the Video is going out of the Screen and some of the Video ist cut off. You can have a look at our site https://test.lmfc.de/webcam/zeitraffervideos
On the Live System with Bootstrap 11.0.3 we have no Problems. Look https://www.lmfc.de/webcam/zeitraffervideos
The Element is a Tab Element, but other Videos which are inserted as Text and Media have the same Problem.
Best Regards Michael
![Screenshot Webcam](https://user-images.githubusercontent.com/88950563/129462194-c677e384-1512-47c7-b401-ef623f0a0cf0.jpg)

**Comment by benjaminkott** [comment]
@LMFC-Krisi hey, thx for the report - missed that for the bootstrap 5 upgrade - added compact now. Changes will be included in the next release.

**Comment by LMFC-Krisi** [comment]
Thank you very much for the fast completion. Great Job.
