### ISSUE TITLE
Bootstrap V 12.0.0 Upgrade Wizard not running

### ISSUE THREAD

**Issue by LMFC-Krisi** [benjaminkott/bootstrap_package#1041]
# Bug Report
After installing Bootstrap 12.0.0 the Upgrade Wizard of Typo3 (10.4.19) is not running. The Wizard hang and in the background comes an error. When I close the Wizard window i see the following Error. I have check of Broken Extensions but all is ok.
Best Regards Michael
![Screenshot 2021-08-15 at 01-23-47 New LMFC  TYPO3 CMS 10 4 19](https://user-images.githubusercontent.com/88950563/129462585-37cc9b7d-0b6f-4377-a7d5-be163ed98dbf.png)
![Screenshot 2021-08-15 at 01-24-25 New LMFC  TYPO3 CMS 10 4 19](https://user-images.githubusercontent.com/88950563/129462586-3b185136-1027-4966-a88c-747de0d74ea7.png)
![Screenshot 2021-08-15 at 01-24-47 New LMFC  TYPO3 CMS 10 4 19](https://user-images.githubusercontent.com/88950563/129462587-470e8241-95f9-4ad2-8754-2f120d798aa0.png)
![Screenshot 2021-08-15 at 01-25-06 New LMFC  TYPO3 CMS 10 4 19](https://user-images.githubusercontent.com/88950563/129462588-97228d9e-179d-4f55-b737-119d71718685.png)
![Screenshot 2021-08-15 at 01-25-24 New LMFC  TYPO3 CMS 10 4 19](https://user-images.githubusercontent.com/88950563/129462589-a6fc1c12-9d1a-4488-90f9-843312ce868c.png)

**Comment by gilbertsoft** [comment]
@LMFC-Krisi Thanks for your report. Is it a composer or legacy install. In case of composer which version of `doctrine/dbal` do you have installed?

**Comment by LMFC-Krisi** [comment]
Hello
It is a legacy Install without composer.

**Comment by benjaminkott** [comment]
@LMFC-Krisi hey, thx for the report and sorry for the inconvenience. We pushed a patch that should resolve the issue.

**Comment by LMFC-Krisi** [comment]
Thank you very much for the fast completion. Great Job.
