### ISSUE TITLE
Exception when using IconSet from Glyphicons or IconsIcons and TYPO3 is installed in a subdirectory

### ISSUE THREAD

**Issue by AlexanderWKoenig** [benjaminkott/bootstrap_package#1042]
Hi.
on my development system the typo3 installtion is based in a subdirectory e.g. /mywebsite/
When selecting a Icon form IconsIcons or Glyphicons in the page settings an Exception occurs when rendering the frontend:

```
Oops, an error occurred!
Folder "/mywebsite/typo3conf/ext/bootstrap_package/Resources/Public/Images/Icons/Glyphicons/list-alt.svg/" does not exist.
```

When using `$src = $this->getSrc();` in
https://github.com/benjaminkott/bootstrap_package/blob/e687172a155d5b0286bcee1aada29ea6a94b2960/Classes/Icons/SvgIcon.php#L50 everything works for me.

Can you please look into this one?

**Comment by gilbertsoft** [comment]
@AlexanderWKoenig Thanks for your report. Can you please provide information about your installation and used versions...

**Comment by AlexanderWKoenig** [comment]
Sure:
TYPO3 Version	10.4.19
Webserver	Apache/2.4.38 (Raspbian)
PHP Version	7.3.29-1~deb10u1
Database (Default)	MySQL 5.5.5-10.3.29-MariaDB-0+deb10u1
Application Context	Development/pi
Composer mode	Enabled
Operating System	Linux 5.10.52-v7l+
Bootstrap Package	12.0.0

**Comment by benjaminkott** [comment]
@AlexanderWKoenig can you please provide the full stacktrace?

**Comment by benjaminkott** [comment]
I am still not sure what's going on without stack trace, but I tried your suggested solution and it "works on my machine" also.
