### ISSUE TITLE
Carousel don't start play pictures automatically

### ISSUE THREAD

**Issue by LMFC-Krisi** [benjaminkott/bootstrap_package#1049]
# Bug Report

## System
Typo3-10.4.19, legacy installation, Bootstrap Package 12.0.1

## Description
When i call my Website e.g https://test.lmfc.de the carousel open with the first picture but after the intervall of 500ms it don't play the other pictures. I wait for a long time but nothing happens. One click to the arrow left or right that starts playing normally. 
Regards Michael

**Comment by gilbertsoft** [comment]
Thanks! It's reproducable at https://www.bootstrap-package.com/content-examples/interactive/carousel

**Comment by gilbertsoft** [comment]
This is a change introduced by TWB 5 so I do not consider this as bug. There are some new options see https://getbootstrap.com/docs/5.1/components/carousel/#options.

I will add some of the new options to the carousel configuration so the user is able to change the behaviour.

**Comment by LMFC-Krisi** [comment]
Thanks for your helpfull information an for your efforts to add some of the new features in next Version.

**Comment by gilbertsoft** [comment]
For the moment I've fixed the issue without adding new options. There were some missing pieces in the Fullscreen and Small carousel.
