### ISSUE TITLE
Color Secondary 2 has white text on light yellow bg

### ISSUE THREAD

**Issue by linawolf** [benjaminkott/bootstrap_package#1057]
# Bug Report
After Updating from bootstrap package 11.0 to 12.0.0-dev the introduction package has 
white text on yellow background. The text was black before, see screenshots

## Prerequisites

* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package)
  to see if your bug or enhancement is already reported?

## Description

[A clear and concise description of what the bug is.]

## Steps to Reproduce

You can reproduce it by using the introduction version from this PR: 
https://github.com/FriendsOfTYPO3/introduction/pull/41

### Expected behavior

black text on yellow background

### Actual behavior

white text on yellow background

### Screenshots

![FrontendBP11](https://user-images.githubusercontent.com/48202465/129883928-717818b4-1286-4461-8008-6ea9b37d070f.png)
![FrontendBP12](https://user-images.githubusercontent.com/48202465/129883932-a1351d0e-9814-4f9f-a8bb-fb2431318ba0.png)

## Versions
After Updating from bootstrap package 11.0 to 12.0.0-dev, TYPO3 dev-master

**Comment by gilbertsoft** [comment]
@linawolf did you run the Upgrade Wizard after the upgrade? And I would suggest choosing dark and not secondary to keep the former appeareance. Also keep in mind v12 is a major release with breaking changes so you can't just update but have to make some minor changes maybe. The secondary color is changed in your template so you also have to make sure the font color matches or adapt it accordely.

So far I can not see a bug here.

**Comment by gilbertsoft** [comment]
Now I see another thing in the middle, thought you were talking about the carousel at the top. Will check what's missing here...

**Comment by gilbertsoft** [comment]
@linawolf please check https://github.com/benjaminkott/bootstrap_package/pull/1007

**Comment by gilbertsoft** [comment]
After an update from 11 to 12.0.x-dev and running the upgrade wizards I get these settings in the carousel which is what we like to have:
![grafik](https://user-images.githubusercontent.com/25326036/129903030-882583b4-ee3d-4c91-b391-1810049ba83c.png)
![grafik](https://user-images.githubusercontent.com/25326036/129903086-6bc532e9-fe87-4bab-85f5-2c39a705dfd2.png)
