### ISSUE TITLE
SVG ViewHelper not found after upgrade from 11.0.3 to 12.0.1

### ISSUE THREAD

**Issue by interojengel** [benjaminkott/bootstrap_package#1065]
# Bug Report

## Description

After upgrading from 11.0.3 to 12.0.1 SVG images are not rendered anymore, instead the ugly "Oops" appears in the browser. I have attached a stacktrace.
Backend renders the SVG just fine.

## Steps to Reproduce

1. Include SVG image in website

### Expected behavior

See SVG in browser

### Actual behavior

Browser only shows Typo3's Oops

### Screenshots

[svg_typo3_bootstrap_error.log](https://github.com/benjaminkott/bootstrap_package/files/7017226/svg_typo3_bootstrap_error.log)

## Versions

bootstrap-package 12.0.1
Typo3 10.4.20

**Comment by gilbertsoft** [comment]
Thanks for your report @interojengel ! I'm currently not able to reproduce the issue. Maybe you still use the removed ViewHelper in your Sitepackage? See also https://github.com/benjaminkott/bootstrap_package/commit/34a9680b

**Comment by interojengel** [comment]
Thanks a lot for the hint, that was the issue!
