### ISSUE TITLE
No color declaration teritary and quaternary for buttons in bootstrap 5 

### ISSUE THREAD

**Issue by MikeToelle** [benjaminkott/bootstrap_package#1066]
There is no color declaration in $theme-colors for teritary and quaternary.

See file _variables.scss in Scss/bootstrap5

$theme-colors: (
    'primary':                      $primary,
    'secondary':                    $secondary,
    'success':                      $success,
    'info':                         $info,
    'warning':                      $warning,
    'danger':                       $danger,
    'default':                      $default,
    'lighter':                      $lighter,
    'light':                        $light,
    'dark':                         $dark,
    'darker':                       $darker,
) !default;

**Comment by gilbertsoft** [comment]
Thanks for reporting!
