### ISSUE TITLE
header of CTypes container_... is always shown in frontend

### ISSUE THREAD

**Issue by peerlight** [benjaminkott/bootstrap_package#1079]
# Bug Report

## Prerequisites

* [ x] Can you reproduce the problem on TYPO3 v10.4 LTS
* [ not checked] Can you reproduce the problem on TYPO3 v11.3
* [x ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package)
  to see if your bug or enhancement is already reported?

## Description

"[header_layout]" can not be set for CTypes container_.... Therefor header is always diplayed in frontend as check "!=100" in Header/All fails. Not sure if it is an issue of bootstrap_package or container extension

## Steps to Reproduce

1. add CE with a CType container_... -> field header_layout is not there
2. add text to header 
3. save and view in frontend

### Expected behavior

no header because backend field is labelled " Name (in der Webseite nicht sichtbar)[header]"

### Actual behavior

frontend shows header 

## Versions

TYPO3 10.4.20
bootstrap_package 12.1.0-dev
container 1.3.1

**Comment by benjaminkott** [comment]
@peerlight you are right, fixed it - probably missed that it´s not intended by default that a header will be shown - thx for pointing this out.
