### ISSUE TITLE
Changing headline from H3 to H1 in detail view

### ISSUE THREAD

**Issue by danaron** [benjaminkott/bootstrap_package#1083]
Hi,
for SEO reasons I like to habe the first headling in the detail view to be a h1.

At the moment it is like this:

```
<div class="header">
<h3 itemprop="headline">Headline</h3>
</div>
```
Wolud like to change it to:

```
<div class="header">
<h1 itemprop="headline">Headline</h1>
</div>
```
How can I do that the way that I can update the extension an the change is still here?
Thanks for your help.
Best regards
Dan

PS: may be this would be good to change over all?

**Comment by benjaminkott** [comment]
Hey, not sure what `detail view` you have, we currently don´t set `itemprop` attributes.
If you have suggestions on how to improve BP in that area please go ahead, we can adjust the templates.

On content elements you can just select the `H` variant you want.
![image](https://user-images.githubusercontent.com/3243119/133760805-102bc80f-7efc-47b0-af9e-12e3a8fca263.png)

**Comment by danaron** [comment]
OK, Thank you @benjaminkott 👍
