### ISSUE TITLE
Wrong image cropping for xl screens

### ISSUE THREAD

**Issue by buepro** [benjaminkott/bootstrap_package#1088]
# Bug Report

## Prerequisites

* [x] Can you reproduce the problem on TYPO3 v10.4 LTS
* [x] Can you reproduce the problem on TYPO3 v11.3
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package)
  to see if your bug or enhancement is already reported?

## Description

Since no cropping definition exists for xl screens the default image dimension is used to render the image. The user expects the image dimension to be the same for xl and xxl (default) screens.

## Steps to Reproduce

1. Create an image content element and apply the same cropping dimensions to all screen sizes. Chose dimensions that significantly differ from the original image dimension.
2. The rendered image sizes correspond to the defined copping dimension except for the xl screen where the original image dimension is used.

### Expected behavior

The renderen image dimensions should be as defined fot the content element. Default cropping dimension should be applied to xl and xxl screens.

### Actual behavior

The image dimensions for xl screens are as the original image dimension.

## Versions

bk2k/bootstrap-package: 0c8e4a2e (dev-master)

**Comment by brrrrrrrt** [comment]
just tested your fix with 12.0.4 works great!

before:
![Bildschirmfoto von 2021-11-23 18-32-20](https://user-images.githubusercontent.com/4489013/143078346-a5d98696-5750-4d0e-84ef-e1b85f1f4396.png)
![Bildschirmfoto von 2021-11-23 18-32-41](https://user-images.githubusercontent.com/4489013/143078363-92c0e313-c991-416e-8984-2887b21d6759.png)
![Bildschirmfoto von 2021-11-23 18-33-10](https://user-images.githubusercontent.com/4489013/143078373-55ed2c69-8911-4c90-9967-955a7d07cd94.png)

after applying your changes:
![Bildschirmfoto von 2021-11-23 18-52-30](https://user-images.githubusercontent.com/4489013/143078404-1c5549d8-8651-45f7-81e8-15d7b913ccd0.png)
![Bildschirmfoto von 2021-11-23 18-52-44](https://user-images.githubusercontent.com/4489013/143078430-f02821af-788e-4257-9b2c-f846f735bee9.png)
![Bildschirmfoto von 2021-11-23 18-52-59](https://user-images.githubusercontent.com/4489013/143078453-7bb99822-6c19-4f32-aeb0-a60a63304657.png)

looks great!

**Comment by benjaminkott** [comment]
@buepro thx for the report and the patch - stumbled across the issue also but decided to add the missing crop variant instead of adjusting the template
