### ISSUE TITLE
Global SCSS variable $border-color is polluted by card-component

### ISSUE THREAD

**Issue by Moongazer** [benjaminkott/bootstrap_package#1093]
The default Bootstrap 5 definition of `$border-color` is `$gray-300`. Using this variable in a custom SCSS file always resulted in a red border color which hex-value wasn't defined anywhere (thus it must have been calculated and overwritten somewhere).

Finally found the issue in file `Public/Scss/components/card/_cardpanel.scss` line 103, where the "global" variable is overwritten by `map-get($settings, 'border-color')`. I recommend to rename such temporary variables with a prefix like `tmp-` (also in other/similar routines), just to be sure. This fixes it:
```
@each $name, $settings in $cardpanel-variants {
    $tmp-header-background: map-get($settings, 'header-background');
    $tmp-header-color: map-get($settings, 'header-color');
    $tmp-border-color: map-get($settings, 'border-color');
    .card-panel-#{$name} {
        @if ($tmp-header-background) {
            --cardpanel-header-background: #{$tmp-header-background};
        }
        @if ($tmp-header-color) {
            --cardpanel-header-color: #{$tmp-header-color};
        }
        @if ($tmp-border-color) {
            --cardpanel-border-color: #{$tmp-border-color};
        }
    }
}
```
BP v12.0.2 using Bootstrap 5
TYPO3 v10.4.21

**Comment by benjaminkott** [comment]
Oh, I see, it's not scoped - dang it! I used your solution and pushed a patch, thx for the good explanation was easy to follow and understand the issue.

https://github.com/benjaminkott/bootstrap_package/commit/127c3afc83b37eaded278c4a39038a3883566647

**Comment by Moongazer** [comment]
Thanks for your amazing work, glad if I can help. Btw: I see the same issue in the following files as well, because `$link-color` and `$link-hover-color` are also "global" variables:
- `Public/Scss/components/card/_carousel.scss` line 130+
- `Public/Scss/components/card/_frame.scss` line 321+

That's all I think.

**Comment by benjaminkott** [comment]
thx, added also a patch for that https://github.com/benjaminkott/bootstrap_package/commit/0eccc6af30c325dda6f035c0416fc6fd252a5264
