### ISSUE TITLE
libxml_disable_entity_loader is deprecated since PHP 8

### ISSUE THREAD

**Issue by MaikBeckmann** [benjaminkott/bootstrap_package#1104]
When trying out the typo3/cms-introduction package I countered following error message

    PHP Runtime Deprecation Notice: Function libxml_disable_entity_loader() is deprecated in /home/maik/Projekte/typo3-composermode/intro-site/public/typo3conf/ext/bootstrap_package/Classes/Utility/SvgUtility.php line 58 

PHP 8 has deprecated libxml_disable_entity_loader, since it is no longer needed with the minimum libxml version required by PHP 8. See https://www.php.net/manual/de/function.libxml-disable-entity-loader.php

## Steps to Reproduce

1. $ composer create-project typo3/cms-base-distribution:^11 foo
2. configure installation as ususal (FIRST_INSTALL etc.)
3. $ composer require require typo3/cms-introduction
4. $ ./vendor/bin/typo3cms extension:setup
5. look at frontend

## Versions
 - bk2k/bootstrap-package               12.0.3 
 - typo3/cms-introduction                4.4.1 
 - typo3/cms-core                             v11.5.2

**Comment by gilbertsoft** [comment]
@MaikBeckmann thx for your report. Please check the assinged PR and let me know if it works for you.

**Comment by MaikBeckmann** [comment]
@gilbertsoft it does fix the issue.  Thank you
