### ISSUE TITLE
PHP 8: Missing array key "fixAttrib" causes exception when visiting /customize

### ISSUE THREAD

**Issue by MaikBeckmann** [benjaminkott/bootstrap_package#1106]
Using PHP 8, installing and setting up the typo3/cms-introduction package, clicking the "customize" nav-link shows the following error message

    (1/1) #1476107295 TYPO3\CMS\Core\Error\Exception

    PHP Warning: Undefined array key "fixAttrib" in /home/maik/Projekte/typo3-composermode/intro-site/public/typo3/sysext/core/Classes/Html/HtmlParser.php line 916

## Steps to reproduce
1.  $ composer create-project typo3/cms-base-distribution:^11 foo
2.  configure installation as ususal (FIRST_INSTALL etc.)
3.  $ composer require require typo3/cms-introduction
4.  $ ./vendor/bin/typo3cms extension:setup
5.  visit /customize in browser

## A wild fix that probably isn't one

Looking at the error message and doing some grepping leads to the file

    bootstrap_package/Configuration/TypoScript/ContentElement/Helper/ParseFunc.typoscript

There deleting the lines 81 to 83

    tags.ul.fixAttrib.class {
        default = list-normal
    }
fixes the issue.  Ofc it might break something else. I don't know.  I haven't written a single line of Typoscript yet, lol.  But I hope this info helps figuring this out

## Versions
*  php 8.0.12
*  bk2k/bootstrap-package 12.0.3
*  typo3/cms-introduction 4.4.1
*  typo3/cms-core v11.5.2

## Edit
It works with php version 7.4.25

**Comment by MaikBeckmann** [comment]
Visiting /content-examples/text/rich-text causes the same issue.  However, deleting the lines 81 to 83 in ParseFunc.typoscript doesn't work around the issue this time.  A very similar error appears with the missing array key being "1." instead of "fixAttrib".

**Comment by gilbertsoft** [comment]
This looks more like a core bug, will have a detailed look later...

**Comment by MaikBeckmann** [comment]
> This looks more like a core bug, will have a detailed look later...

I just figured out that it works with PHP 7. It most likely is some bit in the core that hasn't been adjusted to PHP 8, yet.

**Comment by andreasfernandez** [comment]
Can you please check whether this issue is solved with the current master? This could be related to [this merged bugfix](https://github.com/TYPO3/typo3/commit/22702bd6fc334a91b53e4e01ddcfc5ce6d1958be).

**Comment by MaikBeckmann** [comment]
@andreasfernandez Hello Andreas.   I can confirm that it fixes the issue I've reported here. 

Here the steps I've taken
 1. clone typo3 github repo
 2. composer install
 2. FIRST_INSTALL with nginx, php-fpm and SQLite
 3. composer require typo3/cms-introduction
 4. locally patched  typo3conf/ext/bootstrap_package/Classes/Utility/SvgUtility.php, see #1104 
 5. activated introduction extension
 6. navigated to /customize as well as /content-examples/text/rich-text

My thanks to Francois Suter for patching this.  Thank you Andreas of poking me to check again.
 
Related links
 - https://forge.typo3.org/issues/95738
