### ISSUE TITLE
container class missing?

### ISSUE THREAD

**Issue by klodeckl** [benjaminkott/bootstrap_package#1107]
Why is in section Main of themplate Default, Simple and None the content not wrapped in 
`<div class="container">…</div>`
?

Or what is the intention to get the content elements wrapped?

**Comment by gilbertsoft** [comment]
If we would add the container class our no frame would not longer work.

What exactly is your issue @klodeckl ?

**Comment by klodeckl** [comment]
I’m not sure about the „workflow“ to get a content element wrapped in a container. At the demo page at https://www.bootstrap-package.com/ I have seen the class frame-container-default but I have no idea how to get that class into the source code.

**Comment by klodeckl** [comment]
Could you please tell me how to get that class?

**Comment by olivermeckel** [comment]
I don't know exactly what you mean by that?
You can change the class in each content element -> Appearance -> Frame
Default adds the class "frame-container-default". this is equivalent to "container".

**Comment by klodeckl** [comment]
Thank you for the hint. I was using an old template.
