### ISSUE TITLE
Additional content element

### ISSUE THREAD

**Issue by chequille** [benjaminkott/bootstrap_package#1111]
Hi Benjamin,
using the extension since a long time and I am almost happy with it.

Now, I have new project using Typo3 Version 10 and of course your extension.
As well I am using your sitebuilder to have an own extension installed based on bootstrap_package.

So far everything is fine and working. I coud add additional page layouts and it looks pretty good.

Now, I wanted to add some additional content elements within my extension.

Unfortunately, this did not work.  I made everything similar to how it is done in bootstrap_package but the additional content element is not there.

If I make the chances directly in the bootstrap_package, the new content element is there.

First question: is it possible to add new content elements within the sitebuilder extension?
Second question: If it is possible, is there any documention how to do it?

I could do it directly in bootstrap_package but I wanted to do it in the sitebuilder extension.

An idea?
Best regards,
Chequille

**Comment by gilbertsoft** [comment]
Hi @chequille , modifying a third party extension is always a bad idea as you will loose all your changes on updates. Using the Sitepackage or another extension is recommended. Here you can find more information about creating content elements https://docs.typo3.org/m/typo3/reference-coreapi/10.4/en-us/ApiOverview/ContentElements/AddingYourOwnContentElements.html#register-the-content-element

**Comment by chequille** [comment]
Hello @gilbertsoft,
thank you for the answer.
Yes that is exactly what I would like to do. I already have a sitepackage and I also managed to add more page templates, unfortunately it doesn't work with an additional content element. Somewhere I have probably forgotten something. As a template I did it like in the bootstrap_package.
I look at it again exactly step by step, somehow it should work.
You do not have maybe a sitepackage as an example, so I could orient myself on it?

Regards,
Chequille

**Comment by chequille** [comment]
Hi @gilbertsoft,

found the problem: it was simply a type mismatch in a directory name. I wrote ContentElement instead of ContentElements

Sometimes you just have to talk to someone to take a closer look afterwards and then you often find the mistake.
Greetings and have a nice weekend
Chequille

**Comment by gilbertsoft** [comment]
Glad you finally got it working @chequille , gonna close your issue.

**Comment by rowild** [comment]
@chequille Have you checked the "mask" extension? Très fantastique for adding individual CEs!
