### ISSUE TITLE
Text & Images, image size too small

### ISSUE THREAD

**Issue by Marx1st** [benjaminkott/bootstrap_package#1116]
# Support

TYPO3 10.4.21 and bootstrap-package 11.0.3

## Description

Images in "Text & Images" are always rendered/loades with a very low resolution, though the div is 1100 pixels wide, the picture is only 530 pixels wide: `<img loading="lazy" src="/fileadmin/_processed_/0/d/csm_pic_BAS_aussen-05_4c7fb80c56.jpg" intrinsicsize="530x177" title="" alt="" width="530" height="177">
`
Why is this like that? How can I change this?

**Comment by benjaminkott** [comment]
Please check if you have set the columns to 1.
