### ISSUE TITLE
TYPO3 Exception 1476107295

### ISSUE THREAD

**Issue by aktivde** [benjaminkott/bootstrap_package#1120]
After installing the theme as described in _README.rst_ I get this error after refreshing. Does anyone know how to solve this issue?

```
(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: file_get_contents(/var/www/www.domain.de/typo3temp/assets/css/theme_8e08e07f53f2a16d8cf38841fcc7c50a0e5669d2.css): failed to open stream: No such file or directory in /var/www/www.domain.de/typo3_src-10.4.21/typo3/sysext/core/Classes/Resource/ResourceCompressor.php line 284
```

I'm using Typo3 10.4.21 and bootstrap package 12.0.4

**Comment by aktivde** [comment]
issue is solved: conflicts with other plugins.

**Comment by gilbertsoft** [comment]
@aktivde was the conflict from a public extension? Or related to a configuration?

**Comment by aktivde** [comment]
Bootstrap package was installed on a multi domain typo3 instance with lots of plugins. I'm not the administrator myself so I don't know what exactly conflicted, but we decided to setup the website seperately. Now everything works fine.
