### ISSUE TITLE
Update from 11 to 12 crashes my site to acces denied

### ISSUE THREAD

**Issue by amr-webdesign** [benjaminkott/bootstrap_package#1123]
# Bug Report

## Prerequisites

* [x] Can you reproduce the problem on TYPO3 v10.4 LTS
* [ ] Can you reproduce the problem on TYPO3 v11.3
* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package)
  to see if your bug or enhancement is already reported?

## Description

[A clear and concise description of what the bug is.]

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior

[What you expected to happen]

### Actual behavior

[What actually happened]

### Screenshots

[If applicable, add screenshots to help explain your problem.]

## Versions

You can get this information from executing `composer show` at the command line
if your TYPO3 installation is composer based, otherwise the version number will
be shown in the extension manager.

**Comment by amr-webdesign** [comment]
Using 10.4  with BP 11.03 at update to 12 the site crash with acces denied - not possible to reach ext_manager or anything in the backend.
using sitepackage builder theme  for BP10 depends = bootstrap_package 10.0.0-12.9.99
Only deleting BP Package and install old makes the site run again

**Comment by gilbertsoft** [comment]
You should check your logs to get more information. The Sitepackage needs some smaller changes like an adaption of the inlcude path in the theme.scss.

**Comment by sebdavid** [comment]
I'm facing the same problem (Typo3 10.4 + BP 11.0.2).
I have nothing in my logs, but this might be because I'm using a docker container.

If some changes have to be done, is there a migration guide to upgrade BP from 11 to 12 ? Or is there a list of the changes we should apply ?

**Comment by amr-webdesign** [comment]
I don't know what ever ist the ground to give a theme or extention porgramming  a  :(die)  function so that it is not possible to check errors by TYPO3  system debbugging, sorry that ist crazy!

**Comment by Jaykju** [comment]
I just had exactly the same problem. 
Despite the claims bootstrap_package 12 is definitely not compatible with all typo3 10 versions.

The TYPO3 constant was introduced somewhere along the way during an 10.4.x release. I could not exactly identify which one, but updating to a later 10.4 release fixes the problem.
