### ISSUE TITLE
Deactivate dropdown menu

### ISSUE THREAD

**Issue by aktivde** [benjaminkott/bootstrap_package#1124]
Is there a way setting up the navbar without displaying any submenu entries and then only displaying them in the sidebar? I used display:none but that doesn't work properly for mobile.

**Comment by gilbertsoft** [comment]
You can reconfigure the MenuProcessor in your TypoScript setup to get less levels generated:

```
page.10.dataProcessing.10.levels = 1
```

**Comment by aktivde** [comment]
Works perfectly, thanks!
