### ISSUE TITLE
WHy is less compiler removed?

### ISSUE THREAD

**Issue by chequille** [benjaminkott/bootstrap_package#1130]
I jut want to aks why you removed the less compiler?
I have to change all my styling and this is a lot of work.

Is there a chanc to enable it again?

**Comment by gilbertsoft** [comment]
No, Bootstrap has removed LESS support with v4 so it does not make sense to have it longer.

**Comment by benjaminkott** [comment]
@chequille it´s been removed but you can add it to your site package and register it as a workaround if you still need it.

**Comment by chequille** [comment]
@benjaminkott hi, thanks for this info.
I made the workaround currently by using bootstrap_package version 11.0.3 where it is still included.
Adding it to my sitepackage is a good idea and I will have a look how to do it. I guees will find this in the bootstrap_package.
Currently I just wanted to have my site running with Typo3 Version 10, as I am on Typo3 Version 8 which is pretty old and not supported anymore. 
Best regards,
Chequille
