### ISSUE TITLE
Last element of 6 inside of ctype container 3_colums has wrong position

### ISSUE THREAD

**Issue by web2date** [benjaminkott/bootstrap_package#1136]
# Support

## Description

I use a container element with 3 columns to show 6 "Text and Icon" elements (Position Icon top). The last Text and Icon element is positioned too low in nearly all breakpoints. Thinking of a wrong padding of "lastChild". But I cannot find a solution...
Any idea how to solve the problem? Thanks in advance.

TYPO3 10.4.23 / BP 12.0.4

## Screenshots

![image](https://user-images.githubusercontent.com/8898397/149329598-abfb5e33-d35c-47be-92a6-a3342eaca2f7.png)

**Comment by gilbertsoft** [comment]
The issues comes imho from the rwo above where you have 3 lines, others have 2 lines only.

**Comment by web2date** [comment]
Sorry - longer text causes the problem...
