### ISSUE TITLE
Accordion and Tabs with content elements

### ISSUE THREAD

**Issue by McKoy61** [benjaminkott/bootstrap_package#1142]
Accordions and tabs are great for structuring content, but the possibilities are very limited with just text and images. Even more flexibility would be achieved if you could place any content elements in accordions and tabs, such as file links for download areas and much more.

**Comment by benjaminkott** [comment]
The out of box support for this extends the scope of the bootstrap_package, if you want to build something in that direction please consider using the container extension.
