### ISSUE TITLE
Bootstrap Package logo at the top

### ISSUE THREAD

**Issue by Vito974** [benjaminkott/bootstrap_package#1143]
Hi Bejamin,
I do not want to have the "Typo3 Bootstrap Package" image shown before my site.
How can i disable this. Some website tell me to use 
page.preloader.enable = 0
but it didn't work.

Please let me know.

**Comment by gilbertsoft** [comment]
Hey @Vito974 

Looks you have messed up something if `page.preloader.enable = 0` does not work for you and another logo than yours is shown. But hard to say without more information. Also check the Sitepackage Builder at https://www.sitepackagebuilder.com/.

**Comment by Vito974** [comment]
Thank you for your reply. I use Typo3 11.5.4 and bootstrap_package 12.0.4. I don't know what I have misconfigured, what information do you need?

**Comment by Vito974** [comment]
Hello, I have solved my problem. In the Bootsrap_package folder I copied the file 
/var/www/html/typo3/typo3conf/ext/bootstrap_package/Resources/Private/Layouts/Page/Default.html
into the folder: /var/www/html/typo3/typo3conf/ext/mysitepackage/Resources/Private//Layouts/Page/Default.html

and I put in comment the html code which concerns the navigation bar.

**Comment by benjaminkott** [comment]
Preloader was dropped.
