### ISSUE TITLE
xlarge image variant without cropVariant generates <picture><source>

### ISSUE THREAD

**Issue by mueller-sebastian** [benjaminkott/bootstrap_package#1153]
Hi, thank you for bootstrap_package!
I am using:
TYPO3 11.5.8
bootstrap_package: 12.0.5

Problem: In FE there is an image for xlarge which can not be manipulated in the backend.

`responsiveimages.variants` configure a variant "xlarge" (got into repo in Boostrap 5 commits),
```
xlarge {
    breakpoint = 1200
    width = 1100
}
```
Therefore in frontend a <source> in the <picture> element is created for this variant.
In Backend there is no cropping possibility for xlarge, so it is not possible to set the whished cropping area for this variant.

![image](https://user-images.githubusercontent.com/20316366/159861499-0c6ca353-2a58-4e6b-bbfa-2532c3303bf8.png)
![image](https://user-images.githubusercontent.com/20316366/159861971-f738627a-7794-4b07-95b9-af1d59d6969a.png)

Im not sure if there should be a xlarge cropping possibility in BE or if the variant should not be present in FE.
Or maybe I am missing something.

**Comment by benjaminkott** [comment]
resolved with https://github.com/benjaminkott/bootstrap_package/commit/1dbb1ab2497bcd86d9eabbfeaac534662f77627a
