### ISSUE TITLE
Reduce number of processed files

### ISSUE THREAD

**Issue by LMFC-Krisi** [benjaminkott/bootstrap_package#1156]
Hello together
I have too many processed Files in my Website processed Folder and i think it is Time to reduce something. I think at the present time it is not to be needed to make processed files for small or extra small images because this Display sizes that are sizes of the past from mobile devices. So i think we dont need it. 
Regards Michael

**Comment by benjaminkott** [comment]
@LMFC-Krisi i am not sure why smaller images are a thing of the past. If you want to optimize for all kinds of devices you also have to deliver the assets for that devices. If you think that you don't need it for your project you can adjust the processing and remove variants you think you don't need. **Anyway i think you should not.**

https://github.com/benjaminkott/bootstrap_package/blob/master/Configuration/TypoScript/ContentElement/Helper/ContentElement.typoscript#L200-L225
