### ISSUE TITLE
Error trying Typo3 Upgrade Wizard

### ISSUE THREAD

**Issue by LMFC-Krisi** [benjaminkott/bootstrap_package#1162]
# Bug Report

* [x] Can you reproduce the problem on TYPO3 v10.4 LTS
 I have 10.4.27 and Bootstrap 12.0.5

## Description

If i try the Typo3 Upgrade Wizard i get the following Error.

![grafik](https://user-images.githubusercontent.com/88950563/166121922-793b4aea-2f97-49d4-ac86-0bb0c7990622.png)
![grafik](https://user-images.githubusercontent.com/88950563/166121964-2823f738-cf80-4572-a3a4-e26b1367bc26.png)
![grafik](https://user-images.githubusercontent.com/88950563/166121984-34d89934-1b69-48e9-919e-09ac33d50381.png)
![grafik](https://user-images.githubusercontent.com/88950563/166121998-724134e7-b443-43ed-918e-203299346f8a.png)
![grafik](https://user-images.githubusercontent.com/88950563/166122004-4563c059-7531-43a6-9839-8c1fc26006c2.png)

**Comment by gilbertsoft** [comment]
Are you sure about your Bootstrap Package version?

**Comment by LMFC-Krisi** [comment]
Hello Gilbert
I check it again and it is really 12.0.5 
You Guess right, it ist not a composer based installation.
![grafik](https://user-images.githubusercontent.com/88950563/166122308-b167bcd3-7568-4eff-adc1-a50bcb19edea.png)

**Comment by gilbertsoft** [comment]
Oh, somehow the last release is missing so your version is fine.

**Comment by LMFC-Krisi** [comment]
Thanks for your fast Reply. Then i will wait for a new Version. Nice Weekend.
Best Regards Michael

**Comment by mbaer558** [comment]
TYPO3 V 10.4.28 / bootstrap_package 12.0.4
Installation: Classic Way

After update bootstrap_package from V. 12.0.4 to V. 12.0.5 and running the Upgrade Wizard I got the same error message as LMFC_Krisi.
Checking the admin log Details:
Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to undefined method Doctrine\DBAL\Driver\Mysqli\MysqliStatement::fetchOne() | Error thrown in file /home/codeagc/www/codeag.ch/typo-104/htdocs/typo3conf/ext/bootstrap_package/Classes/Updates/AccordionContentElementUpdate.php in line 74. Requested URL: https://www.codeag.ch/typo3/install.php?install[controller]=upgrade&install[context]=backend&install[action]=upgradeWizardsList

Going back to bootstrap_package V. 12.0.4: no more error messages.

Best Regards, Michael

**Comment by RudStar** [comment]
Here as well: 
TYPO3 10.4.30 & bootstrap_package 12.0.5.
Installation: via Backend

Also affects the "Report" module and "Flush cache".

**Comment by SchoolGuy** [comment]
I also have the same problem today. Is there any workaround or any chance we can resolve this?

**Comment by benjaminkott** [comment]
resolved with https://github.com/benjaminkott/bootstrap_package/commit/d43358be5cb8ace2c5e3239504836c988bb61155
