### ISSUE TITLE
Include Static and Basis templates

### ISSUE THREAD

**Issue by webian** [benjaminkott/bootstrap_package#117]
Hi @benjaminkott,

I just enabled EXT:index_search and found that it didn't index pages cause config.index_enable = 0.

I did expect index_enable to be 1 cause file **EXT:bootstrap_package/Configuration/TypoScript/setup.txt** set it to 1 but then I found that file **EXT:indexed_search/ext_typoscript_setup.txt** set it to 0 and this typoscript is included after the one of EXT:bootstrap_package.

I know that there are many way to re-set that index_enable to 1 but I'm wondering if this is the expected behavior and what's the best way to re-set it.

One way is to set it to 1 in field Setup of the root template but I don't like it cause I prefer to use files to handle configurations. Then I could include an external file in the Setup field.
Another way is to set "Include before all static templates if root flag is set" but I never needed to change it from the "Default (include before if root flag is set)" so it sounds a little hard even if more logical.

Do you have any suggestion to give me to handle this little problem in the best way?
Thank you!

**Comment by ikkez** [comment]
@cedricziel 
I have the same issue, but using the sysext `felogin`. I haven't found a way yet to overwrite the template setting for it withing my ts files, as it seems it get overwritten afterwards somehow. Putting the same config into a template record in the backend works instead. Adding felogin to the dependencies of the bp did not solve the load-chain-issue.

**Comment by benjaminkott** [comment]
@all closing this issue since this is not a problem of the bootstrap_package
