### ISSUE TITLE
PHP Runtime Deprecation Notice: Automatic conversion of false to array is deprecated in ContainerContextProcessor.php

### ISSUE THREAD

**Issue by Patta** [benjaminkott/bootstrap_package#1170]
# Bug Report

## Prerequisites

* [ ] Can you reproduce the problem on TYPO3 v10.4 LTS
* [x] Can you reproduce the problem on TYPO3 v11.3
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package)
  to see if your bug or enhancement is already reported?

## Description

On a page with a container content element.

Core: Exception handler (WEB):  Uncaught TYPO3 Exception: #1476107295: PHP Runtime Deprecation Notice:  Automatic conversion of false to array is deprecated in  /.../private/typo3conf/ext/bootstrap_package/Classes/DataProcessing/ContainerContextProcessor.php  line 73 \| TYPO3\CMS\Core\Error\Exception thrown in file  /.../private/typo3/sysext/core/Classes/Error/ErrorHandler.php  in line 137. Requested URL: ...

### Expected behavior

No uncaught TYPO3 Exception

### Actual behavior

Uncaught TYPO3 Exception

## Versions

PHP 8.1.5
TYPO3 11.5.10
bk2k/bootstrap-package 12.0.5

**Comment by TB-effective** [comment]
We are running into this issue in a current project. Is there a timeline for when the fix will be merged into some release? (Just so we know whether we should wait, or patch locally.)
