### ISSUE TITLE
Deliver WebP images with WebP Extension

### ISSUE THREAD

**Issue by sheydin** [benjaminkott/bootstrap_package#1173]
Dear community,

I am trying to deliver WebP images with the WebP extension (https://github.com/plan2net/webp/blob/master/README.md). The .webp images are being generated on the server, but no delivery to the browser. They all remain of content type content-type: image/jpeg and content-type: image/png. 

Without bootstrap_package the webp images are delivered correctly. What is it in bootstrap_package that blocks it from happening and how to unblock it?

Thank you for your help.

**Comment by benjaminkott** [comment]
We have no problem running the extension with the bootstrap_package. IIRC the default config needed adjustments:

```        
    'webp' => [
        'convert_all' => '1',
        'converter' => 'Plan2net\\Webp\\Converter\\MagickConverter',
        'mime_types' => 'image/jpeg,image/png,image/gif',
        'parameters' => 'image/jpeg::-quality 85 -define webp:lossless=false|image/png::-quality 75 -define webp:lossless=false|image/gif::-quality 85 -define webp:lossless=false',
        'silent' => '0',
    ],
```

See https://typo3.com/ as working example.
