### ISSUE TITLE
Question: Whats happening here?

### ISSUE THREAD

**Issue by LMFC-Krisi** [benjaminkott/bootstrap_package#1176]
I am worried about reading this Github about Bootstrap Package. 7 weeks ago i wrote some issue about Upgrade wizard and there is no solution. Also there is a disagreement between actual version in TER (12.0.5) and here in Github (actual Release is 12.0.4). And other people write also issues but there are only little actions in the last weeks. perhaps the developer are busy then give us a few information. Then we will wait about news. I think the user love your Bootstrap Package  and you make a great Job but let us now how is the future.
Best Regards Michael

**Comment by benjaminkott** [comment]
Next round of releases will happen around TYPO3 12.1 still some issues to be resolved in core around. Until then all patches should be applied to their release branches.
