### ISSUE TITLE
Change breakpoint for hamburger menu ...

### ISSUE THREAD

**Issue by tegarbe** [benjaminkott/bootstrap_package#1179]
Hi there!

Is it possible to set the breakpoint itself, from when the menu changes to the hamburger menu? Currently it is set to 992px. However, for some projects I need 1024px or 1280px or the hamburger menu throughout.

**Comment by benjaminkott** [comment]
SCSS:
```scss
$grid-float-breakpoint: 1024px;
```

TypoScript Constant
```
plugin.bootstrap_package.settings.scss.grid-float-breakpoint = 1024px
```

**Comment by seirerman** [comment]
That setting is missing from the constants editor. Could you add it in Configuration/Bootstrap5/constants.typoscript?
