### ISSUE TITLE
Ajax Error 

### ISSUE THREAD

**Issue by Hogego** [benjaminkott/bootstrap_package#1193]
# Support

## Description

After upgrading the package from 11.0.3 to 12.0.5 I get an Error-Message in the Upgrade Wizard:

(1/1) Error
Call to undefined method Doctrine\DBAL\Driver\Mysqli\MysqliStatement::fetchOne()

in ../typo3conf/ext/bootstrap_package/Classes/Updates/AccordionContentElementUpdate.php line 74

and some more 

Could someone help me please?
Thanks a lot

**Comment by benjaminkott** [comment]
The upgrade wizards have been reworked. This should be resolved with the latest changes:
https://github.com/benjaminkott/bootstrap_package/commit/8268cd2b07cd9a83b4d4f942af817b4b53b7d322

Patch is available in master and BP_12-0
[master](https://github.com/benjaminkott/bootstrap_package/tree/master)
[BP_12-0](https://github.com/benjaminkott/bootstrap_package/tree/BP_12-0)
