### ISSUE TITLE
Timeline not working

### ISSUE THREAD

**Issue by tenkraD** [benjaminkott/bootstrap_package#1197]
# Bug Report

## Prerequisites

* [ ] Can you reproduce the problem on TYPO3 v10.4 LTS
* [x] Can you reproduce the problem on TYPO3 v11.5.8
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package)
  to see if your bug or enhancement is already reported?

## Description

Timeline entry's can not be set.

## Steps to Reproduce

1. put content element timeline on a page
2. set title and select a date for that timeline
3. create timeline entry

### Expected behavior

create one/multiple timeline entry

### Actual behavior

timeline entry can not be created, an undefined Error is Displayed.
An Error is logged:   

Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1476107295: 
PHP Warning: Undefined array key "date" in /typo3conf/ext/bootstrap_package/Classes/Userfuncs/Tca.php line 19 | 
TYPO3\CMS\Core\Error\Exception thrown in file /typo3_src-11.5.8/typo3/sysext/core/Classes/Error/ErrorHandler.php in line 137. 
Requested URL: /typo3/ajax/record/inline/create?token=--AnonymizedToken--

### Screenshots

![image](https://user-images.githubusercontent.com/48378976/190383992-6b0ac243-443c-44c1-ae89-7d181735c734.png)
![image](https://user-images.githubusercontent.com/48378976/190383069-aa8093b3-8096-4247-8b84-31dc90b94b25.png)

## Versions

Typo3 11.5.8
Bootstrap package 12.0.5

**Comment by tenkraD** [comment]
Bug is closed, it's all working.. I dont know what the problem was but the error is gone and i can create timelines now.  i didnt change or update anything.

**Comment by kimchristiansen** [comment]
I have the exact same error. On my local environment the error is not thrown, but on the production server.
Did you make any setting so that the error was fixed?
Clearing cache and deleting temp data didn't help either.

TYPO3 11.5.19
PHP 8.1.10
bootstrap-package: 12.0.5

**Comment by kimchristiansen** [comment]
It seems that the DB on the Prod system handles the datetime type differently. I have overwritten the label_userFunc with a custom UserFunc where date is queried. This is also already fixed in the master branch.
