### ISSUE TITLE
TYPO3 ver. 6.2.1 with Bootstrap 3 - using blank image in SRC tag

### ISSUE THREAD

**Issue by tpbillund** [benjaminkott/bootstrap_package#12]
I have a little problem showing my image aften some clearing of baseURL. Then my images is blank and it using another image as the SRC, why do it do that ?

See right site main section in this link http://wnf.dk/golf-vinrejser.html

The funny part is that its only the image I have added to the page with Page -> Add Record.

So images added to background in CSS and TS is working fine.

This is an ex. on a image, where all the files is right, but not the SRC. 

<img class="lazyload" alt="" 
data-small="fileadmin/introduction/images/WNF/rejsegarantifonden.JPG"
data-medium="fileadmin/introduction/images/WNF/rejsegarantifonden.JPG" 
data-large="fileadmin/introduction/images/WNF/rejsegarantifonden.JPG"
data-bigger="fileadmin/introduction/images/WNF/rejsegarantifonden.JPG"
data-src="fileadmin/introduction/images/WNF/rejsegarantifonden.JPG" 
src="typo3conf/ext/bootstrap_package/Resources/Public/Images/blank.gif">

**Comment by inaffect-ag** [comment]
I had to change my template from "CSS Styled Content Typo3 v6.1" to the Standard "CSS Styled Content" After that my images will be shown.

**Comment by lampela** [comment]
Hi Benjamin, I have this lazyload problem with fresh installations: the normal images don't sometimes show until the browser is resized. I usually just disable the bootstrap package image rendering, but it would be nice to know what causes this.
