### ISSUE TITLE
Animated SVG Images won't load in Firefox 102.0.1

### ISSUE THREAD

**Issue by handitosb** [benjaminkott/bootstrap_package#1200]
# Bug Report

## Prerequisites

* [ ] Can you reproduce the problem on TYPO3 v10.4 LTS
* [x] Can you reproduce the problem on TYPO3 v11.3
* [x]  Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package)

  to see if your bug or enhancement is already reported?

## Description

Animated svg image as media won't be displayed in Firefox. It only shows black image. The problem only happens in Firefox (It works fine in Chrome or Safari).

## Steps to Reproduce

1. Insert Content Element "Image" or "Text Media".
2. In tab Media choose and upload an animated svg image.
3. Show image in frontend

### Expected behavior

Animated svg image should be displayed without a problem.

### Actual behavior

Image won't load as it supposed to be.

### Screenshots

In Chrome or Safari:
![Bildschirmfoto 2022-09-19 um 22 47 06](https://user-images.githubusercontent.com/97729966/191113541-b96d05e2-451f-4c00-bfb0-a0626eb3158d.png)

In Firefox:
![Bildschirmfoto 2022-09-19 um 22 46 51](https://user-images.githubusercontent.com/97729966/191113577-53c84932-61b3-4d29-b4d3-3f7af3356ebc.png)

## Image Asset

Animated svg image:
![mail](https://user-images.githubusercontent.com/97729966/191200369-756f353e-90be-4c6d-9b0e-5d9760c6ea7b.svg)

## Versions

Bootstrap Package v12.0.5
TYPO3 v11.5.16

**Comment by Xippo** [comment]
i dont think boostrap package cause the problem, i hade a similiar issuse in one project recently and it was related to
https://forge.typo3.org/issues/95312
