### ISSUE TITLE
Accordion Paragraph's Color Bug with Orange and Other Darker Colored Backgrounds

### ISSUE THREAD

**Issue by handitosb** [benjaminkott/bootstrap_package#1211]
# Bug Report

## Prerequisites

* [ ] Can you reproduce the problem on TYPO3 v10.4 LTS
* [x] Can you reproduce the problem on TYPO3 v11.3
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package)
  to see if your bug or enhancement is already reported?

## Description

Bug appeared when orange or other darker as background is chosen.
This happened because accordion's text color inherits from the text color of the frame. (Dark colored background has white colored text, light colored background has black colored text, etc.)
Paragraphs color changes automatically into white instead of its default color.
This causes the paragraph's color to be changed manually in SCSS.

## Steps to Reproduce

1. Create content element "Accordion"
2. Choose background color orange or dark. Here, we used background color orange for example.
3. Add some paragraph text 

### Expected behavior

Font color at the accordion content item should be remain by its default color. Here, for example black.

### Actual behavior

Text color changes automatically into white.

### Screenshots

With orange colored background:
![Accordion background orange](https://user-images.githubusercontent.com/97729966/195282995-9884e42a-c745-4923-a6d5-09006e315193.png)

Without colored background (default):
<img width="1138" alt="Accordion background white" src="https://user-images.githubusercontent.com/97729966/195283165-7cb26e73-74bd-407c-a64b-ada91d75a35f.png">

## Versions

TYPO3 v11.5.16

**Comment by benjaminkott** [comment]
Seems to be resolved. In latest versions
