### ISSUE TITLE
Deactivate bootstrap_package on multisite

### ISSUE THREAD

**Issue by csguevara** [benjaminkott/bootstrap_package#1221]
Hello!
is there a way to limit the bootstrap package to only one page tree in a multisite installation?

One site with Boostrap_Package and the other without the package? The package overwrites my backend layouts and content elements from an older installation website.  

Thanks a lot

**Comment by olivermeckel** [comment]
I had nearly the same question some time ago.
You can adjust values and defaults through TCEFORM and TCAdefaults, but TCA is always instance-wide.

https://github.com/benjaminkott/bootstrap_package/issues/1099

**Comment by csguevara** [comment]
Thank you very much for the quick help. I will try ;-)
