### ISSUE TITLE
Update to 12.0.5 -> change in how "Text and images" display images in columns

### ISSUE THREAD

**Issue by JeromeBusnel** [benjaminkott/bootstrap_package#1222]
Hi,
First a big thank for providing bootstrap-package, helped a lot to configure the website of the small ngo I'm working for.
Sorry to ask for help but when I updated recently to bootstrap-package 12.0.5 and to typo3 10.4.32, the display of images and descriptions of "text and images" content elements became half the width it was before, whatever the image position chosen.
![update - image size](https://user-images.githubusercontent.com/65243300/205672010-4b04956c-b5c4-490a-b991-6598e3c4f9ab.jpg)
On the upper part of the picture, how it became after updating, and on the bottom how it was before.
If I create a new content element with the same picture, the display is normal (that's what I did on the bottom part of the picture).
But if I simply modify the old content element (even removing and adding the picture back), the display remains half the width. The same if I copy and paste the old content element.
It lets me think the problem comes from how the "old" content elements are defined, since new content elements work well.
Has anyone an idea of how to fix this?
Thanks, Jerome

**Comment by JeromeBusnel** [comment]
I thinf I found a clue : if I understand rightly, the content element "Text and images" was by default set on 2 columns for images display.
If you had added only one image, the display was done as if the parameter was set on 1 column.
Since the update, it appears it does not take this parameter into account, and two columns are displayed even if 1 column is empty.

**Comment by benjaminkott** [comment]
@JeromeBusnel i am sorry that you have have to adapt this, but we needed to get the template more strict and remove some magic happened before. I sadly could not provide a good migration for this, since it could do more harm than help depends on the site.
