### ISSUE TITLE
SCSS transition function

### ISSUE THREAD

**Issue by SventB** [benjaminkott/bootstrap_package#1224]
* [ ] Can you reproduce the problem on TYPO3 v10.4 LTS
* [X] Can you reproduce the problem on TYPO3 v11.3
* [X] Did you perform a cursory search to see if your bug or enhancement is already reported?

## Description

There's a transition function provided by Bootstrap, you should use this.

Example:

```DIFF
- transition: border-color .15s ease-in-out, box-shadow .15s ease-in-out;
+ @include transition(border-color .15s ease-in-out, box-shadow .15s ease-in-out);
```

Wherever possible, use default transition:

```SCSS
$transition-base:             all .2s ease-in-out !default;
```

**Comment by benjaminkott** [comment]
should be resolved with https://github.com/benjaminkott/bootstrap_package/commit/c00384ff0fa5ba615aed04c4a5fb2827766c8a56#diff-75bd25d162f29b233fbb123f5fd5374e841f39a19b0b6df3c8d124e9442eda97
