### ISSUE TITLE
Please add "customData" argument to FrameViewHelper.php

### ISSUE THREAD

**Issue by NyanNyanMiau** [benjaminkott/bootstrap_package#1226]
Hello,

after updateing to v13 our custom fields wont exists  while rendering the contentelements templates.

Can you please add a variable to allow passing other data then our own selection to the template.

// i.e. just add "customData"
FrameViewHelper.php -> initializeArguments()
  $this->registerArgument('customData', 'array', '', false, []);

edit:
just noticed cant i override the viewhelper template?
upd:
your constant path is not the same used in setup for Extension Overrides

Thank you

**Comment by benjaminkott** [comment]
that one should resolve your issue https://github.com/benjaminkott/bootstrap_package/commit/51be71975fc838c83c3934ffcb58915a83864abc

let me know if it´s not suitable.
