### ISSUE TITLE
Image size in 2 column page layout too small

### ISSUE THREAD

**Issue by SventB** [benjaminkott/bootstrap_package#1228]
# Bug Report

## Prerequisites

* [ ] Can you reproduce the problem on TYPO3 v10.4 LTS
* [X] Can you reproduce the problem on TYPO3 v11.3
* [X] Did you perform a cursory search to see if your bug or enhancement is already reported?

## Description

Image size in 2 column page layout is too small:

![imagesize](https://user-images.githubusercontent.com/2690489/206872290-ea67d2f5-dec8-427b-b2a1-cf8a70797339.PNG)

This is a screenshot from unmodified TYPO3 system.

I tried to check what the problem is, but image width calculation is really complicated :/ With ViewHelper using TypoScript settings "multiplier" and "gutters" and "correction"... Respect ;)

**Comment by SventB** [comment]
@benjaminkott 
Please, have a look at this. I spend some hours coding and testing ;)
If you have questions, lets make a call with screen sharing.

And, please backport it to version 12.x of EXT:bootstrap_package :)

**Comment by benjaminkott** [comment]
@SventB thx for pointing this out.

Here are my observations so far:
The issue seems to be purely related to the backend layouts with sub navigation.
All other seem to be fine on the first glance, will have a closer look today at this.

I´ve created test examples to verify the issue.
https://www.bootstrap-package.com/issue/1228

**Comment by benjaminkott** [comment]
Resolved with:

https://github.com/benjaminkott/bootstrap_package/commit/55b4e93496e132ad8229c230cba1b557bcaffc11 [BUGFIX] Correct image scaling in thumbnail menus
https://github.com/benjaminkott/bootstrap_package/commit/4ffcea6a9acb4ea03c9627f06b977cc3cd7df39b [BUGFIX] Correct image scaling in card menus
https://github.com/benjaminkott/bootstrap_package/commit/fd3ba341803c45b236bf382beebcde0fe0af0e1c [BUGFIX] Correct image scaling in card groups
https://github.com/benjaminkott/bootstrap_package/commit/dcc08bb3c9d07c33aa8ef4635341c974f7512228 [BUGFIX] Correct image scaling in accordions
https://github.com/benjaminkott/bootstrap_package/commit/195f60cc90d5462c79b3ab2ac3711d330ecdab8b [BUGFIX] Correct image scaling in tabs
https://github.com/benjaminkott/bootstrap_package/commit/e852dc36dcc8959e05bfedb4cff463e1990f89ff [!!!][BUGFIX] Correct responsive image config for backend layouts (https://github.com/benjaminkott/bootstrap_package/pull/1232)
