### ISSUE TITLE
Partial BackgroundImage.html is missing and breaking frontend

### ISSUE THREAD

**Issue by nanna-dk** [benjaminkott/bootstrap_package#1233]
# Support

## Description

After upgrading BP 12 -> 13.0.0 on TYPO3 v.11.5.20 based on PHP 8.1.11 I get the following error in the frontend:
```
(1/1) #1225709595 TYPO3Fluid\Fluid\View\Exception\InvalidTemplateResourceException
The Fluid template files
....
bootstrap_package/Resources/Private/Partials/ContentElements/Frame/General/BackgroundImage.html could not be loaded.
```

## Screenshots

![bp_13](https://user-images.githubusercontent.com/14937325/207367478-b648b749-b79c-4c59-a7a7-3791ce021daf.jpg)

What do I have to do to fix this?

**Comment by nanna-dk** [comment]
Found some references in my constants which caused the problem.
Closing.

**Comment by benjaminkott** [comment]
@nanna-dk i am sorry, i somehow missed to mark this change as breaking.

The rendering was moved to a ViewHelper to ease the configuration within each content element.
https://github.com/benjaminkott/bootstrap_package/commit/6dc537d66cb6f1d93c1f482c3cef26e54a9348b8

Please adjust your custom configuration / template overwrite and adjust them accordingly.

**Comment by braukma** [comment]
I am facing the same problem, but sadly cannot follow your hints. Is there an example for what to change? Am I missing some entry in my constants.typoscript? Sorry for beeing a bit dumb. :-), but I feel lost.

**Comment by dasoe** [comment]
Dear all,

I just stumbled upon the same problem. Probably too late for [braukma](https://github.com/braukma) and [subnoodle](https://github.com/subnoodle), still I try to explain for people less deep in the subject:

The Partial  `bootstrap_package/Resources/Private/Layouts/ContentElements/Default.html` has changed. You have probably overwritten this file in your extension with some adjustments. So now your file is used, which tries to access a Partial (ContentElements/Frame/General/BackgroundImage) that does not exist any more.

To migrate, you will have to use the original file  `bootstrap_package/Resources/Private/Layouts/ContentElements/Default.html`, copy this to your extension and add your adjustments in this file anew.

have a good day!
oe
