### ISSUE TITLE
Blocking the link to the item id on another page of the site.

### ISSUE THREAD

**Issue by aksenovaa** [benjaminkott/bootstrap_package#1235]
# Bug Report

## Prerequisites
TYPO3 v11.5.21
bootstrap_package v13.0.1

## Description
A link to an element (id) of another page of the site is set on the site page. ( href="/page1#c1")

### Expected behavior
Clicking the link takes you to the specified element of another page.
### Actual behavior
Nothing happens ( in v13. In version 12 of the extension everything works

## Versions
bootstrap_package v13.0.1
Error in js file:
EXT:bootstrap_package/Resources/Public/JavaScript/Dist/bootstrap.smoothscroll.min.js
(bootstrap_package/Resources/Public/JavaScript/Src/bootstrap.smoothscroll.js
```
window.addEventListener('DOMContentLoaded', function () {

    /*
     * Smooth Sroll
     */
    const ankers = document.querySelectorAll('a[href*="#"]:not([href^="http"]):not([href$="#"])');
    ankers.forEach(function (anker) {
        anker.addEventListener('click', function (event) {
            event.preventDefault();
...
};
};
}

```
when remove  event.preventDefault(); all working fine

**Comment by benjaminkott** [comment]
resolved with https://github.com/benjaminkott/bootstrap_package/commit/1657d99c4a9a7c73c7192b039d5f7ea383e31232
