### ISSUE TITLE
Footer content section is visible if no content

### ISSUE THREAD

**Issue by Patta** [benjaminkott/bootstrap_package#1236]
# Bug Report

## Prerequisites

* [x] Can you reproduce the problem on TYPO3 v11.5
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package)
  to see if your bug or enhancement is already reported?

## Description

The footer content section is always added by default in some templates, also if no content is e.g. in colPos 10.
On mobile devices, the footer content section is visible if empty, due to flexbox styles.

## Steps to Reproduce

1. Setup site
2. Choose default backend layout
3. Leave the three column footer content section empty
4. Visit the page in frontend
5. Open dev tool inspector and change screen size to max 767px
6. The empty footer content section is visible if the screen size is smaller than 768px

### Expected behavior

If no content is e.g. in colPos 10, 11 and/or 12 or parent page (slide -1) do not show the footer content section.

### Actual behavior

On mobile devices, the footer content section is visible if empty, due to flexbox styles.

### Screenshots

![image](https://user-images.githubusercontent.com/2151127/208657519-6a732d4d-fd51-4a8f-b29f-fafa9b69d584.png)

## Versions

TYPO3 11.5.21
bootstrap_package 13.0.1

**Comment by benjaminkott** [comment]
i removed the vertical gap spacing, that should resolve the issue
