### ISSUE TITLE
Image to small for Carousel (smallest breakpoint)

### ISSUE THREAD

**Issue by blueamerican** [benjaminkott/bootstrap_package#1238]
TYPO3 11.5.21
bp 13.0.1

When using the content element carousel, as seen here:
https://www.bootstrap-package.com/content-examples/interactive/carousel

the image in the smallest breakpoint (mobile) is pixeling.

This is difficult to see.

The smallest image ist 374px, but the background-size ist cover, that means that the image is too small here.

### Expected behavior
The image does not pixel in the smallest breakpoint

### Actual behavior
The image pixels in the smallest breakpoint, see attached screen
![Unbenannt-4](https://user-images.githubusercontent.com/5647051/211251875-305963e3-b7a2-426c-8530-698ac74e4ef2.png)

**Comment by benjaminkott** [comment]
it´s configured to fit most devices. if you need to adjust the configuration please simply increase the size for your needs.

https://github.com/benjaminkott/bootstrap_package/blob/master/Configuration/TypoScript/ContentElement/Helper/ContentElement.typoscript#L199-L225
