### ISSUE TITLE
3-columns are wrong displayed

### ISSUE THREAD

**Issue by gustiaeppli** [benjaminkott/bootstrap_package#1239]
# Bug Report

## Prerequisites

* [ ] Can you reproduce the problem on TYPO3 v10.4 LTS
* [ ] Can you reproduce the problem on TYPO3 v11.3
* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package)
  to see if your bug or enhancement is already reported?
Yes : Columns are displayed one above the other, but not side by side #799

## Description
with 3 columns, the right column is displayed on the left

## Steps to Reproduce

1. Install only the Typo3 Core V12
2. Install bootstrap package 13.0.1

### Expected behavior
i expect the column to be displayed on the right

### Actual behavior
in the configuration on the right, the column on the left is displayed

[If applicable, add screenshots to help explain your problem.]
the same behavior can be seen on the current website
https://www.bootstrap-package.com/pages/3-columns

## Versions
Typo 3 Version 12.1.3
Bootstrape Package 13.0.1

**Comment by gustiaeppli** [comment]
the same issue is on https://www.bootstrap-package.com/pages/3-columns

**Comment by flemmome** [comment]
Hi,

I have the same behaviour with Typo3 Version 11.5.22. If I upgrade to bootstrap package 13.0.1, with 13.0.0 the columns are displayed correctly but for me there is another bug with my news extension then, so I will stay in Version 12.x.x for the moment.

**Comment by derseeli** [comment]
For me, this brought the solution. Can anyone confirm?

```
@media (min-width: 992px) {
  .backendlayout-3_columns .maincontent-wrap {
    order: 2;
    --section-gaps: 2;
    --section-colspan: 6;
  }
  .backendlayout-3_columns .subcontent-wrap {
    order: 3;
    --section-gaps: 2;
    --section-colspan: 3;
  }
}

```

**Comment by mediaessenz** [comment]
I can confirm your solution!

**Comment by flemmome** [comment]
Hello, where I have to place this code to check if this is working for me too?

**Comment by benjaminkott** [comment]
thx all, you are right i can validate your solution and pushed a patch
