### ISSUE TITLE
Photoswipe icons are missing when using composer installers v4

### ISSUE THREAD

**Issue by Patta** [benjaminkott/bootstrap_package#1244]
# Bug Report

## Prerequisites

* [ ] Can you reproduce the problem on TYPO3 v10.4 LTS
* [x] Can you reproduce the problem on TYPO3 v11.5
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package)
  to see if your bug or enhancement is already reported?

## Description

The relative paths to the photoswipe images default-skin.png and default-skin.svg are not resolved correctly when the new composer installers v4 are used. This results in missing icons in the image lightbox.

### Expected behavior

Photoswipe lightbox icons are visible.

### Actual behavior

Photoswipe lightbox icons are not visible.

### Screenshots

![image](https://user-images.githubusercontent.com/2151127/213689730-e937e63d-69d7-49ce-9e36-d4bb4108c693.png)

## Versions

TYPO3 11.5.22
bootstrap_package 13.0.1

**Comment by buepro** [comment]
What about setting the typoscript constant `plugin.bootstrap_package.settings.scss.pswp__assets-path = ../../Images/PhotoSwipe/`? In case you roll the theme in your site package add the resources as well there (copy `Resources/Public/Images/PhotoSwipe`). Mind the relative path from the theme file to the PhotoSwipe folder.

**Comment by benjaminkott** [comment]
resolved with https://github.com/benjaminkott/bootstrap_package/commit/2ab06cf6c551ab281be9e4889a1e16855f453d50
