### ISSUE TITLE
accordion image position wrong

### ISSUE THREAD

**Issue by chrcan** [benjaminkott/bootstrap_package#1249]
the image position in mediaorient is wrong.
Right = Left and Left = Right

TYPO3 v12.1.3 with PHP 8.1 and the BP 13.x is in use.

![Bildschirmfoto 2023-02-07 um 11 04 04](https://user-images.githubusercontent.com/53138963/217216620-ca101831-c21b-4e78-8a23-e5b0ef4a8508.jpg)
![Bildschirmfoto 2023-02-07 um 11 04 17](https://user-images.githubusercontent.com/53138963/217216650-634a049f-1ada-4b20-822f-ffc6724f412d.jpg)

**Comment by classic0815** [comment]
TYPO3 v12.4.0 with PHP 8.2 and the Bootstrap Package-13.0.2 in use.

1) Content Element / Type / Tab
Media position (Orientation) the image position is wrong. The position is reversed:     
If you choose the position for the photo on the left, then it is on the right and vice versa

The same mistake occurs:

2) Content Element / Type / Accordion
Media position (Orientation) the image position is wrong. The position is reversed:     
If you choose the position for the photo on the left, then it is on the right and vice versa
