### ISSUE TITLE
How to re-enable tags for RTE

### ISSUE THREAD

**Issue by derralf** [benjaminkott/bootstrap_package#125]
Hi,
I'm using bootstrap package 6.2.6 and need to re-enable h5 and h6 tags.
In my extension template i have overriden parts of the RTE config (copied original bs_p tag lists and and added mine), see code below.
Similar to your suggestion here: https://github.com/benjaminkott/bootstrap_package/issues/24
But is not working.
In RTE the Dropdown shows the h5 and h6 tags an i am able to apply them to the text but on save they are replaced by the p-tag (and strange: are then disappeared from the dropdown and will only show up again on browser refresh).
I tried and searched for hours and feel very dumb... please help...

Cheers,
Ralf

```
RTE.default.buttons {
    formatblock {
        removeItems = address, article, aside, div, header, footer, section, nav
        # im Original sind hier noch enthalten: h5, h6
    }
}
RTE.default.proc.allowTags (
    [....] , h5, h6, [....]
)
RTE.default.proc.allowTagsOutside (
    [....], h5, h6, [....]
)
RTE.default.proc.entryHTMLparser_db.allowTags < RTE.default.proc.allowTags
RTE.default.proc.exitHTMLparser_db.allowTags < RTE.default.proc.allowTags
RTE.default.FE < RTE.default

```

**Comment by derralf** [comment]
A little correction:
As I wrote i have a theme extension to extend bootstrap_package (own layouts/backend-layouts and other TSPPageTS, own less theme, and so on)
- when I include my RTE.ts-file in ext_localconf.php it's not working (maybe somehow gets overridden though included after the bootstrap_package ts files)
- when I include the same external RTE.ts-file in the tsconfig field in my root page it works as expected

I don't really understand why, but for the moment it works for me
Maybe someone can shed some light on this :)

For whom it may interest:
the above TS now looks like this (shorter, cleaner)
```
RTE.default.buttons.formatblock.removeItems := removeFromList(h5,h6)
RTE.default.proc.allowTags := addToList(h5,h6)
RTE.default.proc.allowTagsOutside := addToList(h5,h6)

RTE.default.proc ...
RTE.default.proc ...
RTE.default.FE ...
```

**Comment by benjaminkott** [comment]
@derralf sorry for the lack of feedback here on this issue.
This issue relates to RteHtmlArea taht we are no longer supporting, but - in never versions the rte configuration from the bootstrap_package can be disabled in the extension configuration. This was implemented to provide more flexibility and also give the freedom to use a custom configuration without conflicting with the bootstrap_package. RteHtmlArea was to be honest always pain in the a**, and we are really glad its gone for good and replaced with ckeditor.
