### ISSUE TITLE
Add BackendLayouts for the BackendLayout DataProvider in ext_localconf.php:29

### ISSUE THREAD

**Issue by bk-damian-slomian** [benjaminkott/bootstrap_package#1250]
![grafik](https://user-images.githubusercontent.com/82408053/217882156-04144947-639a-4f79-bea2-752385b51156.png)

// PageTS

// Add Content Elements
if (!(bool) $extensionConfiguration->get('bootstrap_package', 'disablePageTsContentElements')) {
    \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addPageTSConfig('<INCLUDE_TYPOSCRIPT: source="FILE:EXT:bootstrap_package/Configuration/TsConfig/Page/ContentElement/All.tsconfig">');
}

// Add BackendLayouts for the BackendLayout DataProvider
if (!(bool) $extensionConfiguration->get('bootstrap_package', '**disablePageTsContentElements**')) {
    \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addPageTSConfig('<INCLUDE_TYPOSCRIPT: source="FILE:EXT:bootstrap_package/Configuration/TsConfig/Page/Mod/WebLayout/BackendLayouts.tsconfig">');
}

**Comment by benjaminkott** [comment]
resolved with https://github.com/benjaminkott/bootstrap_package/commit/056c6f37b553ce73a3194f0a1ef80237d74c202a
