### ISSUE TITLE
Animation for sticky header fails if page reloads and scroll position is mid page

### ISSUE THREAD

**Issue by Patta** [benjaminkott/bootstrap_package#1251]
# Bug Report

## Prerequisites

* [x] Can you reproduce the problem on TYPO3 v11.5
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package)
  to see if your bug or enhancement is already reported?

## Description

With commit https://github.com/benjaminkott/bootstrap_package/commit/b3cdba77750ee95b708bc552c24f333294a97e83 the event listener DOMContentLoaded was added in bootstrap.stickyheader.js. But now, if a page is scrolled e.g. to mid page position and reloads or the page reloads and scrolls to an element, the animation hangs and the class "navbar-transition" is not added to sticky header.

## Steps to Reproduce

1. Setup site with default config
2. set "page.theme.navigation.style" to "default-transition"
3. visit page and scroll to the mid or end
4. reload the page
5. see the sticky header layout issue because of missing class

### Expected behavior

Proper styled navbar after transition if navigation style is "default-transition".

### Actual behavior

Navbar with missing background and other missing styles after transition if navigation style is "default-transition".

## Versions

TYPO3 11.5.24
bootstrap_package 13.0.1

**Comment by christophbee** [comment]
I can confirm the bug (same versions of TYPO3 + bootstrap_package)

**Comment by Patta** [comment]
resolved by #1362
