### ISSUE TITLE
bootstrap_package 12.0.0 (12.0.x) is not compatibe with typo3 v10.4 LTS (10.4.36)

### ISSUE THREAD

**Issue by gotu** [benjaminkott/bootstrap_package#1252]
bootstrap_package is calling undefined methods:

`Call to undefined method Doctrine\DBAL\Driver\Mysqli\MysqliStatement::fetchAllAssociative() | Error thrown in file bootstrap_package/Classes/Updates/AbstractUpdate.php`

`Call to undefined method Doctrine\DBAL\Driver\Mysqli\MysqliStatement::fetchOne() | Error thrown in file bootstrap_package/Classes/Updates/AccordionContentElementUpdate.php`

**Comment by oliverklee** [comment]
Probably a duplicate of #1234.

**Comment by benjaminkott** [comment]
resolved with https://github.com/benjaminkott/bootstrap_package/commit/d43358be5cb8ace2c5e3239504836c988bb61155
