### ISSUE TITLE
"layout" on "Appearance"-Tab can not be changed

### ISSUE THREAD

**Issue by Starraider** [benjaminkott/bootstrap_package#1253]
# Bug Report

## Prerequisites

* [x ] Can you reproduce the problem on TYPO3 v11.3
* [x ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package)
  to see if your bug or enhancement is already reported?

## Description

If you create your own layouts and register them in TCEFORM, you can select them under "layout" on the "Appearance" tab. But in the frontend only the CSS class "frame-layout-default" is generated, no matter which layout you have selected.
This is because in the file "Resources/Private/Layouts/ContentElements/Default.html" in line 25 the value "{data.frame_layout}" is passed to the ViewHelper. But the correct value would actually be "{data.layout}".
Unfortunately, correcting this leads to another error, because the value is passed as an integer (index of the selection), but the ViewHelper expects a string value. I use a workaround in which I pass "L{data.layout}" to the ViewHelper in the Fluid template. The additional "L" converts the integer value into a string value. But it would be better if the ViewHelper would expect an integer value.

## Steps to Reproduce

1. Create your own Layout with TCEFORM.tt_content.layout.altLabels.1 = Test
2. Choose your layout in the "Appearance" tab under "Layout" and save.

### Expected behavior

The generated CSS class should be "frame-layout-1", 

### Actual behavior

The generated CSS class is "frame-layout-default" which is wrong.

## Versions

- TYPO3: v11.5.24
- bootstrap_package: v13.0.1

**Comment by juergen1964** [comment]
Same behavior i can confirm by using the layout appearance tab with own layout options on the felogin plugin.

Looks like the
<bk2k:frame
...
        layout="{data.frame_layout}"
...
    >
in layouts/ContentElements/default.html  template not take the new value and shows always output: "frame-layout-default"

**Comment by juergen1964** [comment]
... sorry just saw you already got a workaround - i can confirm your workaround is working. i do it for now just like you did.
Thanks a lot!

**Comment by benjaminkott** [comment]
The field `layout` is not the same as `frame_layout`.  `layout` is not considered and only kept for custom implementations.
