### ISSUE TITLE
More mainavigation levels with v12.0.7

### ISSUE THREAD

**Issue by Tonyt8** [benjaminkott/bootstrap_package#1256]
Hello,

Bootstrap version 12.0.7
Typo3 11.5.25

I try to add more levels to main navigation. I would like to have four levels.

So far I have managed to get four levels, but the parent navigation links (for example in level-2) need two clicks to open.

It has taken days to get this far, but I am unable to figure out what to do to stop the need for a double click.

Can anyone help me with this?

Thanks.
Regards,
Tony
++++++++++++++++++++++++++++++++++++++++++++++++
**I have changed the set scritp to include four levels:**

page {
    10 = FLUIDTEMPLATE
    10 {
		dataProcessing {
            10 = TYPO3\CMS\Frontend\DataProcessing\MenuProcessor
            10 {
                levels = 4
            }
            20 = TYPO3\CMS\Frontend\DataProcessing\MenuProcessor
            20 {
               	levels = 4
			}
	    }
	}

**I use this file Main.html**

<f:section name="MainNavigation">
    <f:if condition="{menu}">
        <ul class="navbar-nav">
            <f:for each="{menu}" as="item">
                <f:if condition="{item.spacer}">
                    <f:then>
                        </ul>
                        <ul class="navbar-nav">
                    </f:then>
                    <f:else>
                        <li class="nav-item{f:if(condition: item.active, then:' active')}{f:if(condition: item.children, then:' dropdown dropdown-hover')}">
                            <a href="{item.link}" id="nav-item-{item.data.uid}" class="nav-link{f:if(condition: item.children, then:' dropdown-toggle')}"{f:if(condition: '{item.target}', then: ' target="{item.target}"')}{f:if(condition: '{item.target} == "_blank"', then: ' rel="noopener noreferrer"')} title="{item.title}"{f:if(condition: item.children, then:' aria-haspopup="true" aria-expanded="false"')}>
                                <f:if condition="{theme.navigation.icon.enable} && {item.icon}">
                                    <span class="nav-link-icon">
                                        <bk2k:icon icon="{item.icon}" width="{theme.navigation.icon.width}" height="{theme.navigation.icon.height}" />
                                    </span>
                                </f:if>
                                <span class="nav-link-text">{item.title}<f:if condition="{item.current}"> <span class="visually-hidden">(current)</span></f:if></span>
                            </a>

                            

                            <f:if condition="{item.children}">
                                 <ul class="level-2 dropdown-menu xxxx"  aria-labelledby="nav-item-{item.data.uid}" >
                                                                      
                                    <f:for each="{item.children}" as="child">
                                        <f:if condition="{child.spacer}">
                                            <f:then>
                                                <li class="dropdown-divider"></li>
                                            </f:then>
                                            <f:else>
                                                <li class="nav-item{f:if(condition: child.active, then:' active')}{f:if(condition: child.children, then:' dropdown dropdown-hover')}">
                                                     
                                                        <a href="{child.link}"  class="dropdown-item nav-link{f:if(condition: item.children, then:' dropdown-toggle')}"{f:if(condition: '{item.target}', then: ' target="{item.target}"')}{f:if(condition: '{item.target} == "_blank"', then: ' rel="noopener noreferrer"')} title="{item.title}"{f:if(condition: item.children, then:' aria-haspopup="true" aria-expanded="false"')}>
                                                               <f:if condition="{theme.navigation.dropdown.icon.enable} && {child.icon}">
                                                            <span class="dropdown-icon">
                                                                <bk2k:icon icon="{child.icon}" width="{theme.navigation.dropdown.icon.width}" height="{theme.navigation.dropdown.icon.height}" />
                                                            </span>
                                                        </f:if>
                                                        
                                                        <span class="dropdown-text">{child.title}<f:if condition="{child.current}"> <span class="sr-only">(current)</span></f:if></span>
                                                    </a>
                                                    
                                                    <f:if condition="{item.children}">
                                                        
                                                            <ul class="level-3 dropdown-menu {f:if(condition: child.children.active, then:' show')}" aria-labelledby="nav-item-{item.data.uid">
                                                            <f:for each="{child.children}" as="child">
                                                                <f:if condition="{child.spacer}">
                                                                    <f:then>
                                                                        <li class="dropdown-divider"></li>
                                                                    </f:then>
                                                                    <f:else>
                                                                        <li class="nav-item{f:if(condition: child.active, then:' active')}{f:if(condition: child.children, then:' dropdown dropdown-hover')}">
                                                                            
                                                                                <a href="{child.link}" id="nav-item-{child.data.uid}" class="nav-link{f:if(condition: child.children, then:' dropdown-toggle')}"{f:if(condition: child.target, then: ' target="{child.target}"')} title="{child.title}">
                                                                                <f:if condition="{theme.navigation.dropdown.icon.enable} && {child.icon}">
                                                                                    <span class="dropdown-icon">
                                                                                        <f:if condition="{child.icon.0.extension} === svg">
                                                                                            <f:then>
                                                                                                <bk2k:inlineSvg image="{child.icon.0}" width="{theme.navigation.dropdown.icon.width}" height="{theme.navigation.dropdown.icon.height}" />
                                                                                            </f:then>
                                                                                            <f:else>
                                                                                                <f:image image="{child.icon.0}" alt="{child.icon.0.alternative}" title="{child.icon.0.title}" width="{theme.navigation.dropdown.icon.width}" height="{theme.navigation.dropdown.icon.height}" />
                                                                                            </f:else>
                                                                                        </f:if>
                                                                                    </span>
                                                                                </f:if>
                                                                                <span class="dropdown-text">{child.title}<f:if condition="{child.current}"> <span class="sr-only">(current)</span></f:if></span>
                                                                            </a>
                                                                            
                                                    
                                                    <f:if condition="{item.children}">
                                                        
                                 
                                     <ul class="level-4 dropdown-menu aaa {f:if(condition: child.children.active, then:' show')}" aria-labelledby="nav-item-{item.data.uid}">
                                     <f:for each="{child.children}" as="child">
                                         <f:if condition="{child.spacer}">
                                             <f:then>
                                                 <li class="dropdown-divider"></li>
                                             </f:then>
                                             <f:else>
                                                 <li class="nav-item{f:if(condition: child.active, then:' active')}{f:if(condition: child.children, then:' dropdown dropdown-hover')}">
                                                     <a href="{child.link}" class="dropdown-item{f:if(condition: child.active, then:' active')}"{f:if(condition: child.target, then: ' target="{child.target}"')} title="{child.title}">
                                                         <f:if condition="{theme.navigation.dropdown.icon.enable} && {child.icon}">
                                                             <span class="dropdown-icon">
                                                                 <f:if condition="{child.icon.0.extension} === svg">
                                                                     <f:then>
                                                                         <bk2k:inlineSvg image="{child.icon.0}" width="{theme.navigation.dropdown.icon.width}" height="{theme.navigation.dropdown.icon.height}" />
                                                                     </f:then>
                                                                     <f:else>
                                                                         <f:image image="{child.icon.0}" alt="{child.icon.0.alternative}" title="{child.icon.0.title}" width="{theme.navigation.dropdown.icon.width}" height="{theme.navigation.dropdown.icon.height}" />
                                                                     </f:else>
                                                                 </f:if>
                                                             </span>
                                                         </f:if>
                                                         <span class="dropdown-text">{child.title}<f:if condition="{child.current}"> <span class="sr-only">(current)</span></f:if></span>
                                                     </a>
                                                 </li>
                                             </f:else>
                                         </f:if>
                                     </f:for>
                                 </ul>
                             </f:if>
                                                     <!-- 4 -- end>
                                                                        </li>
                                                                    </f:else>
                                                                </f:if>
                                                            </f:for>
                                                        </ul>
                                                    </f:if>                            
                                                    <!--3-- end>
                                                </li>
                                            </f:else>
                                        </f:if>
                                    </f:for>
                                </ul>
                            </f:if>
                        </li>
                    </f:else>
                </f:if>
            </f:for>
        </ul>
    </f:if>
</f:section>
`

**Comment by schrej-zz** [comment]
Hi,
I don't know how often it was requested to all more navigation levels into the standard bootstrap_package plugin.
I'm also failing, as all other hints I found are based on older bootstrap_package versions.
And still no reply after more than a month :-( 
BTW: @Tonyt8 I cannot even implement your solution, as some text is in coded brackets and some isn't.
Looks scrambled.

Thanks Joerg

**Comment by benjaminkott** [comment]
With the next release we will support also the 3. level out of the box. 
See https://www.bootstrap-package.com/ for a preview.

https://github.com/benjaminkott/bootstrap_package/commit/2775146d21660b1c09bbd9ab093672bfdad326bc

If you need more levels you can now more easy adjust the new dropdown template.

**Comment by Tonyt8** [comment]
Hi,

Great!

This is welcome news, thanks for adding another level.

Regards,
Tony
