### ISSUE TITLE
Image size in relation to tt_content.frame_class field

### ISSUE THREAD

**Issue by createdwithlove** [benjaminkott/bootstrap_package#1258]
I created some different designs for the textpic/media elements and now trying to set different values for  `lib.contentElement.settings.responsiveimages.variants.default.width` in relation to which `frame_class` is selected.

This is the snippet that I think should do the work, but fails:

```
lib.contentElement.settings.responsiveimages {
    variants {
        default {
            width = TEXT
            width.value.cObject = CASE
            width.value.cObject {
                key.data = FIELD:frame_class
                default = TEXT
                default.value = 1032
                fullwidth = TEXT
                fullwidth.value = 1920
            }
        }
    }
}
```

Looking at the output of a fluid debug on `{settings.responsiveimages.variants}` there obviously seems to be a problem, because the CASE object isn't calculated at all.

![Bildschirm­foto 2023-03-20 um 08 55 16](https://user-images.githubusercontent.com/1146811/226280545-1160e5ca-e8af-44fc-95c7-12e7c4b4fd52.jpg)

Maybe the problem isn't really caused by bootstrap_package - but I've used similar code in other projects without any hassle.

**Comment by benjaminkott** [comment]
we are using settings here, that are more or less a simple array. it does not support cObjects.
you will need to adjust the settings somehow different.

see render variants:
https://github.com/benjaminkott/bootstrap_package/blob/master/Resources/Private/Templates/ContentElements/TextmediaCenteredRight.html#L6
