### ISSUE TITLE
A11y Code Sprint Berlin: Success Criterion 9.1.4.4 - Remove to-top button

### ISSUE THREAD

**Issue by SarahEdding** [benjaminkott/bootstrap_package#1279]
# Feature Request

## Description

All content has to be visible and accessible at 200% zoom, even in a small view port. The to-top button overlaps with page content. 

## Solution

It would be easiest to remove the button. As the main navigation is sticky, it ist available at all times, anyway. 

## Alternative

The button can be added back in at a later date, if we make sure it does not overlap with page content. 

## context, links and screenshots

![image](https://github.com/benjaminkott/bootstrap_package/assets/132338236/6ef834c5-0ed5-4a7e-b768-1dab636dca0e)

**Comment by benjaminkott** [comment]
@SarahEdding the navigation is not sticky by default, in this case, it´s configured to be that way.

Navigation Configuration:
https://github.com/benjaminkott/bootstrap_package/blob/master/Configuration/TypoScript/constants.typoscript#L63

I also think that dropping the feature is not an option, we need another solution if this is a problem.

**Comment by benjaminkott** [comment]
Please provide a new option, to enable/disable the functionality

**Comment by SarahEdding** [comment]
As discussed, I'm closing this issue; 
=> not critical for compliance after further examination
