### ISSUE TITLE
Carousel item: bodytext not configured as RTE for type "text and image"

### ISSUE THREAD

**Issue by derjig** [benjaminkott/bootstrap_package#128]
Just a minor issue: Unlike the bodytext field for the accordion item, the carousel's bodytext field is configured as a plain text area only. Unless there's a reason to behave differently i suggest changing the TCA config accordingly.

This affects (at least) version 6.2.8.

Thanks!

**Comment by benjaminkott** [comment]
@derjig the carousel bodytextfield is has no rte options because it could cause editors to produce invalid markup when linking the carousel items.
