### ISSUE TITLE
A11y Code Sprint Berlin: Success Criterion 9.1.4.4 - make 3rd level navigation available on mobile

### ISSUE THREAD

**Issue by SarahEdding** [benjaminkott/bootstrap_package#1280]
# Feature Request

## Description
All content has to be visible and accessible at 200% zoom, even in a small view port. Currently, pages at the third level are not available on small screens or with resized content because the subnavigation disappears on smaller screens or at high zoom.

## Solution
The main navigation for small view ports should have a third level added to it, so all pages can be accessed. 

## context, links and screenshots
To reproduce, open https://bitv-v12.live.typo3.cps.321.works/content-examples/media/text-and-images with small viewport an try to reach other pages on same level

**Comment by SarahEdding** [comment]
@oliverthiele is working on this

**Comment by benjaminkott** [comment]
done

**Comment by alexakressmann** [comment]
QA successful
