### ISSUE TITLE
A11y Code Sprint Berlin: Success Criterion 9.2.1.1 - make main navigation keyboard operable

### ISSUE THREAD

**Issue by SarahEdding** [benjaminkott/bootstrap_package#1283]
# Feature Request

## Description
Main navigation: Users without a mouse can not distinguish between a link and an expand-button that shows subpages. The main navigation should have separate buttons to expand subpages. These buttons should not share a click area with a link to a page. 

## Solution

Add expand button with icon and hidden text ("show subpages") to each navigation point with subpages, both for mobile an desktop navigations: 
https://www.w3.org/WAI/ARIA/apg/patterns/disclosure/examples/disclosure-navigation-hybrid/

**Comment by oliverthiele** [comment]
I'm working on it.

**Comment by oliverthiele** [comment]
I have a new menu in my fork (Remote: git@github.com:oliverthiele/bootstrap_package.git) in the branch feature/new-navigation-variant. I will work on it the next days. Todo: Move drop-down arrows to the corresponding li tag instead of outputting it in a separate li tag.

**Comment by benjaminkott** [comment]
done

**Comment by alexakressmann** [comment]
QA successful
