### ISSUE TITLE
A11y Code Sprint Berlin: Success Criterion 9.2.4.1 - provide functional skip link as first focusable element on any page

### ISSUE THREAD

**Issue by SarahEdding** [benjaminkott/bootstrap_package#1287]
# Feature Request

## Description

Users without a mouse must be provided with the option to jump directly into main content. This makes keyboard navigation easier because users do not have to tab through the entire main navigation after every page load. 

## Solution

Skip links should: 

- be the first focusable element on any given page
- on activation shift focus to first focusable element in target
- be easily perceivable when they receive keyboard focus

## context, links and screenshots
For reference, see https://ptxlablausitz.de/

**Comment by linawolf** [comment]
@SarahEdding please assign me

**Comment by SarahEdding** [comment]
still ToDo: 
after skip link is used, keyboard focus must be on first focusable element of target, e.g. 
after using "skip to main content", keyboard focus for next tab must be on first interactive element in `<main>`
