### ISSUE TITLE
A11y Code Sprint Berlin: Success Criterion 9.1.4.3 - make all Text colour contrast compliant

### ISSUE THREAD

**Issue by SarahEdding** [benjaminkott/bootstrap_package#1290]
# Feature Request

## Description

All Text must have at least a colour contrast of 4.5:1 with any part of its background. 

## Solution

- background colour for footer should be #016CB6 or darker.
- Headings in timeline should be #016CB6 or darker. 
- [panel](https://bitv-v12.live.typo3.cps.321.works/content-examples/text/panel): set new background colours for headings: 
- - replace #0288D1F with #016CB6 (blue)
- - replace #0E8A16 with #0E8A16 (green)
-  - replace #319fc0 with #0480A9 (blue-grey)
- - replace #c9302c with #D93D33 
- Background colour for footer should be #016CB6 or darker.
- Text in main navigation and subnavigation should be black for optimum contrast in an indispensable point of access.
- text in cookie consent dialog must be black on grey. 

Colour choices [offered in RTE](https://bitv-v12.live.typo3.cps.321.works/content-examples/text/rich-text) to editors must meet minimum contrast. None of the current colours meet the standard.
Recommendation: choose new set of colours for both text and call-to-action (button-style) links.

## Alternative

We should consider going through the entire colour palette and making sure that minimum contrasts are met.

## Pages relevant for QA

https://bitv-v12.live.typo3.cps.321.works/content-examples/text/panel
https://bitv-v12.live.typo3.cps.321.works/content-examples/text/rich-text

**Comment by SarahEdding** [comment]
Main Navigation, Cookie dialog, Timeline, Panels and Footer now have sufficient contrast. 
Subnav-links are in #7F7F7F ? that's only 4:1, it must be 4.5:1 
@alexakressmann could you double check this before we get back to Benji? :)

**Comment by benjaminkott** [comment]
subnav links are adjusted
