### ISSUE TITLE
A11y Code Sprint Berlin: Success Criterion 9.2.4.1 - remove superfluous headers from main

### ISSUE THREAD

**Issue by SarahEdding** [benjaminkott/bootstrap_package#1292]
# Feature Request

## Description

Currently, each heading seems to come wrapped in a `header`. As they aren't nested in `section`, `article `or similar, all these headers relate to the [page's](https://bitv-v12.live.typo3.cps.321.works/content-examples/text/headers) `main`. This makes any page very confusing to navigate without sight. 

## Solution
Remove `header` tags from content headings. 
Recommendation: Render page title as H1 and `header` for `main` of each page.

**Comment by schmigotzki** [comment]
@alexakressmann Please assign to me

**Comment by alexakressmann** [comment]
QA successful
