### ISSUE TITLE
A11y Code Sprint Berlin: Success Criterion 9.2.4.1 - remove nav from tab list

### ISSUE THREAD

**Issue by SarahEdding** [benjaminkott/bootstrap_package#1295]
# Feature Request

## Description
The tab list is part of the page's content and should not be marked up as a navigation.

## Solution
Remove `<nav>` from tab list.

**Comment by jwundermann** [comment]
@alexakressmann please assign to me

**Comment by SarahEdding** [comment]
QA done, all fixed.
