### ISSUE TITLE
A11y Code Sprint Berlin: Success Criterion 9.2.4.2 - add site information to pages' title tags

### ISSUE THREAD

**Issue by SarahEdding** [benjaminkott/bootstrap_package#1297]
# Feature Request

## Description
A page's title tag is read out by screen readers as document title. It is useful for screen reader users to have some context information about the website as a whole as opposed to just the current page. 

## Solution
Add "| TYPO3 Introduction Package" to title tags. 
[Example](https://bitv-v12.live.typo3.cps.321.works/content-examples/media/media): `<title>Media | TYPO3 Introduction Package</title>`

**Comment by alexakressmann** [comment]
QA successful
