### ISSUE TITLE
A11y Code Sprint Berlin: Success Criterion 9.2.4.4 - provide meaningful label for lightbox toggle 

### ISSUE THREAD

**Issue by SarahEdding** [benjaminkott/bootstrap_package#1299]
# Feature Request

## Description
Currently, in the [gallery](https://bitv-v12.live.typo3.cps.321.works/content-examples/media/gallery), the button that opens the lightbox is wrapped around the image. This means each gallery image would have to have something like "view larger image" in its alt-attribute. This leaves very little space for an actual image description and places undue responsibility on editors. 
Even with the appropriate alt-text provided, sighted users cannot anticipate the opening of the lightbox. 

## Solution
A seperate button with an icon and, ideally, visible text (e.g. "zoom image") could sit in the bottom right corner of each image. 

## Alternative
We should discuss removing the lightbox feature entirely, since this is not the only issue there.

**Comment by jwundermann** [comment]
@SarahEdding please assign to me

**Comment by benjaminkott** [comment]
done
