### ISSUE TITLE
A11y Code Sprint Berlin: add aria attribute to lightbox modal or rebuild with dialog

### ISSUE THREAD

**Issue by SarahEdding** [benjaminkott/bootstrap_package#1301]
# Feature Request

## Description
The gallery lightbox is not discernible as such for screen reader users. 

## Solution
Add [aria-modal](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-modal) attribute to communicate modal state to screen readers 

## Alternative
We should discuss removing the lightbox feature entirely, since this is not the only issue there.
If we keep the feature, we should rebuild the lightbox using the semantic dialog element containing Heading H3, accessible carousel for images with alt-text, caption and close button.

**Comment by benjaminkott** [comment]
Done
