### ISSUE TITLE
A11y Code Sprint Berlin: Success Criterion 9.2.4.6 - remove redundant fieldsets from forms

### ISSUE THREAD

**Issue by SarahEdding** [benjaminkott/bootstrap_package#1304]
# Feature Request

## Description
In the [contact form](https://bitv-v12.live.typo3.cps.321.works/content-examples/form-elements/forms), fields are currently grouped into two fieldsets, neither of which is labelled. This is based on the form's layout and is confusing to screen reader users, because the grouping is not related to structure and/or content of the form. 
Fieldset in login [form ](https://bitv-v12.live.typo3.cps.321.works/content-examples/form-elements/login)is also redundant. 

## Solution
Removing both fieldsets will result in a concise and clear contact form that is structured in a way users are accustomed to. 

## Alternative
**If removing the fieldsets is not possible**, adding legends to both of them may help users to understand the form better.

**Comment by schmigotzki** [comment]
@alexakressmann Please assign to me

**Comment by schmigotzki** [comment]
@SarahEdding How about this solution?
Adding a label to each fieldset would be easier.

<img width="759" alt="form" src="https://github.com/benjaminkott/bootstrap_package/assets/66358384/141af5b7-362f-41ce-9491-1ff21748386b">
<img width="721" alt="markup" src="https://github.com/benjaminkott/bootstrap_package/assets/66358384/8ad214aa-242e-4135-a718-15b076a7a6db">

**Comment by schmigotzki** [comment]
Fieldsets in the felogin forms are unnecessary and could be removed. This is not optimal from an accessibility point of view, but according to @SarahEdding it can be tolerated. This would be a core change and can be implemented on occasion.

**Comment by benjaminkott** [comment]
We introduce a new element that needs to be used to avoid fieldsets. The form served by the bootstrap_package is already adjusted. If the introduction package uses a different one the fieldset needs to be replaced with grid column.

See change here: https://github.com/benjaminkott/bootstrap_package/commit/9132b048a8089d5162588d1d0527e90e8ea5e959#diff-a51f3921d8ba07c03befce1d404f530f7a8991d3d59df8d52d5ea6e88d823e63
