### ISSUE TITLE
A11y Code Sprint Berlin: Success Criterion 9.3.1.1. - provide correct document language for all pages

### ISSUE THREAD

**Issue by SarahEdding** [benjaminkott/bootstrap_package#1308]
# Feature Request

## Description
Currently, all content is either lorem ipsum or in Englisch. The document language for each page is set for German, however. This prevents screen readers from reading content correctly. 

## Solution
Set`<html lang="EN">` for all pages in English. Make sure that localisation of pages by editor results in the correct value for `<html lang="">`

**Comment by alexakressmann** [comment]
QA successful
