### ISSUE TITLE
A11y Code Sprint Berlin: Success Criterion 9.3.1.1. - remove language switch from footer

### ISSUE THREAD

**Issue by SarahEdding** [benjaminkott/bootstrap_package#1309]
# Feature Request

## Description
If a language switch is offered, it must lead to an actual page where document language and content language both meet user expectation. A lang switch "German" must lead to a page in German with `<html lang="de">`

## Solution
As the website's placeholder content cannot provide properly localised pages, the language switch should be removed.

**Comment by schmigotzki** [comment]
@alexakressmann please assign to me

**Comment by schmigotzki** [comment]
See pull request for detailed information

**Comment by alexakressmann** [comment]
QA successful
