### ISSUE TITLE
Images load only after scrolling

### ISSUE THREAD

**Issue by juschue** [benjaminkott/bootstrap_package#131]
Hi @benjaminkott,
i have a problem with my images, inserted via 'Text and Image' or only via 'Images'.
In the FE i can see them only, if i scroll down. They are loading right after only one scroll move.
Do you have a solution for me? Thanks!

**Comment by olegsv** [comment]
I have this problem too

**Comment by s-leger** [comment]
In order to fix the images not loading on some browsers due to :hidden bug, you need to adjust the $.responsiveimages() options in main.js according. (add skip_invisible:false)
```
$("img.lazyload").responsiveimages({skip_invisible:false}, function () {
Maybe we should adjust default in this file on line 22 (false instead of true) to disable the :hidden state check.
```
