### ISSUE TITLE
A11y Code Sprint Berlin: Success Criterion 9.4.1.2 - remove redundant roles

### ISSUE THREAD

**Issue by SarahEdding** [benjaminkott/bootstrap_package#1313]
# Feature Request

## Description
Semantic elements like `<nav>` and `<main>` do not need corresponding roles "nav" and "main" in order to function as landmarks. Some elements have roles that interfere with screen reader interpretation. 

## Solution

- remove `role="nav"` from all `<nav>`s 
- remove `role="main"` from `<main>`
- in [forms](https://bitv-v12.live.typo3.cps.321.works/content-examples/form-elements/forms), remove roles "group" and "toolbar" from submit button
- remove aria-live="polite" from cookie consent dialog

**Comment by Starkmann** [comment]
aria-live="polite" is coming from upstream package "https://github.com/osano/cookieconsent.git" and can not be configured:

`Build/node_modules/cookieconsent/src/cookieconsent.js:289`

**Comment by Starkmann** [comment]
in [forms](https://bitv-v12.live.typo3.cps.321.works/content-examples/form-elements/forms), remove roles "group" and "toolbar" from submit button

> I can not find any roles on submit butttons

**Comment by alexakressmann** [comment]
@SarahEdding Please QA tomorrow

**Comment by SarahEdding** [comment]
QA done, all fixed
