### ISSUE TITLE
A11y Code Sprint Berlin: Success Criterion 9.1.4.1 - add underline to all text links

### ISSUE THREAD

**Issue by SarahEdding** [benjaminkott/bootstrap_package#1316]
# Feature Request

## Description
Interactive Elements must be recognizable without perception of colour. Currently, text links only show a blue text, underline is only shown on hover, which excludes all users without a mouse or the motor skill needed for steady hovering. 

## Solution

Add text decoration underline to all text links. The underline can disappear on hover to preserve the hover interaction. 

## context, links and screenshots
poorly perceivable links: 
![image](https://github.com/benjaminkott/bootstrap_package/assets/132338236/23f64669-ce66-432e-89a4-e46fae85d2f2)

Links with underline: 
![image](https://github.com/benjaminkott/bootstrap_package/assets/132338236/3a61b253-cc08-4a3d-9623-a0c7d71c9818)

**Comment by linawolf** [comment]
@alexakressmann, please assign me

**Comment by linawolf** [comment]
@alexakressmann please review

**Comment by SarahEdding** [comment]
underline currently does not show in:
- breadcrumb navigation
- Card headings

@linawolf could you have another look? If not, I'll just push it back in ToDo

**Comment by linawolf** [comment]
yes I take care of it

**Comment by SarahEdding** [comment]
QA done, thanks :)
