### ISSUE TITLE
A11y Code Sprint Berlin: Success Criterion 9.1.3.1a - Info and Relationships - Headings in Footer

### ISSUE THREAD

**Issue by alexakressmann** [benjaminkott/bootstrap_package#1319]
**Page**
-
Footer on every page, for example: https://bitv-v12.live.typo3.cps.321.works/

**Description**
-
All headings need to be marked as headings in correct order.
[To WCAG](https://www.w3.org/TR/WCAG21/#info-and-relationships)

**Solution**
-
1. Add hidden H2 before footer entries: `<h2 class="visually-hidden">footer area</h2>`
2. Convert footer entries from H4 into H3

**Context, links and screenshots**
-
![Footer-2023-05-30 15_38_28-Congratulations](https://github.com/benjaminkott/bootstrap_package/assets/131977874/c69b99f4-82b4-47bd-aac1-7e1ca98b6c52)

**Comment by Starkmann** [comment]
On it

**Comment by Starkmann** [comment]
Changing from h4 to h3 needs to be done in content.

**Comment by Starkmann** [comment]
<h2 class="visually-hidden">footer area</h2>
Do we need a translation for "footer area"

**Comment by alexakressmann** [comment]
The wording "footer area" is in German "Footer-Bereich" but we name all elements in the Introduction Package in English. Why do you need a translation?

**Comment by Starkmann** [comment]
German screen reader would read it as "footer area." But if we don't need this, i'm ready with this ticket

**Comment by benjaminkott** [comment]
All headings are now configurable, there is no need for this change, please adjust the content accordingly.

**Comment by SarahEdding** [comment]
Headigs in Footer are now H2 with H3 styles: https://bitv-v12.live.typo3.cps.321.works/#c226
