### ISSUE TITLE
webfont.less slash issue

### ISSUE THREAD

**Issue by metaxos** [benjaminkott/bootstrap_package#132]
Hi @benjaminkott 

Is the slash after @{icon-font-path} not superfluous?
In Typoscript/Bootstrap/constants.txt the const icon-font-path ends with a slash:
```
icon-font-path = "../../typo3conf/ext/bootstrap_package/Resources/Public/Fonts/"
```

Resources/Less/Theme/Webfont.less
```
@font-face {
	font-family: 'Share';
	font-style: normal;
	font-weight: 400;
	src: url('@{icon-font-path}/share-regular-webfont-webfont.eot');
	src: url('@{icon-font-path}/share-regular-webfont-webfont.eot?#iefix') format('embedded-opentype'),
		 url('@{icon-font-path}/share-regular-webfont-webfont.woff') format('woff'),
		 url('@{icon-font-path}/share-regular-webfont-webfont.ttf') format('truetype');
}
```

Again thank you for your great work and your effort!

**Comment by cedricziel** [comment]
True, could be snipped away. But better one that's superflous (webserver cut them away), than one needed where there is none ^^

**Comment by benjaminkott** [comment]
@metaxos you are right, that can be removed - thx a lot for reporting.
