### ISSUE TITLE
A11y Code Sprint Berlin: Success Criterion 9.1.3.1a - Info and Relationships - Headings in Cookie Consent Banner

### ISSUE THREAD

**Issue by alexakressmann** [benjaminkott/bootstrap_package#1320]
**Page**
-
Cookie Consent Banner (Please open any page in private tab to see it)

**Description**
-
All headings need to be marked as headings in correct order.
[To WCAG](https://www.w3.org/TR/WCAG21/#info-and-relationships)

**Solution**
-
Add visible heading level H2 in the cookie consent banner: "We use cookies"

**Context, links and screenshots**
-
![Cookie-Banner-2023-05-30 15_33_52-Congratulations](https://github.com/benjaminkott/bootstrap_package/assets/131977874/91398ecc-692b-4588-9994-1b7d23e75880)
![Cookie-Banner-Schrift markiert-2023-05-30 15_33_52-Congratulations](https://github.com/benjaminkott/bootstrap_package/assets/131977874/38ef1f94-0665-47e0-898e-53e409a6086f)

**Comment by SarahEdding** [comment]
H2 is there, but is the first heading in DOM. We have to make sure, thats okay.

**Comment by SarahEdding** [comment]
H2 is alright in this case.
