### ISSUE TITLE
A11y Code Sprint Berlin: Success Criterion 9.1.3.2 - Meaningful Sequence - Search

### ISSUE THREAD

**Issue by alexakressmann** [benjaminkott/bootstrap_package#1321]
**Page**
-
https://bitv-v12.live.typo3.cps.321.works/content-examples/form-elements/search?tx_indexedsearch_pi2%5Baction%5D=form&tx_indexedsearch_pi2%5Bcontroller%5D=Search&tx_indexedsearch_pi2%5Bsearch%5D%5BextendedSearch%5D=1&cHash=bd4ce4122dff0be3360b7c2c0634c9fb

**Description**
-
When the sequence in which content is presented affects its meaning, a correct reading sequence can be programmatically determined.
[To WCAG](https://www.w3.org/TR/WCAG21/#meaningful-sequence)

**Solution**
-
Remove unnecessary checkbox at the end of the form

**Context, links and screenshots**
-
![Form-Checkbox-2023-06-01 21_13_54-Search](https://github.com/benjaminkott/bootstrap_package/assets/131977874/352b92c9-3f18-4445-91d1-9ae2e0b65265)

**Comment by schmigotzki** [comment]
More detailed information in pull request
