### ISSUE TITLE
A11y Code Sprint Berlin: Success Criterion 9.1.3.5 - Identify Input Purpose

### ISSUE THREAD

**Issue by alexakressmann** [benjaminkott/bootstrap_package#1322]
**Page**
-
https://bitv-v12.live.typo3.cps.321.works/content-examples/form-elements/forms

**Description**
-
The purpose of each input field collecting information about the user can be programmatically determined when the input field serves a purpose identified in the Input Purposes for User Interface Components section and when the content is implemented using technologies with support for identifying the expected meaning for form input data.
[To WCAG](https://www.w3.org/TR/WCAG21/#identify-input-purpose)

**Solution**
-
Add autocomplete attributes to input fields concerning information about the user: value autocomplete= "name" and "email".

**Context, links and screenshots**
-
**[To WCAG Input Purposes](https://www.w3.org/TR/WCAG21/#input-purposes)**
![Forms-autocomplete-2023-06-01 21_17_14-Forms](https://github.com/benjaminkott/bootstrap_package/assets/131977874/451f02d9-d7bf-4924-8eb0-e883350e7faf)

**Example in HTML**
https://www.w3.org/WAI/standards-guidelines/act/rules/73f2c2/#test-cases

**Comment by linawolf** [comment]
@alexakressmann please assign me

**Comment by alexakressmann** [comment]
QA successful
