### ISSUE TITLE
A11y Code Sprint Berlin: Success Criterion 9.4.1.2 Name, Role, Value - aria-current in Breadcrumb

### ISSUE THREAD

**Issue by alexakressmann** [benjaminkott/bootstrap_package#1326]
**Page**
-
Breadcrumb

**Description**
-
For all user interface components (including but not limited to: form elements, links and components generated by scripts), the name and role can be programmatically determined; states, properties, and values that can be set by the user can be programmatically set; and notification of changes to these items is available to user agents, including assistive technologies.
[To WCAG](https://www.w3.org/TR/WCAG21/#name-role-value)

**Solution**
-
1. Slashes (see screenshot) in breadcrumb have to be hidden with `aria-hidden=true`.
2. `aria-current` is only allowed to be used for the actually selected page. In our case, aria-current is read aloud by the screenreader for the two sites (see red border in screenshot). Please set it on the last word "Abstract" in the breadcrumb.

**Context, links and screenshots**
-
![Breadcrumb-aria-current-slashes-2023-06-01 22_20_31-Abstract](https://github.com/benjaminkott/bootstrap_package/assets/131977874/ea51209e-dffd-4543-b86a-3ba3d5d6114d)

**Comment by alboth** [comment]
@alexakressmann 

The Slashes in the Breddcrumb are "just" css `::before` not a HTML node. So there is not HMTL node to apply a aria-hidden attribute 

i could only apply an css `speak: none`
is that a way to go - any experiences ?

**Comment by alboth** [comment]
@linawolf review ready ... merge request sent
