### ISSUE TITLE
A11y Code Sprint Berlin: Success Criterion 9.1.3.1b - Info and Relationships - Lists

### ISSUE THREAD

**Issue by alexakressmann** [benjaminkott/bootstrap_package#1327]
**Page**
-
https://bitv-v12.live.typo3.cps.321.works/

**Description**
-
A list contains at least to items.

**Solution**
-
Marking header link to home and footer language link as `<P>` not as `<ul> <li>` - this is not a list.

**Context, links and screenshots**
-
**Header**
![not-a-list-2023-06-01 22_34_36-Congratulations – Mozilla Firefox](https://github.com/benjaminkott/bootstrap_package/assets/131977874/e9d1b380-80bc-4ce4-9962-ad7c41d50958)

**Footer**
![not-a-list-2023-06-01 22_34_57-Congratulations – Mozilla Firefox](https://github.com/benjaminkott/bootstrap_package/assets/131977874/71249c88-9d77-40c2-8224-84ce0384f226)

**Comment by linawolf** [comment]
@alexakressmann please assign me

**Comment by linawolf** [comment]
@alexakressmann please review
