### ISSUE TITLE
Several form elements hidden

### ISSUE THREAD

**Issue by olegsv** [benjaminkott/bootstrap_package#133]
Hello, it looks like when editing a form content element in visual mode, several form elements are hidden in 6.2.7. I see only the following:
Text Area	
Text Field	
Drop Down	
Upload Field	
Submit Button	
 
And choices like Fieldset or Radio, or Password are hidden.
The default form already contains Fieldset hardcoded.

How I can re-enable the missing fields?

**Comment by cedricziel** [comment]
What CType are we talking about?

**Comment by cedricziel** [comment]
For the standard form CE, you would need to adjust

``https://github.com/benjaminkott/bootstrap_package/blob/master/Configuration/PageTS/Mod/Wizards/form.txt#L11`` in your TSConfig.

Those are advanced elements, which may not be styled.

**Comment by olegsv** [comment]
Thank you. If fieldset is indeed disabled, you may want to remove FIELDSET element from the contact form on example page.
