### ISSUE TITLE
A11y Code Sprint Berlin: Success Criterion 9.1.3.1d - Info and Relationships - Structure of text / CONTENT

### ISSUE THREAD

**Issue by alexakressmann** [benjaminkott/bootstrap_package#1331]
**Pages**
-
https://bitv-v12.live.typo3.cps.321.works/customize
https://bitv-v12.live.typo3.cps.321.works/content-examples/text/rich-text

**Description**
-
Check with the bookmarklet Contents structured if paragraphs are marked with `<p>`. `<p>` without content has to be removed.
[To WCAG](https://www.w3.org/TR/WCAG21/#info-and-relationships)

**Solution**
-
Remove `<p>` without content in first text paragraph.

**Comment by linawolf** [comment]
@alexakressmann please assign me

**Comment by alexakressmann** [comment]
QA successful
