### ISSUE TITLE
A11y Code Sprint Berlin: Success Criterion 9.4.1.3 - Status messages / CONTENT

### ISSUE THREAD

**Issue by alexakressmann** [benjaminkott/bootstrap_package#1333]
**Page**
-
https://bitv-v12.live.typo3.cps.321.works/content-examples/form-elements/forms

**Description**
-
After submit there is a form redirect to the page FE-Login.
[To WCAG](https://www.w3.org/TR/WCAG21/#status-messages)

**Solution**
-
TYPO3 Introduction package does not use powermail, it uses forms.
1. Create a new page with submit text "The form was successfully submitted" etc.
2. Set in this page in form instead of the page FE-Login

**Comment by linawolf** [comment]
@benjaminkott please assign me

**Comment by linawolf** [comment]
@alexakressmann please move to review in project

**Comment by linawolf** [comment]
@alexakressmann done, please test again
