### ISSUE TITLE
Page not redirecting

### ISSUE THREAD

**Issue by v4vishnuprasad** [benjaminkott/bootstrap_package#134]
I have 3 pages Home, about, Contact, with ids 2,3,4
I installed the package and Pages shown in top.
my URL for home is www.mysite.com/index.php?id=2
when i click on about page URL became www.mysite.com/index.php?id=2#3 and not redirecting.
When I inspect the href is <a href="#p3" title="About Us">About</a>
note: I am new to typo3.

**Comment by benjaminkott** [comment]
@v4vishnuprasad did you use the onepage example template?

**Comment by v4vishnuprasad** [comment]
Yes I included " Bootstrap Package: OnePage (bootstrap_package) " in the includes.
When I removed it work fine as i expected.
Can you please explain it also?
Thank you. :+1:

**Comment by v4vishnuprasad** [comment]
.,,,,,,,,,,,,,,,,,,,

**Comment by v4vishnuprasad** [comment]
Yes I included "Bootstrap Package: OnePage (bootstrap_package)" in includes.
When I removed it it work fine as I expected .
Thank you :+1: 

And can u also tel me how to remove the admin panel and languages in footer

**Comment by benjaminkott** [comment]
To deactivate the admin panel for now you need to deactivate it in your typoscript setup, in the next release there will be an option for that.
```
config.admPanel = 0
```

To deactivate the language menu you will also need to unset it in your typoscript setup
```
lib.language >
```
