### ISSUE TITLE
Support for Retina

### ISSUE THREAD

**Issue by SventB** [benjaminkott/bootstrap_package#136]
Do you plan to add Retina support?
If I make a fork and implement this, are you willing to integrate this feature to your extension?

**Comment by cedricziel** [comment]
We would consider it for sure! We can't say of we'd do it without modification, but having something is better than having nothing :)

**Comment by benjaminkott** [comment]
@SventB @cedricziel agree - its complicated so because you have also to consider the ammount of cpu power needed to generate all so files etc. if you have a handy solution - sure we will consider implementing/merging/enhance that also.

**Comment by SventB** [comment]
It seems the only solution is to write a new JavaScript plugin for adaptive/lazyload/retina images which can handle more than one Retina image (adaptive for different screen sizes) AND with support of columns for adaptive images (problem described here #73).

I am not so experienced in JavaScript to do that, so I can't provide a Retina solution for bootstrap_package, sorry.
