### ISSUE TITLE
how to avoid database populate

### ISSUE THREAD

**Issue by gilas1959** [benjaminkott/bootstrap_package#137]
Hi I installed your ext downloading it from typo3.org/extensions
for an old site yet populated (pages and tt_content)
during the installation the +ext creates a new structure (pages tree and related tt_content) that I do not want for new sites.
What can I do to avoid the creation of new (undesired) pages?!?
thank you

**Comment by gilas1959** [comment]
forgive me you can close. The creation of db doesn't depend on your extension but is made through the +ext 'introduction', there is a data.t3d with all data to create a new site.

**Comment by cedricziel** [comment]
Sure, no need to appologize :)
