### ISSUE TITLE
A11y Code Sprint Berlin: QA

### ISSUE THREAD

**Issue by alexakressmann** [benjaminkott/bootstrap_package#1375]
**9.4.1.1**
- [x] Testing of all pages

**9.2.4.4**
- [x] https://bitv-v12.live.typo3.cps.321.works/content-examples/media/file-downloads
add file size and hide icons (Benji)
				
**11.7**
- [x] Testing of all pages

**9.2.4.1**
- [x] Add skip link "Skip to footer area" (Benji)

**Special pages**
- [x] https://bitv-v12.live.typo3.cps.321.works/content-examples/and-more/any-language-any-character
- [x] https://bitv-v12.live.typo3.cps.321.works/content-examples/text/rich-text
deactivate link element because before and after cannot be hidden + add link to email in address
- [x] https://bitv-v12.live.typo3.cps.321.works/content-examples/menus/cards
- [x] https://bitv-v12.live.typo3.cps.321.works/content-examples/text/text-with-teaser
- [x] https://bitv-v12.live.typo3.cps.321.works/content-examples/interactive/carousel
change images in carousel to more consistently dark ones: e.g. this one https://apod.nasa.gov/apod/ap230610.html

**Comment by SarahEdding** [comment]
Change images in [carousel](https://bitv-v12.live.typo3.cps.321.works/content-examples/interactive/carousel) to more consistently dark ones:  e.g. this one https://apod.nasa.gov/apod/ap230610.html

**Comment by benjaminkott** [comment]
Skip to page footer implemented in https://github.com/benjaminkott/bootstrap_package/commit/50cf3082083297d9f8abad10c0c8bdf8e0ba7723
