### ISSUE TITLE
A11y Code Sprint Berlin: Success Criterion 9.4.1.2 - add roles and role desciription to carousel containers

### ISSUE THREAD

**Issue by SarahEdding** [benjaminkott/bootstrap_package#1381]
# Feature Request

To communicate do screen reader users, that they are navigating a [carousel](https://bitv-v12.live.typo3.cps.321.works/content-examples/interactive/carousel), some aria roles with accessible descriptions would be helpful. 

## Solution

To **div containing carousel**, add role region with aria-roledescription and connect carousel heading to "region" via aria-labelledby: 
`<div id="c136" role="region" aria-roledescription="carousel" aria-labelledby="carousel-heading" class="..."><h2 id="carousel-heading" class="element-header  ">...</h2></div>`

To each **div containing a slide**, add role group and aria-roledescription; connect slide heading to "group" via aria-labelledby: 
`<div class="item active carousel-item carousel-item-layout-secondary carousel-item-type-header" role="group" aria-roledescription="slide" aria-labelledby="carousel_slide-heading_1"><h3 id="carousel_slide-heading_1">...</h3></div>`

**Comment by benjaminkott** [comment]
done as discussed, aria-labeledby will not happen today

**Comment by alexakressmann** [comment]
QA successful
