### ISSUE TITLE
A11y Code Sprint Berlin: Success Criterion 9.4.1.2 - remove aria-roledescription from section in lightbox

### ISSUE THREAD

**Issue by SarahEdding** [benjaminkott/bootstrap_package#1382]
# Feature Request

An aria-roledescription is only valid on elements with a role. A section container in the lightbox has a roledescription but no role. 

## Solution
replace aria-roledescription with aria-label. This makes the section element an implicit region with an accessible name. 
`<section class="pswp__scroll-wrap" aria-label="carousel">...</section>`

**Comment by alexakressmann** [comment]
@benjaminkott Have you had the chance to have a look at this?

**Comment by benjaminkott** [comment]
done

**Comment by alexakressmann** [comment]
QA successful
