### ISSUE TITLE
A11y Code Sprint Berlin: Success Criterion 9.2.4.7 - make focus visible on carousel slides with link

### ISSUE THREAD

**Issue by SarahEdding** [benjaminkott/bootstrap_package#1383]
# Feature Request

When [carousel ](https://bitv-v12.live.typo3.cps.321.works/content-examples/interactive/carousel)slides have a link, the keyboard focus on said slide must be clearly visible. 

## Solution
Add clearly visible focus indicator (outline) around linked active slide.

**Comment by alexakressmann** [comment]
@benjaminkott If this can't be fixed, we will remove the links from all slides before testing. Let us know what to do now

**Comment by benjaminkott** [comment]
done

**Comment by alexakressmann** [comment]
QA successful
