### ISSUE TITLE
Accordion (bs 13.0.1) not working due to missing markup

### ISSUE THREAD

**Issue by jeanjann** [benjaminkott/bootstrap_package#1387]
# Bug Report

* [ #] Can you reproduce the problem on TYPO3 v11.5 LTS
* [ ] Can you reproduce the problem on TYPO3 v12.4 LTS
* [ #] Did you [perform a cursory search]

## Description
On Typo3 11.5.23 with Bootstrap 12.0.5, Accordion works fine, but it fails to open after updating to Bootstrap 13.0.1/2
Downgrading to 12.0.5 fixes this issue.

## Steps to Reproduce

Use an accordion element on Typo3 11.5.23 with Bootstrap 12.0.5. The markup has 6 data attributes on the accordion-button element:
 data-toggle, data-target, data-parent, 
and
data-bs-toggle, data-bs-target, data-bs-parent.

2. Update to Bootstrap 13.0.1/2. The accordion stops working, and it has only the data-bs- attributes:
data-bs-toggle, data-bs-target, data-bs-parent.

3. Downgrading to Bootstrap 12.0.5 fixes the issue.
Manually adding the data-attributes (in dev tools) fixes the issue.

### Expected behavior

a working accordion in each case ;)

## Versions
Typo3 11.5.23
Bootstrap 12.0.5, 13.0.1, 13.02

**Comment by benjaminkott** [comment]
@jeanjann can you please provide an example code where it fails.

The example content element here works fine.
https://www.bootstrap-package.com/content-examples/interactive/accordion

**Comment by jeanjann** [comment]
Hi Benjamin,

thanks for your follow up.

Sure, here is the code and some screenshots.

**The failing code generated by v. 13.0.1**

```
<div class="accordion-item">
<h4 class="accordion-header" id="accordion-heading-671-15">
<button class="accordion-button collapsed" type="button" 
data-bs-toggle="collapse" 
data-bs-target="#accordion-671-15" 
data-bs-parent="#accordion-671" 
aria-expanded="false" aria-controls="accordion-671-15">
 Header 2
</button>
</h4>
<div id="accordion-671-15" class="accordion-collapse collapse" aria-labelledby="accordion-heading-671-15" 
data-parent="#accordion-671" 
data-bs-parent="#accordion-671">
<div class="accordion-body">...
```

**The working code generated by v. 12.05:**

```
<div class="accordion-item">
<h4 class="accordion-header" id="accordion-heading-671-15">
<button class="accordion-button collapsed" type="button" 
data-toggle="collapse" 
data-target="#accordion-671-15" 
data-parent="#accordion-671" 
data-bs-toggle="collapse"
data-bs-target="#accordion-671-15" 
data-bs-parent="#accordion-671" 
aria-expanded="false" aria-controls="accordion-671-15">
  Header 2
</button>
</h4>
<div id="accordion-671-15" class="accordion-collapse collapse" aria-labelledby="accordion-heading-671-15" 
data-parent="#accordion-671" 
data-bs-parent="#accordion-671"
aria-expanded="false" style="">
<div class="accordion-body">...
```

Yes, the BS example shown works fine with
```
<button class="accordion-button collapsed" type="button" 
data-bs-toggle="collapse" 
data-bs-target="#accordion-301-4" 
data-bs-parent="#accordion-301" 
aria-expanded="false" aria-controls="accordion-301-4">
```
nevertheless, our installation requires the data-attributes without "-bs" ;(
It's an out-of-the-box system, updated from 10.4.6 to 10.4.31 / 11.5.15 / 11.5.21 / 11.5.23


**failing code:**

![1_notworking_front](https://github.com/benjaminkott/bootstrap_package/assets/104315452/de9352b0-d534-4bee-90c5-fb7a7c0b4764)
![2_notworking-v13_back](https://github.com/benjaminkott/bootstrap_package/assets/104315452/9bea81f5-69a3-4878-b3d9-16347d1f214f)


**working code after downgrade**

![3_working-downgrading_to_v12_back](https://github.com/benjaminkott/bootstrap_package/assets/104315452/fda0fc98-e22e-46d2-9331-0eb94783fc86)
![4_working_front](https://github.com/benjaminkott/bootstrap_package/assets/104315452/fc008d41-090a-482c-b03d-ee8ec2a4a7e9)
![ext](https://github.com/benjaminkott/bootstrap_package/assets/104315452/5102347f-db04-42bc-96e5-8fa0fca069c4)

**Comment by benjaminkott** [comment]
@jeanjann this sounds like an incomplete migration from bootstrap 4 to 5, the code handling unprefixed `data-attributes` is also not shipped anymore when bootstrap 4 was dropped.

> nevertheless, our installation requires the data-attributes without "-bs" ;(
It's an out-of-the-box system, updated from 10.4.6 to 10.4.31 / 11.5.15 / 11.5.21 / 11.5.23

There is not a lot i can do, you probably have overwritten the templates somewhere.

**Comment by benjaminkott** [comment]
@jeanjann as said i can only recommend to migrate your templates. If you have no access to those templates please consider adding this simple JavaScript to your site.

```js
const migrateAttributes = {
  'data-toggle': 'data-bs-toggle',
  'data-target': 'data-bs-target',
  'data-parent': 'data-bs-parent'
}
Object.keys(migrateAttributes).forEach((originAttribute) => {
  const targetAttribute = migrateAttributes[originAttribute];
  const elements = document.querySelectorAll('[' + originAttribute + ']');
  elements.forEach((element) => {
    const currentValue = element.getAttribute(originAttribute);
    element.setAttribute(targetAttribute, currentValue);
  });
});
```

See how it works here:
https://codepen.io/benjaminkott/pen/MWzeqYJ

**Comment by benjaminkott** [comment]
Please reopen if you have further questions, otherwise good luck with your migration! 💪
