### ISSUE TITLE
Wrong path to font files

### ISSUE THREAD

**Issue by aimeos** [benjaminkott/bootstrap_package#139]
The web font files are not loaded correctly when TYPO3 is installed in a deeper sub-directory structure because the used URL is something like:
/aimeos/typo3conf/ext/bootstrap_package/Resources/Public/Fonts/share-bold-webfont-webfont.woff
but the correct URL would be in my installation:
/aimeos/typo3/test/typo3-71/typo3conf/ext/bootstrap_package/Resources/Public/Fonts/share-bold-webfont-webfont.woff

**Comment by cedricziel** [comment]
You would need to adjust the ``@{icon-font-path}`` variable to match your needs.

**Comment by cedricziel** [comment]
Just to be clear, this variable is available via typoscript.

**Comment by aimeos** [comment]
OK, this would be a way to fix the problem manually but shouldn't this path be better calculated automatically to don't bother users with this problem? At least, it's possible to do this without much effort.

**Comment by cedricziel** [comment]
Ok, mind a Pull-Request then?
