### ISSUE TITLE
Extension not updated in the extension catalogue

### ISSUE THREAD

**Issue by SchoolGuy** [benjaminkott/bootstrap_package#1390]
# Bug Report

## Prerequisites

* [x] Can you reproduce the problem on TYPO3 v11.5 LTS
* [x] Can you reproduce the problem on TYPO3 v12.4 LTS
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package)
  to see if your bug or enhancement is already reported?

## Description

When looking at the extension manager one can see that there are no updates available since version 12.0.0.

## Steps to Reproduce

1. Go to https://extensions.typo3.org/extension/blog
2. See that the last uploaded version is 12.0.0

### Expected behavior

I see all versions that are published on GitHub as a release.

### Actual behavior

Multiple versions missing from the extension catalogue.

### Screenshots

None applicable.

## Versions

Independent of the version of the extension.

**Comment by benjaminkott** [comment]
hey, @SchoolGuy not sure what you are looking for exactly. but this is the repository for the bootstrap_package not the blog.
anyways all versions are released also in TER. https://extensions.typo3.org/extension/bootstrap_package

**Comment by SchoolGuy** [comment]
@benjaminkott I don't know how I could mix this up. Sorry that is my bad.
