### ISSUE TITLE
Possible error in documentation

### ISSUE THREAD

**Issue by lars-brinkmann** [benjaminkott/bootstrap_package#1391]
Page:
https://docs.typo3.org/p/bk2k/bootstrap-package/13.0/en-us/Configuration/TypoScript/Index.html

The constants:
plugin.bootstrap_package.settings.override**Less**Variables

seems to be wrong. In constants.typoscript the constant is calles:
override**Parser**Variables

Found in docs for v7 to v14

**Comment by benjaminkott** [comment]
resolved in https://github.com/benjaminkott/bootstrap_package/commit/223d9a31bc7bd5b4d9bbfdeab9bcdf8161337a59
