### ISSUE TITLE
Content Element: Filelinks not working

### ISSUE THREAD

**Issue by Gang359** [benjaminkott/bootstrap_package#1401]
# Bug Report

## Prerequisites

* [ x] Can you reproduce the problem on TYPO3 v11.5 LTS
* [ ] Can you reproduce the problem on TYPO3 v12.4 LTS
* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package)
  to see if your bug or enhancement is already reported?

## Description

Filelinks no longer working after update of bootstrap package 13.02 to 14.04 in Typo3 V11.29

## Steps to Reproduce

1. Disabled Content Element: Filelinks -> Website is working
2. Enabled Content Element Filelinks and changed Files -> Typo3 Error

### Expected behavior

Content Element Filelinks rendering and working

### Actual behavior

Typo3 Exception: Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1407060572: Fluid parse error in template Standard_action_uploads_f239be3c710a78328b163dd74c2a204fbca68076, line 1 at character 30. Error: The ViewHelper "<f:format.trim>" could not be resolved.  ....

### Screenshots

![Typo3_Exception](https://github.com/benjaminkott/bootstrap_package/assets/139459162/6bf0a1f3-05a0-4903-aacd-574dd57df837)

## Versions

typo3: v11.29
bootstrap-package v14.04

**Comment by LMFC-Krisi** [comment]
Same Problem here.
![grafik](https://github.com/benjaminkott/bootstrap_package/assets/88950563/93138048-90e1-428d-b223-e48be07c3d9a)

**Comment by pwilladt** [comment]
This error comes from using fluid component TrimViewHelper.php, which is not present on Typo3 V11.
Peter Willadt

**Comment by LMFC-Krisi** [comment]
In Bootstrap Package 14.0.2 everything looks ok. Problem first time in 14.0.3

**Comment by benjaminkott** [comment]
Yikes! That was an oversight of me. New release will be published soon.

FIX for v14: https://github.com/benjaminkott/bootstrap_package/commit/22f6c99b69fe5d9bb1abf0ed7f3cd2e27beeaf95
Master moving all to f:format: https://github.com/benjaminkott/bootstrap_package/commit/d355cebcbae656cb210fbcb9f3b8b287158daab1

**Comment by LMFC-Krisi** [comment]
Thank you very much. In 14.0.6 it works fine.
Best Regards Michael
