### ISSUE TITLE
Error in Backend > RTE after Sitepackage installation

### ISSUE THREAD

**Issue by LRWphil** [benjaminkott/bootstrap_package#1407]
Hello! 

I've installed a fresh TYPO3 12.4.4

and a Sitepackage via https://www.sitepackagebuilder.com/
MySitepackage @dev
Bootstrap_package 14.0.6 

When i create a content element i get the following error:

```
#1476107295 TYPO3\CMS\Core\Error\Exception

PHP Warning: sha1_file(/var/www/html/public/_assets/9b80d86a98af3ecc38aabe297d2c3695/Css/bootstrap4-rte.min.css): Failed to open stream: No such file or directory in /var/www/html/vendor/typo3/cms-rte-ckeditor/Classes/Form/Element/RichTextElement.php line 146
```

I checked the Directory and there is only a `bootstrap5-rte.min.css`

Did I do sth wrong or is it a Bug?

**Comment by Wahni69** [comment]
Same Problem here.

**Comment by Wahni69** [comment]
I have made a copy of bootstrap5-rte.min.css, renamed it an then the error is gone. But I think, that is not the right way...

**Comment by Starraider** [comment]
Same problem here.
