### ISSUE TITLE
[ENHANCEMENT] Make visibility states of content content elements editable for editors

### ISSUE THREAD

**Issue by walgram** [benjaminkott/bootstrap_package#146]
Hello all! Don't know if i am at the right place with this suggestion.
It would be nice to have the possibility to use hidden-sm hidden-xs etc. with content elements. With this enhancement one could make realy usable sites for different devices, desktop, smartphone, tablet.
Kind regard Eduard

**Comment by benjaminkott** [comment]
Long time, i finally got my head around this one and made a final decision not to make these kind of settings available to the editor. The editor should not have to think about these breakpoints. If content should be hidden on viewports, what i would generally consider a wrong idea - it should be done by the integrator.
