### ISSUE TITLE
Full width template

### ISSUE THREAD

**Issue by simonschaufi** [benjaminkott/bootstrap_package#1475]
# Feature Request

## Is your feature request related to a problem? Please describe

At the moment I can only place content elements within a container with limited width but for some elements I need full screen with.

## Describe the solution you'd like

have a new layout that lets me add elements within a container and full screen width.

## Additional context

See as an example of what I'm trying to achieve:
- https://startbootstrap.com/previews/full-width-pics
- https://startbootstrap.com/previews/new-age

See also: https://github.com/benjaminkott/bootstrap_package/issues/858

**Comment by SvenJuergens** [comment]
hi @simonschaufi 
Shouldn't the "No frame" option be able to help here?
![Bildschirmfoto 2024-02-28 um 10 11 54](https://github.com/benjaminkott/bootstrap_package/assets/20923295/f81c0563-ba9e-4091-8e11-158d09074d59)

**Comment by simonschaufi** [comment]
yes, this solves it! Thank you. There were no example pages like this so I wasn't sure if this is supported.
