### ISSUE TITLE
blank pages after constant change

### ISSUE THREAD

**Issue by m4chi** [benjaminkott/bootstrap_package#148]
Hi Benjamin,
Thanks a bunch for the package, it's great for newbies like me! I've done some customization and all works fine but if I try to make any changes to the styles via the typoscript template constants, my website does not load any more but only produces a blank page. So, for example, if I change the @brand-danger color value to anything else, like, for example, the same value as @brand-primary, the frontend won't load any more. I'm feeling pretty stupid (can't even change the theme color, ha)... Any help would be highly appreciated.
Running Typo3 6.2.9.

**Comment by pyttolomaeus** [comment]
Hi,
I got across the same issue. I’m running Typo3 6.2.14. If I do changes of any other constants than styles everything works fine. But changes of Constants of category style are producing this problem. Thank you for every answer or hint!
Best regards

**Comment by benjaminkott** [comment]
Hey Guys, can you please check your PHP Memory Limit. Processing is a bit Hungry ;)

**Comment by pyttolomaeus** [comment]
Thank you for your answer! I thought that this could be a reason. But now I have tested it on a local mashine. If I set the memory_limit constant in php.ini to a value greater or equal than 54M everything works fine. I will contact my hoster for changing that value and I'll let you know the the result.

Best regards
