### ISSUE TITLE
[TYPO3-BUG] Section Index content item produces incorrect links

### ISSUE THREAD

**Issue by olegsv** [benjaminkott/bootstrap_package#150]
Section Index (tt_content.menu.20.3 ) possibly produces incorrect links to content elements.

How to reproduce: in example website, place a section index on Headers page in Examples.

page URL : http://typo3.localhost/examples/headers.html 

Base HREF tag ( auto generated) will be: <base href="http://typo3.localhost/">

links to sections: <a href="#30">.... 

Click on the link will direct to http://typo3.localhost/#30 , this is incorrect.
Should be:  http://typo3.localhost/examples/headers.html#30

**Comment by olegsv** [comment]
First noticed in typo3 6.2.9, exists in 6.2.11 . Is this a Typo3 bug or the extension's bug?

**Comment by benjaminkott** [comment]
@olegsv thx for reporting. as far as i can reproduce this seems to be a problem with the link generation within typo3 itself. will have a look if i can fix it there.

**Comment by olegsv** [comment]
still exists in 6.2.12

**Comment by s-leger** [comment]
Same issue here, (6.2.12) fixed by using
config.prefixLocalAnchors = all

**Comment by olegsv** [comment]
config.prefixLocalAnchors = all
This fixed the problem. Thanks @s-leger .

**Comment by benjaminkott** [comment]
@olegsv @s-leger thx for digging this out, made this the new default value and added options for the constant editor for that.
