### ISSUE TITLE
main navigation to switch to a burger menu

### ISSUE THREAD

**Issue by mayfeld** [benjaminkott/bootstrap_package#1504]
Is there a way for the navbar - main navigation to switch to a burger menu at, for example, 1260px width, and not only at 991px? The functionality of the navbar-collapse should of course remain intact there as well.

**Comment by olivermeckel** [comment]
You can change the variable $grid-float-breakpoint from 992 px to 1260 px. It controls the breakpoint for the visibilty of the navbar-toggler.

**Comment by mayfeld** [comment]
Thank you Oliver. Found it in:
/Resources/Public/Scss/bootstrap5/_variables.scss
