### ISSUE TITLE
Error in Sites after todays update

### ISSUE THREAD

**Issue by gmt-it** [benjaminkott/bootstrap_package#1522]
# Bug Report

## Description

Hello.

Since today's update, I've been getting the following error under Sites:

An error occurred while attempting to process the elements for field "Sets for this website" (Invalid setting definition: {"label":"$primary","category":"BootstrapPackage.scss.colors","type":"string","default":"#577760"}).

## Steps to Reproduce

1. Update to latest bootstrap-package
2. go to sites and click edit

## Versions
Typo3 13.2.1
Bootstrap-package  dev-master

**Comment by benjaminkott** [comment]
Hey, the release is prepared for tomorrow. The sets can be used from 13.4 onwards it needs a patch that was merged today.

**Comment by benjaminkott** [comment]
Please stay on this commit meanwhile to avoid this error when using any v13 release aside from current main. https://github.com/benjaminkott/bootstrap_package/commit/32c1e1d34b27b11f5b550d7601179e6296084ef2

**Comment by benjaminkott** [comment]
@gmt-it v13.4 is now released, let me know if the problem still exists.

**Comment by gmt-it** [comment]
Hi.

Everything seems to be working so far.
