### ISSUE TITLE
[ENHANCEMENT] Add link to the icon in text with icon content element

### ISSUE THREAD

**Issue by gilas1959** [benjaminkott/bootstrap_package#154]
Hi
could you add a BE field to render the ICON linked to a page, external url, etc?!?
thank you

ALEX

**Comment by benjaminkott** [comment]
Hey @gilas1959, can you make a usecase of this?
Would like to figure out what exactly you are going to achive and why.

For example:
Do you need an individual link for the icon or can it be the same like the link for the header?

**Comment by gilas1959** [comment]
hi Benjamin and my congratulations for your work.
   I mean to add a new field to link the circle (or square) to a specific internal page or external url.
   However to solve this I added some typoscript (made a new typolink object) for this site:
   http://ainf.uniud.it/reti/panoramica/
   and some CSS to grant the opacity (0.9) when the mouse is over.
   Please do the modifications you think to be the best or right!
   thank you for your help
   ALEX

   From "Benjamin Kott" notifications@github.com

   To "benjaminkott/bootstrap_package" bootstrap_package@noreply.github.com

   Cc "gilas1959" at@specialistaweb.it

   Date Sat, 11 Apr 2015 07:05:15 -0700

   Subject Re: [bootstrap_package] feature request: text/icon with link (#154)
