### ISSUE TITLE
Time Date & Time will not accept

### ISSUE THREAD

**Issue by unsuwe0** [benjaminkott/bootstrap_package#1544]
# Bug Report

## Prerequisites

* [ ] Can you reproduce the problem on TYPO3 v11.5 LTS
* [ ] Can you reproduce the problem on TYPO3 v12.4 LTS
* [ x ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package)
  to see if your bug or enhancement is already reported?

## Description
Time Date & Time will not accept
The field is red after input

## Steps to Reproduce
1. create content timeline
2. fill fields
3. the field date & time remains red and not accept the button date

1. [First Step]
4. [Second Step]
5. [and so on...]

### Expected behavior

[What you expected to happen]

### Actual behavior

[What actually happened]

### Screenshots
![Bild_2024-12-16_084858685](https://github.com/user-attachments/assets/4c4aea78-ac60-4334-b43b-9e2f4a72c625)

[If applicable, add screenshots to help explain your problem.]

## Versions

b13/container                       3.1.1    Create Custom Container Content Elements for TYPO3
bacon/bacon-qr-code                 3.0.1    BaconQrCode is a QR code generator for PHP.
baschte/content-animations          2.5.2    TYPO3 CMS extension to have some fun and animate your content elements
bk2k/bootstrap-package              15.0.0   Bootstrap Package delivers a full configured frontend theme for TYPO...
buepro/typo3-container-elements     6.0.4    TYPO3 extension providing content elements powered by container and ...
buepro/typo3-pvh                    3.1.0    A collection of view helpers used by pizpalue. Contains copies from ...
christian-riesen/base32             1.6.0    Base32 encoder/decoder according to RFC 4648
dasprid/enum                        1.0.6    PHP 7.1 enum implementation
doctrine/annotations                2.0.2    Docblock Annotations Parser
doctrine/dbal                       4.2.1    Powerful PHP database abstraction layer (DBAL) with many features fo...
doctrine/deprecations               1.1.4    A small layer on top of trigger_error(E_USER_DEPRECATED) or PSR-3 lo...
doctrine/event-manager              2.0.1    The Doctrine Event Manager is a simple PHP event system that was bui...
doctrine/instantiator               2.0.0    A small, lightweight utility to instantiate objects in PHP without i...
doctrine/lexer                      3.0.1    PHP Doctrine Lexer parser library that can be used in Top-Down, Recu...
egulias/email-validator             4.0.2    A library for validating emails against several RFCs
enshrined/svg-sanitize              0.20.0   An SVG sanitizer for PHP
firebase/php-jwt                    6.10.2   A simple library to encode and decode JSON Web Tokens (JWT) in PHP. ...
friendsoftypo3/tt-address           9.0.1    Displays a list of addresses from an address table on the page.
guzzlehttp/guzzle                   7.9.2    Guzzle is a PHP HTTP client library
guzzlehttp/promises                 2.0.4    Guzzle promises library
guzzlehttp/psr7                     2.7.0    PSR-7 message implementation that also provides common utility methods
hucken/schwarzerhucken              dev-main Vereins Homepage
lolli42/finediff                    1.1.1    PHP implementation of a Fine granularity Diff engine
masterminds/html5                   2.9.0    An HTML5 parser and serializer.
nikic/php-parser                    5.3.1    A PHP parser written in PHP
nitsan/ns-snow                      13.0.0   Spread the joy of Christmas on your TYPO3 website with the Snowfall ...
phpdocumentor/reflection-common     2.2.0    Common reflection classes used by phpdocumentor to reflect the code ...
phpdocumentor/reflection-docblock   5.6.1    With this component, a library can provide support for annotations v...
phpdocumentor/type-resolver         1.10.0   A PSR-5 based resolver of Class names, Types and Structural Element ...
phpstan/phpdoc-parser               1.33.0   PHPDoc parser with support for nullable, intersection and generic types
psr/cache                           3.0.0    Common interface for caching libraries
psr/clock                           1.0.0    Common interface for reading the clock.
psr/container                       2.0.2    Common Container Interface (PHP FIG PSR-11)
psr/event-dispatcher                1.0.0    Standard interfaces for event handling.
psr/http-client                     1.0.3    Common interface for HTTP clients
psr/http-factory                    1.1.0    PSR-17: Common interfaces for PSR-7 HTTP message factories
psr/http-message                    2.0      Common interface for HTTP messages
psr/http-server-handler             1.0.2    Common interface for HTTP server-side request handler
psr/http-server-middleware          1.0.2    Common interface for HTTP server-side middleware
psr/log                             3.0.2    Common interface for logging libraries
quellenform/t3x-lib-jquery          4.0.3    Integrates the jQuery-library from CDN with a local fallback if requ...
ralouphie/getallheaders             3.0.3    A polyfill for getallheaders.
scssphp/scssphp                     1.13.0   scssphp is a compiler for SCSS written in PHP.
specialistaweb/textimage-size       4.0.1    useful to change the output  layout for text/image (also said: textp...
symfony/cache                       7.2.1    Provides extended PSR-6, PSR-16 (and tags) implementations
symfony/cache-contracts             3.5.1    Generic abstractions related to caching
symfony/clock                       7.2.0    Decouples applications from the system clock
symfony/config                      7.2.0    Helps you find, load, combine, autofill and validate configuration v...
symfony/console                     7.2.1    Eases the creation of beautiful and testable command line interfaces
symfony/dependency-injection        7.2.0    Allows you to standardize and centralize the way objects are constru...
symfony/deprecation-contracts       3.5.1    A generic function and convention to trigger deprecation notices
symfony/doctrine-messenger          7.2.0    Symfony Doctrine Messenger Bridge
symfony/event-dispatcher            7.2.0    Provides tools that allow your application components to communicate...
symfony/event-dispatcher-contracts  3.5.1    Generic abstractions related to dispatching event
symfony/expression-language         7.2.0    Provides an engine that can compile and evaluate expressions
symfony/filesystem                  7.2.0    Provides basic utilities for the filesystem
symfony/finder                      7.2.0    Finds files and directories via an intuitive fluent interface
symfony/http-foundation             7.2.0    Defines an object-oriented layer for the HTTP specification
symfony/mailer                      7.2.0    Helps sending emails
symfony/messenger                   7.2.1    Helps applications send and receive messages to/from other applicati...
symfony/mime                        7.2.1    Allows manipulating MIME messages
symfony/options-resolver            7.2.0    Provides an improved replacement for the array_replace PHP function
symfony/polyfill-ctype              1.31.0   Symfony polyfill for ctype functions
symfony/polyfill-intl-grapheme      1.31.0   Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-idn           1.31.0   Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer    1.31.0   Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring           1.31.0   Symfony polyfill for the Mbstring extension
symfony/polyfill-php80              1.31.0   Symfony polyfill backporting some PHP 8.0+ features to lower PHP ver...
symfony/polyfill-php83              1.31.0   Symfony polyfill backporting some PHP 8.3+ features to lower PHP ver...
symfony/polyfill-uuid               1.31.0   Symfony polyfill for uuid functions
symfony/process                     7.2.0    Executes commands in sub-processes
symfony/property-access             7.2.0    Provides functions to read and write from/to an object or array usin...
symfony/property-info               7.2.1    Extracts information about PHP class' properties using metadata of p...
symfony/rate-limiter                7.2.0    Provides a Token Bucket implementation to rate limit input and outpu...
symfony/routing                     7.2.0    Maps an HTTP request to a set of configuration variables
symfony/service-contracts           3.5.1    Generic abstractions related to writing services
symfony/string                      7.2.0    Provides an object-oriented API to strings and deals with bytes, UTF...
symfony/type-info                   7.2.1    Extracts PHP types information.
symfony/uid                         7.2.0    Provides an object-oriented API to generate and represent UIDs
symfony/var-exporter                7.2.0    Allows exporting any serializable PHP data structure to plain PHP code
symfony/yaml                        7.2.0    Loads and dumps YAML files
tritum/form-element-linked-checkbox 5.0.2    Adds a new form element which allows the editor to create a checkbox...
typo3/class-alias-loader            1.2.0    Amends the composer class loader to support class aliases to provide...
typo3/cms-adminpanel                13.4.2   TYPO3 CMS Admin Panel - The Admin Panel displays information about y...
typo3/cms-backend                   13.4.2   TYPO3 CMS backend
typo3/cms-belog                     13.4.2   TYPO3 CMS Log - View logs from the sys_log table in the TYPO3 backen...
typo3/cms-beuser                    13.4.2   TYPO3 CMS Backend User - TYPO3 backend module System>Backend Users f...
typo3/cms-cli                       3.1.2    TYPO3 command line binary
typo3/cms-composer-installers       5.0.1    TYPO3 CMS Installers
typo3/cms-core                      13.4.2   TYPO3 CMS Core
typo3/cms-dashboard                 13.4.2   TYPO3 CMS Dashboard - TYPO3 backend module used to configure and cre...
typo3/cms-extbase                   13.4.2   TYPO3 CMS Extbase - Extension framework to create TYPO3 frontend plu...
typo3/cms-extensionmanager          13.4.2   TYPO3 CMS Extension Manager - Backend module (Admin Tools>Extensions...
typo3/cms-felogin                   13.4.2   TYPO3 CMS Frontend Login - A template-based plugin to log in website...
typo3/cms-filelist                  13.4.2   TYPO3 CMS Filelist - TYPO3 backend module (File>Filelist) used for m...
typo3/cms-filemetadata              13.4.2   TYPO3 CMS File Metadata - Adds additional metadata to file management.
typo3/cms-fluid                     13.4.2   TYPO3 CMS Fluid Integration - Integration of the Fluid templating en...
typo3/cms-fluid-styled-content      13.4.2   TYPO3 CMS Fluid Styled Content - Fluid templates for TYPO3 content e...
typo3/cms-form                      13.4.2   TYPO3 CMS Form - Flexible TYPO3 frontend form framework that comes w...
typo3/cms-frontend                  13.4.2   TYPO3 CMS Frontend
typo3/cms-impexp                    13.4.2   TYPO3 CMS Import/Export - Tool for importing and exporting records u...
typo3/cms-indexed-search            13.4.2   TYPO3 CMS Indexed Search - Provides indexing functionality for TYPO3...
typo3/cms-info                      13.4.2   TYPO3 CMS Info - TYPO3 backend module for displaying information, su...
typo3/cms-install                   13.4.2   TYPO3 CMS Install Tool - The Install Tool is used for installation, ...
typo3/cms-linkvalidator             13.4.2   TYPO3 CMS LinkValidator - Checks for broken links and displays resul...
typo3/cms-lowlevel                  13.4.2   TYPO3 CMS Lowlevel - Technical analysis of the system. This includes...
typo3/cms-opendocs                  13.4.2   TYPO3 CMS Open Docs - Shows opened documents for the TYPO3 backend u...
typo3/cms-reactions                 13.4.2   TYPO3 CMS Reactions - Handle incoming Webhooks for TYPO3
typo3/cms-recycler                  13.4.2   TYPO3 CMS Recycler - Restore deleted records or remove them from the...
typo3/cms-redirects                 13.4.2   TYPO3 CMS Redirects - Create manual redirects, list existing redirec...
typo3/cms-reports                   13.4.2   TYPO3 CMS Reports - Show status reports and installed services in th...
typo3/cms-rte-ckeditor              13.4.2   TYPO3 CMS RTE CKEditor - Integration of CKEditor as a Rich Text Edit...
typo3/cms-scheduler                 13.4.2   TYPO3 CMS Scheduler - Schedule tasks to run once or periodically at ...
typo3/cms-seo                       13.4.2   TYPO3 CMS SEO - SEO features including specific fields for SEO purpo...
typo3/cms-setup                     13.4.2   TYPO3 CMS Setup - Allows users to edit a limited set of options for ...
typo3/cms-sys-note                  13.4.2   TYPO3 CMS System Notes - Records with messages which can be placed o...
typo3/cms-tstemplate                13.4.2   TYPO3 CMS TypoScript - TYPO3 backend module for the management of Ty...
typo3/cms-viewpage                  13.4.2   TYPO3 CMS Viewpage - Use the (Web>View) backend module to view a fro...
typo3/cms-webhooks                  13.4.2   TYPO3 CMS Webhooks - Handle outgoing Webhooks for TYPO3
typo3/cms-workspaces                13.4.2   TYPO3 CMS Workspaces - Workflows with custom stages and versioning f...
typo3/html-sanitizer                2.2.0    HTML sanitizer aiming to provide XSS-safe markup based on explicitly...
typo3/minimal                       13.4.0   Minimal required set of TYPO3 extensions
typo3fluid/fluid                    4.0.2    The TYPO3 Fluid template rendering engine
webmozart/assert                    1.11.0   Assertions to validate method input/output with nice error messages.
wsr/myttaddressmap                  2.3.3    Google maps for tt_address with radial search and categories

You can get this information from executing `composer show` at the command line
if your TYPO3 installation is composer based, otherwise the version number will
be shown in the extension manager.

**Comment by andreaskienast** [comment]
Hello,
thank you for your report. This is a bug in TYPO3 itself, but not in EXT:bootstrap_package. I've filed an issue [at TYPO3](https://forge.typo3.org/issues/105829), therefore I'll close this ticket.

Kind regards
Andreas

**Comment by gmt-it** [comment]
One more note: In the introduction package you can edit the timeline and change the date without any problems. Only newly created timeline elements show the behavior that the entered date cannot be validated. Changing the timeline constant also has no effect.
