### ISSUE TITLE
Multicolumn images

### ISSUE THREAD

**Issue by timofo** [benjaminkott/bootstrap_package#156]
If you use for example the element "Images" and choose 6 columns for the columns then you run into a problem with column clearing. It is the same for 4 columns at certain breakpoints.
See here : http://getbootstrap.com/css/#grid-responsive-resets
Any idea how to fix this? There must be a clearfix div between the columns.

**Comment by s-leger** [comment]
As column rendering is done in core it's realy difficult.

Maybe a css rule with equalheight display will make the trick.
Just find the right selectors.

```
.equal-height {
	display: -webkit-box;
	display: -webkit-flex;
	display: flex;
	flex:1 0 auto;
}
```

**Comment by benjaminkott** [comment]
All gallerys for media and have been migrated to flexbox since the nessesary support is now widely available. In addtion the column sizes can now be set via typoscript constants if nessesary.

https://github.com/benjaminkott/bootstrap_package/commit/e5d9cade9925cec367bad184e90b5489280c32e5
