### ISSUE TITLE
Performance issue in frontend

### ISSUE THREAD

**Issue by aimeos** [benjaminkott/bootstrap_package#158]
We've found out that using the bootstrap package slows down page rendering 4-5 times if the page contains a non-cachable plugin compared to a standard page layout without Fluid. I'm unsure if Fluid is the problem (it should be available in a compiled form after the first request) or more likely, if any TypoScript statements causes this slowdown. We've used version 6.2.9 for our tests.

Our tests results:
- Page fully cachable: ca. 90ms
- Standard page template w/o bootstrap and Fluid: ca. 150ms
- With bootstrap package: ca. 600-750ms

To answer that question upfront: No, the non-cachable plugin is not the problem because it only adds a few milliseconds (ca. 5ms) to the response time.

**Comment by benjaminkott** [comment]
@aimeos the problem seems to be located in the located at the less parser - already talked to the themes guys about their solution, they implemented a custom caching for the less files so the less parser does not need to handle the lookups.

**Comment by cedricziel** [comment]
this wouldnt work without external dependencies (dyncss in this case).

**Comment by aimeos** [comment]
@benjaminkott Thanks a lot for your efforts! :-)
Maybe it's an option to call the less parser only after clearing the cache. This should be practical as the bootstrap package is configured via TypoScript and the cache has to be cleared afterwards nevertheless

**Comment by benjaminkott** [comment]
Well they are using mainly the same implementation as we do here - its more a copy the check thingy. Kay said its ok 😊

**Comment by aimeos** [comment]
We've finally found the root case for the performance issues of the bootstrap_package in combination with the aimeos extension: The TypoScript of the bootstrap_package contains settings for compressing/concatenating CSS/JS files, which is a performance killer if one plugin on the page is configured that its output should not be cached (like a shop basket).

The problematic TypoScript settings are:
```
config.concatenateCss = 1
config.compressCss = 1
config.concatenateJs = 1
config.compressJs = 1
```

We've created a bug report at TYPO3 Forge: https://forge.typo3.org/issues/75127

**Comment by benjaminkott** [comment]
@aimeos Funny, we recently disabled the concatenation settings by default because people complained that they could not find their included css and js files in the source code.
