### ISSUE TITLE
div .image-center-outer (float container) overlaps side container

### ISSUE THREAD

**Issue by Gorli** [benjaminkott/bootstrap_package#159]
Relates to the desktop view!

When centered images are added the container (<div class="image-center-outer>) overlap a possible side column because this container float over the side column. If this side column contains links, this can no longer be used!

I recommend in this case the parent container (<div class="image-center image-xy">) to give a overflow:hidden!

Example:
.image-center {
  overflow: hidden;
}

**Comment by Gorli** [comment]
First entry sent incomplete, therefore resent.....

When centered images are added, the container (div class="image-center-outer) covered a possible side column. If this page column contains links, this can no longer be used!
I recommend in this case the container (div class="image-center-xxxx) to give a overflow:hidden!

example:
.image-center {
overflow: hidden;
}

**Comment by brrrrrrrt** [comment]
very similar:

when using the Backendlayout "Special Feature" and adding two images in a row into "Special 1" and another to images in a row into "Special 2" looking like this:

```
Special 1    | Special 2
-------------------------------
header       | header
<img1><img2> | <img3><img4>
```

in this case **the link on img2 is unclickable** :(

and yes:
```
.image-center {
	overflow: hidden;
}
```
or
``` 
.image-center-outer {
	float: none;
}
```
does fix the problem :)

**Comment by benjaminkott** [comment]
Hey guys, should be fixed now. Please let me know if it works for all your cases.
