### ISSUE TITLE
[ENHANCEMENT] Add swipe support for carousels

### ISSUE THREAD

**Issue by brrrrrrrt** [benjaminkott/bootstrap_package#161]
Everything needed for swipe would be the "Touch"-part of jQuery Mobile which is about 8KB (min).
http://jquerymobile.com/download-builder/  (select "Touch" -> Build my Download)
included as includeJSFooterlibs

and includeJSFooter with a file containing this:

```
$(document).ready(function() {  
	$("div[id^=carousel-]").each(function(index){ 
		$(this).swiperight(function() {  
			$(this).carousel('prev');  
		});
		$(this).swipeleft(function() {  
			$(this).carousel('next');  
		});		
	});
});
```

i can make a pull request, but i am not sure how to integrate the library and the javascript?

**Comment by benjaminkott** [comment]
Hey @brrrrrrrt. i would like to have the package as clean as possible and not to overload it with dependencies - bacause all of them need to be maintained. I think its fairly easy to extend and could also be done by the integrator if he wants to use it.

What do you think am i wrong here?

**Comment by brrrrrrrt** [comment]
@benjaminkott you are absolutely right, this can easily be done by the integrator, i also understand, that you want to keep the code as clean as possible, this is also the reason why i did not create a pull request right away.

**Comment by sbarbieri** [comment]
As much as I am for clean and maintainable code: as an Integrator I also like to minimize standard (integration) for imho standard features like swipe on mobile devices.

**Comment by brrrrrrrt** [comment]
how about a seperate extension? would that be a valuable option?

**Comment by benjaminkott** [comment]
i`ll have a look later on this - there is now a full grunt/bower support so we can maintain these stuff more easy. have to evaluate what libarys to take for this then we can put it just into the package.

**Comment by benjaminkott** [comment]
@brrrrrrrt @sbarbieri ive added swipe support for carousels, please have a look.

**Comment by s-leger** [comment]
Hi,
Hammer is 18k minimified where jquery.touchSwipe 10k
https://github.com/mattbryson/TouchSwipe-Jquery-Plugin
Any reason to use hammer.js ?

**Comment by benjaminkott** [comment]
hey @s-leger, i know its 8 kb more but i want to assure that we are delivering the best we can accross all device types. Hammer.js is making use of the Pointer Events [http://www.w3.org/TR/pointerevents/] that are now also finally adopted by google. That means we have a lib in the background that is indeed a bit bigger - but is way more powerful and future proof than any other solution i could find. 

Most other libs like TouchSwipe are sadly failing on windows enabled touch devices.

**Comment by brrrrrrrt** [comment]
great job @benjaminkott ! just tried current-master, works like a charm!

well 8KB for a wider range of supported devices seams reasonable.
