### ISSUE TITLE
File Downloads aren't displayed correctly

### ISSUE THREAD

**Issue by juschue** [benjaminkott/bootstrap_package#164]
Hi @benjaminkott and other developers,
the bootstrap media list / file downloads with images/preview are not displayed correctly:
The first item is "normal", but the following items are displayed with offset..
Thanks for fixing it/commenting it!
![bildschirmfoto 2015-04-11 um 13 43 20](https://cloud.githubusercontent.com/assets/10188619/7101266/c0ef4f98-e050-11e4-9cb1-47baa4feabc6.png)

**Comment by benjaminkott** [comment]
@juschue, thx for reporting seems that a old version of bootstrap markup was used. is now fixed.
