### ISSUE TITLE
Problem mit gridelements

### ISSUE THREAD

**Issue by LRWphil** [benjaminkott/bootstrap_package#166]
Wenn ich einen Datensatz vom Typ "Text and Icon" innerhalb eines Gridelement-Containers anlegen will kommt nach dem Speichern eine Fehlermeldung "WERT NICHT ERLAUBT".

Wenn ich den Datensatz außerhalb des Gridelements anlege und nachträglich ins Gridelement ziehe, funktioniert es aber.

TYPO3 Version 6.2.11
bootstrap_package	6.2.9 
gridelements		3.1.0

**Comment by benjaminkott** [comment]
Hey, klingt leider eher nach einem GridElements Problem oder einem Configurations. 
Würde damit mal auf Jo Hasenau zugehen der kann dir da bestimmt weiterhelfen. 

Kriegste auf Twitter unter "@bunnyfield" oder direkt im TYPO3 Slack.

**Comment by LRWphil** [comment]
Danke!
