### ISSUE TITLE
HTML5 markup for sub navigation (secondary menu)

### ISSUE THREAD

**Issue by webian** [benjaminkott/bootstrap_package#171]
Hi @benjaminkott!
Following https://github.com/benjaminkott/bootstrap_package/pull/153 I think that also the markup of the sub navigation (lib.navigation.subnavigation) should be changed.

Actually it is:
```wrap = <div class="hidden-print hidden-xs hidden-sm" role="complementary"><div class="list-group">|</div></div>```
it's not semantic and also it's hard to CSS style specifically the secondary menu without altering also any .list-group of the site.

It could be simply changed to:
```wrap = <div class="hidden-print hidden-xs hidden-sm" role="complementary"><nav class="list-group">|</nav></div>```
it's backward compatible and easy to style with a rule like nav.list-group {}

What do you think?

**Comment by benjaminkott** [comment]
@webian hey i am totally fine with it - done
