### ISSUE TITLE
Use extention from global typo3 installation 

### ISSUE THREAD

**Issue by PaulMcGregory** [benjaminkott/bootstrap_package#172]
To use the less lib from a global extention installation, just change the autoload file to

$extensionPath = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('bootstrap_package');
return array(
    'Less_Autoloader'   => $extensionPath . '/Contrib/less.php/Autoloader.php',
);

**Comment by benjaminkott** [comment]
@PaulMcGregory hey, thx for the hint - just changed it.
