### ISSUE TITLE
Images lazyload

### ISSUE THREAD

**Issue by s-leger** [benjaminkott/bootstrap_package#173]
Hi,
Working hard on a solution for images, i've discover some rules.

The number of srcset should be breakpoints + 1

```
images          1         2         3         4         5
breakpoint             1       2        3        4
screen        0      480      768      992     1200
```

JQuery is not able to correctly detect media queries. The reported width is wrong. 
To adress this problem, there is a little lib named "verge".

In order to limit callbacks to responsiveimages on scroll, there is also "jquery.throttle"

Feel free to take inspiration from
https://github.com/s-leger/lef_responsive_images
for the enhanced responsiveimages script and the typoscript configuration of srcset.

**Comment by benjaminkott** [comment]
@s-leger thx will have a look.

**Comment by Outdoorsman** [comment]
https://github.com/benjaminkott/bootstrap_package/issues/187

**Comment by benjaminkott** [comment]
Image handling has been completeley reworked, this should not be a problem anymore. Please see https://github.com/benjaminkott/bootstrap_package/commit/0d35fdcb597249715e2c9eece8f3d2ac57b7de94 for all the changes.

**Comment by netbrothers-tr** [comment]
@benjaminkott This is great news! Do you have a regular release cycle or can you estimate when this will make it into a release?
