### ISSUE TITLE
mailform

### ISSUE THREAD

**Issue by timofo** [benjaminkott/bootstrap_package#175]
i have testet the mailform config and i have some improvements maybe:

please take a look: http://pastebin.com/bBhFRGz3

It looks much better. For example the radio group, the checkboxes etc.
Without the changes, checkboxes are not under the other textfields, radiogroups legend is on the left and looks ugly under the other labels etc. 
textblock, header for example is missing in your config.

**Comment by benjaminkott** [comment]
We moved to the new TYPO3 Form implementation with CMS8, the old mailform is not used anymore.
