### ISSUE TITLE
Base.js typo in lib.stdHeader

### ISSUE THREAD

**Issue by s-leger** [benjaminkott/bootstrap_package#177]
Base.js ~line 296

noTrimWrap = | <span class="news-date">|</strong>|

span-> stong

**Comment by brrrrrrrt** [comment]
this should be fixed already:
https://github.com/brrrrrrrt/bootstrap_package/commit/697bedc47b69ffba1dfa9ff322937e88ed8efd06

https://github.com/benjaminkott/bootstrap_package/pull/143

**Comment by s-leger** [comment]
Ok thanks !
