### ISSUE TITLE
what is the right path for icon within backendLayouts?

### ISSUE THREAD

**Issue by gilas1959** [benjaminkott/bootstrap_package#179]
Hi Benj

I moved my backend layouts to fileadmin dir:

fileadmin/template/BackendLayouts/

and create new BE Layouts; all works fine, but when I modify this line (within a Backend Layout):

icon =  EXT:bootstrap_package/Resources/Public/Images/BackendLayouts/new_icon_name.gif

to change the path where T3 should keep the icons, ie:

icon =  fileadmin/template/BackendLayouts/Images/new_icon_name.gif

or

icon =  FILE:fileadmin/template/BackendLayouts/Images/new_icon_name.gif

or

icon =  ../fileadmin/template/BackendLayouts/Images/new_icon_name.gif

or

icon =  FILE:/fileadmin/template/BackendLayouts/Images/new_icon_name.gif

the BE Layout works correctly but there is no way to show the connected image into the BE (?)

what is wrong? thank you....

**Comment by brrrrrrrt** [comment]
i use icon = ../fileadmin/path/to/the/icon.png

and it works, are sure your path is correct?

**Comment by benjaminkott** [comment]
I am not sure about this, i am using the core functions to resolve the path - will have a look later. 

But why are you putting your stuff into the fileadmin????
Please have a look into: https://speakerdeck.com/benjaminkott/the-anatomy-of-typo3-sitepackages

**Comment by gilas1959** [comment]
Hi thank you very much
it seems that  is working this syntax

icon = ../fileadmin/...etc.../new_icon.gif

I suppose the path is relative to "typo3conf" folder. OK.

About the fileadmin, I moved in it:

* all my new templates and icons
* Resources
* BackendLayouts and subfolder: Images (where I have stored the icons for each web layout)
* another folder named 'ext' where I put some templates of other extensions
* the I have created a folder with the name Typoscript where I put setup.txt and constants.txt that overrides your constants/setup or add new TSobjects
* finally a folder named LOGO where I store the logo

using this method I should to:
* move template folder in a global accessible folder from other sites
* share your bootstrap_package extension putting it into a global accessible folder for other sites

Maybe I'm wrong but I am attempting to separate css styles, etc from the bootstrap extension to customize the template and the update to a new version when needed.

Obviously less.css and other in this case shoud be reloaded within fileadmin.... 
or there is a better solution?!?

thank you very much again!

ALEX

**Comment by benjaminkott** [comment]
In general its completly correct not to make adjustmends in the boostrap_package extension and override it only from the outside, i am only wondering why you put your stuff into the fileadmin?

I would pack the stuff into a custom extension, to handle also all dependencies your website is based on. The talk ive linked is describing this in detail.

**Comment by gilas1959** [comment]
Hi I used the paths above and all is working fine. Today I'm running your +ext  v.6.2.8.
However I attempted to install the new 6.2.10 and unfortunately some things are not working (carousel, 2nd level menu [top]) etc. Maybe I should adjust some templates, stiles, etc. to migrate from 6.2.8.
The fact is that I'm worried because in the future if I continue to use 6.2.8:
* I can't improve bugs or templates
* cannot get compatibility with newer version of PHP
Obviously with a bit of patience I can see the differences and merge the modules to obtain the newer version of your ext. 
Please comment, thanks

**Comment by benjaminkott** [comment]
Between 6.2.8 and 6.2.10 there was noting critical changed so everything should still work as expected. Can you provide me some more detailed informations about this so i can have a look at whats going wrong exactly?

You can hit me anytime on slack for a private conversation.

**Comment by gilas1959** [comment]
good. Let me reorganize and prepare a complete report and we can continue in private conversation. 
Today I registered the demo-domain; I'll send you the username/password so you can inspect the code faster and easily.

**Comment by benjaminkott** [comment]
@all is this still an issue?

**Comment by gilas1959** [comment]
Forgive me benj for my absence. This was to extra-work due to cookie policy and several mods to my sites.
At first sight it seems linked to some modification made (I suppose) with CSS or something.
Updating the site to the new (6.2.10) version of bs, the carousel doesn' work more.
Tomorrow (monday) I'll check the problem again (inspect the code and replace CSS).
Within 2-3 days I'll recontact you with the promised report.
Thank you again for your availability

**Comment by gilas1959** [comment]
HI, I have a test site (I can give you user/password and url) and when I update from 6.2.8 to 6.2.10:

* carousel doesn't work (button < and > appear but the carousel do not run; still stopped at first image
* secondary menus doesn't appear

I have seen your log and there was some changes to:

[TASK] HTML5 markup for sub navigation
maybe I should change my templates (?)

[TASK] Carousel: allow to set the max width of background images
(?)

Please tell me what can I do.... or I will send you the credentials.
Infact switching back to 6.2.8 all is working, but if I update to 6.2.10 there is some problems.

Maybe there is some code on my fileadmin/template folder to change...

any ideas?!?

thank you for your great work!

**Comment by benjaminkott** [comment]
@gilas1959 can you please join slack so we can have a talk there? https://forger.typo3.org/slack

**Comment by gilas1959** [comment]
dear benj
thank you for your patience; connecting to 
 https://forger.typo3.org/slack
I can't register (@###grrr!) there is something wrong, because the last name field, filled OK has been not accepted (!).

**Comment by benjaminkott** [comment]
mmm... they just fixed something about the lastname validation that did not accept spaces. sounds stupid but just enter something - you can change your first and lastname later within the slack settings ^^

**Comment by gilas1959** [comment]
Forgive me for this never ending story,
but I have not whitespaces.
Now I'm going to open a ticket and tell them to check for this stupid error.
thank you




Da: "Benjamin Kott" notifications@github.com
A: "benjaminkott/bootstrap_package" bootstrap_package@noreply.github.com
Cc: "gilas1959" at@specialistaweb.it
Data: Mon, 08 Jun 2015 02:52:24 -0700
Oggetto: Re: [bootstrap_package] what is the right path for icon within backendLayouts? (#179)

**Comment by benjaminkott** [comment]
Solved this in private.
