### ISSUE TITLE
inclusion of external BE templates

### ISSUE THREAD

**Issue by gilas1959** [benjaminkott/bootstrap_package#180]
Hi,
moving the templates to an external path, such as within:

fileadmin/template/BackendLayouts

if I use the INCLUDE TYPOSCRIPT
<INCLUDE_TYPOSCRIPT: source="DIR:FILE:fileadmin/template/BackendLayouts/" extensons="txt" />

nothing works; templates are not included; instead if include one file at time. ie:

<INCLUDE_TYPOSCRIPT: source="FILE:fileadmin/template/BackendLayouts/my_template.txt" />

all works fine.

Moreover after moved and included all seems to work without problems, but still persists a problem. Columns are correctly shown into BE and I can drag'n'drop contents from a column to another, but TYPO3 cannot understand which columns are vailable, the field "columns" display only left/right/normal/border choices.

Forgive me I post this here because I do not know if this is a problem linked to your +ext or something not working in TYPO3.

**Comment by benjaminkott** [comment]
Trying to understand where the root of the problem is, is this about a Template that could not be found or that the BackendLayouts are not displayed in the Backend?

**Comment by gilas1959** [comment]
? damn !? html was cleaned up, then there is not some lines on my post.
this should be visible:

INCLUDE_TYPOSCRIPT: source="FILE:fileadmin/template/BackendLayouts/my_be_layout.txt"

works correctly

but this:

INCLUDE_TYPOSCRIPT: source="DIR:FILE:fileadmin/template/BackendLayouts" extensions="text"

to fetch all BE templates, doesn't works: no templates are loaded and available for the BE.

thanks

**Comment by brrrrrrrt** [comment]
INCLUDE_TYPOSCRIPT: source="DIR:FILE:fileadmin/template/BackendLayouts" extensions="**text**"

will only work when your files have the extension .text

--

but i think i know what you mean, you can see the correct layout in the page module, but when you edit a contentelement, in the column-dropdown you only have the default columns and not the columns of your backendlayout?

**Comment by brrrrrrrt** [comment]
i also noticed, in listview, when you make the columns visible by selecting them from the list of db-fields, they are never shown by their name as set in the backendlayout (instead the default names are shown: left, right, normal, border, everything else shows only the number), maybe this is also what is experienced as "*TYPO3 cannot understand which columns are vailable*".

**Comment by gilas1959** [comment]
HI, about the INCLUDE_TYPOSCRIPT I have tried again today in this way:

adapt the original code found within the boostrap package file: web_layouts.txt; this is the code:

INCLUDE_TYPOSCRIPT: source="DIR:EXT:bootstrap_package/Configuration/PageTS/Mod/WebLayout/BackendLayouts" extensions="txt"

changed it to:

INCLUDE_TYPOSCRIPT: source="DIR:FILE:fileadmin/template/BackendLayouts"  extensions="txt"

obviously the BE layout files stored in the folder have the extension: .txt and (as you can see above) the extension name is right.

but this doesn't works....

**Comment by brrrrrrrt** [comment]
source="**DIR:FILE**:fileadmin does not make any sense, try: source="DIR:fileadmin

**Comment by gilas1959** [comment]
Damn...... this confused me infact the original syntax was:

INCLUDE_TYPOSCRIPT: source="DIR:EXT:bootstrap_package/Configuration/PageTS/Mod/WebLayout/BackendLayouts" extensions="txt"

and I supposed to substitute DIR:EXT with DIR:FILE: followed by the new path....

now it works with:

INCLUDE_TYPOSCRIPT: source="DIR:fileadmin/path/to/dir"  extensions="txt"

then I close this comment,

thank yoy very much
