### ISSUE TITLE
Carousel slider with responsive Images

### ISSUE THREAD

**Issue by omittelstaedt** [benjaminkott/bootstrap_package#181]
I changed the carousel slider to support only images (without heading or text, so its an images slider) and changed it to have the image not in the background but instead as html img tag. I needed this change because the height of the slider should automatically be changed, when resizing the window (so the full image is allways shown). 

At the moment I have changed the template (file "Carousel.html") to use the img tag like this (it works because the variable backgroundImagePath is set in the upper part of the template):
```
<div class="item{f:if(condition: iteration.isFirst,then:' active')} carousel-item-type carousel-item-type-{item.item_type}" data-itemno="{iteration.index}" style="{itemStyleColor}">
  <img src="{backgroundImagePath}" />
  ...
</div>
```
But now I want to have the slider output the images as responsive images (the same way as content images are rendered with data-bigger attribute, etc). So the output should be like this:
```
<div class="item{f:if(condition: iteration.isFirst,then:' active')} carousel-item-type carousel-item-type-{item.item_type}" data-itemno="{iteration.index}" style="{itemStyleColor}">
  <img src="img1.jpg" data-bigger="img2.jpg" data-large="img3.jpg" ... />
  ...
</div>
```

I tried a lot of things to do this, but I just don't get it done. Do you know a good/easy way how to do this?

I tried to use the Uri-ImageViewHelper to create images with different widths – but the ViewHelper always returned the URL to the original image instead of creating new images with the new width. How can I do this?

**Comment by benjaminkott** [comment]
@omittelstaedt please pick up the discussion in #356 i am closing this ticket to collect all requirements of the carousel at a single ticket.
