### ISSUE TITLE
Media Object

### ISSUE THREAD

**Issue by juschue** [benjaminkott/bootstrap_package#183]
Hi together,
in the last time i missed the functionality to create a image list like given (from bootstrap) the media object. Maybe it's possible to implement a function like it's already realized for a panel or accordion.
My wish is to have a several blocks containing an image and some text besides. At the moment i only can create some text with image items, which may be have different sizes (because of the image size).
Is this realizable? Many thanks for your work so far.
Have a nice day!

**Comment by benjaminkott** [comment]
@juschue ive added media options to the accordion and tabs, do you see a need for an additional ce?

**Comment by juschue** [comment]
@benjaminkott that sounds nice!
I'll try it out and give my review, but I think that'll be enough. :+1:

**Comment by benjaminkott** [comment]
@juschue since no more feedback was provided - i think we can close this issue as resolved
