### ISSUE TITLE
How to solve hidden responsive images

### ISSUE THREAD

**Issue by eduludi** [benjaminkott/bootstrap_package#184]
In some cases, the responsive images are not being loaded. This happens mostly because the `.checkviewport()` is executed only on `load`, `resize` or `scroll`. So, wherever the image should be displayed but except on these mentioned events, you must execute `.checkviewport()` by your own.

There is a lack of documentation on how to do this, and is not so clear by looking at the code. Turns out that the latest versions includes plugin's object into a `data-*` attribute. So, to access that object you can do something like this:

``` javascript
$('img.lazyload').each(function(index, img) {
  var resImg = $(img).data('bk2k.responsiveimage');
  if (resImg) resImg.checkviewport();
});
```

In the case of Carousel, you need to include something like this on page's load:

``` javascript
$('.carousel').find('img.lazyload').data('skip_invisible', false);
```

Please, there are some better ideas or solutions for this?

**Comment by s-leger** [comment]
Scroll / resize events are bound to window (container).
so forcing checkviewport() by triggering event like this should work
```javascript
$(window).trigger('scroll.bk2k.responsiveimage');
```
@benjaminkott As a side note skip_invisible should be set to FALSE by default as jQuery :hidden is far from being safe and may lead to images not loading on page load under some conditions in chrome at least.
