### ISSUE TITLE
Show Content from Page

### ISSUE THREAD

**Issue by MariaSaarland** [benjaminkott/bootstrap_package#185]
Since version 6.2.8 the " Show Content from Page" no longer works.
In version 6.2.4 this works yet. 
The template is displayed correctly; are not the content. 
This problem is also described on http://www.typo3forum.net/forum/typo3-installation-updates/76025-introduction-package-6-2-8-show-content-page.html

About feedback I would be very happy
Maria

**Comment by benjaminkott** [comment]
@MariaSaarland hey, i can reproduce this issue and trying to find an easy solution for this.
