### ISSUE TITLE
Make image lazy loading optional

### ISSUE THREAD

**Issue by sbarbieri** [benjaminkott/bootstrap_package#187]
It would be great to be able to make image lazy-loading configurable (on/off). We have some sites where the client wants to print out (or make a pdf through the print dialog - we therefore have a print.css) and when images are off-screen on a long content page (and the client does not scroll down) the images are just not yet loaded. The result in the print dialog preview are missing images - that's the reason why I would appreciate a configurable option.

**Comment by eduludi** [comment]
+1

**Comment by gitChriss** [comment]
+1

**Comment by Outdoorsman** [comment]
+1

**Comment by s-leger** [comment]
Hi guys,
With recent js plugin, you may enable this feature by typoscript. It simply disable inviewport check of the lazy load plugin, so images are loaded even when not visible. Pushed modifications to allow to setup this by constant editor in a next release, but until then :

In template mode, select the root page of your tree, select Info/modify from the dropdown list on top, then edit the setup part and put the following.

tt_content.image.20.1.params = class="lazyload" data-preload="true"

**Comment by benjaminkott** [comment]
lazyloading can be disabled by setting 

```
plugin.bootstrap_package_contentelements.preload.images = 1
```

**Comment by KreativeKrise** [comment]
> lazyloading can be disabled by setting
> 
> ```
> plugin.bootstrap_package_contentelements.preload.images = 1
> ```

This seems not possible anymore. It seems lazy loading is hard coded now.
