### ISSUE TITLE
Update deprecated TCA definitions

### ISSUE THREAD

**Issue by Chrissitopher** [benjaminkott/bootstrap_package#192]
Since TYPO3 7.3, running bootstrap_package gives these deprecation warnings:

> Automatic TCA migration done during boostrap. Please adapt TCA accordingly, these migrations will be removed with TYPO3 CMS 8. The backend module "Configuration -> TCA" shows the modified values. Please adapt these areas:
Changed showitem string of TCA table "tt_content" type "bootstrap_package_panel" due to changed field "bodytext".
Changed showitem string of TCA table "tt_content" type "bootstrap_package_listgroup" due to changed field "bodytext".
Changed showitem string of TCA table "tt_content" type "bootstrap_package_texticon" due to changed field "bodytext".
Changed showitem string of TCA table "tx_bootstrappackage_carousel_item" type "html" due to changed field "bodytext".
Migrated t3editor wizard in TCA of table tx_bootstrappackage_carousel_item field bodytext to a renderType definition with columnsOverrides in type html.

The new definitions are in "Configuration -> TCA"!

**Comment by benjaminkott** [comment]
Did you actually read the messages? It´s good to know that the new renderTypes patch for formengine merged, somehow i missed it. But your comment makes not sense?

**Comment by Chrissitopher** [comment]
Basically I only repeated what the deprecation message already says. ;-) If you know how to adjust the definitions, that's fine. If you don't, you can check the "Configuration" BE module. It will display the updated definitions.
