### ISSUE TITLE
Tab: Default tab options

### ISSUE THREAD

**Issue by brainformatik** [benjaminkott/bootstrap_package#197]
Hi.

"default tab options" displays all tabs from all content ids, but it should only display for the current content id.

Problem:
```xml
<foreign_field>tt_content</foreign_field>
```

Solution:
```xml
 <foreign_table_where>
    AND tt_content = ###THIS_UID###
</foreign_table_where>
```

**Comment by benjaminkott** [comment]
@brainformatik thx for pointing this out - fixed!
