### ISSUE TITLE
Carousel: Slide in Safari

### ISSUE THREAD

**Issue by brainformatik** [benjaminkott/bootstrap_package#198]
Hi.

slide transition doesn't work in safari.

In line (6.2):
https://github.com/benjaminkott/bootstrap_package/blob/BP_6-2/Resources/Public/Less/Theme/carousel.less#L84

In line (master):
https://github.com/benjaminkott/bootstrap_package/blob/master/Resources/Public/Less/Theme/carousel.less#L190

Problem

``` css
transform: none;
```

Solution

``` css
.translate3d(0,0,0);
```

**Comment by benjaminkott** [comment]
6.2 is not supported anymore. master is tested and working fine.
