### ISSUE TITLE
OnePage Links

### ISSUE THREAD

**Issue by piccaso** [benjaminkott/bootstrap_package#200]
Recently I created (my first...) Single Pager with this Extension and I noticed that Links in the Content are actually links to a page (`?id=123`) instead of Links to an anchor (`#p123`) while Links in the menu are fine.
I skimmed through the package source (and documentation) and did not find anything that would take care of these links. Furthemore if one of these links is clicked the sorting of the sections is differen (clicked one first).

Is there anything I have missed in the Extension which would counteract with this behaviour?
I must admit, i don't even understand where the sorting is done, if Its in `lib.content.onepage` then I can't see it :)

Right now I have a ['15 minutes hack' javascript solution](https://gist.github.com/piccaso/ee44c03d4d0c6ff73801) which does not cover all situations...
Btw.: If this is by design please tell me where sorting happens, i want to disable it.

Thanks!

**Comment by criwe** [comment]
Hi! 
Did you add both static templates or only the one for the onpages (which should be right). I set up a testsite and it worked fine.
Greets

**Comment by piccaso** [comment]
Only the onepage template, but i also tried both...
Are you sure you are talking about links which are not part of navigation?
I had time to look at the source more closely and IMO this could only be done right using hooks like `typoLink_PostProc` (yes i know my solution is not ideal...) but i did not find any indication of something like this or similar...

Maybe i should explain better - i'll try.

Consider a Pagetree like this:
```
  * root (id=0)
  \-* Home (has template record, id=1)
    |- Section-A (id=2)
    |- Section-B (id=3)
    \- Section-C (id=4)
```

If you create a Link form `Section-C` to `Section-A` then 
the link will look like `"index.php?id=2"` instead of  `"#p2"`.

If you create a Link from `Section-B` to a Element with the id 64 on `Section-C`
 the link will look like `"index.php?id=4#c64"` instead of `"#c64"`.

Im only talking about links which are generated by [typoLink](https://github.com/TYPO3/TYPO3.CMS/blob/TYPO3_6-2/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php#L5759-L6228) or something that makes use of it (like f:link) and not navigation (`lib.navigation.main`), which is handled in [OnePage/setup.txt](https://github.com/benjaminkott/bootstrap_package/blob/v6.2.13/Configuration/TypoScript/OnePage/setup.txt#L29-L45) and there would not be any need to handle it there if some kind of typoLink hooking mechanism was in place...

From what i understand this just isn't implemented/supported and i'll keep my js workaround until i have the time to implement a server side solution, which probably is not an easy task since it will potentially conflict with realurl... 
Or someone else comes up with a better idea :)

**Comment by criwe** [comment]
Oh, I ment the navigation.. sorry.

**Comment by benjaminkott** [comment]
thx for your report @piccaso , but we dropped the experimental onepage setup. i will close this for now
