### ISSUE TITLE
Hover menu fold out?

### ISSUE THREAD

**Issue by LasseTK** [benjaminkott/bootstrap_package#205]
I am new to this package, but find it quite interesting and easy to setup. I have however one thing that I do not seem to be able to configure for a client.

The client would like the menu to fold out when the mouse hovers the menu item, rather than having to click the menu item.

Is it possible to select an option that would enable the menu to fold out when hovering the mouse over the menu item in the main navigation?

**Comment by sbarbieri** [comment]
+1

**Comment by phvt** [comment]
Bootstrap's dropdown "toggle" behavior creates consistency across keyboard, touch and pointing device navigation.

To open menus on :hover with Bootstrap 3, you can just put this in your CSS:

```css
.dropdown:hover .dropdown-menu {
	display: block;
}
```

**Comment by benjaminkott** [comment]
resolved with https://github.com/benjaminkott/bootstrap_package/commit/4b8baeec27de99b65a7a38cb7001be34c51133b9
