### ISSUE TITLE
Wrong order in language menu (footer)

### ISSUE THREAD

**Issue by fnagel** [benjaminkott/bootstrap_package#206]
Language config is: en=0, de=1, dk=2
See https://github.com/benjaminkott/bootstrap_package/blob/master/Configuration/TypoScript/setup.txt#L674-L692
This matches the BE records for localization.

See this config:
https://github.com/benjaminkott/bootstrap_package/blob/master/Configuration/TypoScript/setup.txt#L69
https://github.com/benjaminkott/bootstrap_package/blob/master/Configuration/TypoScript/setup.txt#L75

This results in following order in menu: en, dk, de which is wrong.

Menu should look like this:
````
NO {
	stdWrap.override = English || Deutsch || Dansk
	stdWrap {
		typolink {
			additionalParams = &L=0 || &L=1 || &L=2
			ATagParams = hreflang="en-GB" || hreflang="de-DE" || hreflang="da-DK"
		}
	}
}
````

**Comment by fnagel** [comment]
This issue should have been closed as it was fixed.

**Comment by cedricziel** [comment]
Maybe I used the wrong message tag on the commit-dunno. Thanks for closing.
