### ISSUE TITLE
FLUID only  (without CSS Styled Content)

### ISSUE THREAD

**Issue by konstantin83** [benjaminkott/bootstrap_package#207]
It it possible to use bootstrap_package without CSC? Currently CSC is a dependency.

**Comment by benjaminkott** [comment]
I am planning to do this in the future, but i am waiting until the new content elements for CMS7 are done then i will backport the dataprovider stuff.

**Comment by konstantin83** [comment]
Thanks for you reply. New content elements are going to be created ин Typo3 team? Never heard of this...

**Comment by konstantin83** [comment]
by*

**Comment by benjaminkott** [comment]
With CMS7 there will be new default Content Elements based on Fluid and and DataPreProcessors that are currently under development. There is a group on the TYPO3 Slack working on this. If you want to participate on this or follow the development. 

#cig-ext-frontend is the channel on Slack.
https://forger.typo3.org/slack

**Comment by benjaminkott** [comment]
Closing this for now. Please open a new Issue if you have other questions.
