### ISSUE TITLE
Carousel HTML in header

### ISSUE THREAD

**Issue by rtgmbh** [benjaminkott/bootstrap_package#208]
Hi,
when I use HTML in the header of a carousel item it's not parsed.

e.G.To get a superscript trademark r <sup>®</sup> I use the "sup" tag

--Stephan

**Comment by phvt** [comment]
Hello Stephan,

Fields of type 'input' are passed through htmlspecialchars(). The Carousel header is like tt_content.header in this limitation.

You could put your header tag with superscript into the bodytext field of the carousel item. This field is designed to accept HTML content and has XSS protection.

Paul

**Comment by benjaminkott** [comment]
@rtgmbh @phvt please pick up the discussion in #356 i am closing this ticket to collect all requirements of the carousel at a single ticket.
