### ISSUE TITLE
Issue with a new backend layout

### ISSUE THREAD

**Issue by juschue** [benjaminkott/bootstrap_package#209]
Hi together,
i got an issue, if i try to add a backend layout at the root page of my website. I attached the config at the end of this post. It should produce a row, e.g., for the carousel, and further the layout as in "Default, Subnavigation Right". But if I select this new layout, I get the "header" row and below only one column with the "normal" content and no subnav.
It seems, that this doesn't work since TYPO3 7.X.X.
May someone has a useful hint? Ignore the name read out of the system language file (I saw that this will be changed).
Thanks,
juschue

```
backend_layout {
	colCount = 6
	rowCount = 3
	rows {
		1 {
			columns {
				1 {
					name = LLL:EXT:cms/locallang_ttc.xlf:colPos.I.3
					colPos = 3
					colspan = 6
				}
			}
		}
		2 {
			columns {
				1 {
					name = LLL:EXT:cms/locallang_ttc.xlf:colPos.I.1
					colPos = 0
					colspan = 5
				}
				2 {
					name = LLL:EXT:bootstrap_package/Resources/Private/Language/Backend.xlf:backend_layout.column.subnav
					colspan = 1
				}
			}
		}
		3 {
			columns {
				1 {
					name = LLL:EXT:bootstrap_package/Resources/Private/Language/Backend.xlf:backend_layout.column.footer1
					colPos = 10
					colspan = 2
				}
				2 {
					name = LLL:EXT:bootstrap_package/Resources/Private/Language/Backend.xlf:backend_layout.column.footer2
					colPos = 11
					colspan = 2
				}
				3 {
					name = LLL:EXT:bootstrap_package/Resources/Private/Language/Backend.xlf:backend_layout.column.footer3
					colPos = 12
					colspan = 2
				}
			}
		}
	}
}
```

**Comment by benjaminkott** [comment]
The Configuraiton of the BackendLayout seems to work fine, and also the backend renders it correctly. 
Did you assign a Template for the BackendLayout after adding for the frontend?

**Comment by juschue** [comment]
Hi @benjaminkott,
I added the bootstrap package and the default css to the root template of my site. In the backend the layout is, as you already said, displayed correctly. But the frontend only renders the "Rand" and "Normal" Column. Or how do I assign a template for the backend layout? Thanks for checking

**Comment by benjaminkott** [comment]
You will need to map the key thats inserted into the database to a template. 

Record: uid
PageTS: pagets__<templatename>

Note that the prefix will change with the upcomming release for Configurations via PageTS (https://github.com/benjaminkott/bootstrap_package/blob/master/Configuration/PageTS/Mod/WebLayout/BackendLayouts/default.txt). If youre not on current master of the boostrap_package the provider key is still bootstrap_package__ and not pagets__ (update will be done by tuesday)

https://github.com/benjaminkott/bootstrap_package/blob/master/Configuration/TypoScript/setup.txt#L345-L391

**Comment by juschue** [comment]
I linked the layout with the template but I used the wrong "path" in PageTS.
I'm not on the current master, but I'm on the next release and I'll update the entries next week.
Thank you for helping!
