### ISSUE TITLE
internal server error after installing v6.2.14 on PHP 5.4

### ISSUE THREAD

**Issue by brrrrrrrt** [benjaminkott/bootstrap_package#213]
it seems **class.ext_update.php** is not compatible with PHP 5.4?

after clicking to update the extension, the extension manager breaks / shows an empty page.
no errors logged, either in typo3 log, php log or apache error log - extensionmanager becomes unusable as it shows an empty page only.

after renaming class.ext_update.php the extension manager works again (but no db update has been done)

i am not sure whats the exact cause, but it must be within class.ext_update.php (i know PHP 5.4 is far from up2date, but may be still around...)

**Comment by benjaminkott** [comment]
@brrrrrrrt yeah, i see the problem - we currently going to make of atleast PHP 5.5 because 14th September 2015 is EOL for 5.4. I am unsure about how to handle this.

**Comment by benjaminkott** [comment]
@brrrrrrrt will check the code this evening and will provide a PHP 5.3 patch.

**Comment by neufeind** [comment]
Customer stepped into the same trap. Broken extension-manager without any sign of reason *sigh* Would be great if you could get this one-liner in

**Comment by cedricziel** [comment]
Resolved by #216 

Please update to git master or cherry-pick the commit.
