### ISSUE TITLE
Typo3 Extension-Manager gets lost after Update to 6.2.14

### ISSUE THREAD

**Issue by ULinn** [benjaminkott/bootstrap_package#218]
Typo3 6.2.14, bootstrap_package 6.2.13: everything OK

Update via extensionmanager to 6.2.14: 
Now Extension-Manager shows only a blank page, without any error-message

Everything else in frontend and backend works fine.
Provider checked server-log - everything seems to be fine.
Cleared all cashes etc. - still the same problem.

Other users seem to face the same problem:
http://www.typo3forum.net/forum/typo3-extensions/76773-bootstrap_package-6-2-14-killt-extension-manager.html

**Comment by cedricziel** [comment]
Please use a current git-clone and try again. (And please report back! :) )

@neufeind sent a patch that fixes a bug where we expect Users to be on PHP 5.5-but only in the Extension Manager

**Comment by ULinn** [comment]
I did neufeind's changes on class.ext_update.php - now everything workts fine.
Thank you!

**Comment by neufeind** [comment]
just for reference: that was the fix from #216
