### ISSUE TITLE
SASS

### ISSUE THREAD

**Issue by klodeckl** [benjaminkott/bootstrap_package#22]
How about SASS support? There is already a bootstrap port to SASS.

**Comment by CREEATION** [comment]
You should consider Sass support in the future, as Bootstrap is moving from LESS to Sass in [version 4](http://blog.getbootstrap.com/2015/08/19/bootstrap-4-alpha/).

**Comment by cedricziel** [comment]
I would like SASS support as well - but as neither me nor Benjamin use the package with SASS (I for once solely use external builds for the assets), this would be the perfect piece for some easy pick contribution.

**Comment by benjaminkott** [comment]
I´ve created a feature ticket for sass and bootstrap 4 to collect the duplicates please see #355
