### ISSUE TITLE
Language selection --> upper right

### ISSUE THREAD

**Issue by newenduser** [benjaminkott/bootstrap_package#228]
Hi guys!

I know that you already talked about the position of the language selection (e.g. Language detection / selection needs improvement. #65).

We are doing an international project at the moment. I would like to emphasize that all our overseas testers simply did not find the language selection. Unfortunately the auto-detection plugin (we use) didn´t work either, so they landed on the German page - and were lost.

I like the suggestion from the thread above (icon upper right) a lot. Users do expect to select the language in the upper right corner. They do not look anywhere else. Please bear in mind that a cog icon rather indicates "settings" than "languages". The only icon working maybe the flag.

What I personally would like even more (than an icon) is to have the abbreviation for the current language shown (e.g. "DE" or "EN") and then opening a small modal with all languages available, if the user clicks.

Again, I know you already talked about this, but for us it´s somehow crucial, since - in my eyes - people need to have the navigation for the sites the way they are used to.

Thanks a lot for looking into this again!!!

**Comment by webian** [comment]
Hi,
why did you open a new issue instead of replaying #65?

**Comment by cedricziel** [comment]
Not to sound harsh, but @webian has a point there. Please continue the discussion on #65.

While overriding the behaviour is close to trivial - I also suggest you send a pull request of a solution that fits your needs. We do understand that it's important for you, but please consider helping us out here with your solution.

I'll close this in the confidence that you might show off what you accomplished in #65

Cheers,
Cedric
