### ISSUE TITLE
Beginner's question: content not rendered / no template in the frontend used

### ISSUE THREAD

**Issue by webroko** [benjaminkott/bootstrap_package#230]
Sorry for a typical beginner's question:

I've installed bootstrap_package on a freshly installed 6.2.14. version of typo3.
I followed the steps described in bootstrap_package's "Quick Install Guide" from the repository.

The Problem is: Content that is entered in the backend is not displayed in the frontend. 
The header of the page gets rendered as should be.

My assumption:
Looking at the html of the rendered page I can see that within the <body> of the page there is no template used. The bodytag is simply empty. Therefore I guess that there is a problem with the link to the template files. 

Question: Where can I check or change the path to the template files? Or is there another way that includes the templates?

Robin

**Comment by webroko** [comment]
Finally figured out what caused the problem:

Since I was using a freshly installed version of typo3 the default hello world page setup was still in place overwriting the page setup of bootstrap_package. 
Deleting the default lines solved the problem.
Maybe this should be added to the "Quick Install Guide".

Hope it helps other beginners.

Robin

**Comment by jkkoenig** [comment]
I had the same, took some time until I found this...

**Comment by cedricziel** [comment]
Thank you for the hint, I added a line to the QuickStart which states you should clear the initial TypoScript setup if any in #420 .
