### ISSUE TITLE
change backend icons for 'text & icon'

### ISSUE THREAD

**Issue by fibfab** [benjaminkott/bootstrap_package#238]
Hi,

i tried to change the default glyphicons in the constants but i didn't find a possibility to change it in the backend under the element 'text & icon'. Is there a way to refresh the icon previews?

Thanks a lot.
Fabian

**Comment by benjaminkott** [comment]
@fibfab please pick up the discussion in #357 i am closing this ticket to collect all requirements of the texticon ce at a single ticket.
