### ISSUE TITLE
Carousel item - color issues - possibility to hide headers

### ISSUE THREAD

**Issue by theorak** [benjaminkott/bootstrap_package#240]
Two options could allow the user to hide the header:
1) Using 'transparent' as color setting works, but not with the input field - its not large enaugh
![image](https://cloud.githubusercontent.com/assets/11176401/9905780/3aee34a0-5c87-11e5-9a55-89be30d3e4ea.png)

2) Add a header layout option - hidden (more user friendly)

One isse with colors also is:
In the merged CSS files, the font color settings for headings can overwrite the color for the carousel item.

**Comment by benjaminkott** [comment]
@theorak please pick up the discussion in #356 i am closing this ticket to collect all requirements of the carousel at a single ticket.
