### ISSUE TITLE
Update "iconfile" definitions

### ISSUE THREAD

**Issue by Chrissitopher** [benjaminkott/bootstrap_package#241]
Inside Configuration\TCA\ the definition for "iconfile" needs an update:

Using a relative path like 
``'iconfile' => ExtensionManagementUtility::extRelPath('bootstrap_package') . ....``
is deprecated.

Use ``'iconfile' => EXT:`` instead!

**Comment by benjaminkott** [comment]
@Chrissitopher thx for the hint, already resolved - icons are now registered through the iconregistry
