### ISSUE TITLE
Update "items" array in Configuration\TCA\tx_bootstrappackage_carousel_item.php

### ISSUE THREAD

**Issue by Chrissitopher** [benjaminkott/bootstrap_package#242]
The "items" array in Configuration\TCA\tx_bootstrappackage_carousel_item.php currently references the deprecated i/ path.

Update these four occurences to use ``EXT:`` syntax!

[tx_bootstrappackage_carousel_item.columns.item_type.config.items] i/ within the path (tt_content_header.gif, tt_content_textpic.gif, tt_content_image.gif, tt_content_html.gif) in items array is deprecated, use EXT: reference

**Comment by benjaminkott** [comment]
@Chrissitopher thx for the hint, already resolved - icons are now registered through the iconregistry
