### ISSUE TITLE
svg not supported?

### ISSUE THREAD

**Issue by newenduser** [benjaminkott/bootstrap_package#250]
Hi guys! Today I wanted to exchange graphics that I had uploaded as png files. Due to high density display requirements I wanted to use svg files instead to get better quality. Unfortunately the "add image" function doesn´t recognize any svg files. Is there a special reason for that? If no, wouldn´t you agree that svg makes more sense than png when talking about vector files? Thanks for any help!

**Comment by benjaminkott** [comment]
hey @newenduser 

What TYPO3 version do you use? 
SVG is supported since Version 7 if i remember correctly.

**Comment by newenduser** [comment]
@benjaminkott Hi Benjamin! Ok, I´ve missed that! We are still on 6.2 since 7.x is not LTS yet, is it? So this won´t be an issue any more once we will update, I suppose. Thanks for pointing this out! Have a great day!

**Comment by benjaminkott** [comment]
@newenduser 7 LTS is in preparation for todays release. So youre not going to party today? ;)
https://wiki.typo3.org/Release_Party/TYPO3_7

**Comment by newenduser** [comment]
@benjaminkott If I had only known this earlier...I mean the party!!! ;-)
