### ISSUE TITLE
a constant to move LESS files into another location

### ISSUE THREAD

**Issue by gilas1959** [benjaminkott/bootstrap_package#251]
Hi benj
maybe I'm wrong but it seems that I cannot find any constant to use some less files from another folder, i.e. fileadmin, so that I can  (i.e. that for Theme) modify or add new ones.

**Comment by benjaminkott** [comment]
hey @gilas1959, there is none you need to include/override them manually in your typoscript configuration and then just add your stuff to the less files

```
page {
    includeCSS {
        theme = EXT:myext/Resources/Public/Less/theme.less
    }
}
```


```
// Bootstrap Package Location
@boostrap-package-less-path: '../../../../bootstrap_package/Resources/Public/Less/';

// Bootstrap Package Theme
@import '@{boostrap-package-less-path}Theme/theme.less';

// Your Stuff
@import 'Modules/header.less';
```

**Comment by gilas1959** [comment]
great! It works correctly and as expected.
With this I can keep separate my less with your bootstrap_package less and modify/add some new styles.
