### ISSUE TITLE
Create a new Less file and the system not show

### ISSUE THREAD

**Issue by victorhtorres** [benjaminkott/bootstrap_package#253]
Hi Benjamin,

I have some problems when I try to create or upload a new file on less in public/less/theme because, when the file is uploaded or created with some new style, for example "custom.less" and later I put the @import method in theme.less file to get the new style in frontend but nothing happens.

I cleaned my cache, I changed many configuration on the typoScript object but nothing.

Any idea what is wrong?

I am using typo3 7.4.0 with bootstrap package 6.2.15 version.

**Comment by benjaminkott** [comment]
@victorhtorres if you only get a white page, please check your memory limit in php.ini. should be atleast 256mb

**Comment by benjaminkott** [comment]
i am closing this issue now because it seems there are no more questions to this topic
