### ISSUE TITLE
Website is white when i 've made  Css changes in the Typoscript constants file of bootstrap 

### ISSUE THREAD

**Issue by Costenzo** [benjaminkott/bootstrap_package#259]
i use the 6.2.15 Version on a .6.2 LTS Version. I guess i've some problems to compile the less files, but unfortunatley i don't get the point which one. Maybe someone have an idea.
thxs for any response

**Comment by benjaminkott** [comment]
The only known reason for this is that you do not have enough memory assigned in your webserver configuration, you should at least set your memory_limit to 128mb better 256mb in your php.ini
