### ISSUE TITLE
invalid div-structure if showFooter is not active

### ISSUE THREAD

**Issue by VeraSpiegel** [benjaminkott/bootstrap_package#260]
Resources/Private/Layouts/Page/Default.html  has an if-condition on showFooter witch includes 2 div-tags and TYPO3SEARCH_end. 
If i deactivate the Footer the div-structure ist invalid and TYPO3SEARCH_end is not set. 
Solution: move div-Tags out of if-Condition.

**Comment by benjaminkott** [comment]
Did you manually set show footer and showheader?

**Comment by VeraSpiegel** [comment]
Yes, i set in in my template using

page.10.variables.showFooter.value= 0

 

 

Von: Benjamin Kott [mailto:notifications@github.com] 
Gesendet: Dienstag, 17. November 2015 11:39
An: benjaminkott/bootstrap_package
Cc: VeraSpiegel
Betreff: Re: [bootstrap_package] invalid div-structure if showFooter is not active (#260)

 

Did you manually set show footer and showheader?

**Comment by benjaminkott** [comment]
@VeraSpiegel as noted in the edited comment, it is not intendet to be set manually - the showHeader and showFooter variables are used to render the OnePage Setup correclty and both must be disabled to get a correct valid result. It is used to render the same templates for both variations of Output. I have no clue how to solve this better, so a fix will not be available soon - as it is also not intended to be used like that. 

If you need a different layout i would recommend override the layout paths and deliver custom templates with the changes you need.

**Comment by benjaminkott** [comment]
i am closing this issue now because it seems there are no more questions to this topic
