### ISSUE TITLE
ERROR: Content Element type "textmedia" has no rendering definition! 

### ISSUE THREAD

**Issue by hogiro** [benjaminkott/bootstrap_package#261]
Hello,

as I try to add Text with Media I get this error.  Is it my mistake or there is a solution for this error message?

**Comment by benjaminkott** [comment]
@hogiro hey, fluid styled content is not supported yet - i am currently working on support for this for now only css_styled_content is available as base

**Comment by gilas1959** [comment]
HI, I had the same error. No problem. However I can't see any cType 'Text w/Images' when I create a new cType using the wizard. So, If i need to create a new cType  'Text w/Images'  I need to:
1. create a content like  'Text w/Media'
2. from General switch the cType to    'Text w/Images'  
3. infact this cType is still usable becase you use css_styled_content

ok this works correctly. I suppose that this will be compatibile and moreover that there will be the possibility to convert all cTypes from   'Text w/Images'   to   'Text w/Media'  can you ensure this?
thank you very much

**Comment by benjaminkott** [comment]
Currently heavy working on new fluid templates for all content elements. With the next release you will no longer depend on css_styled_content or fluid_styled_content but all content elements from both versions will be available.

**Comment by Taskrider** [comment]
I like to hear that

A little workaround for all who use 7.6 and bootstrap_package with css_styled_content

This workaround remove textmedia from the wizard and add the text and textpic again.

Add the following line in the file bootstrap_package/Configuration/PageTS/TCEFORM.txt

```
TCEFORM.tt_content.CType.removeItems = textmedia
```

Add this to the file bootstrap_package/Configuration/PageTS/Mod/Wizards/newContentElement.txt
```
mod.wizards.newContentElement.wizardItems.common.show := addToList(text, textpic)
```

After this workaround you will find the old css_styled_content elements text and textpic again, and the fluidelement textmedia is removed from the wizard.

**Comment by gilas1959** [comment]
absolutely correct!
It works without any problem!



Da: "Taskrider" notifications@github.com
A: "benjaminkott/bootstrap_package" bootstrap_package@noreply.github.com
Cc: "gilas1959" at@specialistaweb.it
Data: Mon, 30 Nov 2015 04:25:44 -0800
Oggetto: Re: [bootstrap_package] ERROR: Content Element type "textmedia" has no rendering definition!  (#261)

**Comment by benjaminkott** [comment]
oh, forgot to close it, the textmedia ce is now supported in master have a look guys, keep in mind that this is currently WIP.
