### ISSUE TITLE
Possibility for multilingual 404 pages?

### ISSUE THREAD

**Issue by newenduser** [benjaminkott/bootstrap_package#267]
Hi guys,

we realized that a 404 error strictly leads to one version of a 404 page. As 404 pages sometimes are styled and have nice content, it may be nice as well to offer showing the translations for the different languages as well. Does anyone know how to do this except for using an extra extension (which we would like to avoid)?

Thanks very much in advance!

**Comment by benjaminkott** [comment]
This has to be solved in the TYPO3 Configuration please have a look in your system configuration at "[FE][pageNotFound_handling]"
