### ISSUE TITLE
copy and paste within java script files

### ISSUE THREAD

**Issue by newenduser** [benjaminkott/bootstrap_package#268]
Hi again!

We have a file called js.js (sorry, don´t know if every installation has one). If I try to edit this with the editor (Typo3 7.6.0) using copy and paste, the content inserted is not the content copied (or cut out). It´s all mixed up. Just to let you know! People like me need copy and paste - at least if they don´t know how to write java script... ;-)

Cheers!

**Comment by benjaminkott** [comment]
i have no idea what exactly you want me to do ;)

**Comment by benjaminkott** [comment]
i am closing this issue now because it seems there are no more questions to this topic
