### ISSUE TITLE
Pagination with Thumbnails Menu

### ISSUE THREAD

**Issue by hogiro** [benjaminkott/bootstrap_package#269]
As there is not any stable functioning teaser extension for 7.6 I am trying to use the thumbnail menu es teaser for subpages. Unfortunately you didnt implement any pagination for such a menu. Do you plan it or how could I use pagination with such a menu?

Thanks for your answer,

**Comment by benjaminkott** [comment]
@hogiro i will have a look into this again but it seems that die fluid pagination widget is incompatible with FLUIDTEMPLATE because it needs an controller to work - will have a look later again into this.

**Comment by hogiro** [comment]
I think that the most widely problem by typo3 is a ready teaser - > pages Function. I need many different teasers on start page and on sub rubrics. Some of these teasers should have pagination and some of them shouldnt, As every kind of teaser are different in size, and view, all these options should be set in flexforms.

**Comment by hogiro** [comment]
Hello Benjamin,

unfortunately I will bother you again :)

I see that you removed by last commit the Menu 'Display Subpages as News Entries'. Will you implement it again? It hat a page browser already.

Thanks for your hard work.

**Comment by benjaminkott** [comment]
The "news" implementation was a hardcore typoscript example that actually no normal not typoscript freak would understand so i remove it. I plan to add ext_news support instead for this. 

Already wasted yesterday evening in trying to get the fluid widget pagination to work - but no way it needs an real extbase controller to pass the current page ;). So there is currently no easy way to have simple pagination working. I put this on my todo list and will come up with a solution for this.

**Comment by hogiro** [comment]
thanks for your answer, but as I dont want tu use tx_news, it wont help me. I will try to find another extension or program my own code, if I can make it work :).

I see that you changed general tab by insert plugin view. I think that we still need a Header text, as sometimes we use it over the plugins too.

Thanks again for your help and given informations.

**Comment by benjaminkott** [comment]
just wanted to make an explaination why its removed, still for simple pagination in standalone FLUIDTEMPLATE like the menus or some other records there needs to be a solution.

mm.. interesting, we have always the problem that our plugins takeover since the list views and detailviews always share the same pageto get shorter urls and better fallbacks, for that i disabled it - because i thought that others would do mostly the same and if nessesary it would be easy just to add a ce above it... ill think also about this again.

**Comment by hogiro** [comment]
unfortunately I must bother you again. I see that the other plugins are not showing anymore, I am just able to show them when I include css_styled_content at the end of your setup includes then I can see the plugin contents but so your contents are showing without your renderings. Can you check it please? I am trying to include pw_teaser (development version 3.4.0 dev)

Thanks

**Comment by benjaminkott** [comment]
can you give me a link to the repository?

**Comment by hogiro** [comment]
https://bitbucket.org/ArminVieweg/pw_teaser/src

I got it working as I included the css_styled_content as following in your setup.txt file:

<INCLUDE_TYPOSCRIPT: source="FILE:EXT:bootstrap_package/Configuration/TypoScript/ContentElement/Bullets.txt">
<INCLUDE_TYPOSCRIPT: source="FILE:EXT:bootstrap_package/Configuration/TypoScript/ContentElement/Div.txt">
<INCLUDE_TYPOSCRIPT: source="FILE:EXT:bootstrap_package/Configuration/TypoScript/ContentElement/Header.txt">
<INCLUDE_TYPOSCRIPT: source="FILE:EXT:bootstrap_package/Configuration/TypoScript/ContentElement/Html.txt">
<INCLUDE_TYPOSCRIPT: source="FILE:EXT:bootstrap_package/Configuration/TypoScript/ContentElement/Image.txt">
<INCLUDE_TYPOSCRIPT: source="FILE:EXT:bootstrap_package/Configuration/TypoScript/ContentElement/List.txt">
<INCLUDE_TYPOSCRIPT: source="FILE:EXT:css_styled_content/static/setup.txt">
<INCLUDE_TYPOSCRIPT: source="FILE:EXT:bootstrap_package/Configuration/TypoScript/ContentElement/Menu.txt">
<INCLUDE_TYPOSCRIPT: source="FILE:EXT:bootstrap_package/Configuration/TypoScript/ContentElement/MenuCategorizedContent.txt">
<INCLUDE_TYPOSCRIPT: source="FILE:EXT:bootstrap_package/Configuration/TypoScript/ContentElement/MenuCategorizedPages.txt">
<INCLUDE_TYPOSCRIPT: source="FILE:EXT:bootstrap_package/Configuration/TypoScript/ContentElement/MenuOfSubpagesToThesePages.txt">
<INCLUDE_TYPOSCRIPT: source="FILE:EXT:bootstrap_package/Configuration/TypoScript/ContentElement/MenuOfSubpagesToThesePagesAbstract.txt">
<INCLUDE_TYPOSCRIPT: source="FILE:EXT:bootstrap_package/Configuration/TypoScript/ContentElement/MenuOfSubpagesToThesePagesAndSections.txt">
<INCLUDE_TYPOSCRIPT: source="FILE:EXT:bootstrap_package/Configuration/TypoScript/ContentElement/MenuRecentlyUpdatedPages.txt">
<INCLUDE_TYPOSCRIPT: source="FILE:EXT:bootstrap_package/Configuration/TypoScript/ContentElement/MenuRelatedPagesBasedOnKewords.txt">
<INCLUDE_TYPOSCRIPT: source="FILE:EXT:bootstrap_package/Configuration/TypoScript/ContentElement/MenuSectionIndex.txt">
<INCLUDE_TYPOSCRIPT: source="FILE:EXT:bootstrap_package/Configuration/TypoScript/ContentElement/MenuSitemap.txt">
<INCLUDE_TYPOSCRIPT: source="FILE:EXT:bootstrap_package/Configuration/TypoScript/ContentElement/MenuSitemapOfSelectedPages.txt">


of course that is just a dirty solution. I think that css_styled_content is still needed for some extensions.

**Comment by benjaminkott** [comment]
@hogiro actually both css_styled_content and fluid_styled_content are on the conflict list for current master and its build that none is needed and could make problems if installed. since i could not support both i decided to go for a hybrid solution and supporting the best of both.

can you please check if its working after uninstalling csc and fsc? will also have a look at armins work in progress

**Comment by benjaminkott** [comment]
![image](https://cloud.githubusercontent.com/assets/3243119/11850269/8f62ffc4-a42c-11e5-82b9-878430562d47.png)

![image](https://cloud.githubusercontent.com/assets/3243119/11850285/a08d7b4e-a42c-11e5-8abc-f4a77c4b8216.png)

Its working totally fine here.

**Comment by hogiro** [comment]
Hello

thanks a lot for your help. In that time I solved the problem too. It is not needed even to uninstall the css_styled_content and fluid_styled_content.

**Comment by benjaminkott** [comment]
i am closing this issue now because it seems there are no more questions to this topic

**Comment by dni** [comment]
Hi! Any News on this front?

Im now having the some problem with typo3 8.7.3. Im trying to make a custom menu like it existed in 7.6. everything works fine except the pagination ;(, i kinda need the menu type news for updating my old projects, i really enjoy this menu type i think is far superior than any news extension and far more flexible.

Is it still on your Todo? I cant get it to work with the paginate widget too :(

**Comment by benjaminkott** [comment]
We have revisited the issue and found a temporary solution. The fluid widget needs an extbase controller or atleast it must think there is one. If the pagination widget should be used in context of FLUIDTEMPLATE instead of Extbase we need to provide some additional informations to the setup.

```
tt_content.menu_thumbnail_dir {
    extbase {
        pluginName = Pagination
        controllerExtensionName = BootstrapPackage
        controllerName = Paginate
        controllerActionName = show
    }
}
```

The controller itself does not need to exist. Have fun.
