### ISSUE TITLE
image does not resize in landscape view

### ISSUE THREAD

**Issue by cathys8780** [benjaminkott/bootstrap_package#271]
I have typo3 6.2.15 installed and bootstrap.package 6.2.15.  I have a content element that is Image only with a 1200px image referenced.  When screen gets to about 768px or smaller, it presents a processed image that is only 320px wide instead of full width.  This looks ok on portrait but not landscape views. 

It would be better if it used the original size and set width to 100%.  I can change the css to be 100% on screen sizes less than 768px but then the image is distorted since it is stretching a 320px image to a larger size.

Any suggestions on how to change this behavior?

**Comment by s-leger** [comment]
There is an extension to fix this behavior,  and adapt the size of images according every breakpoint.
Basically bootstrap_package only generate 4 images where there should be 5 to match every breakpoint.
Take a look at lef_responsive_images in the TER. You may need to adjust the templates as they may not match the one provided with bootstrap_package, according the developper section of the extension manual
