### ISSUE TITLE
Flexible Carousel height

### ISSUE THREAD

**Issue by juschue** [benjaminkott/bootstrap_package#278]
Hi together,
may it's possible to make the height of the carousel more flexible?
So one is able to change the height via TS or (what would be more flexible) via a value in the form for the content element (like max. image width).
Thanks for your work so far!
Regards

**Comment by benjaminkott** [comment]
@juschue please pick up the discussion in #356 i am closing this ticket to collect all requirements of the carousel at a single ticket.
