### ISSUE TITLE
Manipulating Content Element

### ISSUE THREAD

**Issue by hogiro** [benjaminkott/bootstrap_package#279]
Hello Benjamin,

really sorry but I need to disturb you one more time. I need to insert some javascript code just in first (it can be second or another one too) content element. It should be just in one content element on the page. I couldnt find the place to insert the code. Could you tell me how I could realize it?

Thanks for your Help and nice Greetings from Hamburg :)

**Comment by mojojuju** [comment]
You can put the Javascript code in a "Plain HTML" content element. This content element can be found under the "Special Elements".

![selection_049](https://cloud.githubusercontent.com/assets/7339576/12376106/0a0e7810-bcb1-11e5-9f2c-c52bfff37401.jpg)

**Comment by cedricziel** [comment]
FYI: The recommended way is to attach them to the page renderer via the page object.

https://docs.typo3.org/typo3cms/TyposcriptReference/Setup/Page/Index.html#includejs-array

**Comment by hogiro** [comment]
cedricziel, it is not about a javascrippt library, the code should be at a certain place. But I solved the problem already with new backend layouts :)

**Comment by cedricziel** [comment]
I wonder, why that's necessary -can you give me an example? 

Anyways: I'm glad you solved it! :)

**Comment by hogiro** [comment]
my problem was that, that I needed to insert the ad tags in every content page and it should be automatically and not manual. As Content I dont have any problem and I think my problems are more complex problems than normal user problems :)

**Comment by cedricziel** [comment]
Hmm not at all. It's pretty common to decorate elements. - Nevertheless: Glad you solved it :)
