### ISSUE TITLE
Tables in RTE

### ISSUE THREAD

**Issue by SventB** [benjaminkott/bootstrap_package#280]
When adding a table in RTE and choosing a style, for example "Striped rows", this class isn't outputted in frontend because of this configuration:

```
fixAttrib {
    class {
        default = table
        always = 1
        list = table
    }
}
```

With this configuration it works:

```
fixAttrib {
    class {
        always = 1
        prefixRelPathWith = table###SPACE###
    }
}
```

**Comment by jvanderkroon** [comment]
My solution for this problem is:
```
fixAttrib {
    class {
        default = table
        always = 1
        list = table, table-bordered, table-striped, table-hover, table-sm
    }
}
```
by list you define al the possible classes.

**Comment by SventB** [comment]
Old RTE (rtehtmlarea) is replaced by new RTE rte_ckeditor, this issue is obsolete.
