### ISSUE TITLE
RTE: Classes for links

### ISSUE THREAD

**Issue by SventB** [benjaminkott/bootstrap_package#281]
If I want a link in button style, e.g. style "Success", I have to select in selectbox "textstyle" first "Buttons: Base" and then "Buttons: Success", because only then the a-tag gets the correct classes ("btn btn-success").

This is a little bit complicated, isn't there a better solution for that? I've tried to accomplish this with TypoScript (lib.parseFunc_RTE.externalBlocks) but didn't succeed.

**Comment by SventB** [comment]
A working solution seems to be to extend the LESS styles a little bit:

```
.btn-success,
.btn-danger,
.btn-all-other-buttons {
	&:extend(.btn);
}
```

**Comment by SventB** [comment]
Or better this way, for correct hover effects:
```
.btn-default {
	.btn();
	.btn-default();
}
.btn-primary {
	.btn();
	.btn-primary();
}
.btn-success {
	.btn();
	.btn-success();
}
.btn-warning {
	.btn();
	.btn-warning();
}
.btn-danger {
	.btn();
	.btn-danger();
}
```

**Comment by cedricziel** [comment]
Yep. The editor won't let you attach multiple classes at once. Same goes for detaching fyi.

Do you care to make a pull-request?
