### ISSUE TITLE
Fluid Content Elements with ext. gridelements

### ISSUE THREAD

**Issue by SventB** [benjaminkott/bootstrap_package#282]
The new rendering of content elements (FLUID instead of css_styled_content) doesn't work together with gridelements. When rendering the content elements of a gridelements column in a FLUIDTEMPLATE...

```
<f:for each="{data.tx_gridelements_view_children}" as="content">
	<f:if condition="{content}">
		<f:cObject typoscriptObjectPath="tt_content" data="{content}" />
	</f:if>
</f:for>
```

...the element is rendered but the images are missing.

**Comment by benjaminkott** [comment]
@SventB ive documented what you need to do to have grid elements running with the new fluid templates. https://github.com/benjaminkott/bootstrap_package/wiki/Use-GridElements-with-the-BootstrapPackage-greater-than-7.0.0

**Comment by SventB** [comment]
That doesn't work for me. I used the ContentViewHelper from Ext. nettgrids: https://github.com/debacher/nettgrids/blob/master/Classes/ViewHelpers/ContentViewHelper.php

**Comment by benjaminkott** [comment]
can you specify your problem, this does not seem to be a bootstrap_package problem.
gridelements itself needs to be run in dev-master or something like this to work with CMS8 maybe @Bunnyfield can tell you more about this.

when the viewhelper is not working the provided list of source seems to be wrong, according to the documentation it needs to be a comma separated list https://docs.typo3.org/typo3cms/TyposcriptReference/ContentObjects/Records/Index.html?highlight=records#source

**Comment by Bunnyfield** [comment]
You should follow the instructions here https://coders.care/blog/tutorial/gridelements-and-cms-8/ and remove additional extensions that might circumvent the actual rendering process. If this still does not work out, feel free to ask in the #gridelements channel on https://typo3.slack.com
