### ISSUE TITLE
Language menu shows non existent languages

### ISSUE THREAD

**Issue by justfortherec** [benjaminkott/bootstrap_package#30]
By default bootstrap_package shows a language menu with English, Danish and German. This is the case even when there is no additional languages configured in the CMS.

By default the language selector should only be visible if there is at least one second language and no non existent menus should be displayed. 

My guess is that languages used in the TYPO3 Introduction package are hardcoded in typoscript of bootstrap_package. This configuration should not be part of bootstrap_package but of Introduction package (or whatever extension uses needs this feature).

**Comment by benjaminkott** [comment]
while the problem is still existend, it can now be configured with constants and and we provided more adaptable templates, still typoscript configuration needs to be made. as soon as we can see a light at the end of the tunnel we will try to provide a better solution.
