### ISSUE TITLE
page speed insight

### ISSUE THREAD

**Issue by gilas1959** [benjaminkott/bootstrap_package#309]
HI
I hope to be in the right place to ask what happens.

In brief: using bootstrap package +introduction and modifying .htaccess to activate the file compression, i.e. these few lines:

<FilesMatch "\.js\.gzip$">
        AddType "text/javascript" .gzip
</FilesMatch>
<FilesMatch "\.css\.gzip$">
        AddType "text/css" .gzip
</FilesMatch>
AddEncoding gzip .gzip

where SETUP has configured according the above instructions:
-> config.compressJs and config.compressCss for GZIP compression of Frontend JS and CSS files.

the point obtained from the test, for a simple site are:
mobile 52
desktop 64

ok but if I add in the top of .htaccess the following lines, I get
mobile 64
desktop 86

there are 20+ points of difference, could you integrate eventually the lines that I'm using?

Here the code I have added to  .htaccess:

# Enable Compression
    <IfModule mod_deflate.c>
      AddOutputFilterByType DEFLATE application/javascript
      AddOutputFilterByType DEFLATE application/rss+xml
      AddOutputFilterByType DEFLATE application/vnd.ms-fontobject
      AddOutputFilterByType DEFLATE application/x-font
      AddOutputFilterByType DEFLATE application/x-font-opentype
      AddOutputFilterByType DEFLATE application/x-font-otf
      AddOutputFilterByType DEFLATE application/x-font-truetype
      AddOutputFilterByType DEFLATE application/x-font-ttf
      AddOutputFilterByType DEFLATE application/x-javascript
      AddOutputFilterByType DEFLATE application/xhtml+xml
      AddOutputFilterByType DEFLATE application/xml
      AddOutputFilterByType DEFLATE font/opentype
      AddOutputFilterByType DEFLATE font/otf
      AddOutputFilterByType DEFLATE font/ttf
      AddOutputFilterByType DEFLATE image/svg+xml
      AddOutputFilterByType DEFLATE image/x-icon
      AddOutputFilterByType DEFLATE text/css
      AddOutputFilterByType DEFLATE text/html
      AddOutputFilterByType DEFLATE text/javascript
      AddOutputFilterByType DEFLATE text/plain
    </IfModule>

    <IfModule mod_gzip.c>
      mod_gzip_on Yes
      mod_gzip_dechunk Yes
      mod_gzip_item_include file .(html?|txt|css|js|php|pl)$
      mod_gzip_item_include handler ^cgi-script$
      mod_gzip_item_include mime ^text/.*
      mod_gzip_item_include mime ^application/x-javascript.*
      mod_gzip_item_exclude mime ^image/.*
      mod_gzip_item_exclude rspheader ^Content-Encoding:.*gzip.*
			 </IfModule>

    # Leverage Browser Caching
    <IfModule mod_expires.c>
      ExpiresActive On
      ExpiresByType image/jpg "access 1 year"
      ExpiresByType image/jpeg "access 1 year"
      ExpiresByType image/gif "access 1 year"
      ExpiresByType image/png "access 1 year"
      ExpiresByType text/css "access 1 month"
      ExpiresByType text/html "access 1 month"
      ExpiresByType application/pdf "access 1 month"
      ExpiresByType text/x-javascript "access 1 month"
      ExpiresByType application/x-shockwave-flash "access 1 month"
      ExpiresByType image/x-icon "access 1 year"
      ExpiresDefault "access 1 month"
    </IfModule>
    <IfModule mod_headers.c>
      <filesmatch "\.(ico|flv|jpg|jpeg|png|gif|css|swf)$">
      Header set Cache-Control "max-age=2678400, public"
      </filesmatch>
      <filesmatch "\.(html|htm)$">
      Header set Cache-Control "max-age=7200, private, must-revalidate"
      </filesmatch>
      <filesmatch "\.(pdf)$">
      Header set Cache-Control "max-age=86400, public"
      </filesmatch>
      <filesmatch "\.(js)$">
      Header set Cache-Control "max-age=2678400, private"
      </filesmatch>
    </IfModule>

**Comment by cedricziel** [comment]
Doesn't core auto-provide an optimized config these days?

**Comment by gilas1959** [comment]
forgive me; i tried the code above with TYPO3 CMS 7.6 and v. 6.2 it is the same. The .htaccess file doesn't includes anythig so I posted this comment almost for curiosity.
As I can see there is not something available from the core or, if we inspect more in detail and remove the code, the result is 20 points less. May be the point obtained are not to be related with the quality of the site. Maybe should I post the message to the core developers or other people?
Tell me what can I do... thank you very much for your help

**Comment by cedricziel** [comment]
No need for excuses - thank you for proposing a change in the first place! :)

Well - I would propose you compare your list of changes with those already shipped by the core. (https://github.com/TYPO3/TYPO3.CMS/blob/master/_.htaccess#L54)

Unfortunately, the core doesnt use github as primary source for patches. You should open a feature request on forge.

**Comment by gilas1959** [comment]
Thank you very  for your help. To be sincere I proposed the code without inspecting it in detail, so that it can be surely improved (I'm not an apache expert).
   It is interesting that the code configure apache for the LEVERAGE so that the site is speedy and compatible with Google Page Speed Insight.
   Ok I will contact the core developers, have a nice day!


   Da "Cedric Ziel" notifications@github.com
   A "benjaminkott/bootstrap_package" bootstrap_package@noreply.github.com
   Cc "gilas1959" at@specialistaweb.it
   Data Tue, 02 Feb 2016 05:18:38 -0800
   Oggetto Re: [bootstrap_package] page speed insight (#309)

   No need for excuses - thank you for proposing a change in the first place! :)

   Well - I would propose you compare your list of changes with those already shipped by the core. (https://github.com/TYPO3/TYPO3.CMS/blob/master/_.htaccess#L54)

   Unfortunately, the core doesnt use github as primary source for patches. You should open a feature request on forge.
