### ISSUE TITLE
open menu top menu when menu has submenu

### ISSUE THREAD

**Issue by Bambie42** [benjaminkott/bootstrap_package#311]
Hi,
first of all thanks for this great package.

unfortunately I got a small problem with it:

I've got a menu like this:

- start
- foo
   - bar
- asdf

I'm unable to open the "foo"-site because it has a subpage. (href="#"). One Solution is to leave the "foo" site empty because nobody is able to navigate to it. But if I enable breadcrumbs and open "bar", I'm able to navigate back to "foo".

Hope you unterstand my problem. Maybe there is an easy solution. Im quite new to typo ;)

Bambie

**Comment by cedricziel** [comment]
Hey @Bambie42,

Thank you for reporting! It is quite common to have a shortcut page that references the first subpage.
You would add a page foo2 underneath foo, copy the content from foo and then make foo a shortcut that references its first subpage (which should be foo2, then). That way it works well. Unfortunately the javascript doesnt handle the menus correctly-if you would want to fix it there.

Thx!
