### ISSUE TITLE
PHP7: static call to non-static callback: PHP Runtime Deprecation Notice

### ISSUE THREAD

**Issue by opi99** [benjaminkott/bootstrap_package#313]
I use TYPO3 7.6/master with bootstrap_package 6.2.15 and get following error

#1: PHP Runtime Deprecation Notice: call_user_func_array() expects parameter 1 to be a valid callback, non-static method BK2K\BootstrapPackage\UserFunc\Typo3VersionCondition::match() should not be called statically in /home/opitz/projects/typo3-master/typo3_src-git/typo3/sysext/core/Classes/Configuration/TypoScript/ConditionMatching/AbstractConditionMatcher.php line 345 

The problem is, that Typo3VersionCondition::match is called statically from TypoScript but isn't defined as static. Fixing this resolves the error.

**Comment by opi99** [comment]
And another one:

PHP Runtime Deprecation Notice: Non-static method BK2K\BootstrapPackage\Service\CompileService::getVariablesFromConstants() should not be called statically in /home/opitz/projects/typo3-master/typo3conf/ext/bootstrap_package/Classes/Service/CompileService.php line 68

**Comment by cedricziel** [comment]
Hi Alex,

thank you for reporting. The errors are both fixed in the current master.

Cheers,
Cedric
