### ISSUE TITLE
RTE > gives problems with Enable images in the RTE

### ISSUE THREAD

**Issue by ghost** [benjaminkott/bootstrap_package#315]
When using Enable images in the RTE the bootstrap package clears the RTE pageTS settings.
Giving pretty nasty errors.
More details can be found here:
https://forge.typo3.org/issues/71494

**Comment by jvanderkroon** [comment]
no solution yet?

i added the line 
`// reconfigure the image handlers`
`<INCLUDE_TYPOSCRIPT:` `source="FILE:EXT:rtehtmlarea/Configuration/PageTSconfig/Image/pageTSConfig.txt">`

after RTE > in the file typo3conf/ext/bootstrap_package/Configuration/PageTS/RTE.txt

Images work again with this code.

**Comment by jeemit2007** [comment]
By default bootstrap package disable the image option in rte.
1) we need to enable it from the extension manage > rtehtmlarea > enable insert image.

# include the defulalt rtehtmlarea image configuration file in your pagetsconfig.ts 
2)  `<INCLUDE_TYPOSCRIPT: source="FILE:EXT:rtehtmlarea/Configuration/PageTSconfig/Image/pageTSConfig.txt">`

# need to remove the img tag from the disable tags
3) add this bunch of ts on root page > Resources > into the box of pageTsConfig 
```
RTE.default {
    proc.entryHTMLparser_db.allowTags =  b, strong, i, em, u, strike, del, big, small, sub, sup, ol, ul, li, a, link, br, p, pre, h1, h2, h3, h4, hr, span, table, tr, th, td, thead, tbody, tfoot, img

    removeTags = center, font, o:p, sdfield
}
RTE.default.proc {
    denyTags = center, font, span
}
```

Works fine in TYPO3 7.6.16 , bootstrap_pacakge 7.1.0

Thanks.
JIMIT SHAH

**Comment by benjaminkott** [comment]
Images should not be available in RTE, and Bootstrap Package will not support this.
