### ISSUE TITLE
Broken RTE toolbar in TYPO3 8

### ISSUE THREAD

**Issue by tmotyl** [benjaminkott/bootstrap_package#316]
in bootstrap_package/Configuration/PageTS/RTE.txt
there is a line:
  skin = EXT:t3skin/rtehtmlarea/htmlarea.css

in TYPO3 8 this file is not there any more.
This breaks the toolbar of RTE

![image](https://cloud.githubusercontent.com/assets/515397/13495257/f2d1197e-e149-11e5-9c71-75f81677daf7.png)

**Comment by benjaminkott** [comment]
Solved in 3a6d10a6a4441b44f4667b9908008152423cb500
Package is released to TER for CMS7
Version for V8 is available through composer / git
