### ISSUE TITLE
bootstrap_package fails with extension realurl

### ISSUE THREAD

**Issue by stweil** [benjaminkott/bootstrap_package#317]
After installation of TYPO3 7.6.4, bootstrap_package 6.2.15 (or latest from git) and realurl 2.0.3, I get  this error when trying to show a newly created web page:

> Oops, an error occurred!
PHP Catchable Fatal Error: Argument 2 passed to BK2K\BootstrapPackage\Hooks\RealUrl\AutoConfig::addConfigVersion2x() must be an instance of Tx\Realurl\Configuration\ConfigurationGenerator, instance of DmitryDulepov\Realurl\Configuration\AutomaticConfigurator given in /var/www/html/periodika-7.6.4/typo3conf/ext/bootstrap_package/Classes/Hooks/RealUrl/AutoConfig.php line 59

With TYPO3 6.2.19, bootstrap_package 6.2.15 (not newer) and realurl 1.13.6 (not newer), everything works fine.

**Comment by benjaminkott** [comment]
@stweil update is in progress, will be released during the next days - current master is working fine with realurl 2.0

**Comment by stweil** [comment]
Yes, your latest commit b44a7983a5dad0823192fcb4d624fc66b1be32a7 should fix this issue, thanks.

**Comment by dmitryd** [comment]
@benjaminkott If you have questions about 2.x configuration, feel free to contact :smile: It is generally compatible with 1.x, just interfaces changed.

**Comment by benjaminkott** [comment]
@dmitryd thx already on it, problem is that there was already a configuration for the autoconfig for version 2, because the fork of helhum used the version number in his fork. i have already removed the autoconfig for now, since the benefit is not that high - since we had only mappings for the language params in it.

**Comment by dmitryd** [comment]
> we had only mappings for the language params in it.
Realurl does it too **if** `EXT:static_info_tables` is installed and language code is assigned in each system language record.

**Comment by benjaminkott** [comment]
Solved in b44a7983a5dad0823192fcb4d624fc66b1be32a7
Package is released to TER
