### ISSUE TITLE
Upgrade for 7.0 version break TS

### ISSUE THREAD

**Issue by alat54** [benjaminkott/bootstrap_package#318]
Hi, 

I have this TS in previous version to have 5 columns rendering for images.
`tt_content.image.20 {
  addClassesCol.override.cObject.10 {
    5 < .default
    5.value = col-xs-15 col-sm-15 col-md-15 col-lg-15
  }
}`

But after upgrade, this code is invalid and it broke my pages...

Do you have a solution?

thanks

**Comment by cedricziel** [comment]
What version did you upgrade from?

**Comment by alat54** [comment]
the last before this (6.XXX from memory)

**Comment by cedricziel** [comment]
From TER?

**Comment by alat54** [comment]
Yep :)

**Comment by cedricziel** [comment]
Meanwhile all the content elements were redefined using fluidtemplate TypoScript objects (which is good). What's not so good (in your case) is that the css_styled_content definitions are no longer valid.

You would need to add a templateRootPaths / partialRootPaths override and override the fluid templates as needed. Take a look at the official documentation about the FLUIDTEMPLATE object and the path overrides (https://docs.typo3.org/typo3cms/TyposcriptReference/ContentObjects/Fluidtemplate/Index.html), then take a look at how the content elements are defined now (the image element for example: https://github.com/benjaminkott/bootstrap_package/blob/master/Configuration/TypoScript/ContentElement/Image.txt) and finally, to put it all together, take a look at the templates and partials referenced in the ce definition: https://github.com/benjaminkott/bootstrap_package/tree/master/Resources/Private.

I consider this issue solved, as we wont adapt to the old behaviour again. If you have specific questions about your new implementations dont hesitate to open another ticket.
