### ISSUE TITLE
Frames: No Frame option vanished

### ISSUE THREAD

**Issue by aimeos** [benjaminkott/bootstrap_package#319]
Using the new v7 bootstrap package, the "Indentation and Frames" "No Frame" option isn't available any more in the "Appearance" tab of content elements (i.e. plugins). This always wraps a <div> around plugin output an creates an invalid response for "application/javascript" or "application/json" responses.

**Comment by cedricziel** [comment]
Can you give an example?

**Comment by aimeos** [comment]
Without bootstrap_package v7.0: ["No Frame" available](https://aimeos.org/fileadmin/frame-nobs.png)
After installing the package: ["No Frame" is gone and "Plugin" tab is displayed below other options](https://aimeos.org/fileadmin/frame-withbs.png)

The output was without BS:
```
// <!--
var aimeosStockHtml = {"90335": ...
// -->
```
Now it's
```
<div id="487">
// <!--
var aimeosStockHtml = {"90335": ...
// -->
</div>
```
