### ISSUE TITLE
Content element types selection error and image text position selection error

### ISSUE THREAD

**Issue by thomasmstein** [benjaminkott/bootstrap_package#322]
I just started to setup the content of a new site on a new installation of Typo 7.6.4 with bootstrap_package 7.0.0 - (but no preconfigured 'Congratulations' distribution ) when I noticed the following:

**_[1] Missing (?) some position and alignment options (Text & Images)_** to older version; 
My older local test version 7.6.2 with bootstrap_package 6.2.15 had two more image and text alignment options. The 'In text, right' and 'In text, left' have disappeared. Have they been skipped or is it related to 2 ? 
_7.6.2 with bootstrap_package 6.2.15_
![7 6 2 image1](https://cloud.githubusercontent.com/assets/17682916/13776592/1a817b58-eaff-11e5-8415-da92efa63cd3.jpg)
_7.6.4 with bootstrap_package 7.0.0_
![7 6 4 image1](https://cloud.githubusercontent.com/assets/17682916/13776622/4bd8c3c8-eaff-11e5-8543-ae4b6bb21819.jpg)

**_[2] Errors position and alignment options (Text & Images)_**;
Selecting the image alignment gives the error INVALID VALUE ("17") 
This error only shows when creating the content element and adding an image. Once saved it seems to disappear.
_7.6.2 with bootstrap_package 6.2.15_
![7 6 2 image2](https://cloud.githubusercontent.com/assets/17682916/13776525/b7c4a670-eafe-11e5-8dee-efb7ae9ed939.jpg)
_7.6.4 with bootstrap_package 7.0.0_
![7 6 4 image2](https://cloud.githubusercontent.com/assets/17682916/13776692/9c709838-eaff-11e5-8808-32834121de48.jpg)

[3] **_Errors with content type selection_**
When selecting the content type the types "Text, Text & Image, Text & Media, Images" are being displayed twice in different order.
_7.6.2 with bootstrap_package 6.2.15_
![7 6 2 image3](https://cloud.githubusercontent.com/assets/17682916/13776788/22ace668-eb00-11e5-9183-bf2f5fa7c164.jpg)
_7.6.4 with bootstrap_package 7.0.0_
![7 6 4 image3](https://cloud.githubusercontent.com/assets/17682916/13776794/2772a804-eb00-11e5-9c97-550123091a1c.jpg)

Thanks
Thomas

**Comment by thwittek** [comment]
I had the same issue. Thanks for the report here.
Also in the special section "html", and other stuff is missing

![html missing](https://cloud.githubusercontent.com/assets/5112607/13779056/7bd3e724-eab9-11e5-8232-6ad3259ff5bf.png)

**Comment by thomasmstein** [comment]
@thwittek 
Thomas,
I have used the **_'In text, right_**' and '_**In text, left**_' extensively (in Typo 3.5 my previous prod  ... ; -) . I hope very much that these 'In text ..' options can come back again.

When you mentioned the '**_Special elements_**' content types it gave me a bit of a fright as I did not notice yet - and I use the 'Plain HTML' extensively and need it. However, I checked and in my installation _(7.6.4 with bootstrap_package 7.0.0)_ with no additional extensions they are all there .... A first quick test shows that they are working.

Are these the ones you were expecting from your previous installation? 
Where do you get the _'**Media**'_ one from?

![7 6 4 image4_ce_special](https://cloud.githubusercontent.com/assets/17682916/13798851/119b1ec6-eb6e-11e5-9698-39dda39f3cb9.jpg)
Cheers 
Thomas

**Comment by md-akenzo** [comment]
are there any news to this? @benjaminkott

**Comment by beetle-joe** [comment]
Hi,
I miss these orientations too, some of my contents look weird without the possibility to adjust the image inside text.

Is it planned to implement these? I tried to add the missing positions by changing PageTS, and TS but I failed (maybe somebody can give me a hint?)

Best wishes
Joe

**Comment by benjaminkott** [comment]
image position intext is currently not support not planned to be.
