### ISSUE TITLE
Accordion Item not created SQL error: 'Incorrect integer value: '' for column 'sys_language_uid'

### ISSUE THREAD

**Issue by thomasmstein** [benjaminkott/bootstrap_package#323]
@benjaminkott 
Benjamin, 
When trying to save an 'Accordion Item' I get the following error message:
`2: SQL error: 'Incorrect integer value: '' for column 'sys_language_uid' at row 1' (tx_bootstrappackage_accordion_item:NEW56ebd1cb5f82d419022030)`

While the 'Accordion Content Element' itself is being created and saved, no items are included. 

I tried it with two language settings Default [0] and [All] 

I checked the sys_language table, which is empty.

Any idea?

Thanks

Thomas

**Comment by thomasmstein** [comment]
As to   [https://forge.typo3.org/issues/70629](url) there seems to be a bug with MySQL mode STRICT_TRANS_TABLES

_Wouter Wolters_ suggested to disable the strict mode. I have set in the Backend Install section under [SYS][setDBinit] 
`SET SESSION sql_mode = 'NO_ENGINE_SUBSTITUTION';`

This fixed the problem which also showed on other bootstrap elements such as 'Carousel'.

Thomas

**Comment by Malharrathod** [comment]
Thanks thomasmstein 
it's working now

**Comment by benjaminkott** [comment]
awesome you figured it out, i am closing this for now

**Comment by mbrodala** [comment]
The actual Forge link: https://forge.typo3.org/issues/70629

**Comment by RobertKesseler** [comment]
This is just a workaround for the problem, for a solution read  
https://stackoverflow.com/questions/40542151/typo3-sql-error-incorrect-integer-value-for-column-sys-language-uid-at

"explicitly cast values to integer by modifying TCA (table configuration array) for the according field definitions"
