### ISSUE TITLE
Content elements overlap if first / previous has frame set to indent 

### ISSUE THREAD

**Issue by thomasmstein** [benjaminkott/bootstrap_package#325]
Hi Benjamin,
I noticed that if a content element (text or text & images) has the frame set to '**indent left**', '**indent center**' or '**indent right**' is followed by a content element (text or text & images) with the frame set to '**default**', then the text of the 2nd content element partly flows beside or over the 1st. (Figure 1)
Is it something you can reproduce?
Thanks 
Thomas

_Figure 1: 1st CE frame set to 'indent left', 2nd to 'default'_
![7 6 4 image7_ce](https://cloud.githubusercontent.com/assets/17682916/14019675/1d650c10-f228-11e5-8f4c-f345ed9725ac.jpg)

_Figure 2: 1st CE frame set to 'default', 2nd to 'indent left - OK '_
![7 6 4 image8_ce](https://cloud.githubusercontent.com/assets/17682916/14019684/2a5c8db2-f228-11e5-9bee-4799cf629517.jpg)

**Comment by web2date** [comment]
Hi Benjamin, this is the same bug - the missing row wrap for the following cases
    <f:case value="10"><bk2k:var name="sectionClass" value="col-xs-10 col-xs-push-1" /></f:case>
    <f:case value="11"><bk2k:var name="sectionClass" value="col-xs-9 col-xs-push-3" /></f:case>
    <f:case value="12"><bk2k:var name="sectionClass" value="col-xs-9" /></f:case>
