### ISSUE TITLE
Bootstrap v4 uses SASS instead of LESS, will you be moving that direction?

### ISSUE THREAD

**Issue by Outdoorsman** [benjaminkott/bootstrap_package#326]
Bootstrap v4 will be using SASS. **Can/will you migrate bootstrap_package to SASS** for TYPO3 8.something? If it isn't migrated for TYPO3 8, it could be long time wait. Bootstrap is currently Alpha 2... they plan on having approx 2 betas so it will probably be little while yet, but for planning purposes want to know your thoughts for the future.

Here's a link to the alpha website that of course will be deprecated with beta and final come out:
http://v4-alpha.getbootstrap.com/

_I for one prefer SASS over LESS but tend to go with the majority rules thing. Bootstrap was the main element that kept me from using SASS but with bootstrap switching this could very well be the turning point for the community at large favoring SASS... we will see._

**Comment by benjaminkott** [comment]
@Outdoorsman i will provide a new version based on sass around the timeframe bootstrap 4 is released. But expect a major version release for that.

**Comment by benjaminkott** [comment]
Please see #355
