### ISSUE TITLE
Adding, activating e.g. links or other tags to bullet lists and tables etc.

### ISSUE THREAD

**Issue by thomasmstein** [benjaminkott/bootstrap_package#327]
I am sorry but I am a bit confused on this on how to set or reactivate this in the new version 7.0.1. 

I would like to reactivate certain tags for content elements mainly in bullet lists and tables so that e.g. `<link 7>Link to page 7</link>` would create a link to page 7 and `<b>bold text</b>` would make a section bold, just to name two, etc. 

I thought it would possible to just activate and allow these and other tags for certain content elements? I am not using RTE.

Maybe I have missed the option after a long search but any hint on how to go about it would be greatly appreciated.

Thanks

Thomas

**Comment by benjaminkott** [comment]
These elements are not intended to be used that way, please consider using a menu or something else.
