### ISSUE TITLE
Other Content Extensions

### ISSUE THREAD

**Issue by chequille** [benjaminkott/bootstrap_package#328]
Dear Benjamin,
just a simple question.
Is it correct, that when using latest bootstrap_package there is no chance to get a non fluid based extension to work? F.e. gridelements.
I am asking because I am looking for a carousel be able to show other content elements like in gridelements. Could you image to enhance your carousel with this feature?
Or do you now an extension doing this working with bootstrap_package?

Sorry, now I asked not only one but three questions :-)
Looking forward to hearing from you.

Best regards,
Chequille

**Comment by Wahni69** [comment]
Did you try bootstrap_grids? Maybe that's what you are looking for. 
https://typo3.org/extensions/repository/view/bootstrap_grids

**Comment by chequille** [comment]
@Wahni69 
Thanks for this info, but yes, I tried it already, but it did not work together with the bootstrap_package.
In the meantime, I did my own modification of the Carousel Content element to f.e. showing a news plugin object and it is working.

But I saw that there is a new version of bootstrp_grids as of 15th May.
I will try this to see if it is working.

Thanks again and best regards,
Jürgen

**Comment by benjaminkott** [comment]
@Wahni69 @chequille gridelements is working fine, but it needs some adjustments see. compatibility depends on how the extension authors are implementing their features
https://github.com/benjaminkott/bootstrap_package/wiki/Use-GridElements-with-the-BootstrapPackage-greater-than-7.0.0

**Comment by typo3ua** [comment]
I'm using "**bootstrap_package**" (with "[GridElements with the BootstrapPackage](https://github.com/benjaminkott/bootstrap_package/wiki/Use-GridElements-with-the-BootstrapPackage-greater-than-7.0.0)") and "**gridelements**" and "**bootstrap_grids**" (and without "bootstrap_grids").

In the backend all good, but on frontend page empty.

What do I wrong?
