### ISSUE TITLE
Setting @carousel-caption-color doesnt have effekt

### ISSUE THREAD

**Issue by criwe** [benjaminkott/bootstrap_package#333]
Hi!
I´ve tried to change the @carousel-caption-color via constant editor, but the color in the fe remains #fff 
When setting the color in the content element, it works. 

TYPO3  7.6.4
Bootstrap Package 6.2.15

Best,
Chris

**Comment by benjaminkott** [comment]
@criwe the carousel caption color has no effect for the carousel content element, this is because you can set the color on every item manually to be more flexible. the result is that it will override the default color you set in the less files.
