### ISSUE TITLE
Internal anchor points to wrong position 

### ISSUE THREAD

**Issue by thomasmstein** [benjaminkott/bootstrap_package#334]
I have noticed that when an internal anchor e.g. `<link #c155>My Content Object</link>` is being used (manually or by using the special menu section index) the target position will be scrolled above the visible section of my page and hence is covered by the navbar header section (by about 140px).

Can anyone reproduce this?

Thanks

Thomas

Typo3 7.6.5
Bootstrap 7.0.2

**Comment by benjaminkott** [comment]
works fine on 8.x and master, cannot reproduce.
