### ISSUE TITLE
icon_color, icon_background don't display in Backend by Text with Icon

### ISSUE THREAD

**Issue by paulsen-it** [benjaminkott/bootstrap_package#336]
Hello Together,
I have Typo 3 7.6.x installed with bootstrap_package. When I want to use Text with Icon the Icon have everytime the Background 333333 and color FFFFFF. This Values are saved in the Database, and I cannot change this Values in the Backend. I look and found that both should shown in the Dataset, next to Icon Position. But they are not there. Why?
Thank you for any help

**Comment by derde68** [comment]
Hi,
when change the Position, the type or size the color-section will appear.
cio derde68

**Comment by paulsen-it** [comment]
Yes, it shows only when Type is not Default. Position and size have no effect. But Why? Why it is only by Type != Default?

**Comment by benjaminkott** [comment]
Here is a screenshot to visualize the intended behaviour
![image](https://cloud.githubusercontent.com/assets/3243119/16356887/3fbf33fa-3ae7-11e6-9170-12976a99894a.png)
