### ISSUE TITLE
RTE / Clearing html / Word

### ISSUE THREAD

**Issue by criwe** [benjaminkott/bootstrap_package#337]
Hi!
When copying some text from Word to the RTE and then removing both "HTML" AND "Word"-styles, some strange output happens:

![t3error](https://cloud.githubusercontent.com/assets/7531138/14798847/dfb499c8-0b39-11e6-9885-5466762c360e.jpg)

Removing one of these works.
In native TYPO3 it works fine too.
TYPO3 7.6.4
Bootstrap Package 6.2.15

Best,
Chris

**Comment by benjaminkott** [comment]
@criwe can you please provide a example file, i am currently unable to reproduce the missbehavior

**Comment by benjaminkott** [comment]
no response, rtehtmlarea is obsolete and ckeditor cleaning seems to work fine
