### ISSUE TITLE
No "Typical Page Content" after update 

### ISSUE THREAD

**Issue by maddinq** [benjaminkott/bootstrap_package#338]
After I updated the bootstrap_package to the latest version (from 6.x.x) there are no default content elements any more. (text & media etc.). (adding a new element)...
![bildschirmfoto 2016-04-26 um 14 12 37](https://cloud.githubusercontent.com/assets/2078227/14817676/f405b6da-0bb8-11e6-83f9-f1c82959d34a.png)
But they are there if you edit an existing element..
![bildschirmfoto 2016-04-26 um 14 13 34](https://cloud.githubusercontent.com/assets/2078227/14817737/4db094e8-0bb9-11e6-9e78-33eebc23db20.png)

Any Ideas?

**Comment by maddinq** [comment]
newContentElement.txt

>>>
The PageTS-Config: mod.wizards.newContentElement.wizardItems.*.elements.*.icon is deprecated since TYPO3 CMS 7, will be removed in TYPO3 CMS 8. Register your icon in IconRegistry::registerIcon and use the new setting: mod.wizards.newContentElement.wizardItems.*.elements.*.iconIdentifier
<<<

You are already using the "iconIdentifier" but something is wrong, so after I removed the lines...I can see the content elements again

**Comment by benjaminkott** [comment]
@maddinq should be fixed in more up2date versions of the bootstrap_package
