### ISSUE TITLE
Breadcrumps parents are not working

### ISSUE THREAD

**Issue by maddinq** [benjaminkott/bootstrap_package#339]
The bread crump parent links are not working - they just have have the root page in the href ("/")

> page.theme.breadcrumb = 1
> page.theme.breadcrumbEnableLevel = 0

**Comment by maddinq** [comment]
newContentElement.txt

>>>
The PageTS-Config: mod.wizards.newContentElement.wizardItems.*.elements.*.icon is deprecated since TYPO3 CMS 7, will be removed in TYPO3 CMS 8. Register your icon in IconRegistry::registerIcon and use the new setting: mod.wizards.newContentElement.wizardItems.*.elements.*.iconIdentifier
<<<

**Comment by maddinq** [comment]
No ideas?

**Comment by benjaminkott** [comment]
@maddinq i cannot reproduce the issue, what version are you using?

**Comment by maddinq** [comment]
Hey Ben, you can see it on: http://www.rideengine.de/trapeze/hex-series.html or http://www.rideengine.de/trapeze/elite-series/bamboo-forest.html

also on http://www.moonshinemfg.de/freeride/county-line-soft.html

if you want to see the config, please write me a message (skype etc)
