### ISSUE TITLE
Extension destroys feedit

### ISSUE THREAD

**Issue by darthnorman** [benjaminkott/bootstrap_package#340]
Bootstrap Package clears tt_content thus the rendering of feedit panels fail.
\bootstrap_package\Configuration\TypoScript\setup.txt line 12

**Comment by benjaminkott** [comment]
@darthnorman should be resolved with https://github.com/benjaminkott/bootstrap_package/commit/00d42a06745e1c43d15c7f6dc98b791e6cf63a3b

thx for reporting
