### ISSUE TITLE
Empty description marker in cal extension since v7

### ISSUE THREAD

**Issue by hieblmedia** [benjaminkott/bootstrap_package#341]
Hi,
in the Calendar Base (cal) extension the description marker is empty in version 7 of this package.

After long search finally i found the issue and i have fixed it with:
```
tt_content.text.20 = TEXT
tt_content.text.20 {
	parseFunc = < lib.parseFunc_RTE
}
```

I don't now this is general or specific on the cal extension,
but maybe other also extensions affected on this issue.

**Comment by benjaminkott** [comment]
hey @hieblmedia, you sadly find some of those issues until extension authors adjusted their extensions. the extension cal seems to be depending on css_styled_content and does not support "fluid" extensions yet. some extensions still copy configurations directly from the css_styled_content rendering definition but do not add it to their dependency graph.
