### ISSUE TITLE
Content elements of gridelements are outside the frame using bootstrap_package

### ISSUE THREAD

**Issue by webian** [benjaminkott/bootstrap_package#342]
Typoscript of gridelements:

```
tt_content.gridelements_pi1 = COA
tt_content.gridelements_pi1 {
	10 =< tt_content.header
	20 = COA
	20 {
		10 = USER
		10 {
			userFunc = GridElementsTeam\Gridelements\Plugin\Gridelements->main
			setup {
				default < lib.gridelements.defaultGridSetup
			}
		}
	}
}
```

bootstrap_package uses its own tt_content.header typoscript that outputs by default the frame code around the header:
`<div id="c{data.uid}" class="frame {sectionClass} {data.custom_class}"><!--header here--></div>`
then the rendered code is
```
<div id="c229" class="frame default "></div>
<div class="row"><!--content of tt_content.gridelements_pi1.20--></div>

```
So the content elements of gridelements are outside the frame.

I can't find a decent solution.

**Comment by benjaminkott** [comment]
@webian checkout https://github.com/benjaminkott/bootstrap_package/wiki/Use-GridElements-with-the-BootstrapPackage-greater-than-7.0.0
