### ISSUE TITLE
A lot of line brakes and spaces in the final html code

### ISSUE THREAD

**Issue by chequille** [benjaminkott/bootstrap_package#343]
Sorry, but the part of the html file cannot be inserted because it is changed into the interpreted look.
I will attach a file.

#####

Hi Benjamin,
first of all, I am using Typo3 7.6.6 and Bootstrap latest version from TER.
SO far everthing is working but my html output does contain a lot of line brakes and spaces which enhances of course the total size of the size. Below just an example. It really looks like that.
DO you have any idea where this comes from? Is it fluid, or bootstrap or Typo Core?
please let me know.
Best regards,
Jürgen
[partofhtmloutput.txt](https://github.com/benjaminkott/bootstrap_package/files/255890/partofhtmloutput.txt)

**Comment by cedricziel** [comment]
Fluid does that. It would normally be compressed out by deflate or you could utilize something like EXT:sourceopt to snip it away before the response is emitted.
