### ISSUE TITLE
Where is the onePage stuff gone?

### ISSUE THREAD

**Issue by metaxos** [benjaminkott/bootstrap_package#344]
Hi

Just a question? Is there no more onePage template?

Kind regards
metaxos

**Comment by Wahni69** [comment]
Good question. How is it possible to make a onepage layout with the version for 7.x Typo3?

**Comment by chequille** [comment]
hi @all,
first wondered as well, but this is quit easy.
Just use the onepage setup.txt and the layouts/page/default.html from the privious bootstrap package.
Onepage is nothing else than to render the content from the defined pages (onepage/setup.txt) into a typo object (lib.content.onepage) and to render this object into one page.
This is the trick which was done in the older bootstrap package.
It is working under 7.6.x as well. I did it.
Best regards,
Jürgen

**Comment by benjaminkott** [comment]
@metaxos @Wahni69 i removed it to streamline templates and avoid cluttering, needed to get the templates more simple to be more easy exchangeable and understandable - sry for any inconvenience
