### ISSUE TITLE
Uploads.html {file.description} is empty

### ISSUE THREAD

**Issue by metaxos** [benjaminkott/bootstrap_package#345]
Hi there

I cannot access the description of a file in my FLUID. {file.description} is empty. I suppose this has a relation with "metaDataLoaded" = false.

![screen shot 2016-05-26 at 09 19 14](https://cloud.githubusercontent.com/assets/5360113/15566770/0d929c36-2323-11e6-93d8-0d0aa4118ffb.png)

How can I access the description data? Do I have to write my own viewHelper or can I force loading the meta data (maybe lazy)?

**Comment by benjaminkott** [comment]
@metaxos the file resource will not represent the values on debug, but should be available anyways - there is some magic going on in the background. you should be able to get data with {file.description}

https://github.com/benjaminkott/bootstrap_package/blob/master/Resources/Private/Templates/ContentElements/Uploads.html

![image](https://cloud.githubusercontent.com/assets/3243119/16357042/9ab14a92-3aeb-11e6-8bd8-89b590ccbf54.png)

**Comment by benjaminkott** [comment]
Will close this issue now
