### ISSUE TITLE
Tabs, Accordion, and Carousel Items not referencing files on sys_file_reference and sys_refindex

### ISSUE THREAD

**Issue by mfvetter** [benjaminkott/bootstrap_package#349]
When adding a link **via the text editor** to a file on Tabs, Accordion, or Carousel items, the file is not referenced on tables sys_file_reference and sys_refindex. This may cause incorrect deletion of files when you see the file not being referenced on Fileadmin. Users may assume there's no reference to the file and may delete it thinking the file is not being used on Typo3.

**Comment by mfvetter** [comment]
Found the solution. Adding this:

'softref' => 'rtehtmlarea_images,typolink_tag,images,email[subst],url'

to the TCA solved the problem. The line was added to three files under the folder Configuration/TCA:

- tx_bootstrappackage_accordion_item.php
- tx_bootstrappackage_carousel_item.php
- tx_bootstrappackage_tab_item.php

`...
'bodytext' => array(
            ...,
            'config' => array(
                ...,
                'softref' => 'rtehtmlarea_images,typolink_tag,images,email[subst],url',
            ),
          ...
        ),
...}
`

After clearing all caches and added a new file, it started recording on the database. It doesn't apply the references for existing links in the bootstrap items. I'll have to create the references myself I believe. 
Maybe someone could help me create a script to add the references of existing links to sys_refindex...

**Comment by benjaminkott** [comment]
@mfvetter youre awesome for fiddling this out, added patches for the issue - thx a lot
