### ISSUE TITLE
Advanced Editor permissions 

### ISSUE THREAD

**Issue by AdvanceWM** [benjaminkott/bootstrap_package#35]
The Advanced McEditor role cannot see or add images, nor can they access any files through File|Filelist.

Accessing File|Filelist gives the error:
Oops, an error occurred!
You are not allowed to access the given folder
More information regarding this error might be available online.(links to http://wiki.typo3.org/Exception/CMS/1375955684)

This happens even when the missing directories user_upload/documents, user_upload/images, and user_upload/news are created.

**Comment by benjaminkott** [comment]
should not be a problem anymore, closing this for now.
