### ISSUE TITLE
Wrong preview images in backend for content element "Text & Images"

### ISSUE THREAD

**Issue by SventB** [benjaminkott/bootstrap_package#350]
Wrong preview icons or wrong frontend output for content element "Text & Images":

Backend preview image shows content left, picture right.
TCA for icon is: ['LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:imageorient.I.10', 26, 'content-beside-text-img-right']
TypoScript is: 26.value = TextpicLeft
Frontend output for template TextpicLeft.html is image left, content right

Eventually, content element "Text & Media" is also affected.

**Comment by benjaminkott** [comment]
@SventB thx a lot, fixed it in https://github.com/benjaminkott/bootstrap_package/issues/352
