### ISSUE TITLE
[FEATURE] Support SASS with Bootstrap 4

### ISSUE THREAD

**Issue by benjaminkott** [benjaminkott/bootstrap_package#355]
- Add SASS Parser
- Move Custom CSS to SASS
- Update to Bootstrap 4

**Comment by daybugging** [comment]
If I wanted to contribute, what would be the best way? It obviously wouldn't be branched off the `master` branch, no?

**Comment by benjaminkott** [comment]
The master branch is compatible with bootstrap3 and bootstrap4 (not finished) you can have a look at the current state here: https://www.bootstrap-package.com/?framework=bootstrap4

- Bootstrap 4  Sources are available
- SASS Parser is available
- Almost all custom css is already moved to SASS

Currently i am using this addition to test bs3 and bs4
```
[globalVar = GP:framework = bootstrap4]
<INCLUDE_TYPOSCRIPT: source="FILE:EXT:bootstrap_package/Configuration/TypoScript/Bootstrap4/setup.typoscript">
[end]
config.linkVars = L(int),framework
```
All changes are going always to master, after a release the versions get own branches to backport bugfixes, stuff etc if nessesary.

Currenlty missing stuff:
- [ ] New Google Webfont implementation with local cache
- [ ] TypoScript Constants for SCSS
- [ ] Better subnavigation implementation
- [ ] Responsive images rework

**Comment by hilburger** [comment]
Hi Benjamin, 
I have built the files from here locally and overwritten the TER version installed on my staging. 
But where can I switch to BS4? 
Even if I add the lines in the Setup of the template and &framework=bootstrap4 to the URL things are kind of strange - e.g. I get an Oooops-error on sub pages. 
Thanks for your help, 
Thomas

**Comment by hilburger** [comment]
Alright, thats working now - had to re-select the Backend-Layouts of the "Content Elements" page and sub pages. The demo template looks alright now. 

But the carousel CEs do not work (Ooops error within the CE on the correctly rendered page). 
Looks like a template file thing.

**Comment by hilburger** [comment]
Haha, also done - just had to change the CE type of two CE inside the carousel - works perfect - thanks for the awesome work! 
Will continue testing the BS4 part.

**Comment by benjaminkott** [comment]
The default rendering is now bootstrap 4. See 
https://github.com/benjaminkott/bootstrap_package/commit/6dee2d125c9b2e0e6c181d3ad2610b86b594bdb4 for more details.
