### ISSUE TITLE
[FEATURE] Make Carousel more flexible

### ISSUE THREAD

**Issue by benjaminkott** [benjaminkott/bootstrap_package#356]
The current implementation seems not flexible enough. We need an easy option for integrators to register new templates to the package.

**Comment by s-leger** [comment]
Hi, 
Seem carousel layout always has been a big pain.

Why not a fully responsive carousel ? 

Advantages :
One single solution for all cases.
Width depends only on external layout (and/or maybe a bootstrap column+offset wrapper )
height may be set by a ratio eg: 16x9 etc...

**Comment by Sonezi** [comment]
how to disable zoom in on image in slider? Is't possible to import images 1:1?
