### ISSUE TITLE
Pages are not working after update from 6.2.10 

### ISSUE THREAD

**Issue by electrigga** [benjaminkott/bootstrap_package#359]
I have tried to update from 6.2.10 to 6.2.15. But after update the extension and starting the update-script the page in frontend seems to be unformatted. It seems there is no css which formats the content. I have clear all caches. I was searching for answers in AdministratorManual/Migration. But nothing seems to work here. What could be wrong? I use Typo 6.2.25.

**Comment by benjaminkott** [comment]
can you please try to clear all frontend caches and clear the typo3 temp folder?

**Comment by electrigga** [comment]
@benjaminkott thanks for answer. This doesn't help. I cleared the cache in frontend, in the install tool and the folder. The page seems to have no formatting.

**Comment by benjaminkott** [comment]
@electrigga i guess, you are using the automatic less compiling - if thats correct what php version please ensure that at least 5.5 or 5.6 is loaded. 

if that also does not help, i would need to have a look at your instance to find the error.
just hit me on slack for that https://typo3.slack.com/messages/bootstrap-package/

**Comment by electrigga** [comment]
Thanks again for help, @benjaminkott. Great support!
