### ISSUE TITLE
Menu "mainnavigation": shortcuts aren't set as "active"

### ISSUE THREAD

**Issue by wtfred** [benjaminkott/bootstrap_package#360]
Hello,

I'm trying to build a website with bootstrap_package 7.0.2, and it seems that with this new thing "MenuProcessor", the shortcuts pages aren't set as "active" when you are on the target page.

Btw i'm wondering why you made a MenuProcessor over the "Pure" typoscript menu like on previous version ? What are the pros/con ?

Thanks :)

**Comment by blackde5ert** [comment]
Hello wtfred,

did you solve this issue?
I'm having the same problem with the "t3sbootstrap" extension for Typo3 8.7.10.

Thanks!

**Comment by wtfred** [comment]
I was browsing the issue and found this old one ^^

I'm closing it, as the navigation template can be overrided to set the "active" class with something like this (ofc variable `currentUid` has to exists):
```
<f:variable name="classActive">
        <f:if condition="{item.active} || ({item.data.doktype} == 4 && {item.data.shortcut} == {currentUid})">
            active
        </f:if>
</f:variable>
```
As for my questions about MenuProcessor, since the time i understood what is was, i'm using and loving it ^^
