### ISSUE TITLE
html code in bootstrappackage 6.2.16

### ISSUE THREAD

**Issue by robdevries** [benjaminkott/bootstrap_package#365]
After updating to v. 6.2.16 we get html code <small> with the photos of the carousel

 <div class="container">
        <div id="c469" class="csc-space-after-15"><h1 class="first-headline">Vakantie in Portugal.  &lt;small&gt;Een land om te ontdekken&lt;/small&gt;</h1>

    
        
        <div id="carousel-469"
             class="carousel slide carousel-small"
             data-interval="3000"
             data-wrap="1"
             data-ride="carousel">
            <div class="carousel-inner" role="listbox">
                
                    
                    
                    <div
                        class="item active carousel-item-type carousel-item-type-header"
                        data-itemno="0" style="

**Comment by benjaminkott** [comment]
@robdevries this was changed due a security release to avoid self xss please have a look here https://github.com/benjaminkott/bootstrap_package/commit/e0cbfad1f3f69f17c25ad6b93e8df52d1a9f4784
