### ISSUE TITLE
Subheader shows <small>-Tag

### ISSUE THREAD

**Issue by HamburgerJungeJr** [benjaminkott/bootstrap_package#368]
If I use the subheader, Typo3 renders the <small>-Tag as Text not as HTML-Tag.
I could fix this by changing the TS lib.stdheader.10.1.20.htmlSpecialChars to 0 (in file base.ts on line 204)

**Comment by benjaminkott** [comment]
@HamburgerJungeJr this was changed due a security release to avoid self xss please have a look here https://github.com/benjaminkott/bootstrap_package/commit/e0cbfad1f3f69f17c25ad6b93e8df52d1a9f4784

**Comment by timri** [comment]
But then the next line in the Typoscript does not make any sense:
field = subheader
htmlSpecialChars = 1
stdWrap.noTrimWrap = | <small>|</small>|
stdWrap.htmlSpecialChars = 0
stdWrap.required = 1
