### ISSUE TITLE
Missing addQueryString on f:link.page

### ISSUE THREAD

**Issue by webian** [benjaminkott/bootstrap_package#370]
In a page generated with query string parameters, like a news post or a product detail, the links generated with `f:link.page` (by instance "skip to main content" or "scroll to top") point wrongly to the list page.
This is because the `f:link.page` is missing the parameters `addQueryString="1"`.

**Comment by webfacer** [comment]
i used therfore the `f:link.action`

**Comment by webian** [comment]
ic but, correct me if I'm wrong, `f:link.page` with `addQueryString="1"` can generate the right link also for non extbase plugins and this way there's no need to overwrite template/partials.

**Comment by webian** [comment]
Another solution could be to write directly the A tag instead of use f:link.page since the href will be statically "#content" or "#top".

**Comment by benjaminkott** [comment]
Would prefer the static link, can someone create a pull request for that? Would be awesome!

**Comment by benjaminkott** [comment]
@webian this seems to be resolved by your patch, thx a lot for providing it.
