### ISSUE TITLE
External Link as mainmenu item

### ISSUE THREAD

**Issue by bluebyte1985** [benjaminkott/bootstrap_package#373]
At the moment external links in mainmenu are not opening in a new window. No matter if the link target is set to _blank under "behaviour".

I guess that's why Menu is rendered in fluid now. Is there a possibility to get the linktarget in fluid?

best regards

**Comment by benjaminkott** [comment]
@bluebyte1985 we just made some adjustments to the menu processor, we sill have to adjust the templates - but the data should be available now. 

please see:
https://github.com/benjaminkott/bootstrap_package/issues/380
https://github.com/benjaminkott/bootstrap_package/commit/0f206e87fc9bd8fb4a70e3af85f6018a33e78332
https://github.com/benjaminkott/bootstrap_package/commit/a59e481cf7adf48e95e515dc434ac8ceaebee9a2

thx for reporting
