### ISSUE TITLE
I can't get support the "gridelements" for the "bootstrap_package"

### ISSUE THREAD

**Issue by typo3ua** [benjaminkott/bootstrap_package#374]
Hello, everyone!
I can't get support the "gridelements" for the "bootstrap_package"
**Step 1:**
![setup](https://cloud.githubusercontent.com/assets/638022/18610436/08b8d05c-7d25-11e6-9d54-fac098b69029.png)
**Step 2:**
I'm added to `/Configuration/TypoScript/setup.txt` this [code...](https://github.com/benjaminkott/bootstrap_package/wiki/Use-GridElements-with-the-BootstrapPackage-greater-than-7.0.0) 
**Step 3:**
I'm added the GridElements.html to `/Resources/Private/Templates/ContentElements/`
**Step 4:**
I'm added GridElements configuration to `/Configuration/PageTS/GridElements/setup.txt`
**Step 5:**
I'm added content element on page in backend.
![setup1](https://cloud.githubusercontent.com/assets/638022/18610502/c5334a2c-7d26-11e6-9024-6045ce090b7b.png)
**Step 6:**
In left colemn added content element "header"
![setup2](https://cloud.githubusercontent.com/assets/638022/18610508/e5e5f0a8-7d26-11e6-9854-f098776a49da.png)
**Step 7:**
Clear cach...
**Step 8:**
I went to the page, and it is empty.
**What is wrong?**

**Comment by typo3ua** [comment]
When I add this 'TypoScript' [[...](https://github.com/benjaminkott/bootstrap_package/wiki/Use-GridElements-with-the-BootstrapPackage-greater-than-7.0.0)] in field 'setup' base 'Template' Everything works well.

![setup](https://cloud.githubusercontent.com/assets/638022/18759556/a7a77f9a-8105-11e6-823e-fbe761650f3b.png)

**Comment by cedricziel** [comment]
Including it in the setup field is roughly equivalent to including the static template `bootstrap_package` first and then the one from `gridelements`.

In the first screenshot, you include `gridelements` first, but `bootstrap_package`, being a very opinnionated and streamlined package overrides selectors and much of the config that gridelements has added.

**Comment by typo3ua** [comment]
![setup](https://cloud.githubusercontent.com/assets/638022/18809713/3e042e84-828c-11e6-8f17-a9e4f685cd3b.png)

Changing the order. No change.

Add this in ext_localconf.php`\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addTypoScriptSetup('<INCLUDE_TYPOSCRIPT: source="FILE:EXT:' . $_EXTKEY . '/Configuration/TypoScript/ContentElement/GridElements.txt">');`

**Comment by typo3ua** [comment]
My setup.txt ... https://github.com/benjaminkott/bootstrap_package/blob/master/Configuration/TypoScript/setup.txt ... plus this ... https://github.com/benjaminkott/bootstrap_package/wiki/Use-GridElements-with-the-BootstrapPackage-greater-than-7.0.0, My GridElements configuration to /Configuration/PageTS/GridElements/setup.txt ... here ... https://github.com/laxap/bootstrap_grids/blob/master/Configuration/TypoScript/setup.txt
