### ISSUE TITLE
Image appearance - Bild Eigenschaften

### ISSUE THREAD

**Issue by alexd0001** [benjaminkott/bootstrap_package#376]
Hi,

where can i activate the Image appearance height and width for the Images in "Text & Image" Or in "Tabs" - Wo kann ich die Bildeigenschaften "Höhe und Breite" wieder aktivieren bzw. in "Tabs" z. B. einfach aktivieren? Ich fand diese Funktionen schon gut..

gruß und danke für die Extension/Template

**Comment by cedricziel** [comment]
You can reactivate them only through extensive TCA manipulation and switching off the hook that clears those values.
