### ISSUE TITLE
Art direction images

### ISSUE THREAD

**Issue by s-leger** [benjaminkott/bootstrap_package#382]
Hi, everybody here,

Done some job to provide Art direction images (different images for every breakpoint).

This also include 
- a fine tuned responsive images generation with realy needed sizes for every breakpoint.
- layout from 1 to 10 columns 
- responsive carousels backgrounds (extended carousel)
- css backgrounds
- and i'm sure i forgot some other goodies

As integrating this here require some amount of job, i do ask
AnyOne interrested ?

**Comment by mfvetter** [comment]
Sure! It would be really nice to have the features you mentioned to the core of bootstrap_package.

**Comment by benjaminkott** [comment]
There is currently some work going on for CMS8, currently waiting for the TYPO3 Core Patches to have a look how that can be supportet. If you are interested in this check #cig-responsive-images on slack.
Maybe the approaches can be aligned?

Here is also the epic for that stuff: https://forge.typo3.org/issues/77810

**Comment by s-leger** [comment]
Currently i'm using 5 images (or a multiple of 5) to handle this. 
Allowing multiple cropping is only one part of the problem - and maybe not the right way -  what if i want different images (source, quality, ratio h/v ...) ?
So with 5 independant file references i'm allready able to define independant parameters for each one, and also different sources when required.

**Comment by benjaminkott** [comment]
@s-leger @mfvetter art direction provided by the core is now enabled for textpic, textmedia, media and image content elements

**Comment by benjaminkott** [comment]
i guess this one can be resolved not, art direction by TYPO3 is in place now for a while and no new activity here.
