### ISSUE TITLE
accessibility icons cleared out by rte config

### ISSUE THREAD

**Issue by csvadr** [benjaminkott/bootstrap_package#392]
Although the RTE config coming with bootstrap_package produces a very lean source code, clearing out the accessibility icons is perhaps a bit too much.
In some countries, enhanced accessibility is required by law. which means that bootstrap_package is either a no-go there,  *or* one has to use the default RTE settings, which leads to a lot of clutter in html code.

**Comment by benjaminkott** [comment]
@csvadr hey, we are totally open to suggestions - if you think we can do better here and provide a better config we would gladly adapt to your needs.

**Comment by benjaminkott** [comment]
closing this one since no feedback provided
