### ISSUE TITLE
hammer.js searching for hammer.min.map 

### ISSUE THREAD

**Issue by zabinetta** [benjaminkott/bootstrap_package#396]
Dear Benjamin,
my college just told me, that hammer.js is missing /typo3conf/ext/bootstrap_package/Resources/Public/JavaScript/Libs/hammer.min.map 
this is just used for developer functions, but he would appreciate it.
could you please just add the file?
with the best regards,
Sabine

**Comment by benjaminkott** [comment]
@zabinetta i´ve added the sources for the next cms8 release
