### ISSUE TITLE
Text & Image CE wrong image/Text connex

### ISSUE THREAD

**Issue by kludikovsky** [benjaminkott/bootstrap_package#405]
At the "Text & Image" content element at the image alignment the icons for left and right are in the wrong order.
Text says (corretly) "Beside Text, Right" but the icon shows the image wrongly on the left side.

More Information already here: https://forge.typo3.org/issues/78943

I have now found that 

`ext/bootstrap_package/Configuration/TCA/Overrides/tt_content.php:`

has the following statement

`  ['LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:imageorient.I.9', 25, 'content-beside-text-img-left'],`

whereby @imageorient.I.9@ is defined 

```
			<trans-unit id="imageorient.I.9">
				<source>Beside Text, Right</source>

```
at 

`frontend/Resources/Private/Language/locallang_ttc.xlf`

**Comment by IchHabRecht** [comment]
This was fixed with #352 already.

**Comment by kludikovsky** [comment]
Sorry for the dumb question, but what do I need to do to resolve it?
I have 7.0.2 installed, which shall be the latest in TER.

**Comment by benjaminkott** [comment]
There is no dumb question, just me having not enough time to prepeare the releases.

Most easy is to download the sources from here directly. 
You can just download them as zip and replace the sources in your typo3conf/ext folder.

![download](https://cloud.githubusercontent.com/assets/3243119/21105553/ed069dcc-c08a-11e6-8790-133bf120a977.jpg)

https://github.com/benjaminkott/bootstrap_package/tree/BP_7-0

**Comment by kludikovsky** [comment]
OK, thanks.
