### ISSUE TITLE
Image align icon

### ISSUE THREAD

**Issue by Chhunlong** [benjaminkott/bootstrap_package#406]
![capture 2016-12-02 at 9 32 56](https://cloud.githubusercontent.com/assets/13775865/21336436/e0ac3376-c697-11e6-88b7-888260d4d107.png)

I've found a little bit confusing while doing image align adjustment.

**Comment by benjaminkott** [comment]
hey @Chhunlong, this was already fixed in https://github.com/benjaminkott/bootstrap_package/issues/352 - i am just lagging a bit prepping the releases

**Comment by Chhunlong** [comment]
Sound's great!
I will re-checked before reporting.
