### ISSUE TITLE
Page title escaped twice

### ISSUE THREAD

**Issue by georgringer** [benjaminkott/bootstrap_package#409]
If having a page title like `SLA & Sponsoring`, this will be escaped twice in the main navigation (And probably all others)

It is already provided as `SLA &amp; Sponsoring` to the template

**Comment by eberhardloh** [comment]
My current solution is to patch Classes/DataProcessing/MenuProcessor.php,
because there is no way to externally reconfigure the "$menuLevelConfig".

please change the default settings to
...
'htmlSpecialChars' => '0',
...

**Comment by benjaminkott** [comment]
@georgringer @eberhardloh currently unable to reproduce this. can you give me a hint how to exactly reproduce this?

**Comment by eberhardloh** [comment]
'htmlSpecialChars' => '1'
seems to be removed since version 7.0.3 or 7.0.4
so default is now '0', problem solved.

**Comment by benjaminkott** [comment]
@eberhardloh @georgringer i am closing this for now since the problem does not seem to exist anymore.
