### ISSUE TITLE
BE displays non-scaled images ?

### ISSUE THREAD

**Issue by olegsv** [benjaminkott/bootstrap_package#411]
bootstrap_package v7.0.2 , typo3 7.6.14 - image size not adjusted for BE -> Page display.

![screenshot from 2016-12-21 11-09-39](https://cloud.githubusercontent.com/assets/4197479/21383757/096024e8-c770-11e6-8760-26be4a6f653b.png)

![screenshot from 2016-12-21 11-14-38](https://cloud.githubusercontent.com/assets/4197479/21383686/b81def34-c76f-11e6-8248-f8f06e8dc597.png)

Is it a misconfiguration or it's a bug?

**Comment by benjaminkott** [comment]
@olegsv seems that you imagemagick / graphicsmagick is not configured correctly, head to the install tool and check your settings, after setting them correctly the problem should be gone.
