### ISSUE TITLE
 Call to undefined method  ...TypoScriptFrontendController::getPageRenderer()

### ISSUE THREAD

**Issue by ehwg** [benjaminkott/bootstrap_package#412]
Hi, 
when upgrading my typo3 instance from  7.6.14 to 8.5 I get the following error when viewing the pages: 

Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to undefined method TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController::getPageRenderer() | Error thrown in file C:\xampp\xampp706\htdocs\typo3_85_dev\typo3conf\ext\bootstrap_package\Classes\Service\CompileService.php in line 64. Requested URL: http://localhost:88/typo3_85_dev/index.php?id=1

Answer from the typo3 core team was:
see https://docs.typo3.org/typo3cms/extensions/core/8-dev/Changelog/8.0/Breaking-72424-RemovedDeprecatedTypoScriptFrontendControllerOptionsAndMethods.html
just to a makeInstance on the PageRenderer as it is a singleton anyway!

See my ticket: https://forge.typo3.org/issues/79080#change-320080
Is there a way to implement a workaround.
I have bootstrap package 7.0.2 which should work with typo3 8.5
Thanks for your help.
Eckard.

**Comment by ehwg** [comment]
OK I have now commented out the following two lines:
                  // disable CSS compression
                    /** @var $pageRenderer \TYPO3\CMS\Core\Page\PageRenderer */
       --->>>        //$pageRenderer = $GLOBALS['TSFE']->getPageRenderer();
       --->>>        //$pageRenderer->disableCompressCss();
and the issue seems to be resolved at least for now.

**Comment by benjaminkott** [comment]
@ehwg thx for reporting, you are right - already fixed in master https://github.com/benjaminkott/bootstrap_package/blob/master/Classes/Service/CompileService.php#L113-L115 will take care of the backport, currently preparing releases.

**Comment by benjaminkott** [comment]
@ehwg patch is now also applied for the 7.0.x release you can download it directly here of wait for the composer / ter release https://github.com/benjaminkott/bootstrap_package/archive/BP_7-0.zip

sry missed that cssSourceMapping was broken with current release in cms 8, since it was fixed in master already.
