### ISSUE TITLE
Text alignment not working in text and icon elements

### ISSUE THREAD

**Issue by Patta** [benjaminkott/bootstrap_package#415]
In v7.0.4  and TYPO3 8.5.1 the RTE text alignment classes like `class="text-center"` or `class="text-right"` in text and icon elements are removed for paragraphs after saving.

**Comment by benjaminkott** [comment]
@Patta thx for reporting, the next release for CMS8 will not use rtehtml area anymore - with ckeditor everything was tested correctly - please check out master branch.
