### ISSUE TITLE
TCA migrations eed to be done in typo3 8.5

### ISSUE THREAD

**Issue by ehwg** [benjaminkott/bootstrap_package#416]
### Prerequisites
Typo3 8.5

### Description

When upgrading from lower version to typo3 8.5 I see in install tool that TCA migrations need to be applied

I get about 15 deprcated notifications such us: 
>>>Migrated icon path of wizard "link" in field "link" from TCA table "tx_bootstrappackage_carousel_item". New path is: actions-wizard-link

I am using latest version 7.0.5

Best regards
Eckard.

**Comment by benjaminkott** [comment]
@ehwg thx for reporting, all deprecations should be resolved with the upcomming release for CMS8 only - you can already checkout the master branch for testing this. while supporting multiple versions not all deprecations can be resolved easily.
