### ISSUE TITLE
idea for custom content templates

### ISSUE THREAD

**Issue by gilas1959** [benjaminkott/bootstrap_package#422]
Hi
I do not know if there is a way to avoid moving the content template out of your EXT folder.
Infact, this is the way

CONSTANTS

```
plugin.bootstrap_package_contentelements {
  view {
    layoutRootPath = fileadmin/template/Resources/Private/Layouts/ContentElements/
    partialRootPath = fileadmin/template/Resources/Private/Partials/ContentElements/
    templateRootPath = fileadmin/template/Resources/Private/Templates/ContentElements/
  }
}
```

ok. this is right and works correctly. Instead I want to keep the link toward your EXT folder and get some extrafolders. Could you plan to add some typoscript like this?

```
plugin.bootstrap_package_contentelements {
  view {
    layoutRootPath.1 = fileadmin/template/Resources/Private/Layouts/ContentElements/
    partialRootPath.1 = fileadmin/template/Resources/Private/Partials/ContentElements/
    templateRootPath.1 = fileadmin/template/Resources/Private/Templates/ContentElements/
  }
}
```

better explained in SETUP view shoud be treated as COA Object or similiar, so that YOUR code will be not modified and when I add .1, .2 objects I can ADD new folders usually in fileadmin where I  to put my custom templates to add or override your code.

```
plugin.bootstrap_package_contentelements {
  view {
    layoutRootPath = EXT:bootstrap_package/Resources/Private/Layouts/ContentElements/
    partialRootPath = EXT:bootstrap_package/Resources/Private/Partials/ContentElements/
    templateRootPath =EXT:bootstrap_package//Resources/Private/Templates/ContentElements/
  }
}
```

**Comment by cedricziel** [comment]
Hi @gilas1959 !

Thank you for your thoughts on that matter - really appreciated.

Fluid itself has a mechanism to provide a predictable path for overrides. Take for example the accordion CE (definition here: https://github.com/benjaminkott/bootstrap_package/blob/master/Configuration/TypoScript/ContentElement/BootstrapPackageAccordion.txt#L13).

That means you can override any template you want by setting the following typoscript in your own site package TypoScript (preferred) or on a ts template record (not so much preferred).

I've copied the relevant code below. So say you need a 2nd level overlay as you mentioned, you would add the `tt_content.bootstrap_package_accordion.templateRootPaths.20` TypoScript setup definition and be done.

```
tt_content.bootstrap_package_accordion {
    templateRootPaths {
        0 = EXT:bootstrap_package/Resources/Private/Templates/ContentElements/
        10 = {$plugin.bootstrap_package_contentelements.view.templateRootPath} # here's the constant you mentioned
        20 = EXT:my_other_ext/Resources/Private/Templates/ContentElements/
    }
    partialRootPaths {
        0 = EXT:bootstrap_package/Resources/Private/Partials/ContentElements/
        10 = {$plugin.bootstrap_package_contentelements.view.partialRootPath}
    }
    layoutRootPaths {
        0 = EXT:bootstrap_package/Resources/Private/Layouts/ContentElements/
        10 = {$plugin.bootstrap_package_contentelements.view.layoutRootPath}
    }
}
```
