### ISSUE TITLE
double-link: http://domain.com/http://domain.com in main navigation

### ISSUE THREAD

**Issue by rosimittermeier** [benjaminkott/bootstrap_package#423]
### Prerequisites

* [yes ] Can you reproduce the problem on TYPO3 7.6 LTS
* [ i dont know] Can you reproduce the problem on TYPO3 8.5
* [ i dont know] Can you reproduce the problem on TYPO3 8 dev-master
* [ yes] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package) to see if your bug or enhancement is already reported?

### Description

Starting from typo3 6.2.30 I upgraded to 7.6.15. Bootstrap-Package has been updated during this process. Now a problem reappears which I solved in earlier versions, but I cant remember how. Its a problem with the main-navigation. When I go to an arbitrary subpage the link to the starting page (the link in the menu and the logo-link) have the form: http://domain.com/http://domain.com. Following the links I get a 404 error and then everything is ok again: http://domain.com

### Steps to Reproduce
???

**Expected behavior:** [What you expected to happen]
the menu-link and the logo-link to the startpage should only have the form http://domain.com

**Actual behavior:** [What actually happened]

### Versions

You can get this information from executing `composer show` at the command line if your TYPO3 installation is composer based, otherwise the version number will be shown in the extension manager.

**Comment by igodorogea** [comment]
I believe this is related to realurl, and after upgrade it become realurl 2.x.
Check your realurl configuration for this property `emptyUrlReturnValue`.
I would suggest to set it to '/' or ''(empty string).
Don't forget to clear the caches and realurl caches.
Good luck.

**Comment by benjaminkott** [comment]
@rosimittermeier did you check the solution from @igodorogea?

**Comment by rosimittermeier** [comment]
thanks. indeed, now it works again. the exact cause is unclear. the reason was partly my incompetence and partly some logical inconsistence in my typo3-logic which resulted form history of many solutions of multiple problems. I have a multidomain-site and I worked with baseurl (in setup) and conditions (in constants). this seems to be oldfashioned a cause of logical inconsistence with 7.6.x and realurl 2.x. maybe more causes should be identified, but I have not been acting planful in finding a solution. so it works  now, but perhaps it is a real wonder!  now I have no explicit emptyurlvalue declaration but the automatic realurl configuration from somewhere got some freedom to work well (indeed: "/"). thanks again. hans
