### ISSUE TITLE
Extension needs to be compatible with TYPO3 8.6

### ISSUE THREAD

**Issue by josefglatz** [benjaminkott/bootstrap_package#425]
![image](https://cloud.githubusercontent.com/assets/2861556/23094987/cdc2080e-f602-11e6-9717-dd0f65d0f382.png)

**Comment by rainerth** [comment]
Since bootstrap_package is part of the only official distribution package, I am wondering about the schedule to get bootstrap_package unblocking again. Any plans? Or any workarounds? 
Thank you in advance!

**Comment by cedricziel** [comment]
As per https://github.com/benjaminkott/bootstrap_package/blob/master/composer.json#L29 and https://github.com/benjaminkott/bootstrap_package/blob/master/ext_emconf.php#L12 , the extension is >=8.6.* compatible already.

@benjaminkott will surely publish it to TER, once it's stable, please be a little more patient.

As a temporary workaround, you can always require the extension as version `dev-master` via composer or clone it to `typo3conf/ext`. `cd typo3conf/ext && git clone https://github.com/benjaminkott/bootstrap_package.git`. The introduction package will recognize your local copy of `EXT:bootstrap_package`.

**Comment by benjaminkott** [comment]
i guess we can close this one ;)
