### ISSUE TITLE
update from 7.0.5 to 7.1.0

### ISSUE THREAD

**Issue by rosimittermeier** [benjaminkott/bootstrap_package#427]
### Prerequisites

* [ id dont have typo3 8.6] Can you reproduce the problem on TYPO3 8.6
* [ dito] Can you reproduce the problem on TYPO3 8 dev-master
* [ yes, but maybe my search strategy was wrong. I do not really understand the problem] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package) to see if your bug or enhancement is already reported?

### Description

today I updated my typo3_website extension "bootstrap_package" from 7.0.5 to 7.1.0. (tyo3 7.6.15.) The site originally was a Introduction-Package-Site (now version 2.3.0). Now, the Site seems broken. I see only: "Oops, an error occurred! Code: 20170227203735c4708643". Deactivating something (page.config.contentObjectExceptionHandler = 0) I get this Message: "RealURL could not process "/index.php?id=64&L=2" because "L" parameter is invalid. More information can be found in the web server error log." (I deleted realurl_autoconf.php and started the autoconf-process again. The errors come back again.)

Now, deactivating RealUrl has some success. I see the pages, but some Introduction-Package-Icons are missing and the fonts are changed and the pages seem to be different in other respects.

Maybe I am (due to incompetence) the cause. If I build a Typo3-Site with introduction package and/or bootstrap-package I try to get rid of the language menu (I simply dont need it). Thats difficult an so I have to delete some code in the setup.txt (typoscript) on the server. That works, but maybe my problem depends on this fact.

**Comment by benjaminkott** [comment]
RealUrl changed the behaviour here, please see the link above or set the constants
```
page.theme.language.enable = 0
page.theme.language.languageValue = 0
```
https://github.com/benjaminkott/bootstrap_package/blob/master/Configuration/TypoScript/constants.typoscript#L86
