### ISSUE TITLE
Problem with RealURL since bootstrap_package updated to v7.1.0

### ISSUE THREAD

**Issue by jdgonon** [benjaminkott/bootstrap_package#428]
### Prerequisites

* [ I use TYPO3 v7.6.16, not v8.6 ] Can you reproduce the problem on TYPO3 8.6
* [ I use TYPO3 v7.6.16, not v8.6 ] Can you reproduce the problem on TYPO3 8 dev-master
* [ there is this [issue](https://github.com/benjaminkott/bootstrap_package/issues/427), but I don't understand his solution ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package) to see if your bug or enhancement is already reported?
* [ I use :
bootstrap_grids v1.3.1
bootstrap_package v7.1.0
gridelements v7.0.5
realurl v2.1.8 ]

### Description

On a tests site, since I have updated bootstrap_package from v7.0.5 to v7.1.0, I don't have any content displayed, and I have errors message "Oops, an error occurred"

fh_debug extension displays : 
"Code: 2017030420135267f53a11 **RealURL could not process "https://test.espoir-et-vie.net/index.php?id=espoiretvie&L=1" because "L" parameter is invalid**. More information can be found in the web server error log. exception code:1482160086 file:/typo3conf/ext/realurl/Classes/Encoder/UrlEncoder.php line:1410 fh_debug trace: file: /typo3conf/ext/realurl/Classes/Encoder/UrlEncoder.php" line:1245 function:validateLanguageParameter file: /typo3conf/ext/realurl/Classes/Encoder/UrlEncoder.php" line:875 function:setLanguage file: /typo3conf/ext/realurl/Classes/Encoder/UrlEncoder.php" line:132 function:executeEncoder file: " line: function:encodeUrl file: /typo3/sysext/core/Classes/Utility/GeneralUtility.php" line:4377 function:call_user_func_array file: /typo3/sysext/core/Classes/TypoScript/TemplateService.php" line:1581 function:callUserFunction file: /typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php" line:6706 function:linkData file: /typo3/sysext/frontend/Classes/ContentObject/Menu/AbstractMenuContentObject.php" line:2129 function:typoLink"

When I deactivate RealURL, all pages are displayed with URL : https://test.espoir-et-vie.net/index.php?id=page
I don't find more informations in logs.
The site has only one language (french).

My setup configuration is :
`config {
  linkVars=L

  sys_language_uid = 0
  sys_language_overlay = 1
  sys_language_mode = content_fallback
  language = fr
  locale_all = fr_FR.UTF-8
  htmlTag_setParams = lang="fr" dir="ltr" class="no-js"
  htmlTag_langKey = fr
  additionalHeaders = Content-Type:text/html;charset=utf-8
  
  renderCharset = utf-8
  metaCharset = utf-8

  domain = test.espoir-et-vie.net
  absRefPrefix = https://test.espoir-et-vie.net/
  baseURL = https://test.espoir-et-vie.net/

  prefixLocalAnchors = all
  typolinkEnableLinksAcrossDomains = 1
  tx_realurl_enable = 1
  simulateStaticDocuments = 0
}

[globalVar = GP:L = 1]
config {
    sys_language_uid = 1
    language = fr
    locale_all = fr_FR.UTF-8
    htmlTag_setParams = lang="fr" dir="ltr" class="no-js"
    htmlTag_langKey = fr
}
[GLOBAL]`

Is there a bad configuration in my setup ?
What can I search or modify to solve my problem ?

Thanks for all remarks !

### Versions

You can get this information from executing `composer show` at the command line if your TYPO3 installation is composer based, otherwise the version number will be shown in the extension manager.

**Comment by Backdraft007** [comment]
Have a look in your constant editor at language. Default 0,1,2, you have to edit this field to your needs. E.g. if you have only one language, change the setting to 0.

**Comment by jdgonon** [comment]
Thanks very much !!

You have my solution :+1: 
I have to modify LanguageValue to : page.theme.language.languageValue = 0
