### ISSUE TITLE
problem to add a new typical page content (Text & Media , Text & Images ) 

### ISSUE THREAD

**Issue by nabilou01** [benjaminkott/bootstrap_package#431]
### Prerequisites

* [x] Can you reproduce the problem on TYPO3 8.6
* [x] Can you reproduce the problem on TYPO3 8 dev-master
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package) to see if your bug or enhancement is already reported?

### Description

Dears

I have instaled the last commit (09/03/2017) and now I have problem to add a new typical page content (Text & Media , Text & Images ) and instead it i have error message 
              "Oops, an error occurred!
             YAML File "" could not be loaded"

whats the wrong?

Nabil

### Versions
8.0.0-dev

**Comment by nabilou01** [comment]
Dears

Till have the same problem.
The lof file said
Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1485784246: YAML File "" could not be loaded | RuntimeException thrown in file /opt/bitnami/apps/typo3/typo3_src-8.6.1/typo3/sysext/core/Classes/Configuration/Loader/YamlFileLoader.php in line 68.
Regards

**Comment by nabilou01** [comment]
Dears
Problem resolved after instaling CKEditor extension. 
Regards

**Comment by benjaminkott** [comment]
@nabilou01 thx for the pointer, added ckeditor as dependency
