### ISSUE TITLE
Best practice to include own CSS?

### ISSUE THREAD

**Issue by michaelmeurer** [benjaminkott/bootstrap_package#433]
Hello to all.
Please excuse me, if i'm wrong to use this here. It's my first question. And i didn't find here on github anything about my question

I'm using a clean TYPO3 8.6.1 and latest Bootstrap_package from TER. I want to put some of my own CSS to the package.

For example i have a 2 column gridelement CE and defined a breakpoint. Bigger screens should show this CE in 2 columns, smaller screens only in 1 column, the right part behind the left.

I hoped to keep the less-structure from the package and hoped to import my files in the bootstrap.less. Bcause i saw, there are files with normal css too. So i copied the the Resources folders and files to
fileadmin/extensions/bootstrap_package/Resources/Public/Less/Bootstrap/
(with the same .hcaccess-files like in the extensionfolder)
In this bootstrap.less i wanted to import my changes:
@import "mycss.less";
Most works fine. My Css is included in the /typo3temp/boostrappackage/lessphp_487b844cf70dd27a7b6e0050e1e8da2f0d40b1e9.css?1489705316.

But in this moment, when i include the bootstrap.less from outside of the extension, the lightbox doesn't work anymore. The pictures don't open in the lightbox, when i click on it. It happens nothing.
When i comment this line in the Typoscript out and use the bootstrap.less from the extension, the lightbox works again.
Did i made something wrong in this way? Or is it only possible to use it in the way
page.includeCSS {
         myCss = path/to/my/css/my-file.css?
    }

Thanks and greetings.
Michael

**Comment by mfvetter** [comment]
This might not be the answer you are looking for, but:

Are you including any image in the background in your CSS or LESS file? If yes, you should make sure to adjust the relative paths to the images and fonts.

**Comment by michaelmeurer** [comment]
No, i don't do.
**The lightbox doesn't work in this moment, when i include it from outside the extension. It's no difference if i include changes or not.**
I change (or my plan to change is)
- @media (min-width: 1200px) { width:960 px}} to get a 2 column text with about to 60 readable signs per line.
- CD/CI colors, which aren't changable in Constants
- my own font
I think, nothing, what changes the principle or mechanic from including the images in bootstrap

**Comment by michaelmeurer** [comment]
I could limit the problem.
i only found this lines to include the CSS in .../Configuration/Typoscript/setup.ts:
    includeCSS {
        # bootstrap will be included in the themes.less file
        # for standalone usage just uncomment the following line
        # bootstrap = EXT:bootstrap_package/Resources/Public/Less/Bootstrap/bootstrap.less
        theme = EXT:bootstrap_package/Resources/Public/Less/Theme/theme.less
    }
so i used
page.includeCSS >
page.includeCSS {
  bootstrap = path/to/my/file/bootstrap.less
}
In this way the lightbox doesen't work.

When i only use
page.includeCSS {
  bootstrap = path/to/my/file/bootstrap.less
}
both bootstrap.less-File are included: From the extension and my file.
Strange...
With:
page.includeCSS.bootstrapOverrides = path/tp/my/file
everything works fine and i can overwrite, what i can't find in the constants.
Wow, it's a complex extension and much to learn. ;-)
