### ISSUE TITLE
404 on Search

### ISSUE THREAD

**Issue by farconada** [benjaminkott/bootstrap_package#434]
Just backport https://github.com/TYPO3/TYPO3.CMS/commit/2071520d18f37aa9102c602af28b07e880737749#diff-dc41ab52a8d70a9166285efd4ccac0ef 

[BUGFIX] Indexed search causes 404 because of missing cHash 

On TYPO3 8.6

**Comment by benjaminkott** [comment]
Should be resolved with https://github.com/benjaminkott/bootstrap_package/commit/c9ce1dd2bf3ef31bd9ef717d0723e81533fd16ee
