### ISSUE TITLE
Text&media Image manipulation disappears after installing Bootstap_Package

### ISSUE THREAD

**Issue by RS974** [benjaminkott/bootstrap_package#438]
Hello,

TYPO3 8.7 LTS
bootstrap_package 8.0.0 

New install of TYPO3 8.7.0 is clean.
Bootstrap package is the only installed extension

Many fields have disappeared and "Image manipulation" editor in typo3 FAL Image

![typo3_8 7 0_boostrap_package_8 0 0_2017-04-07_1405](https://cloud.githubusercontent.com/assets/23738457/24799486/998bf6d0-1b9b-11e7-8025-6cd589d59380.png)
![typo3_8 7 0_2017-04-07_1404](https://cloud.githubusercontent.com/assets/23738457/24799485/9989be06-1b9b-11e7-94e6-0292d04ee038.png)

**Comment by RS974** [comment]
No one has this display problem ?

**Comment by gilas1959** [comment]
yes, the same. It is provoked from bootstrap package 8.0,0 or it depends from TYPO3 CMS v.8.7.x?!? I do not know.

**Comment by gilas1959** [comment]
Hi Benji
I hope you can solve this annoying problem. Infact the textMedia content cannot more linked and I have two published extension that are not working with this cType. If I uninstall your ext all is working fine and the fields appears, when I reinstall your +ext v. 8.0 (TYPO3 CMS v. 8.7) the fields are not available.
Thank you for your precious work!

**Comment by benjaminkott** [comment]
@gilas1959 i am currently debugging this

**Comment by gilas1959** [comment]
maybe the --pallette is misconfigured in:
Configuration/TCA/Overrides/tt_content_element_media.php or another (similar) file?

**Comment by benjaminkott** [comment]
@gilas1959 it currently looks like the exact same configuration, still unable to find out whats the problem

**Comment by florianstieglbauer** [comment]
The problem is here.
[](https://github.com/benjaminkott/bootstrap_package/blob/33d85248d98fadbae39c9696f54b994a5f82c656/Configuration/TCA/Overrides/tt_content_general_columns.php#L17-L26)

@benjaminkott Can you look at the problem?

**Comment by benjaminkott** [comment]
@florianstieglbauer thx a lot was searching for this a while here and then
