### ISSUE TITLE
constant page.theme.meta.enable shows no impact

### ISSUE THREAD

**Issue by christen90** [benjaminkott/bootstrap_package#439]
### Description
I can not remove the meta section in the footer. Removing of the language menu and the whole footer section works. I would like the language section but I do not need the meta section above

### Steps to Reproduce
Setting the constant in home template
page.theme.meta.enable = 0

**Expected behavior:**
meta section should disappear
**Actual behavior:**
it did not

### Versions
8.0.0

**Comment by benjaminkott** [comment]
hey @christen90, i am sadly unable to reproduce the issue, the meta section gets correctly disabled if the value is set. The menu items from the meta section imprint and privacy were correctly removed after setting the value.

`page.theme.meta.enable = 1`
![image](https://cloud.githubusercontent.com/assets/3243119/26274124/4d3ca11c-3d42-11e7-8046-37037e4ccb1b.png)

`page.theme.meta.enable = 0`
![image](https://cloud.githubusercontent.com/assets/3243119/26274129/7317f526-3d42-11e7-9923-9734baefae14.png)

**Comment by christen90** [comment]
Sorry, my fault.
What I really wanted to get rid of is the grey box above the meta section.
I find out, that it's coming from the PageLayout and by commenting out a few lines in:

`Resources/Private/Partials/Page/Structure/Footer.html`

I finally did it.

For beginners it would be nice to add some pagestyles without the footer areas.
