### ISSUE TITLE
Footer collapsed to a 1 pixel line

### ISSUE THREAD

**Issue by eduardofrank** [benjaminkott/bootstrap_package#440]
### Prerequisites

* [ ] Can you reproduce the problem on TYPO3 8.7 LTS
* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package) to see if your bug or enhancement is already reported?

### Description

I have a site that is being developed for which I recently noticed a problem with the footer. It collapsed into a single 1 pixel line. Upon inspection of the html code, all three col-sm-4 were empty. The footer for this site is rather simple, it has just a copyright notice. The footer is enabled in the basic constants of the bootstrap package. Same thing for the copyright text, which is also present in the constants. Going back to a prior backup of the site didn't solve it.
When I first noticed the issue, Typo3 CMS version was 7.6.15 and the bootstrap package was version TER 7.1.0. After upgrading to CMS 7.6.16, the issue remained.
Tampering with my own site package extension didn't solve it. Addressing the footer with css enabled its full height again, but the copyright text was still absent and the col-sm-4 elements were still empty. I then removed the css code used to restore the height of the footer.
Later I tried bootstrap package version TER 7.0.2 with CMS 7.6.16 and the issue disappeared.
After that, I jumped to TER 7.0.5 keeping CMS 7.6.16 and it still behaves correctly, showing both footer and copyright text. 
If I upgrade to TER 7.1.0 the issue reappears.

Other versions:
Apache: 2.2.31
PHP: 5.6.29
MySQL: 5.6.32

**Comment by eduardofrank** [comment]
Please disregard completely.
The issue was traced back to a wrongly configured site package.
Position 0 in the array for the different paths for the Fluidtemplates was overridden and not assigned to the bootstrap_package which brought up the footers behaviour.

**Comment by benjaminkott** [comment]
@eduardofrank thx a lot for clearing this up, i will close the issue now.
