### ISSUE TITLE
Add custom elements to navigation section

### ISSUE THREAD

**Issue by aimeos** [benjaminkott/bootstrap_package#441]
It would be great if the bootstrap_package offers a possibility to add new elements to the navigation section via TypoScript. In our case, we would like to add the small basket as custom element. Currently, all integrators have to copy the files in `Resource/Private/Partials/Page/Navigation/` and add those lines to the `Main.html` file:
```
<f:if condition="{f:cObject(typoscriptObjectPath:'lib.navigation.misc.basket')}">
    <f:cObject typoscriptObjectPath="lib.navigation.misc.basket" />
</f:if>
```
Unfortunately, a lot of people are unable to get this done right. Therefore it would be very helpful to be able to put custom elements defined via TS between these lines:
https://github.com/benjaminkott/bootstrap_package/blob/master/Resources/Private/Partials/Page/Navigation/Main.html#L15-L16

The best option would be an arbitrary list of elements (`lib.navigation.misc`) where everyone can add what he needs like:
```
lib.navigation.misc = COA
lib.navigation.misc.basket = USER
lib.navigation.misc.basket {
    ...
}
```

**Comment by benjaminkott** [comment]
@aimeos i agree that we could make this a bit more flexible here, but i really do not like to load random typoscript here. We had a similar issue with the flexibility of fluid based content elements. I´ve introduced a new "dropin" concept for that.

https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/core/Documentation/Changelog/8.6/Feature-79622-NewDefaultLayoutForFluidStyledContent.rst#dropin

I would really like to avoid any typoscript when possible, would that also be a suitable way for you?

**Comment by aimeos** [comment]
@benjaminkott How it's done is actually not that relevant as long as it's easy even for non-experts and flexible enough to have several "dropin content" elements from different extensions for the same place. 
Example: We would add our small basket there and the site owner wants additionally the language/currency selector before the small basket but also between logo and menu.
