### ISSUE TITLE
Cropped image does't fall back to default crop if no other more specific crop has been set

### ISSUE THREAD

**Issue by webian** [benjaminkott/bootstrap_package#443]
### Prerequisites

* [x] Can you reproduce the problem on TYPO3 8.7 LTS
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package) to see if your bug or enhancement is already reported?

### Description

Fall back to default crop if no other more specific crop has been set

### Steps to Reproduce

1. Crop a picture only in 'default' configuration
2. Browse the page in a small device

**Expected behavior:**
The image is cropped with default configuration

**Actual behavior:**
The image is not cropped. To have the default crop in every device the editor has to crop the image 4 times.

### Versions

TYPO3 8.7.1 dev
bootstrap_package 8.1.0 dev

**Comment by webian** [comment]
Investigating further I think that the bug is in Fluid not in bootstrap_package:
https://forge.typo3.org/issues/80845

**Comment by benjaminkott** [comment]
thx for reporting, should be fixed in core then.
