### ISSUE TITLE
How to define custom class, title, and target in Link Browser for content elements and the new rte_ckeditor?

### ISSUE THREAD

**Issue by mfvetter** [benjaminkott/bootstrap_package#445]
### Prerequisites

* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package) to see if your bug or enhancement is already reported?
* [x] Can you reproduce the problem on TYPO3 8.7 LTS

### Description

How do I configure default link target, class, and title for the Link Browser in any element link (usually element titles and images) AND in rte_ckeditor? I've spent several hours trying to configure it, but no success and no documentation out there. The fields are empty.

![link-browser-external](https://cloud.githubusercontent.com/assets/7863521/25319067/4de1824e-284e-11e7-9e76-29766eff1c6f.png)

![link-browser-page](https://cloud.githubusercontent.com/assets/7863521/25319074/68d0bac0-284e-11e7-8da4-9e80ee69c48e.png)
### Steps to Reproduce
1. Create any element that you can link the title or image.
2. Click to open the Link Browser
3. The options come empty for any type of link (Page, File, Folder, External URL, Email).

**Expected behavior:** 
I want to define default classes, link targets and titles for each type of link if they are empty.
For example External URL, I want to automatically populate with target="_blank", class "external-link", title="Link to External Website", if the link wasn't configure previously. Basically for any new link I just want to have it auto populated with my custom values and not empty values.

This used to work for rtehtmlarea only on previous Typo3 versions, but not I'm not able to set this option system wide on Typo3 8 LTS.

The PageTS that used to work only for rtehtmlarea was something like this:
```
RTE {
	classesAnchor {
		externalLink {
			class = external-link
			type = url
			titleText = Opens external link in new window
			target = _blank
		}
		externalLinkInNewWindow {
			class = external-link-new-window
			type = url
			titleText = Opens external link in new window
			target = _blank
		}
		internalLink {
			class = internal-link
			type = page
			titleText =  Opens internal link in this window
			target = _top
		}
		internalLinkInNewWindow {
			class = internal-link-new-window
			type = page
			titleText = Opens internal link in new window
			target = _blank
		}
		folder {
			class = folder
			type = folder
			titleText =
			target =
		}
		download {
			class = download
			type = file
			titleText = Initiates file download
			target = _blank
		}
		mail {
			class = mail
			type = mail
			titleText = Email Address
		}
	}
}
```
I would like this to work for the new rte_ckeditor as well for any element options that I can link using the Link Browser.

**Comment by gilas1959** [comment]
The fact is that the new bootstrap_package v8 that is running under T3 8.x do not uses anymore the rtehtmlarea. Bootstrap works with the dependency (ext_emconf.php) with the new editor:

rte_ckeditor

well, downloading the new rtehtmlarea (v.8.x.x) from the repository  this is marked as "obsolete".
So it seems that there is not anymore any setup to put within the tab Resources of your page properties.
Inspecting the boostrap I found the the new conf file is named:
/var/www/www.yoursite.it/web/typo3conf/ext/bootstrap_package/Configuration/RTE/Default.yml
and is a yml file. 
This i s innovative (I suppose)  but a bit annoying because I shold modify the settings site by site. No backward compatibility for rtehtmlarea (I think!)

**Comment by gilas1959** [comment]
moreover rte_ckeditor is a system extension and inspecting the code there is not any documentation. Now I'm going to look if there is some info/docs on the typo3 doc site.

**Comment by gilas1959** [comment]
rte_ckeditor is a system extension. here you can find some infos:
https://typo3worx.eu/2017/02/configure-ckeditor-in-typo3/
http://docs.ckeditor.com/#!/api/CKEDITOR.config

**Comment by mfvetter** [comment]
Hi @gilas1959, the problem isn't the rte_ckeditor extension at all. It's the Link Browser (linkHandler) functionality in the core of Typo3. I was able to solve part of the problem with the following configs:

For rte_ckeditor PageTS I have this:

```   
#############
#### RTE ####
#############
RTE {
    default {
        preset = default
        classesAnchor {
            page {
                class =
                type = page
                titleText =
                target =
                image =
                #params =
                rel =
            }

            file {
                class = download
                type = file
                titleText = Open or download file in new window
                target = _blank
                image =
                #params =
                rel =
            }

            folder {
                class = folder
                type = folder
                titleText = Open or download file in new window
                target = _blank
                image =
                #params =
                rel =
            }

            mail {
                class = email
                type = mail
                titleText = Send email
                image =
                #params =
                rel =
            }

            url {
                class = external-link
                type = url
                titleText = Open external link in new window
                target = _blank
                image =
                #params =
                rel =
            }
        }
        buttons.link {
            options.removeItems = folder

            file.properties {
                class.default = download
                title.readOnly = 1
            }
            folder.properties{
                class.default = folder
                title.readOnly = 1
            }
            url.properties {
                class.default = external-link
                title.readOnly = 1
            }
            mail.properties {
                class.default = email
                title.readOnly = 1
            }
            properties.class.allowedClasses = external-link,folder,email,download,article,phone
            queryParametersSelector.enabled = 0

        }
    }
}

```
For TCEMAIN PageTS I have this:

```
#################
#### TCEMAIN ####
#################
TCEMAIN {
	linkHandler {
		file.addParams = onclick="jumpToUrl('?act=file&linkAttributes[target]=_blank&linkAttributes[title]=Open or download file in new window&linkAttributes[class]=download');return false;"
		url.addParams = onclick="jumpToUrl('?act=url&linkAttributes[target]=_blank&linkAttributes[title]=Open external link in new window&linkAttributes[class]=external-link');return false;"
		mail.addParams = onclick="jumpToUrl('?act=mail&linkAttributes[title]=Send email&linkAttributes[class]=mail');return false;"
	}
}
```

**Comment by gilas1959** [comment]
thank you very much. I have another question: do you know where I can find the RTE PageTS reference valid for the new rte_ckeditor? Or it is the same for rtehtmlarea?!? I.e. howto  configure the path to the CSS file with the styles to use with ckeditor?
Thank you very much for your suggestion. I tried it and works correctly

**Comment by mfvetter** [comment]
@gilas1959, I'm not sure about the refecence in the docs. I don't think the documentation is accurate, so I usually spend hours on trial and errors. But for the path to another css file for the rte_ckeditor, you must define in the .yaml file. This is what you need to define the new CSS file:

```
    config:
        contentsCss:
            - "EXT:bootstrap_package/Resources/Public/Css/rte.min.css" #keep the original if you want
            - "EXT:your_package/Resources/Public/Css/rte/styles.css" #add your custom css
```
You can keep adding as many css files as you want, just add one css file per line.

I suggest you register a new Default.yaml in a custom extension. To define your own yaml configuration, just add this line to your ext_localconf.php file in your custom extension:

`$GLOBALS['TYPO3_CONF_VARS']['RTE']['Presets']['default'] = 'EXT:your_package/Configuration/RTE/Default.yaml';`

Copy the Default.yaml from the bootstrap_package as a base to your_package/Configuration/RTE/ and then start making the changes you want. This way, when the original bootstrap_package has an update, you won't loose your custom configs.

For more options on ckeditor, I go to their website and check their reference. This post helped me a lot as well: https://typo3worx.eu/2017/02/configure-ckeditor-in-typo3/

**Comment by benjaminkott** [comment]
Seems to be related to TYPO3 itself, will not be solved here.
