### ISSUE TITLE
[BUG] Bootstrap button sizes not working

### ISSUE THREAD

**Issue by Patta** [benjaminkott/bootstrap_package#447]
Bootstrap button sizes like `.btn-lg`, `.btn-sm`, or `.btn-xs` not working. 
The Bootstrap button size styles from bootstrap.less are blocked/overwriten by button styles from misc.less.

I think the buttons styles with comment "Buttons from RTE" in misc.less are from a old extension version without ckeditor support and can be removed.

**Comment by benjaminkott** [comment]
@Patta you are absolutely right, thx for pointing this out!
