### ISSUE TITLE
 feature request: Keep accordion closed if only one or make it configueable

### ISSUE THREAD

**Issue by ehwg** [benjaminkott/bootstrap_package#448]
Hi Benjamin,

If there is only one accordion item i suggest to let it closed per default:
Could be reached via the following template modification in accordion.htm in line 16.

`<div id="accordion-{data.uid}-{record.data.uid}" class="panel-collapse collapse {f:if(condition: '{iteration.isFirst} && {iteration.isFirst}!={iteration.isLast}', then: 'in')}" role="tabpanel" aria-labelledby="accordion-heading-{data.uid}-{record.data.uid}">`

Alternatively as just discussed you could also make it more configurable to let decide which on should be opened per default.
Best regards
Eckard.

**Comment by benjaminkott** [comment]
resolved in https://github.com/benjaminkott/bootstrap_package/commit/dca76d18b185c5eb62c5d40ee230d1d0f075ca5a
