### ISSUE TITLE
Full Width Content

### ISSUE THREAD

**Issue by ByteNetworks** [benjaminkott/bootstrap_package#451]
### Description

Is there any way to implement a Full-Width Section for content (like the Footer) on a Page?

**Comment by Patta** [comment]
@ByteNetworks a custom frame class and some fancy css should do that :)

**Comment by benjaminkott** [comment]
@ByteNetworks @Patta  this is now enabled by default in current master. All layouts that have a single column have no restrictions anymore. this allows you to play with custom background colors / background images that are now also supported by default from the bootstrap package.

Results can be checked here:
https://www.bootstrap-package.com/pages/default/
https://www.bootstrap-package.com/pages/simple/
https://www.bootstrap-package.com/pages/feature/
https://www.bootstrap-package.com/pages/startpage/
