### ISSUE TITLE
Error page after installing and configuring bootstrap_package

### ISSUE THREAD

**Issue by hogiro** [benjaminkott/bootstrap_package#453]
Hello,

after installing and configuring the bootstrap_package I get an SQL error.

Oops, an error occurred!
An exception occurred while executing 'SELECT * FROM `tt_content` WHERE (`tt_content`.`pid` IN (1)) AND **(=3)** AND ((`tt_content`.`sys_language_uid` IN (0, -1)) OR ((`l18n_parent` = 0) AND (`tt_content`.`sys_language_uid` = 0))) AND ((`tt_content`.`deleted` = 0) AND (`tt_content`.`t3ver_state` <= 0) AND (`tt_content`.`pid` <> -1) AND (`tt_content`.`hidden` = 0) AND (`tt_content`.`starttime` <= 1498295220) AND ((`tt_content`.`endtime` = 0) OR (`tt_content`.`endtime` > 1498295220)) AND (((`tt_content`.`fe_group` = '') OR (`tt_content`.`fe_group` IS NULL) OR (`tt_content`.`fe_group` = '0') OR (FIND_IN_SET('0', `tt_content`.`fe_group`)) OR (FIND_IN_SET('-1', `tt_content`.`fe_group`))))) ORDER BY `sorting` ASC': You have an error in your SQL syntax; check the manual that corresponds to your MariaDB **server version for the right syntax to use near '=3) AND ((`tt_content`.`sys_language_uid` IN (0, -1)) OR ((`l18n_parent` = 0) AN' at line 1**

The Typo3 Version: 8.7.1
Bootstrap_Package Version: 8.0.3
Fresh Installation, I tested it on local server (XAMPP) and on a Hosting Server too. I get always the same error.

I would appreciate, if you could help me to get rid of this error.

Best Regards,

**Comment by benjaminkott** [comment]
Please install TYPO3 8.7.2 that should resolve the problem.

Gesendet von meinem Windows 10 Phone

Von: Devrim Gülacar<mailto:notifications@github.com>
Gesendet: Samstag, 24. Juni 2017 11:16
An: benjaminkott/bootstrap_package<mailto:bootstrap_package@noreply.github.com>
Cc: Subscribed<mailto:subscribed@noreply.github.com>
Betreff: [benjaminkott/bootstrap_package] Error page after installing and configuring bootstrap_package (#453)


Hello,

after installing and configuring the bootstrap_package I get an SQL error.

Oops, an error occurred!
An exception occurred while executing 'SELECT * FROM tt_content WHERE (tt_content.pid IN (1)) AND (=3) AND ((tt_content.sys_language_uid IN (0, -1)) OR ((l18n_parent = 0) AND (tt_content.sys_language_uid = 0))) AND ((tt_content.deleted = 0) AND (tt_content.t3ver_state <= 0) AND (tt_content.pid <> -1) AND (tt_content.hidden = 0) AND (tt_content.starttime <= 1498295220) AND ((tt_content.endtime = 0) OR (tt_content.endtime > 1498295220)) AND (((tt_content.fe_group = '') OR (tt_content.fe_group IS NULL) OR (tt_content.fe_group = '0') OR (FIND_IN_SET('0', tt_content.fe_group)) OR (FIND_IN_SET('-1', tt_content.fe_group))))) ORDER BY sorting ASC': You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '=3) AND ((tt_content.sys_language_uid IN (0, -1)) OR ((l18n_parent = 0) AN' at line 1

The Typo3 Version: 8.7.1
Bootstrap_Package Version: 8.0.3
Fresh Installation, I tested it on local server (XAMPP) and on a Hosting Server too. I get always the same error.

I would appreciate, if you could help me to get rid of this error.

Best Regards,
