### ISSUE TITLE
Error page after update from 7.1.0 to 8.0.0 [TYPO3 CMS 7.6.18]

### ISSUE THREAD

**Issue by TT-SWP13** [benjaminkott/bootstrap_package#456]
Hello,

### Description
I updated from 7.1.0 to 8.0.0 in my TYPO3 CMS 7.6.18 version with TER.
I missed to read the **important notes** (at https://github.com/benjaminkott/bootstrap_package/releases/tag/8.0.0), so i forgott to run the Upgrade Wizard.

### Issue
Now i got an **error page at backend and frontend**. I can visit the install page, but all actions goes to an error.

### My Steps
1. [update TER]
2. [clear all cache]
3. [update bootstrap_package at TER]

How can i solve this issue?
Thank your very much!

**Comment by cedricziel** [comment]
Could you provide the error message please?

**Comment by TT-SWP13** [comment]
error message: 
"Given select field item list was not found." 

Exception/CMS/1303237468

**Comment by cedricziel** [comment]
bootstrap_package v8 is not compatible with TYPO3 CMS v7. It seems you skipped the version check. If you really want to upgrade to TYPO3 CMS v8, you should roll back the extension, then upgrade the cms, complete all the upgrade wizards, then update bootstrap_package, once you're on v8.

**Comment by TT-SWP13** [comment]
Thank you very much. I have not seen any version check, or I have overlooked him. Now i replaced the extension folder (bootstrap_package) with fresh folder from version 7.1.0. 
It seems to working, but in TER i get this error now:

Oops, an error occurred!
The package "introduction" depends on "rte_ckeditor" which is not present in the system.

Now i following the instructions on https://wiki.typo3.org/Exception/CMS/1382276561 to solve it.

Thank you!

**Comment by cedricziel** [comment]
You need to replace ext:introduction with the old version as well, as it's a dependency of ext:bootstrap_package and got upgraded as well

**Comment by TT-SWP13** [comment]
Ok, i have replace the introduction folder with fresh folder from version 2.3.0 and clear all caches. But the error are still there. I cant find any folder like "rte_ckeditor". Its only for Typo3 versions v8, right?

**Comment by TT-SWP13** [comment]
Ok now it works. I have replace both folder again. Thank you very much for your fast help, you save my day!

**Comment by cedricziel** [comment]
Glad you made it :)
