### ISSUE TITLE
Hamburger menu: hover effect of second bar

### ISSUE THREAD

**Issue by SventB** [benjaminkott/bootstrap_package#459]
### Description

If you click the hamburger menu on mobile and click it again, the second bar is still intended.

### Steps to Reproduce

1. Open frontend with Chrome in mobile view
2. Open menu
3. Close menu

### Suggested solution

Remove "margin-left: 2px" for ".navbar-toggle:hover .icon-bar:nth-child(3)". Because of the CSS transition, this bar gets style "margin-left: 2px" which is never animated back to "margin.left: 0".
There is also no need for a hover animation for the hamburger menu which is only shown on mobile devices: Mobile devices have no hover.

**Comment by benjaminkott** [comment]
@SventB thx for the report i think i have finally a solution for this.
Sicne mobile devices have hover support but hover support is not complete ive added 

```
@media (hover:none), (hover:on-demand) {
    margin-left: 0;
}
```

This will ensure that the hover effect is corrected if not a full implementation of the :hover exists in the current browser. Also ensures that it will work on full qualified implementations as expected.
