### ISSUE TITLE
jQuery equal height script

### ISSUE THREAD

**Issue by SventB** [benjaminkott/bootstrap_package#464]
You include the JavaScript file EXT:bootstrap_package/Resources/Public/JavaScript/Dist/jquery.equalheight.min.js
But it seems, the "equal height" feature isn't used anywhere, so you should remove this script.

If you like to use equal height, this seems to be a good alternative:
http://getbootstrap.com.vn/examples/equal-height-columns/

**Comment by benjaminkott** [comment]
we can remove this in master, but next release must be major then

**Comment by benjaminkott** [comment]
ive dropped it now -
but only in master so next version will be 9.0. thx for your reminder https://github.com/benjaminkott/bootstrap_package/commit/835b16b34697688e800c7d8ff817d9f039f43c63
