### ISSUE TITLE
Gallery / Images in columns

### ISSUE THREAD

**Issue by SventB** [benjaminkott/bootstrap_package#465]
This is a part out of your fluid template for content element type "Images" with "Number of Columns" > 1:

```
<f:case value="2">
  <f:variable name="imageColumnClass">col-md-6 col-xs-12</f:variable>
</f:case>
<f:case value="3">
  <f:variable name="imageColumnClass">col-md-4 col-sm-4 col-xs-4</f:variable>
</f:case>
```

1. Images in 2 columns are shown in one column on tablet and mobile, images in 3 columns are shown in 3 columns in all devices. Much better would be you show images in 2 columns in 2 columns also on tablet and images in 3 columns in 1 column on mobile.
2. Instead of "col-md-4 col-sm-4 col-xs-4" you can write "col-xs-4" which has the same result.

So, in my opinion, this would be better:
```
<f:case value="2">
  <f:variable name="imageColumnClass">col-sm-6 col-xs-12</f:variable>
</f:case>
<f:case value="3">
  <f:variable name="imageColumnClass">col-sm-4 col-xs-12</f:variable>
</f:case>
<f:case value="4">
  <f:variable name="imageColumnClass">col-md-3 col-sm-6 col-xs-12</f:variable>
</f:case>
<f:case value="6">
  <f:variable name="imageColumnClass">col-md-2 col-sm-3 col-xs-12</f:variable>
</f:case>
```

**Comment by l174rd** [comment]
I absolutely agree with that. I created a pull request for this => https://github.com/benjaminkott/bootstrap_package/pull/467

**Comment by benjaminkott** [comment]
@SventB @l174rd thx for your suggestions, while i am understanding your demand i think the current columns are fine except we can remove the obsolete css classes. But i guess we can resolve all issues if we make it configurable without the need to overwrite the template. So i have added new constants, that will you easily allow to override the columns to your wishes.

I hope this solves the issue better than making new static options again, hopefully you can agree with me on that point so please check the changes if it suits your needs.

https://github.com/benjaminkott/bootstrap_package/commit/e5d9cade9925cec367bad184e90b5489280c32e5
