### ISSUE TITLE
Bug in MenuSectionPages

### ISSUE THREAD

**Issue by SventB** [benjaminkott/bootstrap_package#466]
The menu type "Section index of subpages from selected pages" shows content elements with disabled option "Show in Section Menus".

You have to add "where = sectionIndex = 1" in file MenuSectionPages.txt (similar to MenuSection.txt).

**Comment by benjaminkott** [comment]
@SventB as always thx for pointing me to this issue :)

**Comment by wtfred** [comment]
Maybe it will be good to make it `where = sectionIndex = 1 AND CType != "menu"` and in MenuSection as well ?
