### ISSUE TITLE
target- and title-Attributes in Menu Links

### ISSUE THREAD

**Issue by createdwithlove** [benjaminkott/bootstrap_package#468]
Validating the output of bootstrap package the validator warned me about empty `target=""` attributes ([W3C Validator](https://validator.w3.org/nu/?doc=http%3A%2F%2Fwww.bootstrap-package.com%2F)).

The links are generated with this snippet used in several templates:
https://github.com/benjaminkott/bootstrap_package/blob/835b16b34697688e800c7d8ff817d9f039f43c63/Resources/Private/Templates/ContentElements/MenuCategorizedPages.html#L10

A solution could be to just output it if `page.target`exists.

The same way (but not invalid) the `title` attribute could be improved (SEO and accessibility) by using `{page.data.abstract}` instead of `{page.title}`. 

A Solution would be: 
```
<a href="{page.link}" {f:if(condition: page.target, then:'target="{page.target}"')}  {f:if(condition: page.data.abstract, then:'title="{page.data.abstract}"')}>{page.title}</a>
```

**Comment by benjaminkott** [comment]
@createdwithlove thx for your hints, i´ve added the target checks for all pagelinks. We have just also added this for fluid styled content in https://review.typo3.org/#/c/54160/.

I am not a big fan of clustering the templates with conditions, i would prefer to have the data prepared upfront and just print the data in the template. Will think about how to make this better configurable.

Thx for your help.

**Comment by createdwithlove** [comment]
For internal links maybe the `f:link.typolink Viewhelper` could be used? (sorry I hadn't this in mind before my previous comment).
