### ISSUE TITLE
Unclosed Tag

### ISSUE THREAD

**Issue by createdwithlove** [benjaminkott/bootstrap_package#469]
Unclosed `<ul>` Tag:
https://github.com/benjaminkott/bootstrap_package/blob/09d97efd96d204c1dd956653e02c35b525c8b999/Resources/Private/Partials/Page/Navigation/Meta.html#L3

**Comment by benjaminkott** [comment]
@createdwithlove you are right, i am very sorry stuff like this should not happen!
