### ISSUE TITLE
Site-Update 7.6 ---> 8.7 (Contentelementsproblem, esp. Accordeon)

### ISSUE THREAD

**Issue by rosimittermeier** [benjaminkott/bootstrap_package#470]
(A) typo3: 7.6 upgrade einer Site auf 8.7
(B) Alles geht gut
(C) Die alte Site enthält Akkordeons mit Bildern/Media und Text.
(D) Extension Compatibility Typo3-V7 ist installiert.

(1) In der geupdateten Site wird die Akkordeoneinstellung in den ContentElements verloren und kann/muss im Content Element neu eingestellt werden. (Wie bei allen BootstrapPackageContentElementen müssen auch hier die Zuordnungen bei einem ContentElement erneuert werden. Bei anderen ContentElementen, bspw. Tab, erscheint nach der Neuzuordnung des CE zu Tab der gesamte alte Inhalt neu, der schon in der typo3-7.6-version vorlag. Beim AkkordeonElement allerdings nicht.)
(2) Aber die AkkordeonItems sind also verloren. Und erscheinen auch nicht mehr. Sie müssen also neu erzeugt werden.
(3) Ok, man fügt nun erneut die AkkordeonItems im AkkordeonContentElement hinzu.
(4) Bei jedem Mal gibt man alle Daten ein (Title, Alt-Text, Descr, ...).
(5) Dann speichert man.
(6) Nun, Fehlermeldung (notwendige Felder sind nicht ausgefüllt, Hinweis auf Rufzeichen).
(7) Das liegt darin, dass auf einmal noch ein AkkordeonItem (ein leeres vor dem soeben eingefügten und bearbeiteten) eingefügt wurde.
(8) Das muss man löschen. 
(9) Dann klappt das Speichern.

(X) Übrigens: Die Bildbeschreibung (description) wird nun bei mehreren Zeilen mitten im Wort zeilenumbegrochen.

**Comment by benjaminkott** [comment]
@rosimittermeier da sollten keine Einstellungen verloren gehen. Du hast bestimmt auch das Bootstrap Package geupdated. Hast du die Update Wizards im Install Tool laufen lassen?

**Comment by rosimittermeier** [comment]
danke. ich habe die typo3-umgebung nicht mehr. ich werde es demnächst noch mal versuchen. bootstrap_package habe ich in der tat geupdated. die update wizards im install toll habe ich auch laufen lassen. vielleicht war die reihenfolge falsch oder sonst was ging schief. mal sehen! thanx again 23.10.2017, 17:44, "Benjamin Kott" <notifications@github.com>:@rosimittermeier da sollten keine Einstellungen verloren gehen. Du hast bestimmt auch das Bootstrap Package geupdated. Hast du die Update Wizards im Install Tool laufen lassen?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
