### ISSUE TITLE
Responsive images: Trigger "loaded.bk2k.responsiveimage"

### ISSUE THREAD

**Issue by SventB** [benjaminkott/bootstrap_package#471]
You have this trigger for responsive images:

```javascript
$(window).trigger('loaded.bk2k.responsiveimage');
```

This trigger is executed every time an image was handled. It would be more useful, if you add the handled image as parameter:

```javascript
$(window).trigger('loaded.bk2k.responsiveimage', [this.$element]);
```

So it would be possible to add a class to loaded images (just one example of many):

```javascript
$(window).on('loaded.bk2k.responsiveimage', function(event, image) {
    image.addClass('lazyload-loaded');
});
```

**Comment by benjaminkott** [comment]
@SventB thx for the suggestion, added this to master.
