### ISSUE TITLE
database analyzer can not add fields

### ISSUE THREAD

**Issue by DanielRuf** [benjaminkott/bootstrap_package#473]
```
Database update failed
Error: Incorrect table definition; there can be only one auto column and it must be defined as a key
Database update failed
Error: Key column 'uid' doesn't exist in table
Database update failed
Error: Incorrect table definition; there can be only one auto column and it must be defined as a key
Database update failed
Error: Key column 'uid' doesn't exist in table
Database update failed
Error: Incorrect table definition; there can be only one auto column and it must be defined as a key
Database update failed
Error: Key column 'uid' doesn't exist in table
Executed database updates
Analyzed current database
```

```
Add fields to tables
 select/deselect all
 ALTER TABLE `tx_bootstrappackage_carousel_item` ADD `uid` INT AUTO_INCREMENT NOT NULL
 ALTER TABLE `tx_bootstrappackage_carousel_item` ADD PRIMARY KEY (uid)
 ALTER TABLE `tx_bootstrappackage_accordion_item` ADD `uid` INT AUTO_INCREMENT NOT NULL
 ALTER TABLE `tx_bootstrappackage_accordion_item` ADD PRIMARY KEY (uid)
 ALTER TABLE `tx_bootstrappackage_tab_item` ADD `uid` INT AUTO_INCREMENT NOT NULL
 ALTER TABLE `tx_bootstrappackage_tab_item` ADD PRIMARY KEY (uid)
```

**Comment by benjaminkott** [comment]
@DanielRuf what database you are using?

**Comment by DanielRuf** [comment]
MySQL (hosted on All-Inkl)

**Comment by DanielRuf** [comment]
> Software: MySQL
> Software-Version: 5.6.33-nmm1-log - (Ubuntu)

**Comment by benjaminkott** [comment]
@DanielRuf i´ve tried again to reproduce this issue but still without success.

Case 1:
- uninstall extension
- remove tables from database
- install extension
-> table and fields have been added correctly

Case 2:
- remove tables from database
- check database analyzer in the backend
- add all suggested changes and additions
-> table and fields have been added correctly

Case 3:
- remove tables from database
- add sql statement manually through phpmyadmin
- check database analyzer in the backend
- add all suggested changes and additions
-> table and fields have been added correctly

Case 4:
- remove tables from database
- added sql statement without uid keys
->  Incorrect table definition; there can be only one auto column and it must be defined as a key

Case 5:
- remove tables from database
- added sql statement without keys and uid modified to `uid int(11) DEFAULT '0' NOT NULL`
- check database analyzer in the backend
- add all suggested changes and additions
-> table and fields have been added correctly

**Comment by DanielRuf** [comment]
Did you check also strict and normal database mode? I've installed the introduction package with composer afaik.

I can also create a hosting account so you can test here.

**Comment by benjaminkott** [comment]
I am running mysql in strictmode currently by default.
```
@@sql_mode
STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
```

I you could create a account where i can test on would be super awesome, i hope its not related to the initial introduction database import. Then we would need to fix the export there. Ping me on slack for DM.

**Comment by benjaminkott** [comment]
After checking out the environment @DanielRuf provided, it was not possible anymore to reproduce this issue. We had a look at an instance that was affected by this issue, but that onecould now be resolved by reinstalling the bootstrap_package extension.

It seems that the instance suffered from an mysql strict problem with more early TYPO3 versions. The current version 8.7.8 works fine. New acceptance tests in the TYPO3 core will also ensure that the import of the introduction test data will succeed. https://review.typo3.org/#/c/54038/9

I see this issue as resolved, and will close it as that.
Thx @DanielRuf for helping out and reporting the issue.
