### ISSUE TITLE
Page type "popup" not working

### ISSUE THREAD

**Issue by SventB** [benjaminkott/bootstrap_package#476]
The page type “popup” doesn't work, the header is still shown because there is no variable “showHeader”.

In my optinion, it would be better to implement the popup solution with a new page template (Backend Layout), this is more flexible and very easy to implement. It has advantages because the popup template is very easy to modify and an editor can select it in the page properties.

If every page is displayable without header and footer with type=1000, this can have huge disadvantages, e.g. search engines prefer these pages to the regular pages and display them in search results.

**Comment by benjaminkott** [comment]
@SventB thx for the hint, think about this and how we can solve this better.

**Comment by benjaminkott** [comment]
@SventB i follow your suggestion, the current implementation is not useful at all and also broken (i seem to messed this up some time ago). I removed it since the usecases and needs can vary a lot and a custom implementation of someone needs this feature is fairly easy.
