### ISSUE TITLE
Wrong TS setup for accordion

### ISSUE THREAD

**Issue by SventB** [benjaminkott/bootstrap_package#477]
In file Configuration/TypoScript/Helper/ContentElement.txt you have this code:

```
accordion {
    media {
        height = {$plugin.bootstrap_package_contentelements.accordion.media.height}
        width = {$plugin.bootstrap_package_contentelements.accordion.media.width}
    }
}
```

But this setup isn't used anywhere and the constants you assign do not exist.

**Comment by benjaminkott** [comment]
@SventB you are right, this can be removed
