### ISSUE TITLE
Plans for Bootstrap 4 ?

### ISSUE THREAD

**Issue by anedisi** [benjaminkott/bootstrap_package#479]
I know its still in beta but im starting a new project with typo3 8.7 and would like to "future prof" it using bootstrap 4. ( i also have checked my analytics )

So is there i plan for b4 or only when they release the final version this package will be updated.

For right now even "alpha" version of this package would work for me. 
Im still debating to use this or roll my own with b4.

Thank you for your work this package is great, i used it another project and it saved me a ton of time.

**Comment by benjaminkott** [comment]
Update to Bootstrap is planned with next Major version and a stable relase of Bootstrap 4.
https://github.com/benjaminkott/bootstrap_package/issues/355
