### ISSUE TITLE
Language menu shows wrong translation

### ISSUE THREAD

**Issue by IchHabRecht** [benjaminkott/bootstrap_package#483]
### Prerequisites

* [x ] Can you reproduce the problem on TYPO3 8.7 LTS
* [ x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package) to see if your bug or enhancement is already reported?

### Description

The language menu on page with id=10 shows wrong language menu. In the backend the page is translated into Dansk but the frontend links to Deutsch.

### Steps to Reproduce

1. Install bootstrap_package
2. Open page "Any language, any character" (id=10) in default language
3. Scroll to the bottom of the site and see language menu

**Expected behavior:**

As a translation into Dansk is available, I would expect to be able to click this translation.

**Actual behavior:**

I'm able to click the German translation however there is no such translation in the backend,

### Versions

8.0.4

**Comment by benjaminkott** [comment]
Fixed in https://github.com/benjaminkott/bootstrap_package/commit/54dc3d2644852da9b9e43280674e9e4d4659b1f4
