### ISSUE TITLE
"Content Element type "menu_sitemap" has no rendering definition" after upgrading from 8.5.1 to 8.7.8 with bootstrap starter

### ISSUE THREAD

**Issue by trendzetter** [benjaminkott/bootstrap_package#485]
### Prerequisites

* [x] Can you reproduce the problem on TYPO3 8.7 LTS (I am running LTS but I don't have a copy of the old version)
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package) to see if your bug or enhancement is already reported? YES

### Description

After upgrading the typo3 core from 8.5.1 to 8.7.8 the bootstrap package doesn't render the menu_sitemap anymore instead showing an error: Content Element type "menu_sitemap" has no rendering definition

### Steps to Reproduce

1. Install typo3 8.0.1 with bootstrap package and introduction package. 
2. Create a site package.
3. Upgrade to 8.5.1
4. upgrade to 8.7.8

**Expected behavior:** Updating the bootstrap package with a maintance release resolves the issue

**Actual behavior:** The menu_sitemap and other menu elements do not render.

I am not sure if this is a bug or something that I can resolve myself by better studying the docs. I just couldn't find any solution after searching the internet, the backend, the files and the database. Any clues, anything else that I can provide?

**Comment by benjaminkott** [comment]
@trendzetter Between the mentioned versions of TYPO3 there has been a rework of the default content elements within TYPO3 itself. The Menus for example have been splitted into seperate content elements.

To get this fixed you need to do the following:

1. Do a Database Backup
2. Update the Bootstrap Package to 8.0.4
3. Go to the install tool and check and execute the upgrade wizards for menu, section frames etc.
4. Everything should be back to normal.

Let me know how ist going if you need assistance ping me on Slack.

**Comment by benjaminkott** [comment]
Problem was solved locally, issue can be closed.

**Comment by trendzetter** [comment]
The issue was resolved by the steps above and modifying
/Resources/Private/Layouts/ContentElements/Default.html
to:
`<div id="c{data.uid}" class="frame frame-{data.frame_class}">
    <f:if condition="{data._LOCALIZED_UID}"><a id="c{data._LOCALIZED_UID}"></a></f:if>
    <f:render section="Header" optional="true">
        <f:render partial="Header/All" arguments="{_all}" />
    </f:render>
    <f:render section="Main" />
</div>`
