### ISSUE TITLE
Portfolio References

### ISSUE THREAD

**Issue by Sonezi** [benjaminkott/bootstrap_package#486]
Hello,
this is more a question than an issue. I was wondering is there any solution with bootstrap_package to create portfolio with tab navigation per example ALL / websites / design ... etc All tab would represent all categories in tabs all together. I cant find any extension to install or to create in BE with b_p ext. Can you help me?

Kind Regards,

Nenad Antonijevic

**Comment by Sonezi** [comment]
I have found a solution, you can close topic.
Tnx for your time. :)

**Comment by cedricziel** [comment]
Your wish is my command :D
