### ISSUE TITLE
No option to *just* use own Fonts (like Web Font loader) because of PageSpeed

### ISSUE THREAD

**Issue by M4rt1n17** [benjaminkott/bootstrap_package#491]
### Prerequisites

* [X] Can you reproduce the problem on TYPO3 8.7 LTS
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package) to see if your bug or enhancement is already reported?

### Description

When I use bootstrap_package I always see Google PageSpeed Insights telling me to load Google Fonts async becasue its bad for mobil performance.
So a digged around a lot and found a solution which worked fopr me perfectly.
By using Web Font loader on other sites this probem is gone.

If I include Web Font loader via TS the Google Font which is included in the bootstrap_package is still loading. So I load the font twice.

Is there an option to make the bootstrap_package not loading any font?
Or even better implement Web Font loader which makes things much smoother.
( https://www.lockedowndesign.com/load-google-fonts-asynchronously-for-page-speed/ )
This would be awesome as additional option.

### Steps to Reproduce

1. install bootstrap_package
2. include Google Fonts (you have to, as there is no option to disable it)
3. make PageSpeed Insights check

### Versions

Typo3: 8.7.9 (also tested on 9.0.0)
Bootstrap Package: 9.1.0

**Comment by benjaminkott** [comment]
@M4rt1n17 ive added new option to the  boostrap package, the next release will contain an option to load webfonts async that is enabled by default. This also includes a loading overlay that can be turned off via constants or configured to the desired looks.

the webfonts can be disabled by unsetting the nessesary option in the setup for example 
```page.includeCSSLibs.googlewebfont >```

in addition the includeCSS command learned some new configurations, its now possible to load any css font file with these options.

```
page.includeCSS {
    myfont = <url to fontfile>
    myfont {
        fontLoader {
            families {
                0 = <name of font 1>
                1 = <name of font 2>
            }
            enabled = 1
        }
    }
}
```

**Comment by M4rt1n17** [comment]
Damn that sounds great!!!
Can I also include Web Font via konstants?
If I include Web Font is this removing the standard Google Fonts?

Cant wait for the Loading Overlay! 


I have some questions, I hope its ok to ask it here:

**1.)** How do I add templates to bootstrap Package and still be updateable?
Atm I just added my own templates to:

EXT:bootstrap_package/Resources/Private/Layouts/Page/
EXT:bootstrap_package/Resources/Private/Partials/Page/
EXT:bootstrap_package/Resources/Private/Templates/Page/
and
EXT:bootstrap_package/Configuration/PageTS/Mod/WebLayout/BackendLayouts/


It works so far. So I Backuped everything and reinstalled bootstrap_package and everything was gone. How to make this templates persist?

**2.)** when bootstrap_package will be updated to bootstrap v4 will everything be compatible with version which are atm on the version of bp which is based on Bootstrap v3?


Thanks in Advance man!
