### ISSUE TITLE
Subnavigation and Breadcrumb missing in mobile view

### ISSUE THREAD

**Issue by OskarWestmeijer** [benjaminkott/bootstrap_package#492]
Using TYPO3 8.7 LTS

First of all I like the Extension very much. I am using a subnavigation on the right side. Its the "default subnavigation right" backend layout. 

When I am in desktop view, everything looks fine. But when i switch to mobile, the sidenav and breadcrumbs dissapear. I would have expected the in the hamburger menu or on top or bottom...

Now i have some inaccesible pages in mobile view.

Is there anything I am missing?

**Comment by Gulliver123** [comment]
I am using the newest version of the package 9.1.

**Comment by DarthKeks** [comment]
Yeah there are deactiveted bye the default, when i right remember.

**Comment by gilbertsoft** [comment]
You should not use more than 2 levels from the root, this is not supported by the shipped templates and if needed you have to adapt the templates in your Sitepackage. There you also are able to change the behaviour of the subnavigation.

I'm going to close this issue now as we wont fix it currently.
