### ISSUE TITLE
Enable lightbox for news extension

### ISSUE THREAD

**Issue by paulmorphy** [benjaminkott/bootstrap_package#493]
I am trying to enable the lightbox feature for the news extension on my bootstrap_package installation but I can not figure out the correct parameters to use.

The news extension has got five typoscript parameters for it which are usually inherited from css_styled_content or fluid_styled_content which are not installed if the bootstrap package is used:
plugin.tx_news.settings.detail.media.image.lightbox {
           enabled = {$styles.content.imgtext.linkWrap.lightboxEnabled}
           class = {$styles.content.imgtext.linkWrap.lightboxCssClass}
           width = {$styles.content.imgtext.linkWrap.width}
           height = {$styles.content.imgtext.linkWrap.height}
           rel = lightbox[myImageSet]
}

It seems easy to manually set the parameters to replace the missing variables:
plugin.tx_news.settings.detail.media.image.lightbox {
  enabled = 1
  class = lightbox
  width = 800
  height = 600
}

If I do that the lightbox is enabled in the detailed view of a news article but if I click on the image it does not open. Instead I get a JavaScript error:
Error: Syntax error, unrecognized expression: a.lightbox[rel=lightbox[myImageSet]]

The rel parameter seems to be the problem but I have been unable to find out the correct expression for it. The lightbox implementation of bootstrap_package seems to be different from the one in the core extensions. Is there a way to make this work?

I am using the following versions in a composer driven setup with Typo3 8.7.9
            "name": "bk2k/bootstrap-package",
            "version": "9.1.0",
            "name": "georgringer/news",
            "version": "6.1.1",

**Comment by ianbogda** [comment]
Hi @paulmorphy,

the workaround that I'm using is:

setup
```
#################
#### tx_news ####
#################
plugin.tx_news.settings.detail.media.image.lightbox {
    enabled = 1
    class = {$plugin.bootstrap_package_contentelements.lightbox.cssClass}
    prefix = {$plugin.bootstrap_package_contentelements.lightbox.prefix}
    width = 1024
    height = 768
}
```
And I'have created a specific **MediaImage.html** as follow:
```html
<html xmlns:f="http://typo3.org/ns/TYPO3/CMS/Fluid/ViewHelpers"
	  xmlns:n="http://typo3.org/ns/GeorgRinger/News/ViewHelpers"
	  data-namespace-typo3-fluid="true">

<div class="mediaelement mediaelement-image">
	<f:if condition="{mediaElement.link}">
		<f:then>
			<f:link.page pageUid="{mediaElement.link}" target="{n:targetLink(link:mediaElement.link)}">
				<f:image image="{mediaElement}" 
                                    title="{mediaElement.title}"
                                    alt="{mediaElement.alternative}"
                                    maxWidth="{f:if(condition: settings.media.maxWidth, then: settings.media.maxWidth, else: settings.detail.media.image.maxWidth)}"
                                    maxHeight="{f:if(condition: settings.media.maxHeight, then: settings.media.maxHeight, else: settings.detail.media.image.maxHeight)}" />
			</f:link.page>
		</f:then>
		<f:else>
			<f:if condition="{settings.detail.media.image.lightbox.enabled}">
				<f:then>
				<a href="{f:uri.image(image:mediaElement, width:'{settings.detail.media.image.lightbox.width}', height:'{settings.detail.media.image.lightbox.height}')}"
                                    title="{mediaElement.title}"
                                    class="{settings.detail.media.image.lightbox.class}" rel="{settings.detail.media.image.lightbox.prefix}-{mediaElement.uid}"
                                    data-lightbox-height="{settings.detail.media.image.lightbox.height}"
                                    data-lightbox-width="{settings.detail.media.image.lightbox.width}"
                                    data-lightbox-caption="{mediaElement.description}" >
					<f:image image="{mediaElement}"
                                            title="{mediaElement.title}"
                                            alt="{mediaElement.alternative}"
                                            maxWidth="{f:if(condition: settings.media.maxWidth, then: settings.media.maxWidth, else: settings.detail.media.image.maxWidth)}"
                                            maxHeight="{f:if(condition: settings.media.maxHeight, then: settings.media.maxHeight, else: settings.detail.media.image.maxHeight)}" />
					</a>
				</f:then>
				<f:else>
				<f:image image="{mediaElement}"
				    title="{mediaElement.title}"
				    alt="{mediaElement.alternative}"
				    maxWidth="{f:if(condition: settings.media.maxWidth, then: settings.media.maxWidth, else: settings.detail.media.image.maxWidth)}"
				    maxHeight="{f:if(condition: settings.media.maxHeight, then: settings.media.maxHeight, else: settings.detail.media.image.maxHeight)}"/>
				</f:else>
			</f:if>
		</f:else>
	</f:if>
</div>
<f:if condition="{mediaElement.description}">
	<p class="news-img-caption">
		{mediaElement.description}
	</p>
</f:if>
</html>
```

**Comment by paulmorphy** [comment]
Thank you so much @ianbogda for sharing this code!
With your modified MediaImage.html the lightbox works like a treat!

It just took me a minute to find the file. In case anybody else is wandering where to edit, it is in the tx_news extension under typo3conf/ext/news/Resources/Private/Partials/Detail/MediaImage.html

Thanks allot again.

**Comment by miniton** [comment]
Thank you from my side too!

Small addition: to make lightbox groups work, I have changed
`rel="{settings.detail.media.image.lightbox.prefix}-{mediaElement.uid}"`
to
`rel="{settings.detail.media.image.lightbox.prefix}"`

Cheers
Christian

**Comment by Plotz** [comment]
This solution works but forces lightboxed images to be shown up in 4:3 aspect ratio.
All images of other aspect ratio than 4:3 will be deformed.

Any advice?

**Comment by Harmsi** [comment]
The Problem is that part:

lightbox {
	enabled = 1
	class ={$plugin.bootstrap_package_contentelements.lightbox.cssClass}
	prefix = {$plugin.bootstrap_package_contentelements.lightbox.prefix}
	**width = 1024
	height = 768**
}
We need to get the original size of the pictures! 
Just the question where to get that from!?

**Comment by benjaminkott** [comment]
@Harmsi check the implementation for normal images.

https://github.com/benjaminkott/bootstrap_package/blob/master/Resources/Private/Partials/ContentElements/Media/Type/Image.html#L12


It takes the size from the image generation after an image was generated see `{bk2k:lastImageInfo(property: 'width')}` and `{bk2k:lastImageInfo(property: 'height')}`
```
<a 
    href="{f:uri.image(image: file, maxHeight: settings.lightbox.image.maxHeight, maxWidth: settings.lightbox.image.maxWidth)}" 
    title="{file.properties.title}" 
    data-lightbox-caption="{file.properties.description}" 
    class="{settings.lightbox.cssClass}" 
    data-lightbox-width="{bk2k:lastImageInfo(property: 'width')}" 
    data-lightbox-height="{bk2k:lastImageInfo(property: 'height')}" 
    rel="{settings.lightbox.prefix}-{data.uid}">
```

**Comment by Harmsi** [comment]
Hi Benjamin,

I found the Problem, but don’t know what to do.
I marked it red in the Picture. If Change the width and heigth i get the Right pictur size.
Seems to be a Problem in class pswp__img

Thanks for help

Harmsi

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

________________________________
Von: Benjamin Kott <notifications@github.com>
Gesendet: Tuesday, July 23, 2019 9:16:27 PM
An: benjaminkott/bootstrap_package <bootstrap_package@noreply.github.com>
Cc: Harmsi <christianharms@hotmail.de>; Mention <mention@noreply.github.com>
Betreff: Re: [benjaminkott/bootstrap_package] Enable lightbox for news extension (#493)


@Harmsi<https://github.com/Harmsi> check the implementation for normal images.

https://github.com/benjaminkott/bootstrap_package/blob/master/Resources/Private/Partials/ContentElements/Media/Type/Image.html#L12

It takes the size from the image generation after an image was generated see {bk2k:lastImageInfo(property: 'width')} and {bk2k:lastImageInfo(property: 'height')}

<a
    href="{f:uri.image(image: file, maxHeight: settings.lightbox.image.maxHeight, maxWidth: settings.lightbox.image.maxWidth)}"
    title="{file.properties.title}"
    data-lightbox-caption="{file.properties.description}"
    class="{settings.lightbox.cssClass}"
    data-lightbox-width="{bk2k:lastImageInfo(property: 'width')}"
    data-lightbox-height="{bk2k:lastImageInfo(property: 'height')}"
    rel="{settings.lightbox.prefix}-{data.uid}">

**Comment by Plotz** [comment]
**@Benjamin**

Your solution works like a charm!
Danke sehr!

**Comment by Harmsi** [comment]
Perfect! 
Thanks

**Comment by danaron** [comment]
Thank you guys. Works like a charme. To make it easier to copy/paste here is the summary of our treat:

Put hits in TYPOSCRIPT Setup:

```
#### tx_news lightbox mit boothstrap
plugin.tx_news.settings.detail.media.image.lightbox {
    enabled = 1
    class = {$plugin.bootstrap_package_contentelements.lightbox.cssClass}
    width = {$plugin.bootstrap_package_contentelements.lightbox.image.maxWidth}
    height = {$plugin.bootstrap_package_contentelements.lightbox.image.maxHeight}
    rel = {$plugin.bootstrap_package_contentelements.lightbox.prefix}
}
```

Change the file in typo3conf/ext/news/Resources/Private/Partials/Detail/MediaImage.html as followed:

```
<html xmlns:f="http://typo3.org/ns/TYPO3/CMS/Fluid/ViewHelpers"
	  xmlns:n="http://typo3.org/ns/GeorgRinger/News/ViewHelpers"
	  data-namespace-typo3-fluid="true">
<div class="mediaelement mediaelement-image">
  <f:if condition="{mediaElement.link}">
    <f:then>
      <f:link.typolink parameter="{mediaElement.link}" target="{n:targetLink(link:mediaElement.link)}">
        <f:image image="{mediaElement}" title="{mediaElement.title}" alt="{mediaElement.alternative}" maxWidth="{f:if(condition: settings.media.maxWidth, then: settings.media.maxWidth, else: settings.detail.media.image.maxWidth)}" maxHeight="{f:if(condition: settings.media.maxHeight, then: settings.media.maxHeight, else: settings.detail.media.image.maxHeight)}" additionalAttributes="{itemprop:'image'}" />
      </f:link.typolink>
    </f:then>
    <f:else>
      <f:if condition="{settings.detail.media.image.lightbox.enabled}">
        <f:then> <a href="{f:uri.image(image:mediaElement, maxWidth:'{settings.detail.media.image.lightbox.width}', maxHeight:'{settings.detail.media.image.lightbox.height}')}" title="{mediaElement.title}" class="{settings.detail.media.image.lightbox.class}" data-lightbox-caption="{mediaElement.description}" class="{settings.detail.media.image.lightbox.class}" data-lightbox-width="{bk2k:lastImageInfo(property: 'width')}" data-lightbox-height="{bk2k:lastImageInfo(property: 'height')}" rel="{settings.detail.media.image.lightbox.rel}">
          <f:image image="{mediaElement}" title="{mediaElement.title}" alt="{mediaElement.alternative}" maxWidth="{f:if(condition: settings.media.maxWidth, then: settings.media.maxWidth, else: settings.detail.media.image.maxWidth)}" maxHeight="{f:if(condition: settings.media.maxHeight, then: settings.media.maxHeight, else: settings.detail.media.image.maxHeight)}" />
          </a> </f:then>
        <f:else>
          <f:image image="{mediaElement}" title="{mediaElement.title}" alt="{mediaElement.alternative}" maxWidth="{f:if(condition: settings.media.maxWidth, then: settings.media.maxWidth, else: settings.detail.media.image.maxWidth)}" maxHeight="{f:if(condition: settings.media.maxHeight, then: settings.media.maxHeight, else: settings.detail.media.image.maxHeight)}" additionalAttributes="{itemprop:'image'}" />
        </f:else>
      </f:if>
    </f:else>
  </f:if>
</div>
<f:if condition="{mediaElement.description}">
  <p class="news-img-caption"> {mediaElement.description} </p>
</f:if>
</html>
```
That is it! Big hug ans thanks @benjamin!

**Comment by herzogkienast** [comment]
Thank you guys, helped me a lot and works fine.

**Comment by danaron** [comment]
With TYPO3 10.4.20 and news 8.6.0 this solutions does not work any more.
Does someone have an idea why?
Help much aprecitated.
Cheers Danaron

**Comment by quadronet** [comment]
that would also interest me very much, apparently some of the bootstrap_package has been changed.

**Comment by mbaer558** [comment]
The view helper in Image.html in benjaminkott/bootstrap_package/blob/master/Resources/Private/Partials/ContentElements/Media/Type/Image.html changed. 
In Versions before 12.x.x images where called like
  data-lightbox-width="{bk2k:lastImageInfo(property: 'width')}" 
  data-lightbox-height="{bk2k:lastImageInfo(property: 'height')}"

In Versions 12.0.1 and above images are called like
                 <bk2k:link.lightbox
                        image="{file}"
                        maxHeight="{settings.lightbox.image.maxHeight}"
                        maxWidth="{settings.lightbox.image.maxWidth}"
                        class="{settings.lightbox.cssClass}"
                        rel="{settings.lightbox.prefix}-{data.uid}"
                        title="{file.properties.title}"
                        caption="{file.properties.description}"
                    >

I am using TYPO3 10.4.21 and news 8.6.0. Change the relevant part in .../news/Resources/Private/Partials/Detail/MediaImage.html as followed and the relevant part is in between the 
<a href="{f:uri.image....  >
<bk2k:link.lightbox ...... >
</a>

`
<html xmlns:f="http://typo3.org/ns/TYPO3/CMS/Fluid/ViewHelpers"
	  xmlns:n="http://typo3.org/ns/GeorgRinger/News/ViewHelpers"
	  data-namespace-typo3-fluid="true">
<div class="mediaelement mediaelement-image">
  <f:if condition="{mediaElement.link}">
    <f:then>
      <f:link.typolink parameter="{mediaElement.link}" target="{n:targetLink(link:mediaElement.link)}">
        <f:image image="{mediaElement}" title="{mediaElement.title}" alt="{mediaElement.alternative}" maxWidth="{f:if(condition: settings.media.maxWidth, then: settings.media.maxWidth, else: settings.detail.media.image.maxWidth)}" maxHeight="{f:if(condition: settings.media.maxHeight, then: settings.media.maxHeight, else: settings.detail.media.image.maxHeight)}" additionalAttributes="{itemprop:'image'}" />
      </f:link.typolink>
    </f:then>
    <f:else>
      <f:if condition="{settings.detail.media.image.lightbox.enabled}">
        <f:then> 


          <a href="{f:uri.image(image:mediaElement, maxWidth:'{settings.detail.media.image.lightbox.width}', maxHeight:'{settings.detail.media.image.lightbox.height}')}" title="{mediaElement.title}" 
           
          <bk2k:link.lightbox

          data-lightbox-caption="{mediaElement.description}" 
          class="{settings.detail.media.image.lightbox.class}" 
          rel="{settings.detail.media.image.lightbox.rel}"

          data-lightbox-width="{settings.lightbox.image.maxWidth)}" 
          data-lightbox-height="{bk2k:settings.lightbox.image.maxHeight)}">

            <f:image image="{mediaElement}" title="{mediaElement.title}" alt="{mediaElement.alternative}" maxWidth="{f:if(condition: settings.media.maxWidth, then: settings.media.maxWidth, else: settings.detail.media.image.maxWidth)}" maxHeight="{f:if(condition: settings.media.maxHeight, then: settings.media.maxHeight, else: settings.detail.media.image.maxHeight)}" additionalAttributes="{itemprop:'image'}" />
            >

          </a> 

        </f:then>
        <f:else>
          <f:image image="{mediaElement}" title="{mediaElement.title}" alt="{mediaElement.alternative}" maxWidth="{f:if(condition: settings.media.maxWidth, then: settings.media.maxWidth, else: settings.detail.media.image.maxWidth)}" maxHeight="{f:if(condition: settings.media.maxHeight, then: settings.media.maxHeight, else: settings.detail.media.image.maxHeight)}" additionalAttributes="{itemprop:'image'}" />
        </f:else>
      </f:if>
    </f:else>
  </f:if>
</div>
<f:if condition="{mediaElement.description}">
  <p class="news-img-caption"> {mediaElement.description} </p>
</f:if>
</html>
`

TYPOSCRIPT (as it was before...):
#### tx_news lightbox with boothstrap
plugin.tx_news.settings.detail.media.image.lightbox {
    enabled = 1
    class = {$plugin.bootstrap_package_contentelements.lightbox.cssClass}
    width = {$plugin.bootstrap_package_contentelements.lightbox.image.maxWidth}
    height = {$plugin.bootstrap_package_contentelements.lightbox.image.maxHeight}
    rel = {$plugin.bootstrap_package_contentelements.lightbox.prefix}
}

Hope this helps.
Cheers Michael

**Comment by mbaer558** [comment]
Sorry I have a error in the code and have to find out where it is. It does not work right now!

Michael

**Comment by MikeToelle** [comment]
@danaron @quadronet : The Viewhelper in bootstrap_package has changed.

Use:
                        

```
data-lightbox-width="{bk2k:data.imageInfo(src: src,property: 'width')}"
data-lightbox-height="{bk2k:data.imageInfo(src: src,property: 'height')}"
```

for src use a variable like: 

`<f:variable name="src"><f:uri.image image="{mediaElement}" /></f:variable>`

**Comment by mbaer558** [comment]
Change the file in typo3conf/ext/news/Resources/Private/Partials/Detail/MediaImage.html (or better your own partial) as follows and the lightbox will work again.

 `<html xmlns:f="http://typo3.org/ns/TYPO3/CMS/Fluid/ViewHelpers"
	  xmlns:n="http://typo3.org/ns/GeorgRinger/News/ViewHelpers"
	  data-namespace-typo3-fluid="true">

<div class="mediaelement mediaelement-image">
	<f:if condition="{mediaElement.link}">
		<f:then>
			<f:link.typolink parameter="{mediaElement.link}" target="{n:targetLink(link:mediaElement.link)}">
				<f:image image="{mediaElement}" title="{mediaElement.title}" alt="{mediaElement.alternative}" loading="{settings.detail.media.image.lazyLoading}" maxWidth="{f:if(condition: settings.media.maxWidth, then: settings.media.maxWidth, else: settings.detail.media.image.maxWidth)}" maxHeight="{f:if(condition: settings.media.maxHeight, then: settings.media.maxHeight, else: settings.detail.media.image.maxHeight)}" additionalAttributes="{itemprop:'image'}" />
			</f:link.typolink>
		</f:then>
		<f:else>
			<f:if condition="{settings.detail.media.image.lightbox.enabled}">
				<f:then>
					<f:variable name="src"><f:uri.image image="{mediaElement}" /></f:variable>
					<a href="{f:uri.image(image:mediaElement, width:'{settings.detail.media.image.lightbox.width}', height:'{settings.detail.media.image.lightbox.height}')}" title="{mediaElement.title}"  
                    
                    data-lightbox-caption="{mediaElement.description}" 
                    class="{settings.detail.media.image.lightbox.class}" 
                    data-lightbox-width="{bk2k:data.imageInfo(src: src,property: 'width')}"
		    data-lightbox-height="{bk2k:data.imageInfo(src: src,property: 'height')}"
                    rel="{settings.detail.media.image.lightbox.rel}" >
                     
                        <f:image image="{mediaElement}" title="{mediaElement.title}" alt="{mediaElement.alternative}" loading="{settings.detail.media.image.lazyLoading}" maxWidth="{f:if(condition: settings.media.maxWidth, then: settings.media.maxWidth, else: settings.detail.media.image.maxWidth)}" maxHeight="{f:if(condition: settings.media.maxHeight, then: settings.media.maxHeight, else: settings.detail.media.image.maxHeight)}" additionalAttributes="{itemprop:'image'}" />
                    </a>
                  		</f:then>
				<f:else>
					<f:image image="{mediaElement}" title="{mediaElement.title}" alt="{mediaElement.alternative}" loading="{settings.detail.media.image.lazyLoading}" maxWidth="{f:if(condition: settings.media.maxWidth, then: settings.media.maxWidth, else: settings.detail.media.image.maxWidth)}" maxHeight="{f:if(condition: settings.media.maxHeight, then: settings.media.maxHeight, else: settings.detail.media.image.maxHeight)}" additionalAttributes="{itemprop:'image'}" />
				</f:else>
			</f:if>
		</f:else>
	</f:if>
</div>
<f:if condition="{mediaElement.description}">
	<p class="news-img-caption">
		{mediaElement.description}
	</p>
</f:if>
</html>`

Your News Typoscript Setup (as it was before):
plugin.tx_news.settings.detail.media.image.lightbox {
  enabled = 1
  class = {$plugin.bootstrap_package_contentelements.lightbox.cssClass}
  width = {$plugin.bootstrap_package_contentelements.lightbox.image.maxWidth}
  height = {$plugin.bootstrap_package_contentelements.lightbox.image.maxHeight}
  rel = {$plugin.bootstrap_package_contentelements.lightbox.prefix}
}

**Comment by mbaer558** [comment]
`<f:else>
			<f:if condition="{settings.detail.media.image.lightbox.enabled}">
				<f:then>
					<f:variable name="src"><f:uri.image image="{mediaElement}" /></f:variable>
					<a href="{f:uri.image(image:mediaElement, width:'{settings.detail.media.image.lightbox.width}', height:'{settings.detail.media.image.lightbox.height}')}" title="{mediaElement.title}"  
                    
                    data-lightbox-caption="{mediaElement.description}" 
                    class="{settings.detail.media.image.lightbox.class}" 
                    data-lightbox-width="{bk2k:data.imageInfo(src: src,property: 'width')}"
		    data-lightbox-height="{bk2k:data.imageInfo(src: src,property: 'height')}"
                    rel="{settings.detail.media.image.lightbox.rel}" >
                     
                        <f:image image="{mediaElement}" title="{mediaElement.title}" alt="{mediaElement.alternative}" loading="{settings.detail.media.image.lazyLoading}" maxWidth="{f:if(condition: settings.media.maxWidth, then: settings.media.maxWidth, else: settings.detail.media.image.maxWidth)}" maxHeight="{f:if(condition: settings.media.maxHeight, then: settings.media.maxHeight, else: settings.detail.media.image.maxHeight)}" additionalAttributes="{itemprop:'image'}" />
                    </a>
                  		</f:then>
				<f:else>`

My first post doesn't shows the code completely. In this post you will find the relevant part around <f:if condition="{settings.detail.media.image.lightbox.enabled}">

Hope this helps, Michael

**Comment by danaron** [comment]
Hi Michael,
Thank you very much! This works for me with TYPO3 10.4.26, bootstrap 12.0.4 and news 9.2.0.
Can I buy you a coffee?
There the whole typo3conf/ext/news/Resources/Private/Partials/Detail/MediaImage.html  file to copy:

```
<html xmlns:f="http://typo3.org/ns/TYPO3/CMS/Fluid/ViewHelpers"
	  xmlns:n="http://typo3.org/ns/GeorgRinger/News/ViewHelpers"
	  data-namespace-typo3-fluid="true">
<div class="mediaelement mediaelement-image">
  <f:if condition="{mediaElement.link}">
    <f:then>
      <f:link.typolink parameter="{mediaElement.link}" target="{n:targetLink(link:mediaElement.link)}">
        <f:image image="{mediaElement}" title="{mediaElement.title}" alt="{mediaElement.alternative}" loading="{settings.detail.media.image.lazyLoading}" maxWidth="{f:if(condition: settings.media.maxWidth, then: settings.media.maxWidth, else: settings.detail.media.image.maxWidth)}" maxHeight="{f:if(condition: settings.media.maxHeight, then: settings.media.maxHeight, else: settings.detail.media.image.maxHeight)}" additionalAttributes="{itemprop:'image'}" />
      </f:link.typolink>
    </f:then>
    <f:else>
      <f:if condition="{settings.detail.media.image.lightbox.enabled}">
        <f:then>
          <f:variable name="src">
            <f:uri.image image="{mediaElement}" />
          </f:variable>
          <a href="{f:uri.image(image:mediaElement, width:'{settings.detail.media.image.lightbox.width}', height:'{settings.detail.media.image.lightbox.height}')}" title="{mediaElement.title}"data-lightbox-caption="{mediaElement.description}" 
                class="{settings.detail.media.image.lightbox.class}" 
                data-lightbox-width="{bk2k:data.imageInfo(src: src,property: 'width')}"
	    data-lightbox-height="{bk2k:data.imageInfo(src: src,property: 'height')}"
                rel="{settings.detail.media.image.lightbox.rel}" >
          <f:image image="{mediaElement}" title="{mediaElement.title}" alt="{mediaElement.alternative}" loading="{settings.detail.media.image.lazyLoading}" maxWidth="{f:if(condition: settings.media.maxWidth, then: settings.media.maxWidth, else: settings.detail.media.image.maxWidth)}" maxHeight="{f:if(condition: settings.media.maxHeight, then: settings.media.maxHeight, else: settings.detail.media.image.maxHeight)}" additionalAttributes="{itemprop:'image'}" />
          </a> </f:then>
        <f:else>
          <f:image image="{mediaElement}" title="{mediaElement.title}" alt="{mediaElement.alternative}" loading="{settings.detail.media.image.lazyLoading}" maxWidth="{f:if(condition: settings.media.maxWidth, then: settings.media.maxWidth, else: settings.detail.media.image.maxWidth)}" maxHeight="{f:if(condition: settings.media.maxHeight, then: settings.media.maxHeight, else: settings.detail.media.image.maxHeight)}" additionalAttributes="{itemprop:'image'}" />
        </f:else>
      </f:if>
    </f:else>
  </f:if>
</div>
<f:if condition="{mediaElement.description}">
  <p class="news-img-caption"> {mediaElement.description} </p>
</f:if>
</html>
```
And the lines in the Setup of the root template:

```
#### tx_news lightbox mit boothstrap
plugin.tx_news.settings.detail.media.image.lightbox {
	enabled = 1
	class = {$plugin.bootstrap_package_contentelements.lightbox.cssClass}
	width = {$plugin.bootstrap_package_contentelements.lightbox.image.maxWidth}
	height = {$plugin.bootstrap_package_contentelements.lightbox.image.maxHeight}
	rel = {$plugin.bootstrap_package_contentelements.lightbox.prefix}
}
```
