### ISSUE TITLE
Set `config.linkVars` only if `{$page.theme.language.enable}` is set

### ISSUE THREAD

**Issue by sgrossberndt** [benjaminkott/bootstrap_package#494]
`{$page.theme.language.enable}` should define whether `config.linkVars` in https://github.com/benjaminkott/bootstrap_package/blob/65ee9ca8086148dbc0470dfe489c80122b646a08/Configuration/TypoScript/setup.typoscript#L493 and the language conditions in https://github.com/benjaminkott/bootstrap_package/blob/master/Configuration/TypoScript/setup.typoscript#L528 are available at all

**Comment by benjaminkott** [comment]
@sgrossberndt do you have a suggestion how to make this better? in code?

**Comment by benjaminkott** [comment]
Thanks for your report, i´ve created a new epic to collect all language related issues, or areas that could need improvement: https://github.com/benjaminkott/bootstrap_package/issues/510

Will close this issue for now, but will be referenced in the epic.
