### ISSUE TITLE
Reduce spacing (esp. padding) between elements

### ISSUE THREAD

**Issue by pascal-linux** [benjaminkott/bootstrap_package#495]
### Description

How can I change the padding between content elements?
The space is very large (already as default value). Would be great if
it was very small - so that it would make sense to use the "space before" or "space after"
for each content element.

Is there any typoscript variable to be used for that?

I found some information on the web
https://getbootstrap.com/docs/4.0/utilities/spacing/
but I do not see where such changes could be integrated without overwriting the extension..

### Versions

Typo3 8.7.9 with T3bootstrap 9.1.0

Thanks!
Pascal

**Comment by benjaminkott** [comment]
@pascal-linux thx for your feedback - i´ve put some work into this and result is currently available in master. The elements now collapse more a lot better and spacing was reduced.

also browseable via https://www.bootstrap-package.com/

**Comment by benjaminkott** [comment]
No feedback, please open the issue again if you think we still need to improve at this point.
