### ISSUE TITLE
Search currently broken on demo-site? Also requesting example of Searchbox usage?

### ISSUE THREAD

**Issue by Gong-Bao-Chicken** [benjaminkott/bootstrap_package#496]
### Prerequisites

* [X] Can you reproduce the problem on TYPO3 8.7 LTS
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package) to see if your bug or enhancement is already reported?

### Description

The example search on the demo website is not displayed / working. 

### Steps to Reproduce

1. Go to https://www.bootstrap-package.com/content-examples/form-elements/search/
2. Look at search

**Expected behavior:** [What you expected to happen]

See search and how it works.

**Actual behavior:** [What actually happened]

No search available.

<img width="1231" alt="screen shot 2018-01-24 at 22 54 31" src="https://user-images.githubusercontent.com/3042610/35359257-b41cd826-0159-11e8-9add-217dd29d233b.png">

I am also looking for a working example of a global searchbox, which calls the search site and performs the search with the same parameters. 

### Versions

Current

**Comment by benjaminkott** [comment]
@Gong-Bao-Chicken uups i´ve forgot to install the `indexed_search` extension on the demo environment, should now work as expected. thx for reminding me ;)

https://www.bootstrap-package.com/content-examples/form-elements/search/

I will revisit a global search box as the migration to bootstrap 4 continues. But here is a code example what to put into your template to have a global search working.


TypoScript Setup
```
page.10.settings.ids.search =<your searchpage>
```

Fluid
```
<form action="{f:uri.action(pageUid: settings.ids.search, action: 'search', controller: 'Search', extensionName: 'indexedsearch', pluginName: 'Pi2', noCacheHash: true)}" method="post">
    <input type="hidden" name="tx_indexedsearch_pi2[search][_sections]" value="0" />
    <input type="hidden" name="tx_indexedsearch_pi2[pointer]" value="0" />
    <input type="hidden" name="tx_indexedsearch_pi2[ext]" value="0" />
    <f:form.textfield class="form-control" name="tx_indexedsearch_pi2[search][sword]" placeholder="Searchwords" />
    <button type="submit" class="btn btn-primary">
        Search
    </button>
</form>
```

**Comment by Gong-Bao-Chicken** [comment]
Wow thanks for quick reply! Appreciate it a lot!
 I hope the bs4 migration is going smooth :-)

**Comment by benjaminkott** [comment]
@Gong-Bao-Chicken 
well, if you did not adjust the templates -> yes
if you did, ists almost completly breaking, bootstrap4 changed everyrhing from preprocessor language to markup, and all javascript. as you can immagine - i try to make it smoother but there will be work to do

**Comment by Gong-Bao-Chicken** [comment]
@benjaminkott 

Your doing great! Your distribution looks to me like the most up to date, most modern and best supported distribution out there! :-)

I am currently upgrading a distribution from V 7.6.9 which i build a year ago. But indexed_search and fe_login are broken and i am struggeling to get everything to work, so i decided to restructure and take inspriation from well supported and modern distributions. Kudos to you!

Sadly there aren't many 'contemporary' solutions out there :S lots of solutions are (many many) years old...
