### ISSUE TITLE
Show more depth in multi-level Submenu and some bugs

### ISSUE THREAD

**Issue by MartinHotmann** [benjaminkott/bootstrap_package#497]
### Prerequisites

* [x] Can you reproduce the problem on TYPO3 8.7 LTS
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package) to see if your bug or enhancement is already reported?

### Description

I would love to see more then 2 levels of submenu. Actually its 3 but the first just 2 levels of menu. Main Header menu and submenu. I would love to see 4 or 5 levels.

Also if you are hopvering a menu which have children it marks it with the primary color at 100% opacity, but every other menu object with a opacity with 50% (or somethiong like this)

**Expected behavior:** every menu point should be makred (at hover) with the same color if you are currently not at this page

Versions
Typo3: 8.7.9 (also tested on 9.1.0)
Bootstrap Package: 9.1.0

**Comment by DarthKeks** [comment]
Yeah a depper menu where really cool.

**Comment by The-BO** [comment]
Hi,

I got a submenu with 5 layers.

Just go to your Backend to your "**Template**", edit the "**Setup**" and add the following line:

`
page.10.dataProcessing.20.levels = 5
`

This will overwrite the original setup.typoscript from bootstrap_package.
Basically, you want to change the value of line 181.

**Comment by gilbertsoft** [comment]
This is something you can achieve with a Sitepackage by changing the templates there. We will not provide this feature for the moment and in the near future. I'm going to close this issue now.
