### ISSUE TITLE
REQUEST: TwentyTwenty (or any other IMG-Compare Slider)

### ISSUE THREAD

**Issue by M4rt1n17** [benjaminkott/bootstrap_package#498]
Hi, I would love to implement a compareslider to my site which with I can compare to different images with a slider.
I found some good JS jQuery soultions.
One of them (my favorit) is: https://zurb.com/playground/twentytwenty

Some other:
2.) https://github.com/koenoe/cocoen (Demo here --> https://koenromers.com/cocoen/demo.html)
3.) https://juxtapose.knightlab.com
4.) https://codepen.io/bamf/pen/jEpxOX

Is it possible to implement these one of these compare sliders as a carussel with minimal JS and CSS?

Would really love to see such a feature in this package

**Comment by benjaminkott** [comment]
@M4rt1n17 there is already a lot of stuff provided by this package and we need to be really carefully with adding new stuff. I personally think that the userbase for that feature is quite low and would opt for that reason not to add this feature. 

I recently adjusted the the overloading of the carousel items so it now a lot more easy to add new types in there. After registering it will just lookup for a template named  in uppercamelcase "TextAndImage" in your configured template paths.

Example Item Registration:
https://github.com/benjaminkott/bootstrap_package/blob/master/Configuration/TCA/tx_bootstrappackage_carousel_item.php#L215-L219

Example Item Configuration:
https://github.com/benjaminkott/bootstrap_package/blob/master/Configuration/TCA/tx_bootstrappackage_carousel_item.php#L102-L119

**Comment by M4rt1n17** [comment]
Ok so this gives me the option to implement it on my own, thank you!
