### ISSUE TITLE
Content rendered twice after updating from 7.1.0 to 8.0.0

### ISSUE THREAD

**Issue by Ben305** [benjaminkott/bootstrap_package#499]
### Prerequisites

* [x] Can you reproduce the problem on TYPO3 8.7 LTS
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package) to see if your bug or enhancement is already reported?

### Description

I'm currently updating an existing site from TYPO3 7.6 to 8.7. When the bootstrap_package is updated to 8.0 (or 8.0.6 or 9.1.0), the content on every page is rendered twice.

### Steps to Reproduce

1. Update existing instance from TYPO3 7.6 to 8.7
2. Do not update bootstrap_package, keep version 7.10
3. Other extensions (flux, vhs, etc.) can be updated

**Expected behavior:** Content should be rendered once

**Actual behavior:** Content is rendered twice.

### Versions

Versions from 8.7 installation:

fluidcontent: 5.2.0
fluidpages: 4.0.0
flux: 8.2.1
vhs: 4.3.3

**Comment by benjaminkott** [comment]
@Ben305 please check again with a compatible version with 8.7.

The Bootstrap Package version 7.1 is only compatible until 8.5.99, next compatible version is 8.0.
Also Bootstrap Package is marked incompatible with fluidpages, so i will not guarantee that its working.

**Comment by benjaminkott** [comment]
No feedback, please open the issue again if the problem still exists.
