### ISSUE TITLE
Contentelement from own extension wrapped with Containers

### ISSUE THREAD

**Issue by chequille** [benjaminkott/bootstrap_package#503]
Hi Benjamin,
currently testing Typo3 8.7.x and Boostrap_package 9.1.0 after upgrading 7.6.23 to 8.7.x

I use as well an own extension for some content elements. They are based on Fluid.
On the page, these elements are inserted as Type Fluid Content
SO far so good, but it seems, these elements are wrapped additionally with some containers which are not coming from my extension. And therefore, f.e. headers are rendered twice.

Following an example:
```
<div id="c280" class="frame** frame-default frame-type-fluidcontent_content frame-background- frame-no-backgroundimage frame-space-before-none frame-space-after-none">
<div class="frame-container"><div class="frame-inner">
<h3 class="">DER LADEN</h3>
<div id="c280" class="neues-text">
<h3 class="text-center">DER LADEN</h3>
<p class="text-center">Entdecken, stöbern, probieren und genießen . Ob im Anschluss an eine spannenden Führung, als kleine Pause für zwischendurch oder als direktes Ziel für besondere Geschenke: Der Laden im Hopfengut No20 ist immer einen Besuch wert.</p>
</div>
</div>
</div>
</div>
```

The part in the second div with id="c280" is coming from my extension, everythning else is coming from typo3 and/or your extension.

This was not the case under 7.6.23 and bootstrap_package 5.x.x

Any idea why this happens? It is a lot of work to change everything, because this is also breaking my css. As you see in the code there is two times a div with id="c280".

Maybe it is some configuration but I do not no.
Any help would be very helpful.

THanks and best reagrds,
Jürgen

**Comment by benjaminkott** [comment]
@chequille this seems to be not correct, maybe you have an issue in your overrides and they are not adapted yet - there were some stuff streamline work done for 8.7 also in fsc. Hard to tell whats actually going wrong without having a look into your adjustments. But it should be easy to fix.

Can you provide access to the code so i can have a deeper look at your customizations?
You can ping me on the TYPO3 slack anytime for that.

**Comment by chequille** [comment]
@benjaminkott  I had a deeper look into this issue and I think now, that everthing is correct.
Because, Layouts/ContentElements/default.html of bootstrap package changed heavily to the one of version 5.x.x.
And as well, an additional content element from an own extension is still rendered into the main content element. This is as well done with all others f.e. powermail plugin. Of course, I rendered as well a div element with the uid and therefore it appears twice.
To get my desired css classes I am working now with the Text Element from your package and defined layouts which I can look at in the default.html.
This is working pretty good.
Therefore, I guess this issue was just an misunderstanding from my site.
Best regards,
chequille

**Comment by benjaminkott** [comment]
@chequille glad you solved it and its working now. there was a required change to the layouts of content elements to ensure everything is behaving equally, that change has also be done to fsc in 8.7 and will hopefully the last change in that area in terms of structure for a long time.

This means the bootstrap_package and fsc is now more or less completely streamlined (except for some classes names). But the template structure is now treated equally, for all content elements and also for all plugins.

If you have any questions about this feel free to ask for more detailed explanation.
