### ISSUE TITLE
Problem after "Migrate Backend Layouta"

### ISSUE THREAD

**Issue by chequille** [benjaminkott/bootstrap_package#507]
Dear Benjamin,
infortunately, I did something today which I should better not do!!!!!

In Typo3 Installaltion Upgrade Wizard, there were three upgrade wizards, which I executed.
One of them was "Migrate Backend Layouts".

This is causing now a problem which I will try to explain.
I am using Typo3 8.7.10 and bootstrap 9.1.0

I do have a couple of pages, were I am using a TypoObject rendering some subpages which are displayed. Let's call it "onepage".
This is working fine so far, but after the change above, the rendering of the TypoObject is not using the given backend layouts from the pages (in this case form 74,73,75,76) anymore. It is always using the layout from the main page.

This is a part of my Page Layout:
```
<section id="p{data.uid}" class="{pageClass}">
	<f:render section="Main"/>
</section>

<f:if condition="{onePage}">
	<f:cObject typoscriptObjectPath="lib.content.onepage"/>
</f:if>
```

And this is the Typoscript for the lib.content.onepage:
```
lib.content.onepage = COA
lib.content.onepage {
	20 = HMENU
	20 {
		excludeDoktypes < lib.navigation.main.10.excludeDoktypes
		special = list
		special.value = 74,73,75,76
		1 = TMENU
		1 {
			expAll = 1
			noBlur = 1
			NO = 1
			NO {
				doNotLinkIt = 1
				doNotShowLink = 1
				stdWrap2 {
					cObject = COA
					cObject {
						10 = LOAD_REGISTER
						10 {
							curentPageId.cObject = TEXT
							curentPageId.cObject {
								field = uid
							}
							sectionID.cObject = TEXT
							sectionID.cObject {
								field = alias
								ifEmpty = p{field:uid}
								ifEmpty.insertData = 1
							}
							pageClass.cObject < lib.page.class
						}
						20 < page.10
						20 {
							variables {
								showHeader.value = 0
								showFooter.value = 0
							}
						}
						wrap = <section id="{register:sectionID}" class="{register:pageClass}">|</section>
						wrap = |
						wrap.insertData = 1
					}
				}
				wrapItemAndSub = |
			}
		}
		2 < .1
	}
	90 = RESTORE_REGISTER
}
```

Any idea why this is not working as before?

Would be fine if you have any idea.
Best regards,
Jürgen

**Comment by chequille** [comment]
Hi Benjamin,
made a test switching back to Version 9.0.1 and configured the templateName.stdWrap.cObject again as it was before and everything is working again as it should.

So the problem is as I think the new way handling the backend layouts. The rendering of my lib.content.onepage object is not getting the template names.

Any ideas?
BR
Jürgen

**Comment by benjaminkott** [comment]
@chequille Hey i´ve played around with this for some hours and its still far away from good and needs adjustments but here is what i have so far.

Introduced a template that uses the current main navigation and passes the data to a fluid object that renders a complete page.
```
<html xmlns:f="http://typo3.org/ns/TYPO3/CMS/Fluid/ViewHelpers" data-namespace-typo3-fluid="true">
<f:layout name="Default" />
<f:section name="Main">

    <f:for each="{mainnavigation}" as="item">
        <section id="p{item.data.uid}">
            <f:cObject typoscriptObjectPath="lib.renderPage" data="{pageUid: '{item.data.uid}'}" />
        </section>
    </f:for>

</f:section>
</html>
```

Reworked the content rendering on demand by uid, it can accept the `page.10` configuration but needs to be adjusted to use the old configuration syntax because the new one shorthand `pagelayout` does not seem to support a different rendering context except the current page.
```
lib.renderPage = COA
lib.renderPage {
    5 = LOAD_REGISTER
    5 {
        pageUid.cObject = TEXT
        pageUid.cObject {
            field = pageUid
            ifEmpty.data = TSFE:id
        }
    }
    10 = RECORDS
    10 {
        source.data = register:pageUid
        tables = pages
        dontCheckPid = 1
        conf.pages = COA
        conf.pages {
            10 =< page.10
            10.templateName.cObject.data = levelfield:-1, backend_layout_next_level, slide
            10.templateName.cObject.override.field = backend_layout
        }
    }
    90 = RESTORE_REGISTER
}
```

still todo:
- override main default template to exclude footer and header for sub pages
- adjust navigation rendering to use different links

**Comment by chequille** [comment]
Hi Benjamin,
first of all, thanks for your answer and infos.
But, I do not really know if this approach you are trying is exactly what I do need.

Maybe I explain a little bit more, what I am doing.
I do have a couple of pages which show the content of  itself and the subpages defined.
F.e.
Page 1
  Subpage 1
  Subpage 2
  Subpage 3

Page 1 is selectaböe in the Mainnavigation and when pressed, it is than showing on one page the Content from Page 1, Subpage 1, Subpage 2 and Subpage 3

I have to do this like this, because all of these 4 Pages could have a different template File.
This is working fine with the Typoscrypt for the lib.content.onepage and as long as I define the templateName in the old style.
This is also working with 9.1.0, I tested it as well.

The only difference is, that in the page rendered, all sections do have the same class defined. Rendering of teh pages is correct, because it uses the write template (as long as I define it with the old syle).
![grafik](https://user-images.githubusercontent.com/15807794/37315267-20bcb82e-2659-11e8-9959-8b079078965a.png)
This is how it looks now.
![grafik](https://user-images.githubusercontent.com/15807794/37315310-56a089c0-2659-11e8-9bdb-890f2a3da3b5.png)
This is how it looks before.

Must say, that I do not really care about this difference, as long as the pages are rendered correct.
If I do need to keep the old way of defining the templateNames I can live with it.

DO you have any other idea now because of my description?
BR
Jürgen

**Comment by benjaminkott** [comment]
I think we can drop the whole onepage discussion, using ext:container will allow the needed flexibility, and replacing the main menu with a section menu should to the rest.
