### ISSUE TITLE
Languages names are hardcoded into EXT:bootstrap_package/Resources/Private/Partials/Page/Navigation/Language.html

### ISSUE THREAD

**Issue by mbordoni** [benjaminkott/bootstrap_package#508]
Using Bootstrap_package extension for a custom multi language site.
Custom setup of template is needed to override the  Global config harcoded into "EXT:bootstrap_package/Configuration/TypoScript" lines 2708-2726 coherently with language configuration.
In addition to this the file "EXT:bootstrap_package/Resources/Private/Partials/Page/Navigation/Language.html"
has hardcoded languages name in it.

Could you fix Language.html at least to use either the custom template setup or the typo3 languages config for the website?

### Steps to Reproduce

1. Create a web site
2. Add some languages
3. enable the languages via constant: page.theme.language.languageValue = 0,4,2
4. Configure Template setup accordingly: 
#############################
[globalVar = GP:L = 4]
     config {
         sys_language_uid = 4
         language = it
         locale_all = it_IT.UTF-8
         htmlTag_setParams = lang="it" dir="ltr" class="no-js"
     }
[global]
[globalVar = GP:L = 2]
     config {
         sys_language_uid = 2
         language = de
         locale_all = de_DE.UTF-8
         htmlTag_setParams = lang="de" dir="ltr" class="no-js"
     }
[global]
5. Browse the site 

**Expected behavior:** [What you expected to happen]
The language menu shuold give: English, Italian, Deutsch

**Actual behavior:** [What actually happened]
The language menu gives: English, English, Deutsch
If I click on a link it works fine.

### Versions
Typo3: 8.7.11
Bootstrap_Package: 9.1.0

**Comment by benjaminkott** [comment]
Thanks for your report, i´ve created a new epic to collect all language related issues, or areas that could need improvement: https://github.com/benjaminkott/bootstrap_package/issues/510

Will close this issue for now, but will be referenced in the epic.
