### ISSUE TITLE
[HELP] RSS News TypoScript = empty page

### ISSUE THREAD

**Issue by zelcode** [benjaminkott/bootstrap_package#513]
### Prerequisites

* [x] Can you reproduce the problem on TYPO3 8.7 LTS
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package) to see if your bug or enhancement is already reported?

### Steps to Reproduce

Minimal test case, clean install TYPO3 8.7.12, introduction_3.0.1, bootstrap_package_9.1.0 and news_6.3.0, RSS TypoScript setup by News manual: https://docs.typo3.org/typo3cms/extensions/news/AdministratorManual/BestPractice/Rss/Index.html#rss-feed-by-typoscript, after calling http://rss.test/?type=9818 there is empty page only.

Same setup works on 7.6 LTS, but with fluidpages.

Also, found similar question in first comment here, no solution:
http://insight.helhum.io/post/104880845705/dont-use-eid-ajax-dispatchers-for-your-extbase

So, what is missing here?

**Comment by gilbertsoft** [comment]
@zelcode same config works here. do you have the static templates of news and bootstrap_package included to your template? can you see `tt_content.list.20.news_pi1` at the TSOB?

**Comment by gilbertsoft** [comment]
@zelcode don't know either. but everything looks fine so far and seems not to be a bootstrap_package related problem. you better ask in sourceforge (tag with TYPO3) or use the slack channel ext-news (probably the fastest way). go to https://forger.typo3.com/slack/ to register for slack.

**Comment by zelcode** [comment]
TODO
