### ISSUE TITLE
How to disable google webfonts?

### ISSUE THREAD

**Issue by Sarondamai** [benjaminkott/bootstrap_package#516]
I use local fonts. How do I remove Google's link in the header?
`<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source Sans Pro:300,400,700" media="all">`

**Comment by benjaminkott** [comment]
Google fonts are loaded for convenience you can find the implementation here.
https://github.com/benjaminkott/bootstrap_package/blob/master/Configuration/TypoScript/setup.typoscript#L403-L404

If you are using local fonts and do not want to use google fonts you can simply disable them via your setup.typoscript in your sitepackage or in the database.

`page.includeCSSLibs.googlewebfont  >`
