### ISSUE TITLE
Partials not working

### ISSUE THREAD

**Issue by daybugging** [benjaminkott/bootstrap_package#520]
### Prerequisites

* [x] Can you reproduce the problem on TYPO3 8.7 LTS
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package) to see if your bug or enhancement is already reported?

### Description

After installing a sitepackage built upon bootstrap_package, I wanted to include my own mainnavigation. I simply copied `Partials/Page/Navigation/Main.html` to my own theme, changed its name as well as `section` name inside the file.

Now I get an `Oops error`, and don't know how or why - any ideas?

### Steps to Reproduce

1. Use sitepackage based on bootstrap_package
2. Add bootstrap_package's `Navigation/Main.html` to own theme

**Expected behavior:** Working page

**Actual behavior:** Oops error occured

**Comment by S1SYPHOS** [comment]
This bugs me too .. Please explain how it works, I just cannot recreate the way you created this menu & and I don't neccessarily want to include `*_styled_content` packages :dancer:

**Comment by benjaminkott** [comment]
@daybugging could you please temporary `config.contentObjectExceptionHandler = 0` to your typoscript record in the setup section and tell me what the exact error message is? Currently there is no known issue about overriding partials.

**Comment by daybugging** [comment]
```text
#1407060572: Fluid parse error in template partial_Navigation/Headernav_7f108260aea1cbd11b05005f7d898683bc425667, line 45 at character 1. Error: The ViewHelper "<bk2k:inlineSvg>" could not be resolved. Based on your spelling, the system would load the class "BK2K\BootstrapPackage\ViewHelpers\InlineSvgViewHelper", however this class does not exist. (error code 1407060572). Template source chunk: <bk2k:inlineSvg image="{item.icon.0}" width="{settings.navigation.icon.width}" height="{settings.navigation.icon.height}" />
```

.. after removing it, I get this:

```text
#1225709595: The Fluid template files "/var/www/virtual/moirai/html/dev/typo3/private/typo3conf/ext/ffso/Resources/Private/Partials/Page/DropIn/Navigation/MainBefore.html", "/var/www/virtual/moirai/html/dev/typo3/private/typo3conf/ext/ffso/Resources/Private/Partials/Page/DropIn/Navigation/MainBefore", "/var/www/virtual/moirai/html/dev/typo3/private/typo3conf/ext/bootstrap_package/Resources/Private/Partials/Page/DropIn/Navigation/MainBefore.html", "/var/www/virtual/moirai/html/dev/typo3/private/typo3conf/ext/bootstrap_package/Resources/Private/Partials/Page/DropIn/Navigation/MainBefore" could not be loaded.
```

**Comment by benjaminkott** [comment]
@daybugging i am unsure what happens here.

1. the class thats remarked as missing is existing as you can see here: https://github.com/benjaminkott/bootstrap_package/blob/master/Classes/ViewHelpers/InlineSvgViewHelper.php

2. also the partials exist here: https://github.com/benjaminkott/bootstrap_package/tree/master/Resources/Private/Partials/Page/DropIn/Navigation

I think that you are mixing up versions, can you please check what version of the bootstrap package you have installed? If its the latest composer / ter version please check the correct partials here: 
https://github.com/benjaminkott/bootstrap_package/blob/BP_9-1/Resources/Private/Partials/Page/Navigation/Main.html

And ensure you only copy stuff from github from the correct branch of your version:
https://github.com/benjaminkott/bootstrap_package/branches/yours

**Comment by daybugging** [comment]
Right, my mistake.
