### ISSUE TITLE
Bootstrap table-responsive

### ISSUE THREAD

**Issue by dpfahlbusch** [benjaminkott/bootstrap_package#523]
### Prerequisites

* [x] Can you reproduce the problem on TYPO3 8.7 LTS
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package) to see if your bug or enhancement is already reported?

### Description

Add the possibility to add the 'table-responsive'-div to tables in ckeditor

**Expected behavior:** 
Add 'table-responsive' to a table

**Actual behavior:** 
not available

### Versions
current version

You can get this information from executing `composer show` at the command line if your TYPO3 installation is composer based, otherwise the version number will be shown in the extension manager.

**Comment by benjaminkott** [comment]
@dpfahlbusch the table-responsive should be added automaticly during the rendering, no need to set this in the RTE. please check https://www.bootstrap-package.com/content-examples/text/rich-text/ or the frontend source code of your project. 

please also see the rendering parsefunc for ckeditor stuff:
https://github.com/benjaminkott/bootstrap_package/blob/master/Configuration/TypoScript/Helper/ParseFunc.typoscript#L88-L106
