### ISSUE TITLE
Documentation for dynamicContent

### ISSUE THREAD

**Issue by vergissberlin** [benjaminkott/bootstrap_package#524]
**Hi @benjaminkott,**

thank you for that awesome TYPO3 design customiser!
I wonder how to add additional content with TypoScript. I tried to use dynamicContent, but the content appears several times on the page and I don't know why.

Could please add a documentation how to use it, and add one more marker in the header.

https://github.com/benjaminkott/bootstrap_package/blob/4f93616d78b7d69f2a9bf6720f79114b6e12d607/Configuration/TypoScript/Helper/DynamicContent.typoscript#L39

Thank you
André

## here is my try
```typoscript
lib.language = HMENU
lib.language {
    special = language
    special.value = 0,1,2
    special.normalWhenNoLanguage = 0
    wrap =
    1 = TMENU
    1 {
        noBlur = 1
        NO = 1
        NO {
            doNotLinkIt = 1
            linkWrap = <li>|</li>
            stdWrap.override = Text || Deutsche Gebärdensprache || Lautunterstützte Gebärdensprache
            stdWrap {
                typolink {
                    parameter.data = page:uid
                    additionalParams = &L=0 || &L=1 || &L=2
                    addQueryString = 1
                    addQueryString.exclude = L,id,no_cache
                    addQueryString.method = GET
                    no_cache = 0
                }
            }
        }
        ACT < .NO
        ACT.linkWrap = <li class="active">|</li>
        USERDEF1 < .NO
        USERDEF1 {
            linkWrap = <li class="text-muted">|</li>
            stdWrap.typolink >
        }
        USERDEF2 < .ACT
        USERDEF2 {
            linkWrap = <li class="text-muted">|</li>
            stdWrap.typolink >
        }
    }
}

lib.dynamicContent {
 0 < lib.language
}

```

**Comment by benjaminkott** [comment]
@vergissberlin lib.dynamicContent is just a wrapper for fetching content from the database, and should only be used for that. For example the template https://github.com/benjaminkott/bootstrap_package/blob/4f93616d78b7d69f2a9bf6720f79114b6e12d607/Resources/Private/Templates/Page/SpecialStart.html uses lib.dynamicContent multiple times with different parameters (pageUid, colPos) that means your menu would be rendered everytime for each position here.

So i would prefer a different solution for adding your language menu here.
There is already a language menu available that you can use for that. You can simply set the language uids you want to use with the typo3 constant editor please see options here: https://github.com/benjaminkott/bootstrap_package/blob/BP_9-1/Configuration/TypoScript/constants.typoscript#L82-L87

In the current released branches you still need to override the partial after that:
https://github.com/benjaminkott/bootstrap_package/blob/BP_9-1/Resources/Private/Partials/Page/Navigation/Language.html

In current master the language menu is completely auto generated. You just need to create the languages in the backend.

**Comment by vergissberlin** [comment]
**Hi @benjaminkott ,**

thank you for your explanations! I try to avoid to override templates, partials and so on. The idea is, to be save for future updates and easy make a clone of a site. It would be nice to have TypoScript-ViewHelper in most of the templates to give the possibility to add any kind of content with TypoScript. For instance in the header, sidebar, before and after content and in the footer.

What do you think about?
André

**Comment by benjaminkott** [comment]
@vergissberlin should be resolved, released versions are now completly configurable.
