### ISSUE TITLE
TypoScript include deprecation messages

### ISSUE THREAD

**Issue by ohader** [benjaminkott/bootstrap_package#529]
### Description

Due to renamed TypoScript file resources (`*.txt` to `*.typoscript`) in the TYPO3 core for v9 (master branch) according deprecation messages are shown.

### Steps to Reproduce

1. Use TYPO3 v9 (recent master)
2. Open some backend module (e.g. list module or scheduler module)
3. See the following deprecation message

![screen shot 2018-06-09 at 18 52 16](https://user-images.githubusercontent.com/402145/41194097-c4137208-6c16-11e8-9ee0-838989edd59e.png)

### Notice

Changing the behavior in `ext:bootstrap_package`would make it incompatible to earlier TYPO3 versions (such as v8 LTS).

**Comment by benjaminkott** [comment]
resolved in https://github.com/benjaminkott/bootstrap_package/commit/aba2db81942043b39a4f01c0473735fe809a0a5d
