### ISSUE TITLE
Print layout

### ISSUE THREAD

**Issue by SventB** [benjaminkott/bootstrap_package#53]
The print layout doesn't look very well. E.g. text and images are cropped on the right side. This solves this issue:
.container {
  @media print {
    padding: 0;
    width: auto;
  }
}
Useful could be hiding some parts of the page, e.g. the language navigation.

Also, images are not shown in print layout because of the lazy load.

**Comment by SventB** [comment]
Another solution: Add images for print-only:
´´´
tt_content.image.20.1 {
	layout {
		bootstrappackage {
			element (
				<img src="typo3conf/ext/bootstrap_package/Resources/Public/Images/blank.gif" ###PARAMS######SOURCECOLLECTION######ALTPARAMS######SELFCLOSINGTAGSLASH###>
				<img src="###SRC###"###ALTPARAMS### class="visible-print-block"###SELFCLOSINGTAGSLASH###>
			)
´´´

**Comment by cedricziel** [comment]
Following up on this: I wouldnt opt for the last solution you posted, @SventB . The preflight parser will load the images and destroy the purpose for the lazy ones.

**Comment by benjaminkott** [comment]
After all this years, we maybe can finally implement a solution.

Chrome Updates v63 finally include beforeprint/afterprint events.
https://chromium.googlesource.com/chromium/src/+log/62.0.3202.94..63.0.3239.84?pretty=fuller&n=10000

> To improve interoperability, Chrome will fire beforeprint and afterprint events as part of the printing standard, allowing developers to annotate the printed copy and edit the annotation after the printing command is done executing.

I think this helps us, resolving this issue.
Will check later.

**Comment by benjaminkott** [comment]
Image handling has been completeley reworked, this should not be a problem anymore. Please see https://github.com/benjaminkott/bootstrap_package/commit/0d35fdcb597249715e2c9eece8f3d2ac57b7de94 for all the changes.
