### ISSUE TITLE
Migration of the latest changes for TYPO3 8.7 LTS?

### ISSUE THREAD

**Issue by zolthan** [benjaminkott/bootstrap_package#537]
Hi @benjaminkott ,

some parts of your demo page under https://www.bootstrap-package.com/ look way better than provided by the introduction package https://github.com/FriendsOfTYPO3/introduction

Are you planning to release the changes for the current TYPO3 8.7 LTS? Especially the spaces between the elements are so much nicer in the current version of the bootstrap package. Also the Bootstrap Cards introduced in Bootstrap 4 are of great value.

Thank you for your reply.

Best Z

**Comment by typo3ua** [comment]
Yes, you are right, this is because he install old version. You need take news version from [here...](https://github.com/benjaminkott/bootstrap_package) I did it and I have now Everything looks and works well as [here...](https://www.bootstrap-package.com/ )

**Comment by benjaminkott** [comment]
@zolthan the demo website represents always the current development state from master branch. This one is compatible with TYPO3 8.7 and 9.x. A release is planned but need to find time to finish some stuff here and there.

**Comment by zolthan** [comment]
We are using the Composer TYPO3 setup. This only lets us stick to released versions. So using the dev-master is not suitable. Additionally when using the lautest introduction package, it has the requirement of Typo ^9.1 and Bootstrap Package ^9.1. If we want to use a lower version, compatible with Typo 8 LTS, the requirement switches to Bootstrap Package ^8.0 which is rather old. 

Do you have a rough plan, when to release? This summer? Next summer? Next week? 

Thank you for the quick reply. Best
Z

**Comment by benjaminkott** [comment]
@zolthan we are currently prepping the release. Will be out next week together with the TYPO3 CMS9 LTS Release. Sorry for the late reply.
