### ISSUE TITLE
Git Ignore Policy (.gitignore file)

### ISSUE THREAD

**Issue by netbrothers-tr** [benjaminkott/bootstrap_package#539]
### Prerequisites

* [x] Can you reproduce the problem on TYPO3 8.7 LTS
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package) to see if your bug or enhancement is already reported?

### Description

Are you open to add IDE specific patterns to the `.gitignore` file? If so, I would appreciate the NetBeans project folder to be added to the file. The line would look like this:

`nbproject`

This ignores the "shared" settings aswell, which include project name, PHP version, source encoding and a mapping of SASS source and build directories. I think, they rather shouldn't be included, since it's mostly redundant information, likewise given in the `composer.json` file and build files. However, it's safe to have them included in the repo. If wanted, the line would then look like this.

`nbproject/private`

Hope to hear about it. Thanks!

**Comment by benjaminkott** [comment]
@netbrothers-tr sure, just send a pr for that. i think it will not harm anyone

**Comment by netbrothers-tr** [comment]
Thank you! PR is there.
