### ISSUE TITLE
No site found in root line of page 1

### ISSUE THREAD

**Issue by typo3ua** [benjaminkott/bootstrap_package#541]
**I Installed last TYPO3 version 9.3.1**
**Installed last ext: introduction**
`git clone https://github.com/FriendsOfTYPO3/introduction.git`
**Installed last ext: bootstrap_package**
`git clone https://github.com/benjaminkott/bootstrap_package.git`
**Go to the dev.domain.t3 and I see**
```
Oops, an error occurred!
No site found in root line of page 1
More information regarding this error might be available online.
```
This is not problem on TYPO3 version 8.7.17

**Why? What is wrong?**

**Comment by benjaminkott** [comment]
Do you have a site configured for your dev.domain.t3?

![image](https://user-images.githubusercontent.com/3243119/43318616-b9b578a0-91a1-11e8-9e85-973baa84ed47.png)

**Comment by typo3ua** [comment]
No! I see something different
![typo3_9 3 1_install](https://user-images.githubusercontent.com/638022/43318770-c65542da-91aa-11e8-889c-9c3d0c6ee2c8.png)

**Comment by benjaminkott** [comment]
Ok, please add a site configuration for your entry point and check if the problem still exists.

**Comment by typo3ua** [comment]
I understood... I did it.
