### ISSUE TITLE
Wrong l10n_source after installation

### ISSUE THREAD

**Issue by IchHabRecht** [benjaminkott/bootstrap_package#542]
### Prerequisites

* [ x ] Can you reproduce the problem on TYPO3 8.7 LTS
* [ x ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package) to see if your bug or enhancement is already reported?

### Description

After adding a page translation old content elements are available. Those content elements have a wrong l10n_source.

### Steps to Reproduce

1. Go to page "Any language, any character"
2. Change page module view to "Language"
3. Add a new German translation
4. After adding the page translation already existing content elements are available
5. Add a new content element in default language
6. Start the translation wizard until the last step
7. The restored content elements do have a wrong l10n_source and occur in translation wizard

**Expected behavior:**

- Restored content elements of translated page should not be visible in translation wizard

**Actual behavior:**

- Due to wrong l10n_source the translated content elements occur in translation wizard

![2018-07-27_125242](https://user-images.githubusercontent.com/1453345/43325040-f0342a84-91b5-11e8-8c83-cd6d89eb95f2.png)
![2018-07-27_125355](https://user-images.githubusercontent.com/1453345/43325571-4cd3fc64-91b7-11e8-8511-d2145e573eb0.png)

### Versions

- latest TER release 9.1.1

**Comment by benjaminkott** [comment]
@IchHabRecht i am not sure this is an issue of the bootstrap_package, it sounds more related to a false database dump of https://github.com/FriendsOfTYPO3/introduction? what do you think?

**Comment by benjaminkott** [comment]
@IchHabRecht i will close this one since it should be resolved with the latest release.
