### ISSUE TITLE
Breaking: #82709 - TCA option "localizeChildrenAtParentLocalization" removed

### ISSUE THREAD

**Issue by typo3ua** [benjaminkott/bootstrap_package#543]
[Request for this in extension](https://github.com/benjaminkott/bootstrap_package/search?q=localizeChildrenAtParentLocalization&unscoped_q=localizeChildrenAtParentLocalization) ... remove please.

About this "**Breaking: #82709 - TCA option "localizeChildrenAtParentLocalization" removed**" look at this [here...](https://docs.typo3.org/typo3cms/extensions/core/Changelog/9.0/Breaking-82709-TCAOptionLocalizeChildrenAtParentLocalizationRemoved.html), please

Last TYPO3 version 9.3.3

**Comment by benjaminkott** [comment]
thx for the report, this can only be removed if we drop support for verstion 8.7, we will move this to the next version.

**Comment by typo3ua** [comment]
I use last TYPO3 version 9.4.0
