### ISSUE TITLE
Gridelements embedding

### ISSUE THREAD

**Issue by buepro** [benjaminkott/bootstrap_package#544]
### Prerequisites

TYPO3 8.7.17
bootstrap_package 8.0.6

### Description

When using the snippet found in the wiki page the gridelements provided by bootstrap_grids didn't render correctly. The following snipped rendered it correctly:

temp.gridelements_pi1.setup < tt_content.gridelements_pi1.20.10.setup
tt_content.gridelements_pi1 {
	20 >
	20 = FLUIDTEMPLATE
	20 {
	    templateName = GridElements
        layoutRootPaths {
            10 = EXT:bootstrap_package/Resources/Private/Layouts/ContentElements
            30 = EXT:user_customer/Resources/Private/Layouts/ContentElements
        }
        templateRootPaths {
            10 = EXT:bootstrap_package/Resources/Private/Templates/ContentElements
            30 = EXT:user_customer/Resources/Private/Templates/ContentElements
        }
        partialRootPaths {
            10 = EXT:bootstrap_package/Resources/Private/Partials/ContentElements
            30 = EXT:user_customer/Resources/Private/Partials/ContentElements
        }
        variables {
            content = USER
            content {
                userFunc = GridElementsTeam\Gridelements\Plugin\Gridelements->main
                setup < temp.gridelements_pi1.setup
            }
        }
	}
}

**Comment by benjaminkott** [comment]
@buepro grid elements was configured wrong out of the box - talked to jo about this and he fixed it in grid  elements. https://gitlab.com/coderscare/gridelements/merge_requests/3
