### ISSUE TITLE
Crop Settings for all Content Elements

### ISSUE THREAD

**Issue by olivermeckel** [benjaminkott/bootstrap_package#549]
How can i define crop settings (e.g. allowedAspectRatios) for nested content elements like Carousel Items and Accordion Items? This is only working for elements like image, textpic, media etc.
The following line in tt_content_cropping.php is not working:
`$GLOBALS['TCA']['tt_content']['types']['tx_bootstrappackage_carousel_item']['columnsOverrides']['image']['config']['overrideChildTca']['columns']['crop']['config']['cropVariants']['default'] = $defaultSettings;`

**Comment by benjaminkott** [comment]
@olivermeckel see https://github.com/benjaminkott/bootstrap_package/blob/master/Configuration/TCA/Overrides/cropping.php#L88-L95

**Comment by olivermeckel** [comment]
Yes, that's what i'm looking for.
Thanks. Looking forward to next version.

**Comment by olivermeckel** [comment]
@benjaminkott 
Can i remove existing cropVariants?

for some content elements i want to use only one aspectratio (default) for all viewpoints.
E.g. image has 4 CropSettings, i want to remove "medium", "small" and extrasmall in the backend.
  

$GLOBALS['TCA']['tt_content']['types']['image']['columnsOverrides']['image']['config']['overrideChildTca']['columns']['crop']['config']['cropVariants']['default'] = $defaultCropSettings;
$GLOBALS['TCA']['tt_content']['types']['image']['columnsOverrides']['image']['config']['overrideChildTca']['columns']['crop']['config']['cropVariants']['medium'] =
$GLOBALS['TCA']['tt_content']['types']['image']['columnsOverrides']['image']['config']['overrideChildTca']['columns']['crop']['config']['cropVariants']['small'] =
$GLOBALS['TCA']['tt_content']['types']['image']['columnsOverrides']['image']['config']['overrideChildTca']['columns']['crop']['config']['cropVariants']['extrasmall'] =

**Comment by benjaminkott** [comment]
since this is just an array, you can simply unset the values.

```
unset($GLOBALS['TCA']['tt_content']['types']['image']['columnsOverrides']['image']['config']['overrideChildTca']['columns']['crop']['config']['cropVariants']['medium'])
```
