### ISSUE TITLE
[Feature] Differents preloader types : Logo, HTML, Inline SVG...

### ISSUE THREAD

**Issue by fchaussin** [benjaminkott/bootstrap_package#556]
As discuss on Slack, It could be great to handle different preloader types.
By adding a constant parameter **type** like this: 

`page.preloader.type=[ logo | html | inline_svg | ... ]`

- **logo** will be the default value. Specified as it already is in: `page.preloader.logo`

I'm not sure how to implement `page.preloader.html` and `page.preloader.svg`, since it need to stay **sanitized** (that means all css scripts and all that stuff will be remove automaticly).
Is wrapping HTML with Typoscript in the setup a good convention for the bootstrap_package project?  Maybe with a Fluid Partial?
Any suggestion to handle this properly?

For a memo here a commetn from Ben Kott, while talking about this on Slack:
> Benjamin Kott [15 h 51]
> i can think about this for a bit - currently do not have a clear answer to that. problem is - rendering svgs inline is a pretty easy task. the package is already doing this a lot for all kinds of icons you can set.
> 
> but all svgs will be inserted `sanitized` inline - that means all css scripts and all that stuff will be remove automaticly
> or atleast script stuff
> providing full control with an option to allow any kind of html in there could be an option because the user opted to take full security control here
> still unsure about this one
> whats the best way to go
> type could be an option to switch between that modes
> i need to play around with this idea for a bit - currently in preperations for LTS so could take a while

**Comment by benjaminkott** [comment]
preloader was dropped, this issue can be closed
