### ISSUE TITLE
enable-rounded = true not working

### ISSUE THREAD

**Issue by mediaessenz** [benjaminkott/bootstrap_package#558]
The TypoScript Constant to activate rounded buttons etc. is not working:
plugin.bootstrap_package.settings.scss.enable-rounded = true

**Expected behavior:** Buttons, Alert-Boxes, Cards should get rounded 

**Actual behavior:** Not rounded

**Affected Version:** 10.0

**Solution:*** Change line 24 of Resources/Public/Scss/Theme/_variables.scss from 
$enable-rounded:              false;
to
$enable-rounded:              false !default;

**Comment by benjaminkott** [comment]
@mediaessenz thx a lot for the pointer, fixed
