### ISSUE TITLE
Burger navigation - Firefox 62.0.2 CSS error

### ISSUE THREAD

**Issue by zolthan** [benjaminkott/bootstrap_package#561]
### Prerequisites

* [x] Not tried to reproduce it, because it appears on the demo page https://www.bootstrap-package.com/
* [x] No issue for Firefox found

### Description

In Firefox 62.0.2 the burger navigation has an error. If you open the third navigation layer, there is a huge distance between the heading an the layer below.

The issue appears on https://www.bootstrap-package.com/. I don't know if that is the current version. Because of this issue I haven't updated yet.

### Steps to Reproduce

![navbar-in-firefox-62-0-2-small-viewports](https://user-images.githubusercontent.com/3035434/46407102-00b2fd80-c70e-11e8-80a9-848b3c413bc6.png)

**Comment by C0NN3R111** [comment]
Same issue here, beside Firefox also with Edge, IE, and Android devices. Have that issue also in a fresh Typo3 v9 LTS installation and no idear how to solve.

**Comment by benjaminkott** [comment]
@zolthan @C0NN3R111 thx a lot for reporting could reproduce and resolve the issue will come with the next bugfix release.

**Comment by C0NN3R111** [comment]
Great, just implemented manually and can confirm thats working now.
