### ISSUE TITLE
[BUG] Dropdowns in mainnavigation are missplaced on mobile

### ISSUE THREAD

**Issue by blueamerican** [benjaminkott/bootstrap_package#565]
TYPO3 8.7.19
boostrap_package 10.0.2
using boostrap4 sass

In mobile navigation the level 2 ul is in the wrong position.
It breaks down to the next li.
After adding position static to .drowdown-menu is works.

**Comment by benjaminkott** [comment]
@blueamerican thx a lot for reporting could reproduce and resolve the issue will come with the next bugfix release.
