### ISSUE TITLE
Submenu with another level visible

### ISSUE THREAD

**Issue by LaKiKat** [benjaminkott/bootstrap_package#566]
### Prerequisites

* [x] Can you reproduce the problem on TYPO3 8.7 LTS
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package) to see if your bug or enhancement is already reported?

### Description

I wanted to add another level to the submenue. I don't find the TS in order to add it. I suppose I am just too blind or it is kind of different from what I know so far.

Can you please support me on this issue? Thank you so much!

**Comment by fansari** [comment]
I have the same issue. In the bootstrap 9 extension with  bootstrap3 you could find out whether you need to loop over each item by checking for subitems like this:
```
<f:if condition="{child.children}">
```
Now in the boosttrap 10 extension with bootstrap 4 I did not find any children. Something must have changed so this approach is not working anymore.

Currently I don't know how to build submenus. I will continue with bootstrap 9 extension until I find some hint how to check for subitems.

**Comment by benjaminkott** [comment]
@joenat75 @LaKiKat I have this in mind for a while, still looking into the how - bootstrap framework itself does NOT support this, so we need a custom implementation here.

- how it should behave?
- what should be included? 
- do we need a mega menu?
- do we need to add content to the menu?
- how should it look like?
- how long does it take to build?
- who is interested in this?

**Comment by joenat75** [comment]
Hello, see the attached pdf-file
Great thanks
Josef
[Navigation_Submenu.pdf](https://github.com/benjaminkott/bootstrap_package/files/2719470/Navigation_Submenu.pdf)

**Comment by fansari** [comment]
Well, I had the same issue and always have to work around.

For version 1.9 (bootstrap_package9) I used the multi level solution from Thomas M. Stein. Now with bootstrap_version10 this did not work anymore and I had to look for another solution.

For me it seemed best (matter of taste of course) to have the submenu on the right hand side. But this did not work for mobile. In mobile view the submenu vanished completely.

So what I did is to add the SubnavigtaionItem to the Navigation/Main.html file and put this after the <li><a href=...>.

```
<span class="dropdown-text">{child.title}<f:if condition="{child.current}"> <span class="sr-only">(current)</span></f:if></span>

<f:if condition="{child.active} && {child.children}">
   <div class="my-media-menu-display">
      <f:render section="SubnavigationItem" arguments="{menu: child.children, theme: theme}" /> 
    </div>
```
My class "my-media-menu-display" makes sure that the submenu is only visible inside the main menu section its is for mobile view (because I don't want to have it both in main menu and on the right hand side for larger view):

```
.my-media-menu-display {
        @media all and (min-width: $print-body-min-width) { 
                display: none;
    }
}
```

**Comment by aksenovaa** [comment]
Also ran into this problem. Maybe still consider creating a mega menu?

**Comment by joenat75** [comment]
Hello,
thanks for the answere. Yes I would be glad to have a megamenue. Right 
now I'm just working with what I have within the installation.
How to get forward?
Best wishes
Josef


Am 13.06.2019 um 09:58 schrieb Andrey:

**Comment by McKoy61** [comment]
It would be great to have a multi column menu at the width of frame-container. For me it could be a very simple solution using the menue-seperator for defining the start of a new menu column and its headers. Using the menu-seperators again as visible menu-headers to structure the menu, can reduce the number of necessary sublevels in some cases. So nothing must be changed for tablets and smartphones. Of course, this is not a real mega menu, but it would help.

**Comment by benjaminkott** [comment]
resolved with https://github.com/benjaminkott/bootstrap_package/commit/2775146d21660b1c09bbd9ab093672bfdad326bc
