### ISSUE TITLE
How to remove fontloader script code from head of the page

### ISSUE THREAD

**Issue by blueamerican** [benjaminkott/bootstrap_package#570]
TYPO3 8.7.19
bootstrap_package 10.0.2
scss BT 4

is there a possibility to remove this code:

<script>WebFontConfig={"custom":{"urls":["\/typo3conf\/ext\/bootstrap_package\/Resources\/Public\/Fonts\/bootstrappackageicon.min.css"],"families":["BootstrapPackageIcon"]},"timeout":1000};(function(d){var wf=d.createElement('script'),s=d.scripts[0];wf.src='/typo3conf/ext/bootstrap_package/Resources/Public/Contrib/webfontloader/webfontloader.js';wf.async=false;s.parentNode.insertBefore(wf,s);})(document);</script>

**Comment by benjaminkott** [comment]
The webfontloader you want remove is developed by google together with typekit.
https://github.com/typekit/webfontloader

It simply reacts to your CSS File configuration and is build in, so you cannot just disable it.
The code is only applied IF css files are configured to use the webfontloader.

The last file that is in your case configured to use the webfontloader is in your case the BootstrapPackage Icon-Font. You can just disable the fontloader configuration for that file in yout TypoScript Setup.

```
page.includeCSSLibs.bootstrappackageicon.fontLoader >
```

**Comment by blueamerican** [comment]
ah ok, thanks!
