### ISSUE TITLE
Using a link scrolls instead of opening other page if only query differs in href attribute

### ISSUE THREAD

**Issue by markuspoerschke** [benjaminkott/bootstrap_package#572]
### Prerequisites

* [x] Can you reproduce the problem on TYPO3 8.7 LTS
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package) to see if your bug or enhancement is already reported?

### Description

If an fragment is used within a `<a>` tag then the page scrolls to that fragment, if only the query is different to the current URL.

This is because within `Resources/Public/JavaScript/Src/bootstrap.smoothscroll.js` only the `host` and `path` are compared.

The following URL components should be compared to decide wether or not to smooth scrool. All components should match:

* schema
* host
* port
* path
* query

URL components that do not have to match:

* fragment

Furthermore scrolling should be disabled if user or password is given. Optional it can be helpful to provide a data attribute (e.g. `data-no-smoth-scroll`) to deactivate smooth scrolling.

### Steps to Reproduce

GIVEN the current url is `/some/page`
AND GIVEN a link tag is placed on the page `<a href="/some/page?a=b#c-123">...</a>`
WHEN the link is clicked
THEN the page scrolls to the anchor rather than openening the URL

**Expected behavior:** The page with the URL `/some/page?a=b#c-123` should be opened, because the query within the URL differs from the current page.

### Versions

Tested with version `9.1.1`.

**Comment by a-r-m-i-n** [comment]
+1

**Comment by benjaminkott** [comment]
should be resolved with https://github.com/benjaminkott/bootstrap_package/commit/f589ba076111b995af24d8bbd2e38b022b17b190
