### ISSUE TITLE
PDF thumbnails for uploads CE type or Images CE not rendering.

### ISSUE THREAD

**Issue by pixelplumber** [benjaminkott/bootstrap_package#576]
### Prerequisites

* [ ] TYPO3 8.7? No only used 9.5.0 LTS
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package) to see if your bug or enhancement is already reported?
Can only find [an old bug on forge](https://forge.typo3.org/issues/71502) re. PDF media rendering and uploads:  

### Description

The Uploads CE does not render PDF thumbnails or icons and the Images CE does not render PDF file links.

### Steps to Reproduce for uploads

1. Edit an Uploads CE on intro package:  https://-domain-/content-examples/media/file-downloads
2. Add a PDF filetype to the list
3. View on the front end

**Expected behavior:** PDF thumbnail is rendered next to downloads header and size.

**Actual behavior:** Downloads entry is rendered without `<div class="media-left"></div>` node.

### Steps to Reproduce for images CE

1. Edit an images CE in intro package:  https://-domain-/content-examples/media/images
2. Add a PDF filetype to the list of images
3. View on the front end.

**Expected behavior:** PDF thumbnail rendered as part of images CE

**Actual behavior:** Images entry is rendered with comment <`div class="gallery-item gallery-item-size-3"><!-- NOT SUPPORTED MEDIA TYPE --></div>`
Crop variants in BE reports in a blue message: 

> No image dimensions could be determined

### Investigation

- Found [forge issue](https://forge.typo3.org/issues/71502) re. PDF but is apparently patched.
- Compared FSC templates against the template/partials in the bootstrap package and the [conditions](https://github.com/benjaminkott/bootstrap_package/blob/ced0fd77e67eb32c8db2cbeaf300bf55ef9d0d30/Resources/Private/Templates/ContentElements/Uploads.html#L11) and image tags [seem to be the same](https://github.com/TYPO3-CMS/fluid_styled_content/blob/8b738f57cff3883d9581dffad83eb16532a262cc/Resources/Private/Templates/Uploads.html#L14). 
- Using FSC rendering instead of bootstrap package generates a thumbnail for Uploads CE. 
- PDF thumbnails are rendered in the BE and image processing is working for PDF.

### Versions

TYPO3 9.5.0
Bootstrap Package: 10.0.2
Introduction Package: 4.0.1

**Comment by hweckhardt** [comment]
@pixelplumber: how was this issue solved? I have a similar problem.

**Comment by osahner** [comment]
@hweckhardt not fixed by now. #647 the same

**Comment by osahner** [comment]
found it:
https://github.com/benjaminkott/bootstrap_package/blob/716f8074b5bf6e481496f15b03017f17b085843c/Resources/Private/Templates/ContentElements/Uploads.html#L10

just add type 5:
```html
<f:if condition="{file.type} == 2 || {file.type} == 4 || {file.type} == 5">
```
