### ISSUE TITLE
language menu with link using GET vars

### ISSUE THREAD

**Issue by specialistaweb** [benjaminkott/bootstrap_package#577]
your template code creates a link using directly the <a> tag, as you can see here
https://github.com/benjaminkott/bootstrap_package/blob/master/Resources/Private/Partials/Page/Navigation/Language.html

lines from #8 to #10

maybe this should be susbtituted with the fluid <f:link.page ...> like here:
https://docs.typo3.org/typo3cms/ExtbaseGuide/Fluid/ViewHelper/Link/Page.html

infact, if I access a dynamic page like NEWS, there is no way to attach the GET vars to the link. I tried some typoscript without success, moreover disabling tx_real_url. 

The problem is that I cannot switch in a particular dynamic page, from one language to another passing the GET vars that are not appendend to the created URL

any suggestion?

**Comment by otisid** [comment]
If anyone is interested, for now this would do the trick, as mentioned above:

`<f:link.page pageUid="{data.id}" additionalParams="{L: '{item.languageId}'}" addQueryString="1" title="{item.title}" additionalAttributes="{hreflang: '{item.hreflang}'}">
    <span>{item.navigationTitle}</span>
</f:link.page>`

There is the difference in accessing the URL as the **f:link.page** ViewHelper accepts only pageUid as a link definition.
Also, it should be noted for users to be carefull while using **addQueryString** and disabling cHash.

**Comment by gilbertsoft** [comment]
I hardly guess this should not longer be an issue since the introduction of the LanguageMenuProcessor so I'm going to close this issue now.
