### ISSUE TITLE
Cosmetic "bug" with border-bottom on accordion

### ISSUE THREAD

**Issue by wtfred** [benjaminkott/bootstrap_package#579]
### Description
In _accordion.scss, you add margin-top over "native" bootstrap style.
This result in double border on collapse item:
![double_border](https://user-images.githubusercontent.com/3072924/47428196-d2679180-d792-11e8-8dce-eaf2cbf8aaf4.png)
And no border-bottom when item is displayed
![no_border](https://user-images.githubusercontent.com/3072924/47428235-f2975080-d792-11e8-9c34-e8dc5828e1ef.png)

To fix it you need to add this in _accordion.scss (once again, didn't try with Less, sorry!)
```
.accordion {
    .card {
        border-bottom: 0;
    }
    .accordion-collapse{
      border-bottom: $card-border-width solid $card-border-color;
    }
}
```

**Comment by typo3ua** [comment]
I think better ...
```
.accordion {
    .card:last-child {
        border-bottom: 0;
    }
}
```
