### ISSUE TITLE
[branch BP_10-0] Template "Quote" not Bootstrap4 compatible

### ISSUE THREAD

**Issue by hoelbing** [benjaminkott/bootstrap_package#583]
File: Resources/Private/Templates/ContentElements/Quote.html

line6:
 `<blockquote` cite="{f:uri.typolink(parameter: `data.quote_link)}">`

change to 
`<blockquote` **class="blockquote"** cite="{f:uri.typolink(parameter: `data.quote_link)}">`

line 9: 
`<footer><f:link.typolink` `parameter="{data.quote_link}">{data.quote_source}</f:link.typolink></footer>`

change to 
`<footer` **class="blockquote-footer"**><f:link.typolink `parameter="{data.quote_link}">{data.quote_source}</f:link.typolink></footer>`

Source: hhttps://getbootstrap.com/docs/4.1/content/typography/#blockquotes

**Comment by benjaminkott** [comment]
@hoelbing i know that this one is nor perfect atm, problem is i had to do some workarounds to have bootstrap3 and bootstrap4 not heavily conflicting for the moment. I´ve decided to help people to migrate their less bootstrap3 code to sass bootstrap4 means for now. as soon as we drop bootstrap3 support we will adjust this issue and adjust also the markup.
