### ISSUE TITLE
Warning in less.php with PHP 7.3

### ISSUE THREAD

**Issue by opi99** [benjaminkott/bootstrap_package#584]
Maybe there is an updated version of the used less.php or it needs to be reported upstream.

> Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /typo3conf/ext/bootstrap_package/Contrib/less.php/Less.php on line 9709
> Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /typo3conf/ext/bootstrap_package/Contrib/less.php/Less.php on line 9717
> Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /typo3conf/ext/bootstrap_package/Contrib/less.php/Less.php on line 9722
> Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /typo3conf/ext/bootstrap_package/Contrib/less.php/Less.php on line 9728
> Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /typo3conf/ext/bootstrap_package/Contrib/less.php/Less.php on line 9738
> Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /typo3conf/ext/bootstrap_package/Contrib/less.php/Less.php on line 9741
> Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /typo3conf/ext/bootstrap_package/Contrib/less.php/Less.php on line 9761
> Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /typo3conf/ext/bootstrap_package/Contrib/less.php/Less.php on line 9766
> Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /typo3conf/ext/bootstrap_package/Contrib/less.php/Less.php on line 9787
> Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /typo3conf/ext/bootstrap_package/Contrib/less.php/Less.php on line 9794

**Comment by opi99** [comment]
Using Bootstrap Package version 10.0.3

**Comment by benjaminkott** [comment]
@opi99 the development of the less parser is stalled, and there does not seem to happen any further development - if you can provide a patch for the version included in the bootstrap package version we will alter the original code to get the support included.
