### ISSUE TITLE
Carousel background image (.carousel-backgroundimage-container) rendered twice covering actual content

### ISSUE THREAD

**Issue by hilburger** [benjaminkott/bootstrap_package#586]
### Prerequisites

* [X] Can you reproduce the problem on TYPO3 8.7 LTS -> 8.7.20 LTS
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package) to see if your bug or enhancement is already reported?

### Description

Placing the normal carousel adding a background image within a slider item create 2 similiar   background divs (.carousel-backgroundimage-container) with identical css-ID: 
carousel-backgroundimage-{uip-page-13}-{uid-slide}. 
This let's one bg-div lay over the content of th slide. 

### Steps to Reproduce

1. Add carousel
2. Add a slide of type Header
3. Fill out content fields and add a background image in tab "Background" of carousel item itself. 

**Expected behavior:** 
Render only one DIV. 

**Actual behavior:** 
Renders background div twice (identical IDs)

### Versions

10.0.3.
[buggy-html.txt](https://github.com/benjaminkott/bootstrap_package/files/2558472/buggy-html.txt)

**Comment by benjaminkott** [comment]
@hilburger i`ve made some tests on this one - and my markup looks slightly different then yours.

As you can see that the ordering of the divs like carousel-backgroundimage-container` and `carousel-content` is inverted for example. 

```
<div class="item active carousel-item carousel-item-type carousel-item-type-text_and_image" data-itemno="0" style="background-color: #333333;">
    <div class="carousel-backgroundimage-container">
        <div id="carousel-backgroundimage-182-4" class="carousel-backgroundimage">
            <style>
                #carousel-backgroundimage-182-4 {
                    background-image: url('/fileadmin/_processed_/5/1/csm_editing_interface_01_20590b42fa.png');
                }

                @media (min-width: 576px) {
                    #carousel-backgroundimage-182-4 {
                        background-image: url('/fileadmin/_processed_/5/1/csm_editing_interface_01_c9acedd045.png');
                    }
                }

                @media (min-width: 768px) {
                    #carousel-backgroundimage-182-4 {
                        background-image: url('/fileadmin/_processed_/5/1/csm_editing_interface_01_5bf54f435f.png');
                    }
                }

                @media (min-width: 992px) {
                    #carousel-backgroundimage-182-4 {
                        background-image: url('/fileadmin/_processed_/5/1/csm_editing_interface_01_c1a92eacc0.png');
                    }
                }

                @media (min-width: 1200px) {
                    #carousel-backgroundimage-182-4 {
                        background-image: url('/fileadmin/_processed_/5/1/csm_editing_interface_01_602032c1be.png');
                    }
                }
            </style>
        </div>
    </div>
    <div class="carousel-content">
        <a href="/features" draggable="false">
            <div class="valign">
                <div class="carousel-text vcontainer" style="color: #FFFFFF;">
                    <h1 class="carousel-header none">Text and Image</h1>
                    <h2 class="carousel-subheader none">In consectetuer turpis ut velit</h2>
                    <p>Vestibulum dapibus nunc ac augue. Class aptent taciti sociosqu ad litora torquent per conubia
                        nostra, per inceptos hymenaeos. Quisque rutrum. Aliquam eu nunc. Nam adipiscing.
                    </p>
                    <p>Ut a nisl id ante tempus hendrerit. Vivamus aliquet elit ac nisl. Cum sociis natoque penatibus
                        et magnis dis parturient montes, nascetur ridiculus mus. Praesent egestas neque eu enim.
                        Praesent congue erat at massa.</p>
                </div>
                <div class="carousel-image vcontainer">
                    <picture>
                        <source data-variant="default" data-maxwidth="550" media="(min-width: 1200px)" srcset="/fileadmin/_processed_/a/7/csm_extensionmanager_ae054d2058.png">
                        <source data-variant="large" data-maxwidth="460" media="(min-width: 992px)" srcset="/fileadmin/_processed_/a/7/csm_extensionmanager_eb5c56eba7.png">
                        <source data-variant="medium" data-maxwidth="340" media="(min-width: 768px)" srcset="/fileadmin/_processed_/a/7/csm_extensionmanager_a1998de3e4.png">
                        <source data-variant="small" data-maxwidth="250" media="(min-width: 576px)" srcset="/fileadmin/_processed_/a/7/csm_extensionmanager_172a7553ee.png">
                        <source data-variant="extrasmall" data-maxwidth="374" srcset="/fileadmin/_processed_/a/7/csm_extensionmanager_3671f46ae7.png">
                        <img src="/fileadmin/_processed_/a/7/csm_extensionmanager_ae054d2058.png" title="" alt="">
                    </picture>
                </div>
            </div>
        </a>
    </div>
</div>
```

Can you please check if you have overridden the carousel main templates and check if the for each loop more or less matches this one?

```
<f:for each="{records}" as="item" iteration="iteration">
	<f:variable name="itemStyleColor"><f:if condition="{item.data.background_color}">background-color: {item.data.background_color};</f:if></f:variable>
	<div class="item{f:if(condition: iteration.isFirst,then:' active')} carousel-item carousel-item-type carousel-item-type-{item.data.item_type}" data-itemno="{iteration.index}" style="{itemStyleColor}">
		<f:render partial="Carousel/General/BackgroundImage" arguments="{_all}" />
		<div class="carousel-content">
			<f:render partial="Carousel/Item/{item.data.item_type -> bk2k:format.upperCamelCase()}" arguments="{_all}" />
		</div>
	</div>
</f:for>
```

**Comment by hilburger** [comment]
> @hilburger i`ve made some tests on this one - and my markup looks slightly different then yours.
> 
> As you can see that the ordering of the divs like `carousel-backgroundimage-container` and `carousel-content` is inverted for example.
> 
> ```
> <div class="item active carousel-item carousel-item-type carousel-item-type-text_and_image" data-itemno="0" style="background-color: #333333;">
>     <div class="carousel-backgroundimage-container">
>         <div id="carousel-backgroundimage-182-4" class="carousel-backgroundimage">
>             <style>
>                 #carousel-backgroundimage-182-4 {
>                     background-image: url('/fileadmin/_processed_/5/1/csm_editing_interface_01_20590b42fa.png');
>                 }
> 
>                 @media (min-width: 576px) {
>                     #carousel-backgroundimage-182-4 {
>                         background-image: url('/fileadmin/_processed_/5/1/csm_editing_interface_01_c9acedd045.png');
>                     }
>                 }
> 
>                 @media (min-width: 768px) {
>                     #carousel-backgroundimage-182-4 {
>                         background-image: url('/fileadmin/_processed_/5/1/csm_editing_interface_01_5bf54f435f.png');
>                     }
>                 }
> 
>                 @media (min-width: 992px) {
>                     #carousel-backgroundimage-182-4 {
>                         background-image: url('/fileadmin/_processed_/5/1/csm_editing_interface_01_c1a92eacc0.png');
>                     }
>                 }
> 
>                 @media (min-width: 1200px) {
>                     #carousel-backgroundimage-182-4 {
>                         background-image: url('/fileadmin/_processed_/5/1/csm_editing_interface_01_602032c1be.png');
>                     }
>                 }
>             </style>
>         </div>
>     </div>
>     <div class="carousel-content">
>         <a href="/features" draggable="false">
>             <div class="valign">
>                 <div class="carousel-text vcontainer" style="color: #FFFFFF;">
>                     <h1 class="carousel-header none">Text and Image</h1>
>                     <h2 class="carousel-subheader none">In consectetuer turpis ut velit</h2>
>                     <p>Vestibulum dapibus nunc ac augue. Class aptent taciti sociosqu ad litora torquent per conubia
>                         nostra, per inceptos hymenaeos. Quisque rutrum. Aliquam eu nunc. Nam adipiscing.
>                     </p>
>                     <p>Ut a nisl id ante tempus hendrerit. Vivamus aliquet elit ac nisl. Cum sociis natoque penatibus
>                         et magnis dis parturient montes, nascetur ridiculus mus. Praesent egestas neque eu enim.
>                         Praesent congue erat at massa.</p>
>                 </div>
>                 <div class="carousel-image vcontainer">
>                     <picture>
>                         <source data-variant="default" data-maxwidth="550" media="(min-width: 1200px)" srcset="/fileadmin/_processed_/a/7/csm_extensionmanager_ae054d2058.png">
>                         <source data-variant="large" data-maxwidth="460" media="(min-width: 992px)" srcset="/fileadmin/_processed_/a/7/csm_extensionmanager_eb5c56eba7.png">
>                         <source data-variant="medium" data-maxwidth="340" media="(min-width: 768px)" srcset="/fileadmin/_processed_/a/7/csm_extensionmanager_a1998de3e4.png">
>                         <source data-variant="small" data-maxwidth="250" media="(min-width: 576px)" srcset="/fileadmin/_processed_/a/7/csm_extensionmanager_172a7553ee.png">
>                         <source data-variant="extrasmall" data-maxwidth="374" srcset="/fileadmin/_processed_/a/7/csm_extensionmanager_3671f46ae7.png">
>                         <img src="/fileadmin/_processed_/a/7/csm_extensionmanager_ae054d2058.png" title="" alt="">
>                     </picture>
>                 </div>
>             </div>
>         </a>
>     </div>
> </div>
> ```
> Can you please check if you have overridden the carousel main templates and check if the for each loop more or less matches this one?
> 
> ```
> <f:for each="{records}" as="item" iteration="iteration">
> 	<f:variable name="itemStyleColor"><f:if condition="{item.data.background_color}">background-color: {item.data.background_color};</f:if></f:variable>
> 	<div class="item{f:if(condition: iteration.isFirst,then:' active')} carousel-item carousel-item-type carousel-item-type-{item.data.item_type}" data-itemno="{iteration.index}" style="{itemStyleColor}">
> 		<f:render partial="Carousel/General/BackgroundImage" arguments="{_all}" />
> 		<div class="carousel-content">
> 			<f:render partial="Carousel/Item/{item.data.item_type -> bk2k:format.upperCamelCase()}" arguments="{_all}" />
> 		</div>
> 	</div>
> </f:for>
> ```

I'll try to check that asap!

**Comment by benjaminkott** [comment]
@hilburger any update on the issue?
