### ISSUE TITLE
Override Problems Layout Content Elements

### ISSUE THREAD

**Issue by ipnextOne** [benjaminkott/bootstrap_package#587]
Hello

I can´t override the Default.html of the ContentElements. All other files work. 

Thanks a lot for help

Typo3 8.7.20
Bootstrap Package 10.0.3

**Comment by benjaminkott** [comment]
@ipnextOne i cannot see a problem here, can you please provide your configuration so we can check it?

The constants you should change are the following.

```
plugin.bootstrap_package_contentelements {
    view {
        layoutRootPath = EXT:bootstrap_package/Resources/Private/Layouts/ContentElements/
        partialRootPath = EXT:bootstrap_package/Resources/Private/Partials/ContentElements/
        templateRootPath = EXT:bootstrap_package/Resources/Private/Templates/ContentElements/
    }
}
```

**Comment by ipnextOne** [comment]
Thanks a lot for help. It was my mistake. I forgot this override ...
