### ISSUE TITLE
Typoscript Path Typo

### ISSUE THREAD

**Issue by ses2013** [benjaminkott/bootstrap_package#590]
### Prerequisites

* [X] Can you reproduce the problem on TYPO3 9.5.1 LTS
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package) to see if your bug or enhancement is already reported?

/ext/bootstrap_package/Configuration/TypoScript/Bootstrap4/setup.typoscript

### Description
page {
    includeCSS {
        # bootstrap 4.x will be included in the themes.less file
        # for standalone usage just uncomment the following line
        # bootstrap = EXT:bootstrap_package/Resources/Contrib/bootstrap4/scss/bootstrap.scss
        theme = EXT:bootstrap_package/Resources/Public/Scss/Theme/theme.scss
}
}
[Description of the bug or feature]

Must be
# bootstrap = EXT:bootstrap_package/Resources/**Public**/Contrib/bootstrap4/scss/bootstrap.scss

### Versions

Composer Mode bootstrap_package 10.0.3

**Comment by jokumer** [comment]
I dont think so.
_EXT:bootstrap_package/Resources/Public/Scss/Theme/theme.scss_ contains some additional styles, for this bootstrap_package HTML output.
You can or should configure your own theme and adopt this path for your installation alike
_page.includeCSS.theme = EXT:my_sitepackage/Resources/Public/Scss/Theme/theme.scss_

**Comment by benjaminkott** [comment]
@ses2013 @jokumer you are both right, but @ses2013 referred to a comment that is pointing to the plain bootstrap resources and in this case he was also right that the path was missing the `Public` directory.
