### ISSUE TITLE
[suggestion] To do the changes in the Templates of content element MemuCard* or Menu*

### ISSUE THREAD

**Issue by typo3ua** [benjaminkott/bootstrap_package#591]
I have a suggestion to do the changes where we get data from `page`

Sometimes and somewhere I want to show `nav_title` and not `title`,.. in currently it is not possible is need to do custom changes.

**For example:**
```
File: /bootstrap_package/Resources/Private/Templates/ContentElements/MenuCardDir.html
```
**Add this line after 10 line**
```
<f:variable name="titleORnavtitle" value="{f:if(condition:'{page.data.nav_title}',then:'{page.data.nav_title}',else:'{page.data.title}')}"/>
```
**To Change lines 36, 37, 38** 

FROM
```
<a href="{page.link}"{f:if(condition: page.target, then: ' target="{page.target}"')} title="{page.title}" data-toggle="tooltip">
     <f:format.crop maxCharacters="{settings.menucard.title.crop}">{page.data.title}</f:format.crop>
</a>
```
TO
```
<a href="{page.link}"{f:if(condition: page.target, then: ' target="{page.target}"')} title="{titleORnavtitle}" data-toggle="tooltip">
      <f:format.crop maxCharacters="{settings.menucard.title.crop}">{titleORnavtitle}</f:format.crop>
</a>
```
**To Change line 51**

FROM
```
<a href="{page.link}"{f:if(condition: page.target, then: ' target="{page.target}"')} class="card-link" title="{page.title}" data-toggle="tooltip">
```
TO
```
<a href="{page.link}"{f:if(condition: page.target, then: ' target="{page.target}"')} class="card-link" title="{titleORnavtitle}" data-toggle="tooltip">
```
Of course if this possible.
Thank you for your time.

**Comment by jokumer** [comment]
@typo3ua well described. Ofcourse, we can override each HTML template for your our self. But your suggestion will improve the default, especially if it has already been tested by you. 
Could you provide a pull request? Its done quickly for you and afterwards easy and faster to review and merge into this source.
You already have a fork of this source. Use your fork and get started
https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by benjaminkott** [comment]
@typo3ua thx for the pointer you are right, i think it was a simple mistake from my side to not respect the menu processor configuration at this point.
