### ISSUE TITLE
Cookie Consent not working with country code or location detection

### ISSUE THREAD

**Issue by heuchri56** [benjaminkott/bootstrap_package#592]
### Prerequisites

* [Yes ] Can you reproduce the problem on TYPO3 8.7 LTS
* [Yes ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package) to see if your bug or enhancement is already reported?

### Description

Template Constant Editor BOOTSTRAP PACKAGE: COOKIE CONSENT
Cookie Consent window appears in frontend if Location Detection and Country Code are left empty.
Cookie Consent window does not appear if either Location Detection is set to True or a Contry Code is entered (e.g. "de", "DE", "ch", "us")

### Steps to Reproduce

1. [Leave Location Detection and Country Code empty, save template]
2. [Load a page of the installation freshly (Ctrl-F5) in other browser]
3. [Set Country code to "de", save template]
4. [Load a page of the installation freshly (Ctrl-F5) in other browser]

**Expected behavior:** [Cookie Consent window appears in step 2 in English, in step 4 in German]

**Actual behavior:** [Cookie Consent window appears in step 2 in English, nothing appears in step 4
When resetting to step 1, then Cookie Consent window appears in step 2 in English again]

### Versions
Typo3 8.7.20
Bootstrap Package 10.0.3
PHP 7.0.32

Do I have to set any additional parameters in TS or elsewhere?
Many thanks and best regards, Christoph

**Comment by benjaminkott** [comment]
@heuchri56 i think we have a small misunderstanding here. The settings do not influence the **language** the cookie consent will be displayed in. The location detection and the countrycode are only there to check if the region hast an active **Cookie Law** please see [Vendor Example](https://cookieconsent.insites.com/app/themes/insites-cookie-consent/examples/example-6-location.html). 

The translation is handled automaticly by TYPO3 depending on the language the page is currently displayed in. Means if you are using the page in `English` also the Cookie Consent will show `English` texts. If you have set the page language to `German` the Cookie Consent will show `German Text`.

TYPO3 will download and show the content according to the frontend language if available and if someone has already translated the strings. If you prefer custom strings for the messages you can check the mini guide i´ve added for this. https://github.com/benjaminkott/bootstrap_package/wiki/Customize-Cookie-Consent

**Comment by heuchri56** [comment]
Hello Benjamin,

 

Many thanks for your reply – helped a  lot understanding.

*	The custom strings in TS Setup work well
*	Automatic translation does not work, although I have attempted everything I could to have German as default language. And a page translated to German did not work neither.

 

Here is what I have in TS:

config.language.default.title = Deutsch
config.language.default.nav_title = Deutsch
config.language.default.locale = de_CH.UTF-8
config.language.default.language_isocode = de
config.language.default.hreflang = de-CH

config.locale_all = de_CH.UTF-8
config.sys_language_uid = 1
config.linkVars = L(int)
config.language = de
config.htmlTag_setParams = lang="de-CH" dir="ltr" class="no-js"

 

Best regards, Christoph

 

Von: Benjamin Kott <notifications@github.com> 
Gesendet: Sonntag, 18. November 2018 16:14
An: benjaminkott/bootstrap_package <bootstrap_package@noreply.github.com>
Cc: heuchri56 <heuchri@gmx.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [benjaminkott/bootstrap_package] Cookie Consent not working with country code or location detection (#592)

 

@heuchri56 <https://github.com/heuchri56>  i think we have a small misunderstanding here. The settings do not influence the language the cookie consent will be displayed in. The location detection and the countrycode are only there to check if the region hast an active Cookie Law please see Vendor Example <https://cookieconsent.insites.com/app/themes/insites-cookie-consent/examples/example-6-location.html> .

The translation is handled automaticly by TYPO3 depending on the language the page is currently displayed in. Means if you are using the page in English also the Cookie Consent will show English texts. If you have set the page language to German the Cookie Consent will show German Text.

TYPO3 will download and show the content according to the frontend language if available and if someone has already translated the strings. If you prefer custom strings for the messages you can check the mini guide i´ve added for this. https://github.com/benjaminkott/bootstrap_package/wiki/Customize-Cookie-Consent

**Comment by froemken** [comment]
Do it that way:

plugin.tx_bootstrap_package._LOCAL_LANG.de.cookieconsent\.common\.message = Diese Webseite verwendet Cookies, um Ihnen ein angenehmeres Surfen zu ermöglichen.
plugin.tx_bootstrap_package._LOCAL_LANG.de.cookieconsent\.common\.dismiss = Verstanden

I think ticket can be closed now

Stefan

**Comment by heuchri56** [comment]
I did it this way. Yes, ticket can be closed.

 

Many thanks and best regards, Christoph

 

Von: Stefan Frömken <notifications@github.com> 
Gesendet: Samstag, 22. Dezember 2018 19:45
An: benjaminkott/bootstrap_package <bootstrap_package@noreply.github.com>
Cc: heuchri56 <heuchri@gmx.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [benjaminkott/bootstrap_package] Cookie Consent not working with country code or location detection (#592)

 

Do it that way:

plugin.tx_bootstrap_package._LOCAL_LANG.de.cookieconsent.common.message = Diese Webseite verwendet Cookies, um Ihnen ein angenehmeres Surfen zu ermöglichen.
plugin.tx_bootstrap_package._LOCAL_LANG.de.cookieconsent.common.dismiss = Verstanden

I think ticket can be closed now

Stefan

**Comment by danaron** [comment]
Der Header fehlt noch. Komplett habe ich es so gelöst:

```
plugin.tx_bootstrap_package._LOCAL_LANG.de.cookieconsent\.common\.header =  Cookies:
plugin.tx_bootstrap_package._LOCAL_LANG.de.cookieconsent\.common\.message = Webseite verwendet Cookies für beste Ergebnisse.
plugin.tx_bootstrap_package._LOCAL_LANG.de.cookieconsent\.common\.dismiss = Verstanden
```
