### ISSUE TITLE
Full width background-image not possible for two or more columns

### ISSUE THREAD

**Issue by Moongazer** [benjaminkott/bootstrap_package#593]
I like the full-width background image for a section on a landing page for example. Unfortunately this is ONLY possible if I choose "Default", "Simple" or "Special Startpage" as backend-layout. **But how can I use this feature if I want to have e.g. 3 columns with text including a full-width background image?**

Also the "Special Feature" layout is not helpful, because the 2 columns for "Special" content are below the background-image, with a background-color assigned.

Maybe this will work in the future with gridelements, but 1) I don't like to use an extra extension for something what is maybe possible out-of-the-box and 2) gridelements is not available for TYPO3 v9 (or, not yet).

Don't know if I missing something here :-/ Thanks for your help

**Comment by heuchri56** [comment]
Hello Moongazer,
I have solved this (after inspecting the css structure of the FE with browser developer tools) by including css files. 
/* avoids navbar and footer sections covering the background image */
.bg-white, .navbar-default, .navbar-default-transition,
.navbar-default-transition.navbar-transition {
  background-color: transparent !important;
}
.footer-section-meta {
  color: #2b2b2b;
  background-color: transparent;
}
.footer-section-content {
  color: #2b2b2b;
  background-color: transparent;
}

/* gets the background image (in a separate css - you can invoke different background images on pages by including different css in an ext TS template). Maybe you want to have another part with a background image - then you set the background-image for another class*/
.body-bg {
background-image: url("/fileadmin/css/images/hintergrund_gelb.jpg");
background-size: 100%;
}

Hope it helps
Best regards Christoph

**Comment by benjaminkott** [comment]
@Moongazer currently its only supported in the mentioned layouts. there are meanwhile several content elements available such as [Card Group](https://www.bootstrap-package.com/content-examples/media/card-group/) or [Icon Group](https://www.bootstrap-package.com/content-examples/media/icon-group/) as well as different menus that are supporting displaying columns of the same kind of content. In addition we´ve added some features to the RTE that allows you to split text content in multiple columns see (Example)[https://www.bootstrap-package.com/content-examples/text/rich-text/].

![image](https://user-images.githubusercontent.com/3243119/48674214-f88e1080-eb49-11e8-9713-600be883abdc.png)

If you need more structure than this - you need to choose something like Grid-Elements to achieve what you want to do.

**Comment by benjaminkott** [comment]
Closing this issue for now. If still help is necessary please feel free to open a new issue.
