### ISSUE TITLE
Change Name of Default Language

### ISSUE THREAD

**Issue by averlon** [benjaminkott/bootstrap_package#594]
### Prerequisites

* [no, using 9.5.x ] Can you reproduce the problem on TYPO3 8.7 LTS
* [yes ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package) to see if your bug or enhancement is already reported?

### Description

Language of the Default Language is shown as "Default" in FE.

### Steps to Reproduce

permanent

**Expected behavior:** [What you expected to happen]
I am looking for a way to set the Name of the Default Language. Not sure, but it might be outside of the Bootstrap Package - but where.

**Actual behavior:** [What actually happened]

Language Selection is shown as "Default English".

### Versions

9.5.x

You can get this information from executing `composer show` at the command line if your TYPO3 installation is composer based, otherwise the version number will be shown in the extension manager.

Regards
Karl-Heinz

**Comment by benjaminkott** [comment]
In TYPO3 v9 the core introduced a new module called `Sites`. You can configure each language in there also the text that should be shown in the frontend.

![image](https://user-images.githubusercontent.com/3243119/48671839-4b59cf00-eb2e-11e8-998d-df39b6019c5b.png)

**Comment by averlon** [comment]
Thanks - did not know that - works!
