### ISSUE TITLE
language menu error

### ISSUE THREAD

**Issue by heikohaensge** [benjaminkott/bootstrap_package#597]
### Prerequisites

* [YES ] Can you reproduce the problem on TYPO3 8.7 LTS
* [YES ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package) to see if your bug or enhancement is already reported?

### Description

After upgrading from Typo3 7.6.31 to Typo3 8.7.20 including upgrading bootstrap_package to version 10.0.3
there's an error in Typo3 log appearing:
Core: Error handler (FE): PHP Warning: Invalid argument supplied for foreach() in /typo3/sysext/frontend/Classes/DataProcessing/MenuProcessor.php line 440 

In the frontend the main menu is not rendered at all if switching to any language other than the default language. 

Although all migration steps were run without errors the 'Check TCA Migrations' shows an error:
TCA migrations need to be applied
Check the following list and apply needed changes.
The TCA setting 'l10n_mode' was removed in TCA pages['columns']['thumbnail']['l10n_mode']

Running the following wizard doesn't change anything:
Execute database migrations on single rows
Some row updaters have not been executed:
Migrate values in database records having "l10n_mode" either set to "exclude" or "mergeIfNotBlank"

**Comment by benjaminkott** [comment]
The issue was resolved, some record had stored some wired characters. After saving the record again in the backend everything workes as expected.
