### ISSUE TITLE
Google fonts constants are not practical

### ISSUE THREAD

**Issue by stat1x** [benjaminkott/bootstrap_package#598]
### Description

The Google Fonts are not practical. Let's say you need 2 or 3 Google Fonts in your project. The URL of the Google Fonts API will look like this : `https://fonts.googleapis.com/css?family=Noto+Sans+SC|Noto+Sans+TC:400,500|Roboto:400,500`. With the current constants it is not possible to create it. 

**Expected behavior:** 

I would suggest to have only one constant which is the URL instead of splitting it by font and weight. There would be only `page.theme.googleFont.url`.

### Versions

TYPO3 : 8.7.20
Bootstrap Package : 10.0.3

**Comment by benjaminkott** [comment]
@stat1x @Patta 

The current implementation is meant to be as easy as possible for newcomers. The reason its limited to one font is that there is more stuff to be done than simply build the string for the include.

1. Configure WebFontLoader

As you can see in the code the variable is used multiple times, the first usages are defining the url das needs to be included, the second appereance are configuring the webfontloader.

https://github.com/benjaminkott/bootstrap_package/blob/master/Configuration/TypoScript/setup.typoscript#L368-L383

2. Provide Variables to Sass / Less

To ease integration the webfont is passed is made available as variable `google-webfont` in less and sass, so its possible to select a different font in the constant editor and the css files getting recompiled to match that font.

https://github.com/benjaminkott/bootstrap_package/blob/master/Classes/Service/CompileService.php#L96-L101

3. GoogleFontCache

By default the we are caching the google webfont for 24h on the local disc. This can be disabled by setting `disableGoogleFontCaching` in the extension configuration. Please see: https://github.com/benjaminkott/bootstrap_package/blob/master/Classes/Service/GoogleFontService.php for more details on this one.

While the third one would not be affected by your suggestion the other two would be. Do you have a suggestion we can keep the functionality and improving the flexibility?

**Comment by stat1x** [comment]
Thanks for all the informations.
To keep all this two functionalities and to improve flexibility, I would suggest to parse the Google Font URL especially the `family` parameter which look like this : `Noto+Sans+SC|Noto+Sans+TC:400,500|Roboto:400,500` to get the different fonts family. The parsing is quiet easy. Once it is parsed, it is easy to add to the constants maybe with this naming strategy : google-webfont-{index}. Index goes from 1 to 3 in this example. Then in the same way add to cache and webfont loader.
What do you think about it? I can manage a PR for it if you want.

**Comment by stat1x** [comment]
Any plan to merge this?
