### ISSUE TITLE
Template on the first page differently than the others

### ISSUE THREAD

**Issue by galaxist740** [benjaminkott/bootstrap_package#605]
# Bug Report

## Prerequisites

* [x] Can you reproduce the problem on TYPO3 v8.7 LTS
* [ ] Can you reproduce the problem on TYPO3 v9.5 LTS
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package) to see if your bug or enhancement is already reported?

## Description

After update bootstrap-package to latest version on the first page "home" you can see another template, as on the rest of the website. There is only one setup and only one Typo3 template on the whole TYPO3 website.

## Steps to Reproduce

1. open the site www.kornhair.de
2. Go to another page and you will see, there is another template

**Expected behavior:** The same template all over the whole website.

**Actual behavior:** see above

## Versions

TYPO3: 8.7

**Comment by benjaminkott** [comment]
@galaxist740 please check the additional css, if I remove the following files everything looks fine again. These files are only included on the start page.

```
/typo3conf/ext/ns_all_sliders/Resources/Public/slider/owl.carousel/assets/css/bootstrapTheme.css
/typo3conf/ext/ns_all_sliders/Resources/Public/slider/owl.carousel/assets/css/custom.css
```

**Comment by galaxist740** [comment]
I would never have thought of that. 
Many Thanks.
The slider extension has a third css installed, which disturbs the mobile view. 
Now all I have to do is find out how these css are involved. For now I have only removed the contents of the files.

**Comment by benjaminkott** [comment]
@galaxist740 glad I could help, if you have any issues - feel free to open a new ticket. I am closing this for now. Good luck hunting the issue!

**Comment by benjaminkott** [comment]
@galaxist740 hat a quick look at the extension. 

As you can see here, there is no way around to change the file, you could open an issue in the repository. Or choose a different solution for this.
https://github.com/nitsan-technologies/ns_all_sliders/blob/master/Classes/Controller/OwlController.php#L65-L66
