### ISSUE TITLE
Wrong path with sitepackage for Photoswipe Lightbox Skin images

### ISSUE THREAD

**Issue by web2date** [benjaminkott/bootstrap_package#607]
# Bug Report

## Prerequisites

* [ ] Can you reproduce the problem on TYPO3 v8.7 LTS
* [x] Can you reproduce the problem on TYPO3 v9.5 LTS
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package) to see if your bug or enhancement is already reported?

## Description
With a sitepackage generated at https://www.sitepackagebuilder.com/ the path for Images of the lightbox is wrong and there is a 404 error in Console
https://www.example.com/typo3conf/ext/sitepackage/Resources/Public/Images/PhotoSwipe/default-skin.png
## Steps to Reproduce

1. Install sitepackage
2. Add several Images with "Enlarge on Click"
3. open the content in Frontend on a Desktop PC
4. open the lightbox
5. try to go forward to the next image

**Expected behavior:** 
some icons to browse to the next image

**Actual behavior:** 
nothing

## Versions

TYPO3 v.9.5.1, PHP 7.2.10 MySQL 5.7.22

**Comment by blueamerican** [comment]
try it with
config.compressCss = 1
config.concatenateCss = 1

**Comment by kimchristiansen** [comment]
With TYPO3 v11 and cms-composer-installers 4.0.x@dev the paths again seems not to be correct.
In the merged css file, the path to the default-skin is:
`../../../_assets/Public/Images/PhotoSwipe/default-skin.png`

The path of the generated css is 
`/typo3temp/assets/compressed/merged-99b4c13ee7d1dc4dec6fe7dc57c0fe12-95d5a2ea668304014ba3e35a2e217444.css?1662735771`

It seems like the generated hash path of the _assets folder is missing.
