### ISSUE TITLE
The classes .frame-ruler-before and .frame-ruler-after are missing pseudo classes used in fluid_styled_content

### ISSUE THREAD

**Issue by Outdoorsman** [benjaminkott/bootstrap_package#608]
# Bug Report

## Prerequisites

* [x] Can you reproduce the problem all the way from TYPO3 v8.0 to v9.5
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package) to see if your bug or enhancement is already reported?

## Description

When the class `.frame-ruler-after` is used it causes two borders instead of one among other things. This is also true for `.frame-ruler-before` class.

The reason? It appears that `bootstrap_package` is attempting to overriding the `.frame-ruler-before:before` and `frame-ruler-after:after` that are in the `fluid_styled_content` extension, but it does not include the pseudo class so instead of overriding it's causing duplicate CSS. Here's a sample of what what using the `frame-ruler-after` looks like on a real website. This issue goes back a ways so might be good to release fixes for the other releases of `bootstrap_package` beside just the current version 10???

![2018-12-01_19-47-55](https://user-images.githubusercontent.com/3075533/49335489-0197cc80-f5a3-11e8-89dd-dbc5a643de75.png)

## Steps to Reproduce

1. Make sure that `bootstrap_package` and `fluid_styled_content` are both installed an active.
2. Add a content element to the website and select _Ruler After_ or _Ruler Before_ from the dropdown in the _Appearances_ tab and save.

**Expected behavior:** [What you expected to happen]

There should a single border either above or below the content element based on your selection.

**Actual behavior:** [What actually happened]

There are two borders above or below based on your selection.

## Versions

You can get this information from executing `composer show` at the command line if your TYPO3 installation is composer based, otherwise the version number will be shown in the extension manager.

This conflict occurs for `bootstrap_package`:

- The file [Resources/Public/Less/Theme/frame.less](https://github.com/benjaminkott/bootstrap_package/blob/master/Resources/Public/Less/Theme/frame.less) in `bootstrap_package` v8.0.0 to v10.0.3
- The file [Resources/Public/Scss/Theme/_frame.scss](https://github.com/benjaminkott/bootstrap_package/blob/master/Resources/Public/Scss/Theme/_frame.scss) in `bootstrap_package` v10.0.0 to v10.0.3

When this file is present in `fluid_styled_content`:

- The file [Configuration/TypoScript/Styling/setup.typoscript](https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/fluid_styled_content/Configuration/TypoScript/Styling/setup.typoscript) in `fluid_styled_content` v9.3.0 to v9.5.1

**Comment by benjaminkott** [comment]
@Outdoorsman the bootstrap package is completely standalone and doe not support fluid styled content. That said, the reason we are using a different approach is that we need to ensure that our other frame features are working correctly. 

I´ve added some more examples to the frames page, please have a look:
https://www.bootstrap-package.com/content-examples/and-more/frames/

**Comment by Outdoorsman** [comment]
Ahhhh I didn't know that. I like this extension even more now :) Thanks for the info.

However, I suppose even if `fluid_styled_content` is not to be used with this extension, I would still argue that it would be good to mirror `fluid_styled_content` where possible for compatibility reasons so it doesn't cause CSS issues to reduce the vendor lock in effect. I really would like to still see this merged because it is a very subtle change that would increase compatibility. This seems like a reasonable change in my mind still???

**Comment by Outdoorsman** [comment]
I haven't done a comparison between the base CSS of these two extensions so maybe this is entirely the tip of a massive iceburg. I just know what pains we have to go through when migrating from one template to another and when down the road something is no longer supported and like make it easy as possible for migrations down the road.

**Comment by benjaminkott** [comment]
In the past we actually did the opposite. That means that fluid_styled_content get adapted from time to time to match the bootstrap_package. The rendering definitions that are now in fsc are written by me. I'll try to keep it in sync as much as possible.

**Comment by Outdoorsman** [comment]
I don't care which way the synchronization goes but that's AWESOME news! Thanks for the quick feedback. This certainly makes developing sites a lot easier.

**Comment by benjaminkott** [comment]
But since the bootstrap_package is evolving faster and has more build in features, it may diverge for a while until we decided what to adapt and what not.

**Comment by Outdoorsman** [comment]
Makes sense... I totally follow. I have been loving the direction things are going.

**Comment by benjaminkott** [comment]
@Outdoorsman I am closing this issue for now - please feel free to open a new one if you think something is wrong or should work differently.
