### ISSUE TITLE
Carousel type header: Parallax effect not working with scss

### ISSUE THREAD

**Issue by McKoy61** [benjaminkott/bootstrap_package#610]
# Bug Report

## Prerequisites

* [x] Can you reproduce the problem on TYPO3 v8.7 LTS
* [x] Can you reproduce the problem on TYPO3 v9.5 LTS
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package) to see if your bug or enhancement is already reported?

## Description

If static template Bootstrap 4.x (SCSS) is included, the carousel parallax effect do not work. Blur and color effects are working
If static template Bootstrap 3.x (LESS) is includes, everything works fine.

## Steps to Reproduce

1. Include static template Bootstrap 4.x (SCSS)
2. Set up carousel type header with background image
3. Enable parallax effect on background image

**Expected behavior:** On scrolling up and down the header should move background image should stay in fixed position
**Actual behavior:** On scrolling up and down the background images moves with the header

## Versions
typo3 9.5.1 / 8.7.20
bootstrap-package 10.0.3
PHP 7.2

**Comment by benjaminkott** [comment]
Could reproduce the bug in everything except chrome. We are using "background-attachment: fixed" to create this effect. Even its supported everywhere - we seem to have an edge case created here. Will need to investigate further to find a solution for this...

**Comment by benjaminkott** [comment]
Related Issues:
Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1292499

**Comment by benjaminkott** [comment]
Possible Solution:
```
.carousel-fade {
    .carousel-item {
        perspective: initial !important;
        transform: initial !important;
    }
}
```

Drawback:
- Slide animation will **not** support parallax effect. The root cause is also enabling the slide animation.

**Comment by McKoy61** [comment]
Thanks for the solution, I'll test it soon, in this case the fade effect is fine. By the way, Safari is behaving like chrome.
I compared carousel.less and _caousel.scss and found both using "background-attachment: fixed", so I wonder, why it works with less and not with scss. 
Thanks for your investigation, and - of course - for your great work on bootstrap_package.

**Comment by Coders-Care** [comment]
Could you provide a link to a visual use case, where a slide animation is used together with a fixed background? Currently it's hard to imagine what excactly would be the desired result.

**Comment by McKoy61** [comment]
@benjaminkott Your solution works fine, thanks!
@Coders-Care Sorry, I never used this combination. But I think, in this case fixed means vertically fixed

**Comment by Coders-Care** [comment]
OK - thanks for the demo page. Now that the behaviour has been clarified, I guess it will be fine to skip attachment fixed for slide effects, since it seems to be an edge case that is rarely used anyway.

**Comment by benjaminkott** [comment]
Was late yesterday, we still are running into a scaling issue on iPad and Android devices with parallax effect enabled. Still looking for a solution...

**Comment by McKoy61** [comment]
I found 2 articles by Keith Clark showing and discussing pure CSS parallax effects. 
- https://keithclark.co.uk/articles/pure-css-parallax-websites/
- https://keithclark.co.uk/articles/practical-css-parallax/
As far as I can see, its a different approach than using background-attachement fixed. And it provides a CSS Parallax feature detection (2nd article) to switch off parallax effects automatically in not supporting browsers. Maybe this can help to find a solution?

**Comment by benjaminkott** [comment]
@McKoy61 had a look into the examples, I've already tried out that ones because it also solves the scaling of the images on ios and android - but makes scrolling stuttering so I guess we need to find a different approach.

**Comment by benjaminkott** [comment]
@McKoy61 @Coders-Care i needed to make a decision on how to fix it.

I´ve fixed the parallax behavior in all desktop browsers for the fade variation and reset the `background-attachment: fixed;` in addition for mobile browsers. There is no existing solution for pure CSS parallax solutions that would allow smooth scrolling on iPad. Also, mobile browsers are disabling the fixed positioning to save performance on that devices. But instead, they are scaling the background image to a false size that results in a very pixelated image.

This may not be the final implementation but the best choice for now.

**Comment by McKoy61** [comment]
@benjaminkott Thanks, I agree.
