### ISSUE TITLE
Section Index

### ISSUE THREAD

**Issue by hweckhardt** [benjaminkott/bootstrap_package#611]
# Bug Report

## Prerequisites

* [ ] Can you reproduce the problem on TYPO3 v8.7 LTS
* [y ] Can you reproduce the problem on TYPO3 v9.5 LTS
* [n] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package) to see if your bug or enhancement is already reported?

## Description

Section Index shows empty line, if content element is marked as "show in index = no".

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]
Only show entries for content elements which are marked as "show in index = yes".

**Actual behavior:** [What actually happened]
See before.

## Versions
10.0.3
You can get this information from executing `composer show` at the command line if your TYPO3 installation is composer based, otherwise the version number will be shown in the extension manager.

**Comment by benjaminkott** [comment]
Please add a description of how to reproduce.
Please explain what the expected behavior should be.
Please explain what the actual behavior is.

**Comment by hweckhardt** [comment]
Expected behavior: [What you expected to happen]
Only show entries for content elements which are marked as "show in index = yes".

Actual behavior: [What actually happened]
Section Index shows empty line, if content element is marked as "show in index = no".

![image](https://user-images.githubusercontent.com/33839887/49537088-49329700-f8c8-11e8-8846-1c721d58d333.png)

**Comment by aksenovaa** [comment]
Is your item number 313 not the menu itself? And he may not have a name. Then just do not show it in the menu with sections.

**Comment by benjaminkott** [comment]
Oh, we did a patch in that area forgot about this issue. 
@hweckhardt can you check if that one is working for you? 

https://github.com/benjaminkott/bootstrap_package/commit/b47e84801e237930edc05fa8b8bb35f06796e6c4
