### ISSUE TITLE
Please update scssphp library to latest version (>= 0.7.6) because theme-color-level() calculation is wrong

### ISSUE THREAD

**Issue by Moongazer** [benjaminkott/bootstrap_package#612]
# Bug Report / Update needed

It took me hours to figure out why the theme-color-level() function in SCSS returns always too dark colors (you can see this behaviour if you use a `<div class="alert alert-success"></div>` box for example. Without any other definition in bootstrap_package, the background-color is very dark (but very light in the Bootstrap default).

The reason is a negative integer bug in scssphp v0.7.4 (see https://github.com/leafo/scssphp/issues/551)
**I replaced the library with the current v0.7.6 release and its working fine now.**

**Comment by benjaminkott** [comment]
I´ve updated the version to 0.7.7 and fixed the version file manually they are shipping this is also the latest version available via composer. Please check if everything is working as expected.

**Comment by Moongazer** [comment]
I've run a test with the current master branch and it works great. Thank you very much for the fast fix! 

Only thing what I wonder about is that the current `ext_emconf.php` file say version 10.0.0 (and not 10.0.3 from the last release). So TYPO3 shows the update-icon in the extension manager.

**Comment by benjaminkott** [comment]
Master branch is development and will raise version when the next major version is released.
All releases for the 10.x version are running in https://github.com/benjaminkott/bootstrap_package/tree/BP_10-0 - I am currently adding patches to master and then cherry pick them into the responsible branches if necessary.
