### ISSUE TITLE
Text content element after content element with background image collapses

### ISSUE THREAD

**Issue by buepro** [benjaminkott/bootstrap_package#618]
# Bug Report

## Prerequisites
* [x] Can you reproduce the problem on TYPO3 v9.5 LTS
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package) to see if your bug or enhancement is already reported?

## Description

When a text content element is placed after a content element having a background image the text content top margin collapses hence is too close to the bottom edge from the content element having the background image.

## Steps to Reproduce

1. Create content element with a background image
2. Create a text content element following the content element with the background image

**Expected behavior:** There should be a space between the two content elements

**Actual behavior:** The top margin collapses

## Versions

10.0.4

## Corrective action

Change _frame.scss from

`@mixin make-frame-spacing($name) {
    .frame-background-#{$name}.frame-space-after-none:not(.frame-ruler-after) + .frame-background-#{$name}.frame-space-before-none:not(.frame-ruler-before):not(.frame-has-backgroundimage) {
        @extend .frame-collapsible;
    }
}`

to

`@mixin make-frame-spacing($name) {
    .frame-background-#{$name}.frame-space-after-none:not(.frame-ruler-after):not(.frame-has-backgroundimage) + .frame-background-#{$name}.frame-space-before-none:not(.frame-ruler-before):not(.frame-has-backgroundimage) {
        @extend .frame-collapsible;
    }
}`

adding `:not(.frame-has-backgroundimage)` to the preceeding content element selector

**Comment by benjaminkott** [comment]
@buepro thx for the hint, I missed that one.
