### ISSUE TITLE
Bootstrap_package and Gridelements

### ISSUE THREAD

**Issue by hweckhardt** [benjaminkott/bootstrap_package#619]
# Support

Is it possible to use bootstrap_package together with the extension gridelements?

**Comment by osahner** [comment]
I found a setup that works here: http://www.typo3-probleme.de/2017/04/07/typo3-8-7-x-gridelements-typoscript-tca-und-templates-auslagern-1985/

**Comment by hweckhardt** [comment]
I have installed bootstrap_grids and tried with a 3-columns gridelement. It looks nice in backend, however in frontend the columns are not ordered horizontally, but vertically, if the extension gridelements is the last entry in the static template. When i change the sequence between gridelements and bootstrap_grids, the elements are ordered horizontally, but the bootstrap_package backend layout for this page is ignored.

**Comment by hweckhardt** [comment]
I think, the "problem" which I described before is more between bootstrap_package and gridelements, than coming from the extension bootstrap_grids, as i see the same appearance when i use bootstrap_gridelements instead and even with a new extension providing some grid elements for bootstrap named fluid_bootstrap_grids which was published today.

**Comment by benjaminkott** [comment]
@hweckhardt the grid column markup changed from bootstrap3 to bootstrap4 can you check if the bootstrap_grids extension is delivering the correct markup for version 4.x?

**Comment by benjaminkott** [comment]
@hweckhardt check if there is an update, version 2.0.0 seems to have bootstrap 4 support https://github.com/laxap/bootstrap_grids/releases/tag/2.0.0

**Comment by hweckhardt** [comment]
I installed bootstrap_grids version 2.0.0 which should support bootstrap 4 according to their documentation.

**Comment by benjaminkott** [comment]
Do you have a link to the website, would like to investigate the frontend rendering what's going on?

**Comment by hweckhardt** [comment]
http://p496683.mittwaldserver.info/index.php?id=82

**Comment by benjaminkott** [comment]
Ok, there is just no markup in the frontend, means that gridelements seem not to be rendered at all.

**Comment by hweckhardt** [comment]
@benjaminkott: Many thanks for your help. I have copied the setup from bootstrap_grids to the roottemplate, and now the gridelements are rendered (i can see col-4 ...), but their row is not vertically adjusted to the beginnung of the bootstrap_package column.

**Comment by benjaminkott** [comment]
Please Check: https://packagist.org/packages/bk2k/autogrids

**Comment by benjaminkott** [comment]
@hweckhardt please do not use it in combination with bootstrap_grids. If you need a Tab or an Accordion Content-Element there are dedicated Elements for this in the Bootstrap Package already, that are only there to solve this problem, without hacks.

**Comment by hweckhardt** [comment]
Yes, you are right. I only need some gridelements for columns, to get more flexibility in the layout of the pages, and for these elements i do not need bootstrap_grids. The real problem which I had was the integration of gridelements into boostrap_package, and this is solved with autogrids.

 

Von: Benjamin Kott [mailto:notifications@github.com] 
Gesendet: Freitag, 11. Januar 2019 10:32
An: benjaminkott/bootstrap_package
Cc: hweckhardt; Mention
Betreff: Re: [benjaminkott/bootstrap_package] Bootstrap_package and Gridelements (#619)

 

@hweckhardt <https://github.com/hweckhardt>  please do not use it in combination with bootstrap_grids. If you need a Tab or an Accordion Content-Element there are dedicated Elements for this in the Bootstrap Package already, that are only there to solve this problem, without hacks.

**Comment by benjaminkott** [comment]
I am seeing this issue as resolved. 
See: 
https://github.com/benjaminkott/autogrids
https://gitlab.com/coderscare/gridelements/merge_requests/3/commits
