### ISSUE TITLE
Allow subnavigation layout to display side menu on first page

### ISSUE THREAD

**Issue by olegsv** [benjaminkott/bootstrap_package#622]
*Feature Request*

**Is your feature request related to a problem? Please describe.**

I would like to have menu on sidebar navigation on Home page. To do that I tried to change layout to "Subnavigation Left", however the menu section was empty.

**Describe the solution you'd like**

I suggest an option to add configurable side menu on Home page using "Subnavigation Left" and similar layouts. 

In addition it may be useful to have an option to configure menu entries of the top navigation bar, as having similar menus on top and at side is not practical.

**Describe alternatives you've considered**

An alternative solution would be creating side menu using custom typoscript code.

**Additional context**

Changing page.10.dataProcessing.20.entryLevel helped to display side navigation menu on the left side on front page.

**Comment by benjaminkott** [comment]
As you described, you need to change the entryLevel. i will consider this as resolved.
