### ISSUE TITLE
LanguageMenuSlot->addSqlFields() does not exist

### ISSUE THREAD

**Issue by newsdesigner** [benjaminkott/bootstrap_package#624]
After the update from version 10.0.3 to 10.0.5 I got the error on TYPO3 v8.7.22:
**"The slot method BK2K\BootstrapPackage\Slot\LanguageMenuSlot->addSqlFields() does not exist.**
I can't recognize an error otherwise.

**Comment by benjaminkott** [comment]
The function was removed, can you please clear all caches and check if the error still exists?

**Comment by benjaminkott** [comment]
The function was removed - cache clearing should resolve the issue.
