### ISSUE TITLE
Error when using  Menu Subpages

### ISSUE THREAD

**Issue by loeffe1** [benjaminkott/bootstrap_package#631]
## Prerequisites

* [ ] Can you reproduce the problem on TYPO3 v8.7 LTS
* [X] Can you reproduce the problem on TYPO3 v9.5 LTS
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package) to see if your bug or enhancement is already reported?

## Description

I am getting this error when using the content element Menu Subpages:

> Argument 2 passed to TYPO3\CMS\Frontend\Typolink\PageLinkBuilder::populateMountPointMapForPageRecursively() must be of the type integer, string given, called in /var/www/liveweb/files/typo3_src-9.5.3/typo3/sysext/frontend/Classes/Typolink/PageLinkBuilder.php on line 612

## Versions

Tested on bootstrap_package 10.0.0

**Comment by benjaminkott** [comment]
@loeffe1 looks interesting - this one seems to be a core issue, can you reopen a new one on https://forge.typo3.org/projects/typo3cms-core/issues

I guess you are using mount points in some way?

**Comment by loeffe1** [comment]
Yes, indeed.
The bug has already been reported: https://forge.typo3.org/issues/87473#change-393736
