### ISSUE TITLE
Use tab character for indent in *.html files

### ISSUE THREAD

**Issue by stat1x** [benjaminkott/bootstrap_package#634]
Hi,
Is there any reason why you are using 4 spaces to indent html files?
As far as I know the TYPO3 community uses tab (see https://github.com/TYPO3/TYPO3.CMS/blob/44f445492495b8d1cc7f9950358821311241815a/.editorconfig#L18)
Thanks,
Jay

**Comment by benjaminkott** [comment]
FYI: https://review.typo3.org/#/c/57340/

**Comment by benjaminkott** [comment]
Closing this for now, if you have any additional questions on this one - just ping me.

**Comment by stat1x** [comment]
> FYI: https://review.typo3.org/#/c/57340/

Ok good to know! Thanks!
