### ISSUE TITLE
Slider: Link to startpage

### ISSUE THREAD

**Issue by SventB** [benjaminkott/bootstrap_package#64]
The prev and next link of the slider is a link to the startpage, e.g. 
<pre>&lt;a class="left carousel-control" href="#carousel-170" data-slide="prev"></pre>
On click it does not link to startpage, sure, because JavaScript prevents that, but for crawler bots or with deactivated JavaScript it links to the startpage.

The href attribute should contain the url of the current page, e.g.
<pre>&lt;a class="left carousel-control" href="my-carousel-page.html#carousel-170" data-slide="prev"></pre>

Or you could disable base url (see #54), then it will be ok ;)

The "skip to content" link (see #63) will also not work with a base url. I have to write a solution in TypoScript instead of a simple f:link.page in Fluid.

**Comment by benjaminkott** [comment]
solved in https://github.com/benjaminkott/bootstrap_package/commit/61a3fc8535880967980f9b44216fd4fd40309d1b
