### ISSUE TITLE
Subpages on www.bootstrap-package.com not available

### ISSUE THREAD

**Issue by AlexKvrlp** [benjaminkott/bootstrap_package#642]
All Subpages on www.bootstrap-package.com are not available (Error 404).

Example:
-https://www.bootstrap-package.com/de/features
-https://www.bootstrap-package.com/de/pages
-https://www.bootstrap-package.com/de/content-examples/interactive/accordion

**Comment by benjaminkott** [comment]
This one is related to a core issue we are currently working on since not all content is translated.
See: https://forge.typo3.org/issues/86762

For now please use the English version of the website.

**Comment by benjaminkott** [comment]
Update on TYPO3 9.5.5 resolved the issue.
