### ISSUE TITLE
Feature request: add more ratios for external videos and images (e.g. 21:9)

### ISSUE THREAD

**Issue by osahner** [benjaminkott/bootstrap_package#644]
especially 21:9 is a nice ratio

**Comment by Moongazer** [comment]
I think the provided basic ratios are enough to not overfill this extension. If you need more or different ratios, its quite easy by creating a TCA Overwrite and add them to `$defaultCropSettings['allowedAspectRatios']` and `$GLOBALS['TCA']['tt_content']` for the elements where you need it (see `500_cropping.php` file as example). Or is it not what you mean?

**Comment by osahner** [comment]
@Moongazer yes sure, but it feels like a hack somehow. And 21:9 is the new 16:10 ;) 
Of course I can live with that solution!

**Comment by gilbertsoft** [comment]
Looking at the product counts of my distributor I have to agree:

![grafik](https://user-images.githubusercontent.com/25326036/70275917-6df96d00-17af-11ea-970d-46d259cd8c2e.png)

@osahner And btw providing new ratios is not a hack, that's the way of doing it and we do nothing else.

**Comment by benjaminkott** [comment]
I think we are fine with ratios, you can extend them if needed.
