### ISSUE TITLE
View/download PDF files

### ISSUE THREAD

**Issue by hweckhardt** [benjaminkott/bootstrap_package#647]
# Bug Report
Text & Media Element as PDF file is not shown in Frontend.

## Prerequisites
 [ ] Can you reproduce the problem on TYPO3 v8.7 LTS
* [x ] Can you reproduce the problem TYPO3 v9.5 LTS
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package) to see if your bug or enhancement is already reported?

## Description

I have added a Content Element as Text & Media with a PDF file as Media. The thumbnail is shown in the backend, however the file (picture) is not shown in the frontend. In backend, under "Image manipulation" a message (field with blue background) is displayed, saying "No image dimensions could be determined.". I am using Typo3 9.5.4 and bootstrap_package 10.0.4.
In a Typo3 installation without bootstrap_package this works like expected.

## Steps to Reproduce

1. [First Step]
Add a PDF file as Text & Media to a page. The thumbnail of the PDF file is displayed in the backend.

2. [Second Step]
Display the page in frontend.

**Expected behavior:** [What you expected to happen]

The first page of the PDF file should be displayed, together with navigation symbols in the top-right corner of the screen (download, print). A scroll bar on the right side appears, and it is possible to scroll down the PDF file.

**Actual behavior:** [What actually happened]
Only the header of the Text&Media element is displayed.

## Versions
Typo3 9.5.4
bootstrap_package 10.0.4

You can get this information from executing `composer show` at the command line if your TYPO3 installation is composer based, otherwise the version number will be shown in the extension manager.

**Comment by metiny** [comment]
You have to expand the file:

typo3conf/ext/bootstrap_package/Resources/Private/Partials/ContentElements/Media/Type.html

You need a new case for PDF files (Typ 5):

<f:case value="5">
        <f:render partial="Media/Type/Image" arguments="{file: file, data: data, settings: settings, variants: variants}" />
    </f:case>

You can copy the file in your sitepackage and expand

**Comment by metiny** [comment]
#277

**Comment by metiny** [comment]
#277

**Comment by metiny** [comment]
#277

**Comment by hweckhardt** [comment]
I have the new case for PDF files (Type 5) to the partials file „ContentElements/Media/Type.html“ and it works perfect. Many thanks for your help!

 

Von: Metin Yilmaz [mailto:notifications@github.com] 
Gesendet: Dienstag, 19. März 2019 01:22
An: benjaminkott/bootstrap_package
Cc: hweckhardt; Author
Betreff: Re: [benjaminkott/bootstrap_package] View/download PDF files (#647)

 

You have to expand the file:

typo3conf/ext/bootstrap_package/Resources/Private/Partials/ContentElements/Media/Type.html

You need a new case for PDF files (Typ 5):

<f:case value="5">
<f:render partial="Media/Type/Image" arguments="{file: file, data: data, settings: settings, variants: variants}" />
</f:case>

You can copy the file in your sitepackage and expand
