### ISSUE TITLE
More mainavigation levels with v10.0.5

### ISSUE THREAD

**Issue by Tonyt8** [benjaminkott/bootstrap_package#649]
# Support

**Is your question related to a problem? Please describe.**
Hi,
Bootstrap version 10.0.05
Typo3 9.5.4
I need more main navigation levels, up to 4 levels. I have been following some tut's over the last days, looking at past examples and other information, but I cannot make a working main navigation beyond the included 2 levels.
So far I can produce one more level, but I cannot figure out how to add the extra class "show"
to the new list (ul) item to display the 3rd level. Without this class I cannot get any further.
How is the "Show class added"?
This there a main navigation script available which can add the extra levels?
I'm sure there are other users like myself (I'm webmaster, with some scripting know-how) who would also really benefit having extra navigation levels.
Thanks.

Regards,
Tony

**Comment by Tonyt8** [comment]
Hi,
I have tried further. 
I have made some progress with my navigation "main.html" template. 

Perhaps someone can help me the following 2 points
I find when in a desktop view a parent link needs to be click twice before the link will work.
Also a empty third level fly-out appears even when there is no links in it how do I stop this happening.
Thanks
Regards,
Tony
+++++++++++++++++++++++++++++++++++++++++++++++++++
<html xmlns:f="http://typo3.org/ns/TYPO3/CMS/Fluid/ViewHelpers" xmlns:bk2k="http://typo3.org/ns/BK2K/BootstrapPackage/ViewHelpers" data-namespace-typo3-fluid="true">

<header id="page-header" class="bp-page-header navbar navbar-mainnavigation navbar-{theme.navigation.style}{f:if(condition:settings.logo.file,then:' navbar-has-image')}{f:if(condition:theme.navigation.type, else:' navbar-top', then:' navbar-{theme.navigation.type} navbar-fixed-{theme.navigation.type}')}">
    <div class="container">
        <f:if condition="{settings.logo.file}">
            <f:then>
                <f:link.page pageUid="{rootPage}" class="navbar-brand navbar-brand-image" title="{settings.logo.linktitle}">
                    <img class="navbar-brand-logo-normal" src="{f:uri.image(src: settings.logo.file)}" alt="{logoAlt}" height="{settings.logo.height}" width="{settings.logo.width}">
                    <img class="navbar-brand-logo-inverted" src="{f:uri.image(src: settings.logo.fileInverted)}" alt="{logoAlt}" height="{settings.logo.height}" width="{settings.logo.width}">
                </f:link.page>
            </f:then>
            <f:else>
                <f:link.page pageUid="{rootPage}" class="navbar-brand navbar-brand-text" title="{settings.logo.linktitle}">{siteTitle}</f:link.page>
            </f:else>
        </f:if>
        <f:if condition="{mainnavigation}">
            <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#mainnavigation" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <nav id="mainnavigation" class="collapse navbar-collapse">
                <f:render partial="DropIn/Navigation/MainBefore" arguments="{_all}" />
                <f:render section="MainNavigation" arguments="{menu: mainnavigation, theme: theme}" />
                <f:render partial="DropIn/Navigation/MainAfter" arguments="{_all}" />
            </nav>
        </f:if>
    </div>
</header>

<f:section name="MainNavigation">
    <f:if condition="{menu}">
        <ul class="navbar-nav">1
            <f:for each="{menu}" as="item">
                <f:if condition="{item.spacer}">
                    <f:then>
                        </ul>
                        <ul class="navbar-nav">
                    </f:then>
                    <f:else>
                        <li class="nav-item{f:if(condition: item.active, then:' active')}{f:if(condition: item.children, then:' dropdown dropdown-hover')}">
                            <a href="{item.link}" id="nav-item-{item.data.uid}" class="nav-link{f:if(condition: item.children, then:' dropdown-toggle')}" {f:if(condition: item.target, then: ' target="{item.target}"')} title="{item.title}"{f:if(condition: item.children, then:' aria-haspopup="true" aria-expanded="false"')}>
                                <f:if condition="{theme.navigation.icon.enable} && {item.icon}">
                                    <span class="nav-link-icon">
                                        <f:if condition="{item.icon.0.extension} === svg">
                                            <f:then>
                                               aaaa <bk2k:inlineSvg image="{item.icon.0}" width="{theme.navigation.icon.width}" height="{theme.navigation.icon.height}" />
                                            </f:then>
                                            <f:else>
                                              sssss  <f:image image="{item.icon.0}" alt="{item.icon.0.alternative}" title="{item.icon.0.title}" width="{theme.navigation.icon.width}" height="{theme.navigation.icon.height}" />
                                            </f:else>
                                        </f:if>
                                    </span>
                                </f:if>
                                <span class="nav-link-text">{item.title}<f:if condition="{item.current}"> <span class="sr-only">(current)</span></f:if></span>
                            </a>
                            <f:if condition="{item.children}">
                                <ul class="dropdown-menu" aria-labelledby="nav-item-{item.data.uid}">2
                                    <f:for each="{item.children}" as="child">
                                        <f:if condition="{child.spacer}">
                                            <f:then>
                                                <li class="dropdown-divider"></li>
                                            </f:then>
                                            <f:else>
                                                <li class="nav-item{f:if(condition: item.active, then:' active')}{f:if(condition: item.children, then:' dropdown dropdown-hover')}">
                                                    <a href="{child.link}" class="nav-link{f:if(condition: item.children, then:' dropdown-toggle')}"{f:if(condition: child.target, then: ' target="{child.target}"')} title="{child.title}">
                                                       <f:if condition="{theme.navigation.icon.enable} && {item.icon}">
                                    <span class="nav-link-icon">
                                        <f:if condition="{item.icon.0.extension} === svg">
                                            <f:then>
                                                <bk2k:inlineSvg image="{item.icon.0}" width="{theme.navigation.icon.width}" height="{theme.navigation.icon.height}" />
                                            </f:then>
                                            <f:else>
                                                <f:image image="{item.icon.0}" alt="{item.icon.0.alternative}" title="{item.icon.0.title}" width="{theme.navigation.icon.width}" height="{theme.navigation.icon.height}" />
                                            </f:else>
                                        </f:if>
                                    </span>
                                </f:if>
                                                        <span class="dropdown-text">{child.title}<f:if condition="{child.current}"> <span class="sr-only">(current)</span></f:if></span>
                                                    </a>
                                                    <f:if condition="{item.children}">
                                                        
                                                       <ul class="level-3 dropdown-menu {f:if(condition: child.active, then:' show')}" aria-labelledby="nav-item-{child.data.uid}">
                                                           <f:for each="{child.children}" as="child">
                                                           <li><a href="{child.link}" class="dropdown-item{f:if(condition: child.active, then:' active')}"{f:if(condition: child.target, then: ' target="{child.target}"')} title="{child.title}">
                                                               
                                                               <f:if condition="{theme.navigation.dropdown.icon.enable} && {child.icon}">
                                                            <span class="dropdown-icon">
                                                                <f:if condition="{child.icon.0.extension} === svg">
                                                                    <f:then>
                                                                        <bk2k:inlineSvg image="{child.icon.0}" width="{theme.navigation.dropdown.icon.width}" height="{theme.navigation.dropdown.icon.height}" />
                                                                    </f:then>
                                                                    <f:else>
                                                                        <f:image image="{child.icon.0}" alt="{child.icon.0.alternative}" title="{child.icon.0.title}" width="{theme.navigation.dropdown.icon.width}" height="{theme.navigation.dropdown.icon.height}" />
                                                                    </f:else>
                                                                </f:if>
                                                            </span>
                                                        </f:if>
                                                               <span class="dropdown-text">{child.title}<f:if condition="{child.current}"> <span class="sr-only">(current)</span></f:if></span>
                                                               </a>
                                                               
                                                              xxxx
                                                               <f:if condition="{item.children}">
                                                        
                                                       <ul class="level-4 dropdown-menu {f:if(condition: child.active, then:' show')}" aria-labelledby="nav-item-{child.data.uid}">3
                                                           <f:for each="{child.children}" as="child">
                                                           <li><a href="{child.link}" class="dropdown-item{f:if(condition: child.active, then:' active')}"{f:if(condition: child.target, then: ' target="{child.target}"')} title="{child.title}">
                                                               
                                                               <f:if condition="{theme.navigation.dropdown.icon.enable} && {child.icon}">
                                                            <span class="dropdown-icon">
                                                                <f:if condition="{child.icon.0.extension} === svg">
                                                                    <f:then>
                                                                        <bk2k:inlineSvg image="{child.icon.0}" width="{theme.navigation.dropdown.icon.width}" height="{theme.navigation.dropdown.icon.height}" />
                                                                    </f:then>
                                                                    <f:else>
                                                                        <f:image image="{child.icon.0}" alt="{child.icon.0.alternative}" title="{child.icon.0.title}" width="{theme.navigation.dropdown.icon.width}" height="{theme.navigation.dropdown.icon.height}" />
                                                                    </f:else>
                                                                </f:if>
                                                            </span>
                                                        </f:if>
                                                               <span class="dropdown-text">{child.title}<f:if condition="{child.current}"> <span class="sr-only">(current)</span></f:if></span>
                                                               </a>
                                                               
                                                              
                                                         
                                                               
                                                               
                                                               </li>
                                                               
                                                           </f:for>
                                                        </ul>
                                                        
                                                    </f:if>
                                                         
                                                               
                                                               
                                                               </li>
                                                               
                                                           </f:for>
                                                        </ul>
                                                        
                                                    </f:if>
                                                </li>
                                            </f:else>
                                        </f:if>
                                    </f:for>
                                </ul>
                            </f:if>
                        </li>
                    </f:else>
                </f:if>
            </f:for>
        </ul>
    </f:if>
</f:section>
</html>

+++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by amr-webdesign** [comment]
Same probleme here. The subnavigation menu is working fine in desktop view.  But subnavigation menu is not displayed at phone view. So everything down below 2second level is not to see.
Searching the whole web for a solution for the 10.5 package.
Is there anyone who is a step forward to help and discribe ?

**Comment by roki18** [comment]
Hi tonyt8,

first: please apologize my english...

I use typo3 8.7.17 and Bootstrap 10.0.6. I have more levels in the subnavigation in desktop and phone view. I inserted in setup the line:
page.10.dataProcessing.10.levels = 5

and have changed main.html (see below).

Perhaps you can use and modify this.

Kind regards

roki

-----------------------------------------------
<html xmlns:f="http://typo3.org/ns/TYPO3/CMS/Fluid/ViewHelpers" xmlns:bk2k="http://typo3.org/ns/BK2K/BootstrapPackage/ViewHelpers" data-namespace-typo3-fluid="true">

<header id="page-header" class="bp-page-header navbar navbar-mainnavigation navbar-{theme.navigation.style}{f:if(condition:settings.logo.file,then:' navbar-has-image')}{f:if(condition:theme.navigation.type, else:' navbar-top', then:' navbar-{theme.navigation.type} navbar-fixed-{theme.navigation.type}')}">
    <div class="container">
        <f:if condition="{settings.logo.file}">
            <f:then>
                <f:link.page pageUid="{rootPage}" class="navbar-brand navbar-brand-image" title="{settings.logo.linktitle}">
                    <img class="navbar-brand-logo-normal" src="{f:uri.image(src: settings.logo.file)}" alt="{logoAlt}" height="{settings.logo.height}" width="{settings.logo.width}">
                    <img class="navbar-brand-logo-inverted" src="{f:uri.image(src: settings.logo.fileInverted)}" alt="{logoAlt}" height="{settings.logo.height}" width="{settings.logo.width}">
                </f:link.page>
            </f:then>
            <f:else>
                <f:link.page pageUid="{rootPage}" class="navbar-brand navbar-brand-text" title="{settings.logo.linktitle}">{siteTitle}</f:link.page>
            </f:else>
        </f:if>
        <f:if condition="{mainnavigation}">
            <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#mainnavigation" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <nav id="mainnavigation" class="collapse navbar-collapse">
                <f:render partial="DropIn/Navigation/MainBefore" arguments="{_all}" />
                <f:render section="MainNavigation" arguments="{menu: mainnavigation, theme: theme}" />
                <f:render partial="DropIn/Navigation/MainAfter" arguments="{_all}" />
            </nav>
        </f:if>
    </div>
</header>

<f:if condition="{mainnavigation}">
<nav class="navbar-collapse collapse" role="navigation">
  <ul class="nav navbar-nav navbar-main">
   <f:for each="{mainnavigationlala}" as="mainnavigationItem">
    <li class="{f:if(condition: mainnavigationItem.active, then:'active')} {f:if(condition: mainnavigationItem.children, then:'dropdown')}">
     <f:if condition="{mainnavigationItem.spacer}">
      <f:then>
       <p class="navbar-text">{mainnavigationItem.title}</p>
      </f:then>
      <f:else>
       <f:if condition="{mainnavigationItem.children}">
        <f:then>
         <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
         <span>{mainnavigationItem.title}</span>
         <b class="caret"></b>
         <span class="bar"></span>
         </a>
         <ul class="dropdown-menu">
         <f:for each="{mainnavigationItem.children}" as="child">
          <li class="{f:if(condition: child.active, then:'active')} {f:if(condition: child.children, then:'dropdown')}">
          <f:if condition="{child.spacer}">
           <f:then>
            <p class="navbar-text">{child.title}</p>
           </f:then>
           <f:else>
            <f:if condition="{child.children}">
             <f:then>             
              <span>{mainnavigationItem.title}</span>
              <b class="caret"></b>
              <span class="bar"></span>
              <ul>
               <f:for each="{child.children}" as="grandchild">
                <f:if condition="{grandchild.spacer}">
                <f:then>
                 <p class="navbar-text">{grandchild.title}</p>
                </f:then>
                <f:else>
                 <a href="/{grandchild.link}" target="{grandchild.target}" title="{grandchild.title}">
                 <span>{grandchild.title}</span>
                 <span class="bar"></span>
                 </a>
                </f:else>
                </f:if>
               </f:for>
              </ul>
             </f:then>
             <f:else>
              <a href="/{child.link}" target="{child.target}" title="{child.title}">
              <span>{child.title}</span>
              <span class="bar"></span>
              </a>
             </f:else>
            </f:if>
           </f:else>
          </f:if>
         </f:for>
         </ul>
        </f:then>
        <f:else>
         <a href="/{mainnavigationItem.link}" target="{mainnavigationItem.target}" title="{mainnavigationItem.title}">
          <span>{mainnavigationItem.title}</span>
          <span class="bar"></span>
         </a>
        </f:else>
       </f:if>
      </f:else>
     </f:if>
    </li>
   </f:for>
  </ul>
</nav>
</f:if>


<f:section name="MainNavigation">
    <f:if condition="{menu}">
        <ul class="navbar-nav">
            <f:for each="{menu}" as="item">
                <f:if condition="{item.spacer}">
                    <f:then>
                        </ul>
                        <ul class="navbar-nav">
                    </f:then>
                    <f:else>
                        <li class="nav-item{f:if(condition: item.active, then:' active')}{f:if(condition: item.children, then:' dropdown dropdown-hover')}">
                            <a href="{item.link}" id="nav-item-{item.data.uid}" class="nav-link{f:if(condition: item.children, then:' dropdown-toggle')}"{f:if(condition: item.target, then: ' target="{item.target}"')} title="{item.title}"{f:if(condition: item.children, then:' aria-haspopup="true" aria-expanded="false"')}>
                                <f:if condition="{theme.navigation.icon.enable} && {item.icon}">
                                    <span class="nav-link-icon">
                                        <f:if condition="{item.icon.0.extension} === svg">
                                            <f:then>
                                                <bk2k:inlineSvg image="{item.icon.0}" width="{theme.navigation.icon.width}" height="{theme.navigation.icon.height}" />
                                            </f:then>
                                            <f:else>
                                                <f:image image="{item.icon.0}" alt="{item.icon.0.alternative}" title="{item.icon.0.title}" width="{theme.navigation.icon.width}" height="{theme.navigation.icon.height}" />
                                            </f:else>
                                        </f:if>
                                    </span>
                                </f:if>
                                <span class="nav-link-text">{item.title}<f:if condition="{item.current}"> <span class="sr-only">(current)</span></f:if></span>
                            </a>

                            <f:if condition="{item.children}">
                                <ul class="dropdown-menu" aria-labelledby="nav-item-{item.data.uid}">
                                    <f:for each="{item.children}" as="child">
                                        <f:if condition="{child.spacer}">
                                            <f:then>
                                                <li class="dropdown-divider"></li>
                                            </f:then>
                                            <f:else>
                                                <li>
                                                    <a href="{child.link}" class="dropdown-item{f:if(condition: child.active, then:' active')}"{f:if(condition: child.target, then: ' target="{child.target}"')} title="{child.title}">
                                                        <f:if condition="{theme.navigation.dropdown.icon.enable} && {child.icon}">
                                                            <span class="dropdown-icon">
                                                                <f:if condition="{child.icon.0.extension} === svg">
                                                                    <f:then>
                                                                        <bk2k:inlineSvg image="{child.icon.0}" width="{theme.navigation.dropdown.icon.width}" height="{theme.navigation.dropdown.icon.height}" />
                                                                    </f:then>
                                                                    <f:else>
                                                                        <f:image image="{child.icon.0}" alt="{child.icon.0.alternative}" title="{child.icon.0.title}" width="{theme.navigation.dropdown.icon.width}" height="{theme.navigation.dropdown.icon.height}" />
                                                                    </f:else>
                                                                </f:if>
                                                            </span>
                                                        </f:if>
                                                        <span class="dropdown-text">{child.title}<f:if condition="{child.current}"> <span class="sr-only">(current)</span></f:if></span>
                                                    </a>
                                                </li>


<f:if condition="{child.children}">


 	<ul class="level-3 dropdown-menue {f:if(condition: child.children.active, then:' show')}" aria-labelledby="nav-item-{item.data.uid}"> 
		<f:for each="{child.children}" as="child2">
			<f:if condition="{child2.spacer}">
				<f:then>
					<li class="dropdown-divider"></li>
				</f:then>
				<f:else>
					<li>
						<a href="{child2.link}" class="dropdown-item{f:if(condition: child2.active, then:' active')}"{f:if(condition: child2.target, then: ' target="{child2.target}"')} title="{child2.title}">
							<f:if condition="{theme.navigation.dropdown.icon.enable} && {child2.icon}">
								<span class="dropdown-icon">
									<f:if condition="{child2.icon.0.extension} === svg">
										<f:then>
											<bk2k:inlineSvg image="{child2.icon.0}" width="{theme.navigation.dropdown.icon.width}" height="{theme.navigation.dropdown.icon.height}" />
										</f:then>
										<f:else>
											<f:image image="{child2.icon.0}" alt="{child2.icon.0.alternative}" title="{child2.icon.0.title}" width="{theme.navigation.dropdown.icon.width}" height="{theme.navigation.dropdown.icon.height}" />
										</f:else>
									</f:if>
								</span>
							</f:if>
							<span class="dropdown-text">{child2.title}<f:if condition="{child2.current}"> <span class="sr-only">(current)</span></f:if></span>
						</a>
					</li>



<f:if condition="{child2.children}">

 	<ul class="level-4 dropdown-menue " aria-labelledby="nav-item-{item.data.uid}"> 
		<f:for each="{child2.children}" as="child3">
			<f:if condition="{child3.spacer}">
				<f:then>
					<li class="dropdown-divider"></li>
				</f:then>
				<f:else>
					<li>
						<a href="{child3.link}" class="dropdown-item{f:if(condition: child3.active, then:' active')}"{f:if(condition: child3.target, then: ' target="{child3.target}"')} title="{child3.title}">
							<f:if condition="{theme.navigation.dropdown.icon.enable} && {child3.icon}">
								<span class="dropdown-icon">
									<f:if condition="{child3.icon.0.extension} === svg">
										<f:then>
											<bk2k:inlineSvg image="{child3.icon.0}" width="{theme.navigation.dropdown.icon.width}" height="{theme.navigation.dropdown.icon.height}" />
										</f:then>
										<f:else>
											<f:image image="{child3.icon.0}" alt="{child3.icon.0.alternative}" title="{child3.icon.0.title}" width="{theme.navigation.dropdown.icon.width}" height="{theme.navigation.dropdown.icon.height}" />
										</f:else>
									</f:if>
								</span>
							</f:if>
							<span class="dropdown-text">{child3.title}<f:if condition="{child3.current}"> <span class="sr-only">(current)</span></f:if></span>
						</a>
					</li>


<f:if condition="{child3.children}">

 	<ul class="level-5 dropdown-menue " aria-labelledby="nav-item-{item.data.uid}"> 
		<f:for each="{child3.children}" as="child4">
			<f:if condition="{child4.spacer}">
				<f:then>
					<li class="dropdown-divider"></li>
				</f:then>
				<f:else>
					<li>
						<a href="{child4.link}" class="dropdown-item{f:if(condition: child4.active, then:' active')}"{f:if(condition: child4.target, then: ' target="{child4.target}"')} title="{child4.title}">
							<f:if condition="{theme.navigation.dropdown.icon.enable} && {child4.icon}">
								<span class="dropdown-icon">
									<f:if condition="{child4.icon.0.extension} === svg">
										<f:then>
											<bk2k:inlineSvg image="{child4.icon.0}" width="{theme.navigation.dropdown.icon.width}" height="{theme.navigation.dropdown.icon.height}" />
										</f:then>
										<f:else>
											<f:image image="{child4.icon.0}" alt="{child4.icon.0.alternative}" title="{child4.icon.0.title}" width="{theme.navigation.dropdown.icon.width}" height="{theme.navigation.dropdown.icon.height}" />
										</f:else>
									</f:if>
								</span>
							</f:if>
							<span class="dropdown-text">{child4.title}<f:if condition="{child4.current}"> <span class="sr-only">(current)</span></f:if></span>
						</a>
					</li>
				</f:else>
			</f:if>
		</f:for>
	</ul>
</f:if>




				</f:else>
			</f:if>
		</f:for>
	</ul>
</f:if>






				</f:else>
			</f:if>
		</f:for>
	</ul>
</f:if>



                                            </f:else>
                                        </f:if>
                                    </f:for>
                                </ul>
                            </f:if>
                        </li>
                    </f:else>
                </f:if>
            </f:for>
        </ul>
    </f:if>
</f:section>



</html>

-----------------------------------------------

**Comment by amr-webdesign** [comment]
I tried to do your changes,but
 Uncaught TYPO3 Exception
#1238169398: Fluid parse error in template partial_Navigation/Main_d41be2b69b8a2895023616fdffabed294b059411, line 84 at character 2. Error: Not all tags were closed! (error code 1238169398). Template source chunk: </f:if> (More information)

TYPO3Fluid\Fluid\Core\Parser\Exception thrown in file
/var/www/vhosts/suerth-marktplatz.de/httpdocs/neu/vendor/typo3fluid/fluid/src/Core/Parser/TemplateParser.php in line 157.

Maybe you could give the main.html changes as a complete source code to compare

**Comment by amr-webdesign** [comment]
Thanks I worked it out again and now I got the levels 👍

**Comment by gilas1959** [comment]
hi all
thank you for your precious work. Unfortunately here the code is really a totally mess. Could you provide or publish the whole code within a (html) box so I can copy it and try it?!?
thank you very much

**Comment by amr-webdesign** [comment]
Sorry, I deleted my trys in the original bootstrap_package in case of following updates, cause I think, more than one level is not wanted by developers, or nit state of the art. I did the menue and changes in an own sitepackage by https://www.sitepackagebuilder.com/ and for me now it works:-)

**Comment by roki18** [comment]
Hi gilas1959,

you're right. 

I've updated my comment above with a download link to a txt-file.

Kind regards

roki

**Comment by benjaminkott** [comment]
Please see for newer versions: https://github.com/benjaminkott/bootstrap_package/commit/2775146d21660b1c09bbd9ab093672bfdad326bc
