### ISSUE TITLE
Can't access to page ending with `rc` when using generated .htaccess

### ISSUE THREAD

**Issue by wtfred** [benjaminkott/bootstrap_package#652]
# Bug Report

## Prerequisites

* [x] Can you reproduce the problem on TYPO3 v9.5 LTS
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package) to see if your bug or enhancement is already reported?

## Description

Any slug ending with `rc` cause 403 when .htaccess was generated by bootstrap_package

## Steps to Reproduce

1. Have bootstrap_package generate .htaccess
2. Name a page `randomrc` or just rename the slug of an existing page to make it end with `rc`
3. Try to access to the page using the slug

**Expected behavior:** Page display

**Actual behavior:** Error 403

Problem comes from lines https://github.com/benjaminkott/bootstrap_package/blob/master/Configuration/Server/_.htaccess#L315 and https://github.com/benjaminkott/bootstrap_package/blob/master/Configuration/Server/_.htaccess#L323, maybe should end with `(?:~|\.rc))$#">` instead of `(?:~|rc))$#">`
(Thanks to Mathias Brodala for pointing me the cause!)

**Comment by benjaminkott** [comment]
@wtfred thx for pointing this out, i´ve double checked this with the typo3 configuration file and it seems that this one also hat the same problem. 

https://github.com/TYPO3/TYPO3.CMS/blame/f9ea59ca7275b4dbfa8b118fc3e5e44c65b90547/typo3/sysext/install/Resources/Private/FolderStructureTemplateFiles/root-htaccess#L323

@mbrodala do you think we also need to change it there?

**Comment by benjaminkott** [comment]
was added here https://github.com/TYPO3/TYPO3.CMS/commit/edd2a1c53e038d81f28fad05cd606d6dd040c93d

**Comment by mbrodala** [comment]
Yes, the `.htaccess` of TYPO3 should be adjusted to cover [`.rc` (thus file resources)](https://fileinfo.com/extension/rc) instead of `rc`.

**Comment by lolli42** [comment]
I created core patch https://forge.typo3.org/issues/87783 to deal with this. If this has been decided and a merge has happened, we may afterwards put that into BP_8-0 branch of bootstrap package to Configuration/Apache/.htaccess. Other BP branches are not affected since bootstrap package branch v8 only creates that file on its own, in v9 and v10 this is done by core.

**Comment by benjaminkott** [comment]
thx @lolli42 applied the patch also here and voted the one on core, will backport them later to the branches.
