### ISSUE TITLE
Fatal error (memory exhausted) if "timeline" content element should be translated

### ISSUE THREAD

**Issue by Moongazer** [benjaminkott/bootstrap_package#653]
# Bug Report
I've created a timeline element with some items in the default language. If I try to translate this element into the second language, the backend runs into a memory exhausted error on different Doctrine files:

> Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /home/workspace/htdocs/libraries/typo3_src-9.5.4/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/...

I used the new Site module for the language setup/configuration. Because there is no stracktrace I've no idea how to track down this issue to give a better clue or how to fix it (also I'm not familiar with the new translation handling in TYPO3 yet).

**Edit 1:**
The error occurs only if at least one `tx_bootstrappackage_timeline_item` is added. With no such item the translation record of the main timeline content element is created successfully.

**Edit 2:**
I just tested the translation of another element which has sub-items (the Accordeon) and its working well. So it might be only an issue for the timeline.

## Versions
* TYPO3 version: 9.5.4
* bootstrap_package version: 10.0.5
* Is your TYPO3 installation set up with Composer (Composer Mode): no
* OS: Ubuntu 18
* PHP: 7.2

**Comment by jackermann** [comment]
I have the same problem, can not translate timeline...

**Comment by Lefaux** [comment]
Can you give us some information about the amount of timeline elements?
We're trying to reproduce the error so having that info would be great.

**Comment by Moongazer** [comment]
> Can you give us some information about the amount of timeline elements?

Sorry for the late response. In my case I've 7 timeline elements. The default language is set to German and I try to translate to English (Issue also occurs in TYPO3 v9.5.6). Let me know if I can help anyhow.

**Comment by osahner** [comment]
Same here. Even with a memory_limit of 512 MB and only 13 entries:

`Got error 'PHP message: PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 16384 bytes)`

* TYPO3 version: 9.5.8
* bootstrap_package version: 11.0.0
* Is your TYPO3 installation set up with Composer (Composer Mode): no
* OS: Ubuntu 18
* PHP: 7.2

**Comment by Moongazer** [comment]
Amazing, thanks for the fix! I'd never ever guessed that the issue was related with the label text! Huge respect for figuring this out ;-)
