### ISSUE TITLE
Import Demo page

### ISSUE THREAD

**Issue by benhartwich** [benjaminkott/bootstrap_package#654]
# Support

Hi,

is it possible to get an import file from https://www.bootstrap-package.com/ for having a page ready with "demo" content? So I would like to start with the same structure, content and elements from your site, because I don´t know how to insert the header with navigation.

Regards,

**Comment by benjaminkott** [comment]
@benhartwich we got the introduction distribution packaged and available as SQL dump if that may help you. The structure is nearly identical you can find it here: https://introduction.bootstrap-package.com/

Source Code here:
https://github.com/benjaminkott/site-introduction

**Comment by benhartwich** [comment]
@benjaminkott Thanks! My typo3 runs on a server already. Is there any way to import this introduction template to an existing typo3 (blank) install?

**Comment by benjaminkott** [comment]
@benhartwich probably the easiest way is to install the "introduction" extension. You just need to install it once, then you can remove it again. It imports that content to your database and is preconfigured to work with the bootstrap package.

**Comment by benhartwich** [comment]
@benjaminkott Thanks, do you mean this extension: https://extensions.typo3.org/extension/introduction/

**Comment by benjaminkott** [comment]
@benhartwich yes ;)

**Comment by benjaminkott** [comment]
I am closing this issue for now, please open a new one if you have any additional questions.
