### ISSUE TITLE
Images for "Cards" or "Cards of subpages" are not created or refreshed (if changed)

### ISSUE THREAD

**Issue by zeichensatz** [benjaminkott/bootstrap_package#655]
# Bug Report

## Prerequisites

* [ ] Can you reproduce the problem on TYPO3 v8.7 LTS
* [x] Can you reproduce the problem on TYPO3 v9.5 LTS
* [x ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package) to see if your bug or enhancement is already reported?

## Description

For bootstrap package content elements of type "Cards" or "Cards of subpages", I would expect that the image(s) of (a) selected page(s) are included in the cards, when a image is added as relation in the Resources menu of that page(s).
I tried that on my website based on TYPO3 9.5.4 with bootstrap_package 10.0.5 without success.
Therefore I checked it on a clean installation with the Introduction extension, where one can find some examples for Cards/Cards for subpages.
No success with **new** pages. Example pages work as long as you are not changing the images in the Resources menu. I did even delete a related image and it was still displayed on the page with the Cards/Cards of subpages CE. Of course I cleared the cache. I even delete the content of the typo3temp folder completely.

Just checked that there's the same problem with Thumbnail menu.

## Steps to Reproduce

On a bootstrap_package installation with the introduction pages:
1. Add a subpage in the "Content Examples/Menu's/Cards", for example "Page 0", as first page.
2. Add a image relation to this page in the Resources menu
3. Additional delete the image relation for "Page 1".

**Expected behavior:** [What you expected to happen]
In the backend the CE of type "Card of subpages" now show display the card for "Page 0" with an image.
The card for "Page 1" should be displayed without an image now.

**Actual behavior:** [What actually happened]
Card for "Page 0" is displayed without image.
Card for "Page 1" is displayed with the former choosen image.

## Versions

TYPO3 9.5.4 with bootstrap_package 10.0.5

**Comment by benjaminkott** [comment]
@zeichensatz can you please try to add the image to the "Thumbnail" field in the page data?
![image](https://user-images.githubusercontent.com/3243119/53175139-a8f92e00-35eb-11e9-863b-8d8d1c46a8a6.png)

**Comment by zeichensatz** [comment]
@benjaminkott oh hell! I never scrolled down in the appearance tab! Thanks a lot!
For me it would just have been much more convenient to get the image from the resources ...

**Comment by benjaminkott** [comment]
@zeichensatz we had this in the past - problem is that the resources field allows all types of file formats and is not limited to images. to not break existing behavior, I needed to move this one to a dedicated field where only images are allowed. Means it is hard to understand what image is taken in the end. When there are for example multiple images added or the first one is a zip file or whatever.

**Comment by zeichensatz** [comment]
@benjaminkott That's all reasonable. It started for me with the idea to use the Cards/Cards for subpages to group thematic pages for my private website. Since I have images related to most of the pages (about 400 in 2 languages) in the resources field already, I thought, that might be a easy task. I just had a quick glance into the SQL tables (sys_file_reference and pages) and I guess, it can't be easily done with SQL.
BTW: Thanks a lot for your magnificient bootstrap_package. It's a great help for non professionals like me!

**Comment by benjaminkott** [comment]
@zeichensatz actually it is easily possible with SQL.

![image](https://user-images.githubusercontent.com/3243119/53298790-0206d300-3833-11e9-9db8-15005fe44b8c.png)

since you only have to change the `fieldname` from `media` to `thumbnail` in the `sys_file_reference` table for the records you want to move.

**Comment by benjaminkott** [comment]
I am closing this issue, please open a new one if you have any further questions.
