### ISSUE TITLE
Onepage Layout

### ISSUE THREAD

**Issue by chequille** [benjaminkott/bootstrap_package#656]
Hi Benjamin,
I am currently updating from Typo3 7.6.x to 8.7.x.
Unfortunately, I am facing one main error where I do not know how to solve it.
In 7.6.x and your extension version 7.0.2, I could make a onepage site out of a selection of pages using the follwing typoscript which originally came from you within an older version of bootstrap_package:

```
#########################
#### ONEPAGE CONTENT ####
#########################
lib.content.onepage = COA
lib.content.onepage {
	20 = HMENU
	20 {
		excludeDoktypes < lib.navigation.main.10.excludeDoktypes
		special = list
		special.value = 10,11,12,13,14
		1 = TMENU
		1 {
			expAll = 1
			noBlur = 1
			NO = 1
			NO {
				doNotLinkIt = 1
				doNotShowLink = 1
				stdWrap2 {
					cObject = COA
					cObject {
						10 = LOAD_REGISTER
						10 {
							curentPageId.cObject = TEXT
							curentPageId.cObject {
								field = uid
							}
							sectionID.cObject = TEXT
							sectionID.cObject {
								field = alias
								ifEmpty = p{field:uid}
								ifEmpty.insertData = 1
							}
							pageClass.cObject < lib.page.class
						}
						20 < page.10
						20 {
							variables {
								showHeader.value = 0
								showFooter.value = 0
							}
						}
						wrap = |
						wrap.insertData = 1
					}
				}
				wrapItemAndSub = |
			}

		}
		2 < .1
	}
	90 = RESTORE_REGISTER
}


###############################
#### ONEPAGE PAGE SETTINGS ####
###############################
page {
	10 {
		variables {
			onePage = TEXT
			onePage.value = 1
		}
	}
}

```
Unffortunately, when rendering this now with Typ8 and the actual bootstrap_package extension, it is throwing an error:
Oops, an error occurred!
"Argument 3 passed to TYPO3\CMS\Frontend\Resource\FileCollector::addFilesFromRelation() must be of the type array, null given ...

Do you have any idea how to change this typscript to get it working?
Or is there any other simple way to make a onepage site out of some other pages?

Looking forward to hearing from you.
Best regards,
Jürgen

**Comment by chequille** [comment]
Hi Benjamin,
I found the problem. It was some missing stuff in the general Typoscript of bootstrap_package in the FLUIDTEMPLATE section.
I guess it was some missing variables. COuld not verify exactly what it was. Will elt you know as soon as I know it.

BR
Jürgen

**Comment by gilbertsoft** [comment]
Hey @chequille , is this still valid or can we close it?
