### ISSUE TITLE
page.theme.meta.includeNotInMenu is not working in 9.5

### ISSUE THREAD

**Issue by JavierVelazquez** [benjaminkott/bootstrap_package#657]
# Support
Hello all,
I can't get rid of the footer.meta section.
Toggle doesn't seem to do it, whether I edit the constant or the in the constant editor. Any help/ideas?
Thanks a lot for your time and effort.
Typo3 9.5.4 and bootstrap package.
Attentively
Javier

**Comment by JavierVelazquez** [comment]
Ok, I got rid of the meta section, the language, and the copyright by going through different constants but there is still a black bar at the bottom. How can I stop the footer meta section from being rendered all together?
Many thanks,
Javier

**Comment by JavierVelazquez** [comment]
Solved:
Commented line: 

In the bootstrap_package/Resources/Layouts/Page/Deafult.html...
:-)
I like Typo3 but it is sure not the easiest or most intuitive... but I am sticking with it...

**Comment by benjaminkott** [comment]
@JavierVelazquez I tried my best to make the bootstrap package as easy and flexible as possible. The use-case you describe is simply not intended yet. ;)

The best was as you already figured out is to use a sitepackage to extend the bootstrap package and overwrite the template responsible for rendering that part. 

For more information about sitepackages please have a look at:
- https://sitepackagebuilder.com/
- https://docs.typo3.org/typo3cms/SitePackageTutorial/Index.html

Back to your issue, currently you only can disable the parts inside the container at the bottom. To disable all options you would need to disable the following sections with typoscript constants.
```
page.theme.meta.enable = 0
page.theme.language.enable = 0
page.theme.socialmedia.enable = 0
page.theme.copyright.enable = 0
```

I think it makes sense that if someone really disables all elements we also disable the rendering of the outer container. I will provide a patch for that.

**Comment by benjaminkott** [comment]
@JavierVelazquez i wrapped the footer-section-meta into

```
<f:if condition="{theme.meta.enable} || {theme.language.enable} || {theme.copyright.enable} || {theme.socialmedia.enable}">
...
</f:if>
```

This will avoid rendering the section, when all options are disabled. Will be included in the next release for 10.x of the bootstrap package. Thx again for your feedback.

**Comment by JavierVelazquez** [comment]
Hello Benjamin, great!! I did disable the elements but as you pointed out I had to go and change the template. Your new conditional formatting makes sense and is a clever solution.
Thank you very much for looking into it and solving it.
