### ISSUE TITLE
customizing navbar-brand-height

### ISSUE THREAD

**Issue by ghwaldo** [benjaminkott/bootstrap_package#659]
Hallo,

really don't know if it is a issue, but i am trying to change the navbar-brand-height with lines in the template record in constants like this:

`plugin.bootstrap_package.settings.scss.navbar-brand-height = 10000px`

Whatever i try, there is no effect. Is it the wrong way ?

I looked at the genarates css file, but none of the things i change do any effect the awaited class to change.

bootstrap_package cloned from github did not change anything.

---
Waldo

**Comment by gilbertsoft** [comment]
Hi @ghwaldo 

The height is set [here](https://github.com/benjaminkott/bootstrap_package/blob/master/Resources/Public/Scss/Theme/_navbar.scss#L123) with the values from [here](https://github.com/benjaminkott/bootstrap_package/blob/master/Resources/Public/Scss/Theme/_variables.scss#L77). So you can insert something like this to your TypoScript constants:
```
plugin.bootstrap_package.settings.scss.navbar-heights = (lg: 200px, xl: 125px)
```

If you dig a little bit deeper into the provided links you will find other options too.
