### ISSUE TITLE
Bug with User's group (not the good one)

### ISSUE THREAD

**Issue by Salvatore76** [benjaminkott/bootstrap_package#660]
# Bug Report

## Prerequisites

* [x] Can you reproduce the problem on TYPO3 v8.7 LTS
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package) to see if your bug or enhancement is already reported?
* [ ] Can you reproduce the problem on TYPO3 v9.5 LTS

## Description

My bug occurs when we use multisite
As soon as a user creates a page, it is assigned to the group where ID=1 and not to the group which the user belongs.

## Steps to Reproduce

1. Install TYPO3
2. Install bootstrap package
3. Create a first group "Alpha"
4. Create a second group "Beta"
5. Create a user "The director" and link it to "Beta"
6. Connect as "The director"
7. Create a new page 
8. Go to Access
9.The new page  has as owner "The director:Alpha" instead of "The director:Beta"

## Versions

Typo3 v7.6.20 and Bootstrap_package v7.1.0
Typo3 v8.7.17 and Bootstrap_package v8.0.3

I'll already try with BP v9.1.2

**Comment by gilbertsoft** [comment]
Hi @Salvatore76 , does this problem not occur if you deactivate / uninstall Bootstrap Package? My guess currently is this is a core bug and not directly related to this extension.

**Comment by gilbertsoft** [comment]
No feedback so I'm going to close this issue now.
