### ISSUE TITLE
content elements added to news record not shown in news detail view

### ISSUE THREAD

**Issue by softstein** [benjaminkott/bootstrap_package#661]
In news module / news record: adding a content element in a news record (in tab "content elements") does not show up appropriately.
It should be shown in the news detail view.

Instead the element appears just as a normal content element in the backend (and is rendered in the frontend just as a normal content element).

**Comment by benjaminkott** [comment]
@softstein this seems to be a problem related to https://github.com/georgringer/news - I am not sure how @georgringer handles this I think we should transfer this issue to the news repository.

**Comment by georgringer** [comment]
As records are saved in a sysfolder, there is no way how those are shown in the frontend
