### ISSUE TITLE
German language pack seems not available

### ISSUE THREAD

**Issue by zeichensatz** [benjaminkott/bootstrap_package#664]
# Support
When I try to install the German language pack for the bootstrap_package with "Manage Language Packs" I get the following message:

```
Language packs updated
0 new language packs downloaded, 0 language packs updated, 1 language packs not available
```
The folder /typo3conf/l10n/de/bootstrap_package is empty.

I checked the TYPO3 translation server and the translations of the bootstrap_package are complete.
The download of language packs for system extensions (for example) works.

How can I get the German language pack for bootstrap_package?

**Comment by benjaminkott** [comment]
@zeichensatz there was a problem with the translation server please see: https://forge.typo3.org/issues/87727

```
Xavier Perseguers [1:02 PM] (today)
sorry, on it right now, indeed I confirm the backslashes as well on https://translation.typo3.org/l10n_ter/b/o/bootstrap_package-l10n/
fixed for german and danish, wonder how this is possible that every translation is broken
```

maybe it needs some time to be recreated - usually, they are updated overnight. will check tomorrow if the problem still exists.

**Comment by jokumer** [comment]
@zeichensatz if you are in hurry, you can manually add the folders from https://typo3.org/fileadmin/ter/b/o/bootstrap_package-l10n/bootstrap_package-l10n-de.zip to your installation

**Comment by zeichensatz** [comment]
@benjaminkott Works properly today again.
@jokumer Thanks for that information!
Wolle

**Comment by benjaminkott** [comment]
@zeichensatz @jokumer can confirm now that it´s working again, will close the issue.

**Comment by hilburger** [comment]
Hi there! 
I currently have the same problem again. 
It's on a Typo3 9.5.19 with bootstrap_package 11.0.2. 

When I fetch the translation via Maintenance -> Manage Language Packs (if generally or specifically for bs-package) I get: 

0 new language packs downloaded, 0 language packs updated, 1 language pack not available

The folder /public/typo3conf/l10n (Composer install) stays empty. 

Language menu shows German only correctly.

**Comment by hilburger** [comment]
Update: I have added french for testing is this has only to do with German and it down not work either.

**Comment by cm-andrews** [comment]
Problem also exists in completely new 10.4 installations... German language Pack has to be installed by hand

**Comment by hilburger** [comment]
It works for me when I turn off "newTranslationServer" in the "Feature Toggles" in the "Settings" area. 
So we have to switch back and forth for a while until all extensions have migrated, right?

**Comment by frank65307** [comment]
My problem in typo3 10.4.8 in "Manage Language Packs" for Bootstrap Package is, that i can not load the German language pack. I also tried French and Danish, they have the same problem. So it is not only the German language pack what does not download.

The message is always:

Language packs updated
0 new language packs downloaded, 0 language packs updated, 1 language pack not available

In 10.4.8 is no Feature Toggle for newTranslationServer as it is in typo3 9.

So for now, i only can do it manually with the *.zip file.

**Comment by SventB** [comment]
> It works for me when I turn off "newTranslationServer" in the "Feature Toggles" in the "Settings" area.

There is no feature with this name in TYPO3 10.4.8

**Comment by SventB** [comment]
Same problem in TYPO3 v12.4.9 :(
