### ISSUE TITLE
Carousel item type Image and Text and Image are missing responsive image variants

### ISSUE THREAD

**Issue by ghwaldo** [benjaminkott/bootstrap_package#665]
When i add an image to a carousel i can edit the dimension via backend editor, but only the widest image of the resonsive images has the right ratio that i used in the editor.
For the other resultions there is no possibility to change the ratio like in Elemt Text with images.

The only solution at the moment seems to crop the image before uploading to the site.

**Comment by benjaminkott** [comment]
@ghwaldo what version you are using?

**Comment by ghwaldo** [comment]
TYPO3 Version 9.5.4
bootstrap_package master from github.

I attached Images:
1. Upload Image to Carousel
2. Edit in Backend
3. Source / hover first image
4. Source / hover second image
5. Source / hover thirdimage
6. Source / hover fourth image
7. Source / hover fifth image

In backend editor or "normal" picture elements i have the option for cropping the images for 4 resolutions.
![2019-03-08_090035](https://user-images.githubusercontent.com/44200786/54016114-36a75280-4182-11e9-8e58-6791341b9975.png)
![2019-03-08_090111](https://user-images.githubusercontent.com/44200786/54016115-36a75280-4182-11e9-8e0d-32923f85b900.png)
![2019-03-08_090747](https://user-images.githubusercontent.com/44200786/54016116-373fe900-4182-11e9-8c50-4b047de9a84e.png)
![2019-03-08_090814](https://user-images.githubusercontent.com/44200786/54016117-373fe900-4182-11e9-96e8-68a96cb64a87.png)
![2019-03-08_090826](https://user-images.githubusercontent.com/44200786/54016118-373fe900-4182-11e9-8a64-388922ae96a0.png)
![2019-03-08_090834](https://user-images.githubusercontent.com/44200786/54016121-373fe900-4182-11e9-8624-7ad83b03291b.png)
![2019-03-08_090859](https://user-images.githubusercontent.com/44200786/54016122-373fe900-4182-11e9-8996-b56eb006210c.png)

**Comment by benjaminkott** [comment]
@ghwaldo can confirm problem, the variants are simply missing for the image here.

**Comment by ghwaldo** [comment]
@benjaminkott is it just simply adding more entries to 500_cropping.php ? So i could try if nessesary.

**Comment by benjaminkott** [comment]
@ghwaldo should be enough to get this working - will also need to check the responsive behavior later.

**Comment by benjaminkott** [comment]
@ghwaldo applied patches to master and 10.x thx for the report.
