### ISSUE TITLE
Cookieconcent: enable/disable tracking

### ISSUE THREAD

**Issue by wukitech** [benjaminkott/bootstrap_package#666]
# Support

I'm able to enable and customize the cookieconsent of the bootstrap_package but If I use the google tracking (analytics) from the bootstrap_package and try to allow/decliene (need to use the opt-in) on the webpage nothing happens (google tracking parts stays active). Did I miss something? I can't find anything while searching on google. ;-) Would be nice to have this information added to the user manual.

Thanks a lot!

**Comment by benjaminkott** [comment]
@wukitech the cookie consent is built in as a framework you can utilize to customize it to your needs.

Please see the following link for events you can attach your logic to:
https://github.com/benjaminkott/bootstrap_package/wiki/Customize-Cookie-Consent

There is "undocumented" support for google analytics opt-out functionality.
You can place `###GoogleAnalyticsStatus###` in any RTE or in the template, and it will be replaced with a status-text and an opt-out/-in link. 

Example:

![image](https://user-images.githubusercontent.com/3243119/54959506-9ad75e00-4f59-11e9-99f7-5269265cd0fa.png)

https://www.bootstrap-package.com/privacy

**Comment by benjaminkott** [comment]
I hope that helps, please open a new ticket if you have further questions.

**Comment by wukitech** [comment]
Thanks a lot! Is working fine with that information. :-)
