### ISSUE TITLE
Typo3 bootstrap package image before page is loaded

### ISSUE THREAD

**Issue by chequille** [benjaminkott/bootstrap_package#667]
Hi Bejamin,
I do not want to have the "Typo3 Bootstrap Package" image shown before my site is shown.
How can i disable this. I did not find it.

Please let me know.
BR
Jürgen

**Comment by benjaminkott** [comment]
Please check the typoscript constants, there should be an option called `bootstrap package: preloader`. You should find these options. 

```
page.preloader.enable = 1
page.preloader.logo.file = EXT:bootstrap_package/Resources/Public/Images/BootstrapPackageInverted.svg
page.preloader.logo.height = 52
page.preloader.logo.width = 180
page.preloader.backgroundColor = #333333
page.preloader.fadeDuration = 0.25
```

You can also disable the fontloader completely in the extension configuration.

**Comment by chequille** [comment]
Got it. Thanks

**Comment by ses2013** [comment]
All preloader settings are missing in the constant.typoscript in version 10.0.6.
Allthough they are working if you fill them in manually … intended?

**Comment by Corleone87** [comment]
In Typo3 backend you can go to Template Module -> switch to Typoscript Object Browser -> page preloader. You can enable or disable it. 

> 
> 
> All preloader settings are missing in the constant.typoscript in version 10.0.6.
> Allthough they are working if you fill them in manually … intended?

**Comment by benjaminkott** [comment]
@ses2013 to avoid confusions the preloader settings are only added IF its enabled in the extension configuration. see https://github.com/benjaminkott/bootstrap_package/blob/master/ext_localconf.php#L135-L160
