### ISSUE TITLE
Add text in Ukrainian language on the page

### ISSUE THREAD

**Issue by typo3ua** [benjaminkott/bootstrap_package#668]
The Ukrainian language has at least three letters (characters) there are not in neither languages in the world.

I think that need add those two lines on the page "[Languages and characters](https://www.bootstrap-package.com/content-examples/and-more/languages-and-characters)"

### Line one: 
Ukrainian (Українська з апострофом): На подушечці форми любої є й ґудзик щоб пір'я геть жовте сховати.

### Line two: 
Ukrainian (Українська без апострофа): У ґазди є ж бо гевеї, які шиють прості килими, наче хащі фацелій.

[As here for example](https://www.typo3.org.ua/typo3-cms/examples/content/and-more/any-language-any-character).

**Comment by benjaminkott** [comment]
@typo3ua added the examples thx.
