### ISSUE TITLE
Deep link via external url to a open tab

### ISSUE THREAD

**Issue by web2date** [benjaminkott/bootstrap_package#673]
# Support

**How can I link within a Website to a  open tab? **
TYPO3 v9, Bootstrap Package 10.0.6 (/example.html#tabcontent-48-3) 
I've got a couple of links at my homepage to another page where 2 content elements Tabs are placed.
I need to set links to specific open tabs...

**Comment by benjaminkott** [comment]
@web2date you need to add some javascript to your website to enable this. I am not planning to make this a feature of the bootstrap package, but this one should help you get going.

```
$(function() {

    var hash = document.location.hash;
    if (hash.match('#tabcontent')) {
        $('.nav-tabs a[href="#' + hash.split('#')[1] + '"]').tab('show');
    }

});
```
