### ISSUE TITLE
No date localization for "Card of subpages"

### ISSUE THREAD

**Issue by rhabacker** [benjaminkott/bootstrap_package#674]
# Bug Report

## Prerequisites

* [x] Can you reproduce the problem on TYPO3 v8.7 LTS
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package) to see if your bug or enhancement is already reported?

## Description
Specifing a date on a page of type "external link" added to a "Cards of subpages" shows always the date in english format displayed by the "read more" link regardless if the site is configured for  showing a non english  translations (e.g. german)

## Steps to Reproduce

1. Inspect https://github.com/benjaminkott/bootstrap_package/blob/4bc84b4b7cebd85ddea7d655f588c285adc67594/Resources/Private/Partials/ContentElements/Header/Date.html

**Expected behavior:**
The mentioned html fragment should use a translateable date format

**Actual behavior:**
The date format is always "%B %e, %Y" regardless of the choosen language

## Versions
typo3 8.7,
bootstrap package 10.0.6

It would be nice to get at least a how to for an issue worarkound.

**Comment by benjaminkott** [comment]
@rhabacker I am quite unsure what you are exactly referring to. This issue describes that there is an issue with the date format in "Cards of Subpages". This content element has no support for dates being displayed except the header that is used in all content elements.

![image](https://user-images.githubusercontent.com/3243119/54957737-f56dbb80-4f53-11e9-8edf-ad4802284384.png)

You are linking the templates that are used for the header rendering of all content elements, are you talking about these?

![image](https://user-images.githubusercontent.com/3243119/54957819-2bab3b00-4f54-11e9-9a56-04df4c3e6402.png)

![image](https://user-images.githubusercontent.com/3243119/54957470-28637f80-4f53-11e9-8b8f-b77f8f1ea07c.png)

**Comment by rhabacker** [comment]
I used the "Card on subpages content type, inspected the html source where the date is printed,  searched for ```<time datetime="``` in the bootstrap files and got the mentioned location.

The problem with using "%B %e, %Y" is that is prints "March 26, 2019", where in Germany it should display "26. März 2019", which is "%e. %B %Y" according to https://www.php.net/manual/de/function.strftime.php

BTW: There is another location https://github.com/benjaminkott/bootstrap_package/blob/13ce83b62fd2aeddc8b2791ef8a74ef575be8921/Resources/Private/Templates/ContentElements/Timeline.html, suffering from the same problem (it uses Y-%m-%d' where is should use %d.%m.%Y for german language)

**Comment by benjaminkott** [comment]
@rhabacker the `<time datetime="*">` format is totally valid and is not intended to be translated. The content itself of the tag can and should be translated (formatted differently). Please see Mozilla docs for more information: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time

I am having a look at how to make the format of the date in the header configurable, but I do not see this necessity to be translated depending on the language.

**Comment by rhabacker** [comment]
@benjaminkott: Just an example: In typo3 extensions (for example the tt_news plugins) it is common practice to specify language specific date formats as shown below:

# default language (en)
plugin.tt_news.displayList.date_stdWrap.strftime = %Y-%m-%d
plugin.tt_news.displaySingle.date_stdWrap.strftime = %Y-%m-%d

# german
[globalVar = GP:L = 0] 
   plugin.tt_news.displayList.date_stdWrap.strftime = %d.%m.%Y
   plugin.tt_news.displaySingle.date_stdWrap.strftime = %d.%m.%Y

(from http://lists.typo3.org/pipermail/typo3-german/2009-March/056419.html

**Comment by rhabacker** [comment]
For multilingual websites you see a better possibility to define the short and full date format listed at https://en.wikipedia.org/wiki/Date_format_by_country in the correct format for the respective language without storing the corresponding format in the related translation file ?

**Comment by benjaminkott** [comment]
@rhabacker i´ve added a configuration to change the display format of the date. The datetime format keeps as is to spec.

```
<time datetime="*">
   <configurable>
</time>
```

**Comment by rhabacker** [comment]
Thanks
