### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by olegsv** [benjaminkott/bootstrap_package#680]
# Bug Report

## Prerequisites

* [ n/a] Can you reproduce the problem on TYPO3 v8.7 LTS
* [X] Can you reproduce the problem on TYPO3 v9.5 LTS
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package) to see if your bug or enhancement is already reported?

## Description
There are multiple warnings in typo3 log:
```
component="TYPO3.CMS.Backend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed, fallback kicks in. It looks like an old condition with only one equal sign. - {"expression":"userFunc = TYPO3\\CMS\\Core\\Utility\\ExtensionManagementUtility::isLoaded('felogin')"}
component="TYPO3.CMS.Backend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed, fallback kicks in. It looks like an old condition with only one equal sign. - {"expression":"userFunc = TYPO3\\CMS\\Core\\Utility\\ExtensionManagementUtility::isLoaded('indexed_search')"}
component="TYPO3.CMS.Backend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed, fallback kicks in. It looks like an old condition with only one equal sign. - {"expression":"userFunc = TYPO3\\CMS\\Core\\Utility\\ExtensionManagementUtility::isLoaded('form')"}
component="TYPO3.CMS.Backend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed, fallback kicks in. - {"expression":"BK2K\\BootstrapPackage\\TypoScript\\Condition\\CoreVersionCondition < 9.3"}
component="TYPO3.CMS.Backend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed, fallback kicks in. - {"expression":"BK2K\\BootstrapPackage\\TypoScript\\Condition\\CoreVersionCondition >= 9.3"}

component="TYPO3.CMS.Frontend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed, fallback kicks in. It looks like an old condition with only one equal sign. - {"expression":"globalVar = LIT:1 = 1"}
component="TYPO3.CMS.Frontend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed, fallback kicks in. It looks like an old condition with only one equal sign. - {"expression":"globalVar = TSFE:page|no_search = 1"}
component="TYPO3.CMS.Frontend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed, fallback kicks in. It looks like an old condition with only one equal sign. - {"expression":"globalVar = LIT:1 = 1"}
component="TYPO3.CMS.Frontend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed, fallback kicks in. It looks like an old condition with only one equal sign. - {"expression":"globalVar = TSFE:page|no_search = 1"}
```
## Steps to Reproduce

1. Install typo3 9.5 with bootstrap package 10.0.6 and introduction package
2 see logs in typo3temp/var/log/...

## Versions
typo3 9.5.5
bootstrap_package 10.0.6
introduction package 4.0.1

**Comment by benjaminkott** [comment]
@olegsv this just a deprecation warning, it's already resolved in master branch.

**Comment by benjaminkott** [comment]
@olegsv just to clear this a bit more up, until we release v11 of the bootstrap package and we drop support for 8.7 we need to keep some deprecations to keep both versions running and make the transition easy. so a version of bp will try to support two major LTS versions.

I am resolving this issue for now, since the deprecations have already been addressed to be compatible with TYPO3 v10.x in the master branch.

**Comment by volodjaloz94** [comment]
Hello!
I have the same problem on typo3 v9.5.15
`Thu, 16 Apr 2020 21:32:30 +0200 [WARNING] request="d1dbed4804290" component="TYPO3.CMS.Frontend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed, fallback kicks in. It looks like an old condition with only one equal sign. - {"expression":"userFunc = TYPO3\\CMS\\Core\\Utility\\ExtensionManagementUtility::isLoaded('indexed_search')"}
Thu, 16 Apr 2020 21:32:30 +0200 [WARNING] request="d1dbed4804290" component="TYPO3.CMS.Frontend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed, fallback kicks in. It looks like an old condition with only one equal sign. - {"expression":"userFunc = TYPO3\\CMS\\Core\\Utility\\ExtensionManagementUtility::isLoaded('news')"}
Thu, 16 Apr 2020 21:32:30 +0200 [WARNING] request="d1dbed4804290" component="TYPO3.CMS.Frontend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed, fallback kicks in. It looks like an old condition with only one equal sign. - {"expression":"treeLevel = 0"}
Thu, 16 Apr 2020 21:32:30 +0200 [WARNING] request="d1dbed4804290" component="TYPO3.CMS.Frontend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed, fallback kicks in. It looks like an old condition with only one equal sign. - {"expression":"globalVar = LIT:0 < 0"}
Thu, 16 Apr 2020 21:32:30 +0200 [WARNING] request="d1dbed4804290" component="TYPO3.CMS.Frontend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed, fallback kicks in. It looks like an old condition with only one equal sign. - {"expression":"globalVar = TSFE:id = 112"}
Thu, 16 Apr 2020 21:32:30 +0200 [WARNING] request="d1dbed4804290" component="TYPO3.CMS.Frontend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed, fallback kicks in. It looks like an old condition with only one equal sign. - {"expression":"globalVar = TSFE:id = 119"}
Thu, 16 Apr 2020 21:32:30 +0200 [WARNING] request="d1dbed4804290" component="TYPO3.CMS.Frontend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed, fallback kicks in. It looks like an old condition with only one equal sign. - {"expression":"userFunc = TYPO3\\CMS\\Core\\Utility\\ExtensionManagementUtility::isLoaded('form')"}
Thu, 16 Apr 2020 21:32:30 +0200 [WARNING] request="d1dbed4804290" component="TYPO3.CMS.Frontend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed, fallback kicks in. It looks like an old condition with only one equal sign. - {"expression":"userFunc = TYPO3\\CMS\\Core\\Utility\\ExtensionManagementUtility::isLoaded('felogin')"}
Thu, 16 Apr 2020 21:32:30 +0200 [WARNING] request="d1dbed4804290" component="TYPO3.CMS.Frontend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed, fallback kicks in. It looks like an old condition with only one equal sign. - {"expression":"globalVar = TSFE:page|no_search = 1"}
Thu, 16 Apr 2020 21:32:30 +0200 [WARNING] request="d1dbed4804290" component="TYPO3.CMS.Frontend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed, fallback kicks in. It looks like an old condition with only one equal sign. - {"expression":"globalVar = GP:L = 1"}
Thu, 16 Apr 2020 21:32:30 +0200 [WARNING] request="d1dbed4804290" component="TYPO3.CMS.Frontend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed, fallback kicks in. It looks like an old condition with only one equal sign. - {"expression":"globalVar = GP:L = 2"}
Thu, 16 Apr 2020 21:32:30 +0200 [WARNING] request="d1dbed4804290" component="TYPO3.CMS.Frontend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed, fallback kicks in. It looks like an old condition with only one equal sign. - {"expression":"globalVar = TSFE:id = 70"}
Thu, 16 Apr 2020 21:32:30 +0200 [WARNING] request="d1dbed4804290" component="TYPO3.CMS.Frontend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed, fallback kicks in. It looks like an old condition with only one equal sign. - {"expression":"globalVar = TSFE:id = 80"}
Thu, 16 Apr 2020 21:32:30 +0200 [WARNING] request="d1dbed4804290" component="TYPO3.CMS.Frontend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed, fallback kicks in. It looks like an old condition with only one equal sign. - {"expression":"globalVar = TSFE:id = 81"}`

**Comment by elin-y** [comment]
Hello, the same problem here as well. This is not about the deprecation log, it is the typo3.log.

Maybe this log should go into deprecation.log, I have already deactivated it, but typo3.log is filling up with those entries.

**Comment by Joe1am** [comment]
Me too. With Typo3 9.5.14 installed:

`Mon, 25 May 2020 17:26:54 +0000 [WARNING] request="e6d5e8649e5d0" component="TYPO3.CMS.Backend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed, fallback kicks in. - {"expression":"extension.isLoaded('feedit') == 1"}
Mon, 25 May 2020 17:26:54 +0000 [WARNING] request="e6d5e8649e5d0" component="TYPO3.CMS.Backend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed, fallback kicks in. - {"expression":"extension.isLoaded('felogin') == 1"}
Mon, 25 May 2020 17:26:54 +0000 [WARNING] request="e6d5e8649e5d0" component="TYPO3.CMS.Backend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed, fallback kicks in. - {"expression":"extension.isLoaded('form') == 1"}
Mon, 25 May 2020 17:26:54 +0000 [WARNING] request="e6d5e8649e5d0" component="TYPO3.CMS.Backend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed, fallback kicks in. - {"expression":"extension.isLoaded('indexed_search') == 1"}
Mon, 25 May 2020 17:26:54 +0000 [WARNING] request="e6d5e8649e5d0" component="TYPO3.CMS.Backend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed, fallback kicks in. - {"expression":"extension.isLoaded('seo') == 1"}`
