### ISSUE TITLE
TCEMAIN.translateToHidden = 1 ?

### ISSUE THREAD

**Issue by SvenJuergens** [benjaminkott/bootstrap_package#683]
# Bug Report

In Configuration/TsConfig/Page/TCEMAIN.tsconfig is still an option
TCEMAIN.translateToHidden = 1
https://github.com/benjaminkott/bootstrap_package/blob/b8f7d912ffbba89cea638566d59cad01c87971a5/Configuration/TsConfig/Page/TCEMAIN.tsconfig#L11

is this still a valid option? Unfortunately, I can no longer find references to it

sorry, so it's more of a question than a bug report :)

Best regards
Sven

and by the way, really a very, very, very good extension 💯 👍

**Comment by gilbertsoft** [comment]
Thanks for your report, this option will be removed as it's not existing anymore.
