### ISSUE TITLE
Use page.javascriptLibs for jQuery

### ISSUE THREAD

**Issue by SventB** [benjaminkott/bootstrap_package#685]
For including the jQuery library, you should use page.javascriptLibs.jQuery.
This offers some extra features :)
Do you want me to submit a pull request for that?

**Comment by benjaminkott** [comment]
I am not sure what extra features you mean? But it's intended to be loaded in the footer and I would not like to change that.  But you can try to convince me 😊.

**Comment by SventB** [comment]
You can load it from a CDN or easily activate "no conflict" mode.
But it seems, I've missed something:

```@deprecated since TYPO3 v9, will be removed in TYPO3 v10.0, the setting page.javascriptLibs has been deprecated and will be removed in TYPO3 v10.0.```

Sorry 😓
