### ISSUE TITLE
Wrong HTML when using breadcrumbExtendedValue

### ISSUE THREAD

**Issue by SventB** [benjaminkott/bootstrap_package#690]
When using "breadcrumbExtendedValue", e.g. for a news detail page, the resulting HTML looks like this:

```
<li class="breadcrumb-item active" aria-current="page"><a class="breadcrumb-link" href="/features-1/ext-news/news" title="Details"><span class="breadcrumb-text">Details</span></a></li>
<li class="breadcrumb-item active" aria-current="page"><span class="breadcrumb-text">My news item</span></li>
```

Only the last item in the breadcrumb should contain class "active" and aria-current attribute.

**Comment by benjaminkott** [comment]
@SventB thx, I've pushed a patch that is slightly different from your approach.

In addition, I´ve added examples of how to extend the breadcrumb and it's intended to be used.
https://github.com/benjaminkott/bootstrap_package/wiki/Extend-the-breadcrumb
