### ISSUE TITLE
some constants could not saved 

### ISSUE THREAD

**Issue by criwe** [benjaminkott/bootstrap_package#695]
# Bug Report

## Description

When changing constans in BOOTSTRAP 4.x: STYLING (605) via the constant editor, the chances are not saved. Other values from other categories can be chanced like expected.
When writing the values in the constant field of the template, it is shown in the constant editor too.

## Steps to Reproduce

1. Go to the constant editor, 
2. switch to BOOTSTRAP 4.x: STYLING (605)
3. Change a value
4. Save -> check the value (is the same as before changing it in my case)

## Versions

-  TYPO3 v9.5.7 LTS
- Bootstrap Package 10.0.6
- PHP 7.2.15

(I´ve got only one installation with that setting/extension/version, so maybe its something  specitific.. would be great if someone could try to reproduce it)

Best,
Christoph

**Comment by jokumer** [comment]
Tried - can't confirm. The changed value is written to database.

**Comment by criwe** [comment]
@jokumer thanks for testing. I`ve set up another mainly similar installation, no problem threre. Seems to be a specific problem.. -> close.

**Comment by criwe** [comment]
I´ve found the issue: php_value max_input_vars was set to 1000 ... changed it to 1500 (like recommended) and it works fine...
