### ISSUE TITLE
Entry Level 2

### ISSUE THREAD

**Issue by felixgerdes** [benjaminkott/bootstrap_package#699]
Hello,

first of all thank you very much for this awesome package!

In my situation i want to have the headermenu started on the second Level. Not on the first. 
Is there an easy way (TS) to manipulate the menu in this way?

Thanks!

Felix

**Comment by benjaminkott** [comment]
The navigation ins the header menu can be configured through `typoscript`. See original configuration: 
https://github.com/benjaminkott/bootstrap_package/blob/master/Configuration/TypoScript/setup.typoscript#L136-L159

As it´s supporting the same properties as HMENU it should be enough if you set the entrylevel in your typoscript setup.

https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/ContentObjects/Hmenu/Index.html#hmenu-entrylevel

```
page.10.dataProcessing.10.entryLevel = 1
```

**Comment by felixgerdes** [comment]
Thanks for your fast answer, that helped me a lot! 

Btw: If you want to let your Breadcrumbnavigation starts a level deeper as well, just add 
`page.10.dataProcessing.30.special.range = 1|-1`
