### ISSUE TITLE
SCSS variables for cookie consent

### ISSUE THREAD

**Issue by SventB** [benjaminkott/bootstrap_package#704]
You write the variables for cookie consent in file Resources/Public/Scss/Theme/_cookieconsent.scss
Why not using the TypoScript constants (plugin.bootstrap_package.settings.scss)?

**Comment by benjaminkott** [comment]
Hey @SventB thx for pointing that out - i missed some `!default` flags here and there...
Added patches to master and 10.x, you should now be able to overwrite it again with typoscript.

```
plugin.bootstrap_package.settings.scss {
    cookieconsent-bg = #dadada
}
```
