### ISSUE TITLE
og:image should replaced if seo fields are used

### ISSUE THREAD

**Issue by SvenJuergens** [benjaminkott/bootstrap_package#705]
# Bug Report

## Prerequisites

* [ ] Can you reproduce the problem on TYPO3 v8.7 LTS
* [x ] Can you reproduce the problem on TYPO3 v9.5 LTS
* [x ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package) to see if your bug or enhancement is already reported?

## Description

On the start page, I added a "default" og:image image in "Pages -> media". If I embed an og:image (facebook, twitter) on an underside, with installed EXT: SEO then both og:image elements appear in the source text.

## Steps to Reproduce

see above

**Expected behavior:** 
only the above mentioned image of the current page should be attached

**Actual behavior:** 
both are attached

## Versions
10.0.6
You can get this information from executing `composer show` at the command line if your TYPO3 installation is composer based, otherwise the version number will be shown in the extension manager.

**Comment by benjaminkott** [comment]
Is resolved with https://github.com/benjaminkott/bootstrap_package/commit/1dc73ff4e4c8e7296e70bc035696eefa1e6dd5e6 thx for the report @SvenJuergens
