### ISSUE TITLE
Section menu optimizations

### ISSUE THREAD

**Issue by SventB** [benjaminkott/bootstrap_package#706]
The content element "Section index" is mostly used for generating an anchor menu for the current page. If I do so, I get this result:

![screen](https://user-images.githubusercontent.com/2690489/59339821-2c5a9e80-8d05-11e9-8816-96d80569bf49.png)

I don't like the unneeded first `<li>` "Sections".

Also, there's an issue when having a content element without a header: an empty `<a>` tag is generated.

I will create a pull request for that.

**Comment by benjaminkott** [comment]
@SventB the first entry point is generated because you can assign multiple ones.

**Comment by SventB** [comment]
With my changes, there's still the possibility to have multiple entry points.

**Comment by benjaminkott** [comment]
Ok cool, just seen the patch - will check later also if it makes sense to roll this behavior out to more elements.
