### ISSUE TITLE
SCSS mixin with quotation mark

### ISSUE THREAD

**Issue by SventB** [benjaminkott/bootstrap_package#708]
Only a tiny issue, this seems to have no side effects, just for clean code ;)

You often write

`@include media-breakpoint-up('md')`

But correct is without quotation marks (see https://sass-lang.com/documentation/at-rules/mixin and https://getbootstrap.com/docs/4.3/layout/overview/):

`@include media-breakpoint-up(md)`

This is valid for all mixins with arguments.

**Comment by benjaminkott** [comment]
mmm.. it seems to depend, sometimes they are also quoting the arguments see: 
```
@mixin order($height, $selectors...) {
  @for $i from 0 to length($selectors) {
    #{nth($selectors, $i + 1)} {
      position: absolute;
      height: $height;
      margin-top: $i * $height;
    }
  }
}

@include order(150px, "input.name", "input.address", "input.zip");
```

Still, there are inconsistencies in the bootstrap_package SCSS.
For core, I´ve implemented guidelines for that - what do you think would that also make sense for the bp? https://github.com/TYPO3/TYPO3.CMS/blob/master/.stylelintrc

**Comment by SventB** [comment]
Using the core guidelines for bp sounds good.
If you decide not to do that, a consistent solution would be welcome ;)

**Comment by benjaminkott** [comment]
@SventB check the pr

**Comment by SventB** [comment]
I didn't check everything, but most. Looks good for me.
Thank you for your effort.

**Comment by boerge** [comment]
I still see a mixture of (breakpoint) and ('breakpoint') in the package and found just out, where this causes problems:

The bootstrap mixin "@media-breakpoint-only" is NOT working properly, when the breakpoint is given WITH single quotation marks: 

```@mixin media-breakpoint-only($name, $breakpoints: $grid-breakpoints) {
  $min: breakpoint-min($name, $breakpoints);
  $max: breakpoint-max($name, $breakpoints);

  @if $min != null and $max != null {
    @media (min-width: $min) and (max-width: $max) {
      @content;
    }
  } @else if $max == null {
    @include media-breakpoint-up($name, $breakpoints) {
      @content;
    }
  } @else if $min == null {
    @include media-breakpoint-down($name, $breakpoints) {
      @content;
    }
  }
}```

Example with quotes: @include media-breakpoint-only**(md)**:
- as expected i get in frontend: @media (max-width: 991.98px) and (min-width: 768px)

Example without quotes: @include media-breakpoint-only**('md')**:
- as NOT expected i get in frontend just:  @media (min-width: 768px)

BTW as i see, bootstrap 4 itself isnt actually using the "-only"-mixin, but in principle its working. In the "-up" and "-down" mixins and in their docs (ass @SventB also says) they use it without quotes, so i think we also should do so.

--

@benjaminkott Thanks for everything, i love bootstrap and sitepackage. I'm pretty sure typo3 wouldn't be that famous anymore without you :)
