### ISSUE TITLE
Language menu

### ISSUE THREAD

**Issue by SventB** [benjaminkott/bootstrap_package#71]
Can you please add the possibility to disable the language menu with a TypoScript constant, like you can disable e.g. the copyright text?

Can you please add a language menu with flags?

If you agree with me, that this is useful, I could implement this in my fork and you merge this later.

**Comment by benjaminkott** [comment]
Thanks for your report, i´ve created a new epic to collect all language related issues, or areas that could need improvement: https://github.com/benjaminkott/bootstrap_package/issues/510

Will close this issue for now, but will be referenced in the epic.
