### ISSUE TITLE
Working with workspace: can´t change data of content-elements items

### ISSUE THREAD

**Issue by heural** [benjaminkott/bootstrap_package#714]
Hi Benjamin,
work with workspace (draft) and create a content-element (accordion).
Add accordion item and fill out the fields. Save it.

The data will saved, but if i change some fields and save again, the last state will be shown.
Except the title (header), that works as expected.

Typo3 9.5.7, bootsptrap-package ba633fa

**Comment by gilbertsoft** [comment]
This looks like a core bug and should be solved in TYPO3 10.4 and higher. So I'm going to close this issue now.
