### ISSUE TITLE
MegaMenu for the main menu in the Navbar

### ISSUE THREAD

**Issue by aksenovaa** [benjaminkott/bootstrap_package#718]
# MegaMenu for the main menu in the Navbar

For large sites, it is advisable to use the megame instead of the usual. This feature is missing from the package.
An interesting implementation I met in this package t3sbootstrap:
https://www.t3sbootstrap.de/demo/mega-menu?MP=7-97

Where the menu is collected on a separate page of certain content items.
I think this is an interesting implementation.

**Comment by benjaminkott** [comment]
Resolved with https://github.com/benjaminkott/bootstrap_package/commit/2775146d21660b1c09bbd9ab093672bfdad326bc
