### ISSUE TITLE
Setting "no_search" results in "noindex"

### ISSUE THREAD

**Issue by SventB** [benjaminkott/bootstrap_package#725]
When activating setting "Include in Search" (no_search) in page properties, this page isn't indexed for internal search. But in EXT:bootstrap_package/Configuration/TypoScript/setup.typoscript, this setting is also used to disable the page from indexing by robots:

```
[globalVar = TSFE:page|no_search = 1]
    page.meta.robots = noindex,follow
[end]
```

Since setting "Index this page" (no_index) is introduced in TYPO3 9 LTS, only this setting should be used; the TypoScript condition can be completely removed.

**Comment by benjaminkott** [comment]
@SventB i agree, - seo extension is already required and settings can now be dropped sind for master since 8.7 is not supported anymore with the upcomming version 11.
