### ISSUE TITLE
<link> and <a href="t3://page/uid=1"> not working in HTML CE

### ISSUE THREAD

**Issue by aimeos** [benjaminkott/bootstrap_package#729]
# Bug Report

`<link>` and `<a href="t3://page/uid=1">` tags are not parsed in HTML content elements because the `bootstrap_package/Resources/Private/Templates/ContentElements/Html.html` template contains `<f:format.raw>...</f:format.raw>` instead of:
```
    <f:format.html parseFuncTSPath="lib.linkParseFunc">{data.bodytext}</f:format.html>
```
The corresponding TS is:
```
lib.linkParseFunc {
    tags {
        link = TEXT
        link {
            stdWrap.current = 1
            stdWrap.typolink.extTarget = _blank
            stdWrap.typolink.target = {$cLinkTagTarget}
            stdWrap.typolink.parameter.data = parameters : allParams
        }
    }
}
```
This is only a partial solution because `<a href="t3://page/uid=1">` is still not parsed. Removing the `parseFuncTSPath` attribute will use the standard RTE parse functions but they destroy the HTML code and insert `<p>` tags all over.

**Comment by gilbertsoft** [comment]
> <f:format.html parseFuncTSPath="lib.linkParseFunc">{data.bodytext}</f:format.html>

This should be `lib.parseFunc` instead of `lib.linkParseFunc` and it works.

**Comment by gilbertsoft** [comment]
@aimeos Can you please check my patch

**Comment by aimeos** [comment]
Unfortunately, it doesn't work as expected. I transforms
`<a href="#"></a>` to `<a href="/"></a>`
and
`<iframe style="border: none;" src="https://cards.producthunt.com/cards/posts/179110?v=1" width="500" height="405" frameborder="0" scrolling="no" allowfullscreen></iframe>`
to
`&gt;iframe style="border: none;" src="https://cards.producthunt.com/cards/posts/179110?v=1" width="500" height="405" frameborder="0" scrolling="no" allowfullscreen&lt;&gt;/iframe&lt;`

**Comment by benjaminkott** [comment]
Html is meant the be plaintext, we will not support additional transformations.
