### ISSUE TITLE
Option to disable responsive images

### ISSUE THREAD

**Issue by SventB** [benjaminkott/bootstrap_package#73]
Can you please add an option to disable the responsive images and lazy loading?
If you have a webpage with mainly images in columns the responsive images are quite useless, I've described my problem here: http://stackoverflow.com/questions/26190932/responsive-images-in-columns

To disable responsive images, I use a TypoScript condition:

<pre>
[globalVar = LIT:{$page.enable.lazyLoad} &lt; 1]
tt_content.image.20.1.layoutKey = default
page.includeJSFooterlibs.responsiveimages >
[global]
</pre>

And LESS function .img-responsive() should also be disabled, I think this is possible with http://lesscss.org/features/#css-guards-feature

If you agree with me, that this is useful, I could implement this in my fork and you merge this later.

**Comment by No5251** [comment]
Hi, it would be useful for images in Atom/RSS feeds.

**Comment by benjaminkott** [comment]
Lazy loading of images can be set by adding the following to your configuration

```
plugin.bootstrap_package_contentelements.preload.images = 1
```

https://github.com/benjaminkott/bootstrap_package/blob/master/Configuration/TypoScript/constants.typoscript#L222-L225
