### ISSUE TITLE
Possibility to have 100% width frames

### ISSUE THREAD

**Issue by erthi16** [benjaminkott/bootstrap_package#732]
It would be interesting to be able to set zones like "Border, Before Content,...) to be 100% of the screen width.  For the time beeing, I have modified the layout Resources/Private/Layouts/ContentElements/Default.html to add a class "frame-" with the colPos value.  For exemple, this gives me the class "frame-3" for the Border frame.

My CSS changes the styles so that all content is not boxed anymore and my TYPO3 users are able to use full width carousels.

Thank you for your amazing work!

Eric Thibault
University Laval

**Comment by gilbertsoft** [comment]
Copy of a answer in Slack:

Eduardo C Frank  vor 39 Minuten
The feature you wish for is already implemented.

Eduardo C Frank  vor 37 Minuten
If you choose No frame, as in the pic below, you get the result you seek. (bearbeitet)
https://files.slack.com/files-pri/T024TUMLZ-FLS4YK3QA/screen_shot_2019-08-06.png

**Comment by erthi16** [comment]
Simple, effective... that's the way to go! Thank you for pointing me in the right path!

Eric Thibault
