### ISSUE TITLE
Text icon too small

### ISSUE THREAD

**Issue by blueamerican** [benjaminkott/bootstrap_package#737]
after update from 10.0.7 to 11.0.0 a texticon (bell, see screen attached)
appears to small in FE

Before the update is was as big as the lightblue background.

TYPO3 9.5.8
![texticon](https://user-images.githubusercontent.com/5647051/62887991-ad9ed380-bd3e-11e9-8da1-b5d84c17fe05.jpg)

**Comment by benjaminkott** [comment]
@blueamerican the svg seems to have the correct size - and the others seem to be sized correctly - could you provide that svg because i think the svg itself prevents the scaling.

**Comment by web2date** [comment]
I can confirm the behaviour with Glyphicons:
![image](https://user-images.githubusercontent.com/8898397/63162878-fb0f8f00-c023-11e9-8e80-8704ba6ff911.png)
![image](https://user-images.githubusercontent.com/8898397/63163005-7113f600-c024-11e9-9361-25013948e3f9.png)
![image](https://user-images.githubusercontent.com/8898397/63163022-7f621200-c024-11e9-9c21-10e95003167d.png)
It seems to be a problem with Glyphicons....

**Comment by benjaminkott** [comment]
thx @blueamerican and @web2date that this is only happening for glyphicons gave the final hint.
the view box attribute was dropped by accident in an optimization step - that was the root cause of the issue.
