### ISSUE TITLE
Changing data-maxwidth on images

### ISSUE THREAD

**Issue by Vik29** [benjaminkott/bootstrap_package#746]
# Support

**Is your question related to a problem? Please describe.**
The image renderer 
[https://github.com/benjaminkott/bootstrap_package/blob/master/Resources/Private/Partials/ContentElements/Media/Rendering/Image.html](url)
has some predefined max-widths on different breakpoints.

I want to implement some images that are full width on the screen like 1920px width for example.
I think I need to change the max-widths in the renderer to do so, or is there a better solution?
How can i set individual max-widths?

**Comment by taunusweb** [comment]
Had the same problem today, you can set this in your TS:
`lib.contentElement.settings.responsiveimages.variants.default.width = 1920`

**Comment by Vik29** [comment]
That worked great. Thx a lot
