### ISSUE TITLE
overwrite page.10.variables.pageTitle with RECORDS

### ISSUE THREAD

**Issue by EnzephaloN** [benjaminkott/bootstrap_package#747]
# Support

Hello 
I'm trying to overwrite page.10.variables.pageTitiel with typoscript RECORDS:
``` 
page.10.variables{
    pageTitle = RECORDS
    pageTitle {
        tables = tx_news_domain_model_news
        source {
            data = GP:tx_news_pi1|news
            intval = 1
            insertData = 1
        }


        conf{
            tx_news_domain_model_news = TEXT
            tx_news_domain_model_news.field = title
        }
    }
}
```
But sadly this does not work.
What shoudl I do?

**Comment by jokumer** [comment]
EXT:news can override page title itself, using its TitleTagViewHelper.
Have a look at FLUID EXT:news/Resources/Private/Templates/News/Detail.html `<n:titleTag>`

**Comment by EnzephaloN** [comment]
@jokumer This works. But it would be also nice to be able to overwrite this with typoscript.

**Comment by EnzephaloN** [comment]
...also
```
page.10.variables{
    breadcrumbExtendedValue = RECORDS
```
should work, but doesn't. Or I'm totally wrong?

**Comment by gilbertsoft** [comment]
Yes, this works, but your code looks wrong:
- you do not delete the existing TEXT CE, so `data` will stay here what probably not is what you want
- `intval` results in returning a 1, what should this be good for?
- `insertData` is not needed for data, only if you insert data by another wrap e.g.

The rest is fine and this is the result:
```
page.10.variables.pageTitle >
page.10.variables.pageTitle = RECORDS
page.10.variables.pageTitle {
    tables = tx_news_domain_model_news
    source {
        data = GP:tx_news_pi1|news
    }
    conf {
        tx_news_domain_model_news = TEXT
        tx_news_domain_model_news.field = title
    }
}
```
But if you expect that the title tag is changed now, you are wrong. By this code you change the variable `pageTitle` only which you can use in your Fluid templates. If so you should have a look at `config.pageTitle*` with your TypoScript Object Browser or see https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/Setup/Config/Index.html#pagetitle

**Comment by gilbertsoft** [comment]
@EnzephaloN ping

**Comment by EnzephaloN** [comment]
Hello @gilbertsoft .
The TS I wrote did his work - but does not with bootstrap_package. TS-setting intval is used to be safe that parameter "tx_news_pi1[news] is integer only. I can't remember why it was necessary to use insertData - but it was.

The project was finished using title-tag viewhelper from EXT:news. Maybe I can check your code next week with an old projects development-copy.

Thanks for your work.
