### ISSUE TITLE
Is OnePage static template gone?

### ISSUE THREAD

**Issue by narayaralian** [benjaminkott/bootstrap_package#749]
# Support

**Hi Benjamin,
My client is currently using bootstrap_package 6.2.15 with OnePage static template (as a landing page). We need to upgrade typo3 and the bootstrap package to the latest versions but it looks like OnePage is missing in all versions higher 6.2.16. Is it completely gone? Are there any workarounds that we could use? Thank you!**

**Comment by Moongazer** [comment]
+1 for onepage layout feature

I tried to combine bootstrap_package with bwrk_onepage, but gave up after several approaches to reuse the BP layout and partials. The problem with BERGWERK is, that they render everything as content-plugin, so its not possible to render their menu into the navbar header up in the hierarchy.

**Comment by taunusweb** [comment]
Have a look: at #344

**Comment by narayaralian** [comment]
Thank you so much!
