### ISSUE TITLE
Cant edit Footers Backgroundcolor in v11.0.1

### ISSUE THREAD

**Issue by MartinH0** [benjaminkott/bootstrap_package#757]
# Bug Report

## Prerequisites

* [x] Can you reproduce the problem on TYPO3 v10.1.0 LTS
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package) to see if your bug or enhancement is already reported?

## Description

In the file "_footer.sass" th Background of the section gets set by the variable "$footer-background" which again get loaded from the $settings "background"
![Bootstrap Package Footer Background](https://user-images.githubusercontent.com/17692860/66092722-52929b80-e58d-11e9-8a16-0f3788a050e6.PNG)

..but in the Constant-Editor there is no way to edit this or to edit anything in the footer or any section-background.
These variables are **NOT** in the Constant-Editor for Bootstrap v4 (SASS)

Also the new "Timeline" variables are not editable from the Constant-Editor.

## Steps to Reproduce

1. install bootstrap_package (v11.0.1)
2. G to the Constant-Editor
3. Search for a way to edit the Footer

**Expected behavior:** There should be a way (like in the good old versions) to edit the Footer like it was and is possible in Bootstrap v3 (LESS) Like on the pic below:
![Bootstrap Package Old Settings](https://user-images.githubusercontent.com/17692860/66092781-a8674380-e58d-11e9-9863-77690f4e39c0.PNG)

**Actual behavior:** No way to edit the Footer in Bootstrap v4 (SASS)

## Versions
TYPO3 | 10.1.0
bootstrappackage | 11.0.1
introduction | 4.2.0

Anyone else does face this issue?

**Comment by gilbertsoft** [comment]
Yes, this behaviour has a little bit changed. Here is a sample to change your footer colors:

```
plugin.bootstrap_package.settings.scss {
    primary = #00883E
    secondary = #CCE5A2
    footer-sections = (content:(background: $body-bg, color: $body-color, link-color: $primary), meta:(background: #f6f6f6, color: #313131, link-color: $primary))
}
```

This code changes the primary and secondary colors and sets new colors to the footer.

**Comment by MartinH0** [comment]
> Yes, this behaviour has a little bit changed. Here is a sample to change your footer colors:
> 
> ```
> plugin.bootstrap_package.settings.scss {
>     primary = #00883E
>     secondary = #CCE5A2
>     footer-sections = (content:(background: $body-bg, color: $body-color, link-color: $primary), meta:(background: #f6f6f6, color: #313131, link-color: $primary))
> }
> ```
> 
> This code changes the primary and secondary colors and sets new colors to the footer.

Thanks!
I hope this will be editable from the constant-editor soon ;)
