### ISSUE TITLE
disableCssProcessing option still calls the css processing hooks

### ISSUE THREAD

**Issue by ebincm** [benjaminkott/bootstrap_package#760]
# Bug Report

## Prerequisites

TYPO3 v9.5 LTS

## Description

I have disabled the css processing by enabling disableCssProcessing in the extension configuration settings  , but it still calls the css processing hooks. 

What I have found that the disableLessProcessing always returns false and the condition is met for css processing hooks in the ext_localconf.php file

Provide disableLessProcessing in the Extension coniguration also. 
So that it can be also managed by on/off button.

**Comment by benjaminkott** [comment]
@ebincm thanks for pointing that out - the disable less processing was meant as a fallback for older instances, I dropped the option now, that should resolve your issue.
