### ISSUE TITLE
Section Index Menu does not respect sorting order

### ISSUE THREAD

**Issue by ChrisSoelder** [benjaminkott/bootstrap_package#762]
# Bug Report

## Prerequisites

* [ ] Can you reproduce the problem on TYPO3 v8.7 LTS
* [x] Can you reproduce the problem on TYPO3 v9.5 LTS
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package) to see if your bug or enhancement is already reported?

## Description

The Section Index Menu does not respect the sorting order of the Content on the Page.

## Steps to Reproduce

1. Create 2 Content Elements on a Page with Section Index Option Enabled
2. Add Section Index Menu
3. Change Order of the Content on the page

**Expected behavior:** The List should reflect the sorting order of the content as it is displayed on the page

**Actual behavior:** The List shows the content in the order it has been created

## Versions

bk2k/bootstrap-package          v11.0.1
typo3                                          v9.5.10

## Possible Solution

The following Typoscript Config solved the issue for me

```
tt_content.menu_section {
  ##########################
  ### DATA PREPROCESSING ###
  ##########################
  dataProcessing {
    10 {
      dataProcessing {
        20 {
          orderBy = sorting
        }
      }
    }
  }
}
```

**Comment by benjaminkott** [comment]
@ChrisSoelder thx a lot for the report! Checked it against the core and backported the patch.

**Comment by ChrisSoelder** [comment]
Awesome! Thanks for the fast fix!
