### ISSUE TITLE
[BUG] Regression in scssphp/scssphp 1.0.4 and 1.0.5

### ISSUE THREAD

**Issue by mediaessenz** [benjaminkott/bootstrap_package#763]
e.g. the TypoScript Constant
`custom-switch-indicator-border-radius` = $custom-control-indicator-size / 2`

result in an invalid css like this:
`border-radius: 1rem / 2;`

## Steps to Reproduce

1. add a custom element like checkbox with surrounding css classes "form-group custom-control custom-switch" and a label with class "custom-control-label"
2. see generated invalid css on the ::before pseudo class of the label 

**Expected behavior:** 
get a css with `border-radius: 0.5rem;`

**Actual behavior:** 
get a css with `border-radius: 1rem / 2;`

## Versions
10.0.8

**Comment by benjaminkott** [comment]
@mediaessenz can confirm this behavior this is addressed with https://github.com/scssphp/scssphp/commit/ee2b052b7da888b6b4981365b150e8758bfcef10

and will probably be fixed in 1.0.6

It´s currently not working fine in:
https://github.com/scssphp/scssphp/releases/tag/1.0.5
https://github.com/scssphp/scssphp/releases/tag/1.0.4

Recommended solution:
```
composer require scssphp/scssphp:dev-master
```
or downgrade to 1.0.3
```
composer require scssphp/scssphp:1.0.3
```

**Comment by mediaessenz** [comment]
I just installed dev-master version of scssphp/scssphp, but the problem still exists

**Comment by benjaminkott** [comment]
mm.. strange, added a test for your case in the patch - seems to work here. see https://github.com/benjaminkott/bootstrap_package/pull/764/files

**Comment by mediaessenz** [comment]
Maybe the problem only exists, if the result of the calculation is stored in another scss variable, like this is the case in bootstrap.
$radius= 1rem
$halfradius = $radius / 2
.selector { border-radius: $halfradius }

**Comment by benjaminkott** [comment]
Still having problems reproducing the behavior - works here on, added more test cases

**Comment by mediaessenz** [comment]
Maybe it's not a problem of the compiler itself, than more of the combination of your code and theirs.
To reproduce the problem, just add a checkbox with the following markup into a eg. html-content-element:
```
<div class="custom-control custom-switch">
   <input type="checkbox" name="check-button" autocomplete="off" class="custom-control-input" value="true" id="test"><label class="custom-control-label" for="test">Checkbox in switch style</label>
</div>
```
Normally the switch should appear rounded, but it's squared, because of the wrong generated in the ::before-css.

**Comment by gilbertsoft** [comment]
New release https://github.com/scssphp/scssphp/releases/tag/1.0.6
