### ISSUE TITLE
	 Oops, an error occurred! DateTime::__construct(): Failed to parse time string (1571338620) at position 7 (6): Unexpected character

### ISSUE THREAD

**Issue by filoucrackeur** [benjaminkott/bootstrap_package#766]
# Bug Report
	
Oops, an error occurred!
DateTime::__construct(): Failed to parse time string (1571338620) at position 7 (6): Unexpected character

## Prerequisites

* [ ] Can you reproduce the problem on TYPO3 v8.7 LTS
* [ ] Can you reproduce the problem on TYPO3 v9.5 LTS
* [X] Can you reproduce the problem on TYPO3 v10.1 LTS
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package) to see if your bug or enhancement is already reported?

## Description

When i put a date in calendar selector in timeline content item
DateTime::__construct(): Failed to parse time string (1571338620) at position 7 (6): Unexpected character

## Steps to Reproduce

Choose content chronology
Add Item
Put Date and save

**Comment by gilbertsoft** [comment]
Can confirm this exception after I have added a date manually, date picker does not open here.

Works fine with TYPO3 9.5.

**Comment by gilbertsoft** [comment]
Seems to concern two core bugs:
- bug in handling TCA dbType `datetime`, where the mentioned exception is thrown
- bug with date time picker in inline items, date/time selection does not open on clicking the calendar icon

**Comment by benjaminkott** [comment]
Seems to be related to https://review.typo3.org/c/Packages/TYPO3.CMS/+/62197

**Comment by gilbertsoft** [comment]
Can confirm with this patch the issues are gone.

This patch will be included in release 10.2 beginning of december.

I'm gonna close this issue now, if you don't agree feel free to reopen it. Thanks for reporting anyway!
