### ISSUE TITLE
Richt Text Editor in Carousel Element when Type is "HTML"

### ISSUE THREAD

**Issue by andihuber** [benjaminkott/bootstrap_package#770]
Since Version 10 there is a RTE in Carousel Element also when type is HTML.

https://github.com/benjaminkott/bootstrap_package/commit/3049b3455dc3a0eb201dc1d6431da33a63a30bfe

Which seems to be a bug regarding Benjamin Kott's reply at Slack Chat.

**Comment by benjaminkott** [comment]
@andihuber and @gilbertsoft thx for the evaluation in slack - that one slipped, seems to be fine in v10 but broken in v11
