### ISSUE TITLE
Radio buttons not visible

### ISSUE THREAD

**Issue by ehwg** [benjaminkott/bootstrap_package#779]
# Bug Report

## Prerequisites
[X] Can you reproduce the problem on TYPO3 v9.5 LTS

## Description
When using a radio button in a from together with BP v10 the radio button is not displayed. This happens with different browsers such as Chrome and Firefox.

## Steps to Reproduce
create a form with radio buttons ad view the form

**Expected behavior:** I would like to see the radio button, in order to click it.

**Actual behavior:** radio button is not visible
## Versions
BP V10 Typo3 V9 LTE.

## Root cause analysis: 
the css class  custom-control-input is attached to the tag:

<input class="custom-control-input form-check-input" type="radio" name="tx_form_formframework[kontaktanfrage-22][radiobutton-1]" value="Musik">
The problematic atttributes are:     z-index: -1;  opacity: 0;
This is because of the Setup.yaml file in Configuration/Form 
Suggested solution Please remove the RadioButton: properties: elementClassAttribute section or set it to ''. 
See also attached screenshot which shows the rendering with (red mark) and without (green mark) the class, when manipulated in the developper tools. 
Best regards
Eckard.

![radio_button_issue](https://user-images.githubusercontent.com/7009080/68760739-da4ed980-0612-11ea-80f2-b7fe457f0b77.jpg)

**Comment by gilbertsoft** [comment]
I tried to reproduce your issue but I'm not able to do so. I've tested here with BP 10.0.8-dev and TYPO3 9.5.11. Are you probably using the legacy form framework? I'm getting here a complete different HTML output!

**Comment by ehwg** [comment]
No, I am not using the old form, I am using the new form engine. It is a radio button, I am using.
[RadioButton.txt](https://github.com/benjaminkott/bootstrap_package/files/3846789/RadioButton.txt)
I extended the form with the linked checkbox (extension of the checkbox)
[LinkedCheckbox.txt](https://github.com/benjaminkott/bootstrap_package/files/3846791/LinkedCheckbox.txt)
 and there I had the same issue. Maybe you can send me your html output. Do you have the class custom-control-input . What I added in the radioboxes is an additional counting and appropriate class check1, check2, ... within the group so I can set different colors.
I have attached you my adopted RadioButton.html as txt file

**Comment by gilbertsoft** [comment]
Ok, I see. Have to check your custom code first...

**Comment by erthi16** [comment]
Hello!

Just a thought... as in the CSS, it is normal that the actual input is not displaying but there is supposed to be "before" and "after" pseudo elements to "paste" a custom graphic instead... Do you have those styles?

Have a nice day!

**Comment by ehwg** [comment]
Hi, I upgraded to bootstrap11 and added a standard checkbox element and there it works. So I will have a look at my custom code. Seems that it is from BP v7 with typo3 v8.  So some more work to do for the upgrade. Thank's for the hints.

**Comment by gilbertsoft** [comment]
@ehwg So can we close your issue?

**Comment by ehwg** [comment]
Yes, we can close it, thanks for the hints.
