### ISSUE TITLE
Images blurry on Smartphones

### ISSUE THREAD

**Issue by ma8bi4ne** [benjaminkott/bootstrap_package#785]
Dear community,
I am using bootstrap-package 11 on several Typo3-Pages with 9.5.11 and observe the same issue on all of them:
The images, especially in Carousels etc., resize on smartphones and appear very blurry/unsharp. Actually, the look like they are being upscaled from smaller image versions.
Is there a way to set minimum sizes etc. to avoid this?
Best regards
Greg

**Comment by gilbertsoft** [comment]
Do you use the original Fluid templates? If not you perhaps have a misstake in your templates.

Other thing you can try is to adapt the image rendering settings see https://docs.typo3.org/p/bk2k/bootstrap-package/master/en-us/Configuration/ImageRendering/Index.html

**Comment by ma8bi4ne** [comment]
Thanks, the hint with the image rendering settings solved the problem for me!
