### ISSUE TITLE
change default width of processed carousel background images

### ISSUE THREAD

**Issue by Maikel70** [benjaminkott/bootstrap_package#797]
Hi,
where can I change the default width of the processed carousel background images.
current the background images will be processed to:
width: 1100
width: 920
width: 680
width: 500
width: 374
Where can I change this values?

Thanks

**Comment by gilbertsoft** [comment]
Hi @Maikel70 

Please have a look at https://docs.typo3.org/p/bk2k/bootstrap-package/master/en-us/Configuration/ImageRendering/Index.html

**Comment by Maikel70** [comment]
Thank you for your prompt reply.
problem solved.
:-)
