### ISSUE TITLE
Display limit for items of card of subpages

### ISSUE THREAD

**Issue by kalinka2103** [benjaminkott/bootstrap_package#803]
Hi there! Is it possibly to set a limit for the shown card of subpages? For example to display only 4 subpages? I want to use the card of subpages to show the latest items of a blog, but not all, just some latest. If this is not possible, is there another option to realize this? Thanks in advance!

**Comment by rumpfwerk** [comment]
you can do this by css: nth-child(n+x)
habe a look here:
https://stackoverflow.com/questions/22035799/css-nth-child-for-greater-than-and-less-than

**Comment by gilbertsoft** [comment]
@kalinka2103 Does this answer your question?

**Comment by kalinka2103** [comment]
Hi @gilbertsoft, I haven't included an own CSS yet so I could not test. I will give a feedback these days.

**Comment by gilbertsoft** [comment]
@kalinka2103 You can use something like this in you r TypoScript setup to configure menu processor:

```
[page["uid"] == 1]
tt_content.menu_card_dir.dataProcessing.20.maxItems = 4
[GLOBAL]
```

In contrast to the solution of @rumpfwerk this will reduce the rendered items by the menu processor and not hide them via css only - which of course is faster. Btw you can use most options here of the HMENU see https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/ContentObjects/Hmenu/Index.html and https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/frontend/Classes/DataProcessing/MenuProcessor.php#L88
