### ISSUE TITLE
Changing margin for content elements possible?

### ISSUE THREAD

**Issue by kalinka2103** [benjaminkott/bootstrap_package#805]
Hello again, I have one more question: I set up a smaller size for a headline class (1.25rem to 1.1rem) but the distance (should be the margin?) to another content element is not changed. So with the font size getting smaller, the distance looks larger now. Is there a option to change this?

**Comment by pstranghoener** [comment]
You can change every CSS Class via TS

Just like this for eg:

page.cssInline {
    10 = TEXT
    10.value (
        .navbar-inverse { background-color: #FF0000 !important; }
    )
}

**Comment by rumpfwerk** [comment]
yes, and if you want to do more, you can use your own css. 
via TS (Page-TypoScript)


page.includeCSS {
  somecssid = fileadmin/css.css
  somecssid {
      disableCompression = 0
      excludeFromConcatenation = 0
  } 
}

In this way, your css will be concatenated with the outher css-stuff und compressed. 
the result will be cached and everything is smooth and fast ;-)

**Comment by pstranghoener** [comment]
The best way for me is to create a Childtheme with  https://sitepackagebuilder.com and make the change in the less files of this Theme.

**Comment by gilbertsoft** [comment]
@kalinka2103 Is your question answered?

**Comment by kalinka2103** [comment]
Hi @gilbertsoft, I haven't included an own CSS yet so I could not test. I will give a feedback these days.

**Comment by kalinka2103** [comment]
I experimented with changing some classes that are "near" to a content element and found this:
`.frame-space-after-none {`
`  margin-bottom: 0rem;`
`}`

With this I can set a margin at the place I meant, but unfortunately it is already at 0rem. If I set it for example to something like -4rem the distance between the content element(s) is reduced, but this affects the navbar (breadcrumbs) too, which moves right into the header then. So I guess this is not exactly the class I was looking for. I will tell you, if I find it.

**Comment by gilbertsoft** [comment]
This margins are calculated see https://github.com/benjaminkott/bootstrap_package/blob/master/Resources/Public/Scss/Theme/_variables.scss#L111 and https://github.com/benjaminkott/bootstrap_package/blob/master/Resources/Public/Scss/Theme/_frame.scss#L23

To change it simply add something like this to your TypoScript template constants:
> plugin.bootstrap_package.settings.scss.frame-inner-spacing-scaling = (lg: 1, xl: 1.25)

**Comment by kalinka2103** [comment]
That was what I was looking for, thanks! Had not checked the SCSSs.
