### ISSUE TITLE
Box like bp-config possible?

### ISSUE THREAD

**Issue by kalinka2103** [benjaminkott/bootstrap_package#806]
Hello again! Does anyone know how to use a box (i don't know how to describe it better) like the bp-config on the official bootstrap package website? It is the small icon that expand to a box where you can select color/font of the bootstrap package. I would like to get something like that displayed for logged in FE users.

<img width="1440" alt="Bildschirmfoto 2019-12-05 um 19 02 54" src="https://user-images.githubusercontent.com/58035709/70261096-03860400-1792-11ea-8816-2232d995a6f5.png">

<img width="1440" alt="Bildschirmfoto 2019-12-05 um 19 03 01" src="https://user-images.githubusercontent.com/58035709/70261095-03860400-1792-11ea-8f54-30f5943cfe93.png">

**Comment by gilbertsoft** [comment]
@kalinka2103 Have a look at https://github.com/benjaminkott/bootstrap_package_config/ especially https://github.com/benjaminkott/bootstrap_package_config/blob/master/Resources/Private/Templates/Config/Default.html

**Comment by kalinka2103** [comment]
Hi @gilbertsoft, thanks (again) for your help. The Default.html I've already found. But I don't see an option to use the bp-config as something like a plugin / content element?

**Comment by gilbertsoft** [comment]
No, you can't use this out of the box. That was created for bootstrap-package.com. But it's a good starting point for you to create a such feature in your sitepackage instead.

**Comment by kalinka2103** [comment]
I will definitely try to work that out, thanks!
