### ISSUE TITLE
ddev caching with tmpfs not working after restart

### ISSUE THREAD

**Issue by createdwithlove** [benjaminkott/bootstrap_package#833]
# Bug Report

## Prerequisites

* [x] Can you reproduce the problem on TYPO3 v10.2.0
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package)
  to see if your bug or enhancement is already reported?

## Description

After `ddev restart` following error occurs: 
```The directory "/var/www/html/.build/var/cache/code/core/" can not be created.```

## Steps to Reproduce

1. Clean install (git clone, composer install)
2. `ddev start`-> everything works fine
3. `ddev stop`
4. `ddev start` -> error

## Workarounds
- `rm -r .build/var/cache` -> just works till next start
- `chmod -R 777 .build/var/cache`
- remove 'docker-compose.tempfs.yaml'

## Versions

- TYPO3 10.2.0
- Bootstrap Package 11.1.0-dev
- Docker 19.03.5, build 633a0ea
- DDEV v1.12.0
- macOS 10.15.2

**Comment by gilbertsoft** [comment]
@rfay any idea on this? On Windows we have the opposite, without the [tempfs config](https://github.com/benjaminkott/bootstrap_package/blob/master/.ddev/docker-compose.tempfs.yaml) we get troubles

**Comment by rfay** [comment]
> The directory "/var/www/html/.build/var/cache/code/core/" can not be created

Does the directory already exist, and the code naively try to create it and fail? Please try just the `ddev stop` (instead of restart) and inspect (on the host) .build/var/cache (and children) and their permissions

**Comment by createdwithlove** [comment]
Sorry, maybe my knowledge about docker and how it handles permissions is too low.

As far as I can say, the only workaround is too set permissions on `var/cache/` to at least 775 – this still works after `ddev stop/start/restart`.

Deleting the `cache` folder before or/and after `ddev start` just works until next `ddev stop` or `ddev restart`. The newly created `cache` directory has permission 755.

**Comment by rfay** [comment]
Unfortunately, docker handles permissions differently on different platforms. Windows makes it pretty much a disaster. But in general, everything inside the container is as writable as on the host. Still, as above (https://github.com/benjaminkott/bootstrap_package/issues/833#issuecomment-565456317) the most likely reason for failing to create is parent directory not existing.

**Comment by gilbertsoft** [comment]
@createdwithlove is this still an issue or can we close it?

**Comment by createdwithlove** [comment]
@gilbertsoft I think the problem still exists. Currently working with the mentioned workaround (`chmod 755`) solves the problem for me. If I'am the only one who experiences this problem I won't complain if you close it.

**Comment by pxPP** [comment]
Same issue for me :/
