### ISSUE TITLE
I see an error in console of browser

### ISSUE THREAD

**Issue by typo3ua** [benjaminkott/bootstrap_package#834]
# Bug Report

After Update to the last version, I see an error in console of browser

## Prerequisites

* [X] Can you reproduce the problem on TYPO3 v9.5 LTS

## Description

After Update to the last version, I see an error in console of browser

```
Uncaught TypeError: Cannot read property 'classList' of undefined
    at animateHeader (merged-cc3f4158bfb0cb0d11780e1fa49b5285-875f05e8373745d866efe6db70324a13.js?1576277514:37)
```

The same I see on the https://www.bootstrap-package.com/ .. too'

In the bootstrap_package - 11.0.1 was no this error

### Screenshots

![eror_console_classList](https://user-images.githubusercontent.com/638022/70851409-4c7a3e80-1e9d-11ea-8fa1-754906c64630.png)

## Versions

TYPO3 9.5.11 / not composer
PHP 7.2.xx
bootstrap_package - 11.0.2

**Comment by gilbertsoft** [comment]
- Related PR #784
- Source: https://github.com/benjaminkott/bootstrap_package/blob/master/Resources/Public/JavaScript/Src/bootstrap.stickyheader.js#L3
- Docs: https://developer.mozilla.org/en-US/docs/Web/API/Element/classList

Seems to be valid code, don't know why this error is thrown currently.

**Comment by joey-beech-it** [comment]
Error is still present:

bk2k/bootstrap-package: 10.0.9
typo3 v9.5.20

**Comment by sirkostenz** [comment]
The error also exists in:

bk2k/bootstrap-package: 11.0.2

**Comment by blueamerican** [comment]
workaround:
typoscript setup:
page.includeJSFooterlibs.bootstrap_stickyheader >
