### ISSUE TITLE
Dropdown Menu no more working after decrease and resize the page when hamburger menu is active..

### ISSUE THREAD

**Issue by juergen1964** [benjaminkott/bootstrap_package#837]
Hello and thx for the nice bootstrap_package and spending so much time to develop!

I got a issue with the drop-down menu.
I decrease the browser window till the hamburger-menu show up. Then I use the navigation of the hamburger-menu and got them in active status. Then resize the browser and the drop-down menu is no more working. By hovering the dropdown-menu on the right side arrows pop up and no drop-down list is seen anymore after resizing the page.
If i do the same with a no active hamburger-menu (just close the hamburger-menu before resize the page) everything works fine - so this issue is only when the hamburger-menu is still in active state when resize the browser window.
Can someone confir this behavior?
Maybe there is a solution to set the hamburger-menu to inactive when resize the window? Maybe via Js?
Thanks for any help!
Greetings Jürgen

**Comment by gilbertsoft** [comment]
Hi @juergen1964 

I'm trying to reproduce you issue but I'm not able to do so. Please tell us a little bit more about your TYPO3 and Bootstrap Package versions used.

Are you able to reprduce it on https://www.bootstrap-package.com/ ?

**Comment by juergen1964** [comment]
Hi there!
Yes i can redroduce it on https://www.bootstrap-package.com
Just go there  open the page - decrase the browser window so the hamburger-menue comes up. Open the hamburger-manue and leave em open - bring the browser window back to full size and move with the mouse ober the the link "content examples".
If you cant reproduce it i can make screen-shots tomorrow.
Thank You very much for your help!

**Comment by gilbertsoft** [comment]
Perfect, can reproduce it now! Will have look what we can do here...
