### ISSUE TITLE
Webperf - Google Fonts - Load woff & woff2

### ISSUE THREAD

**Issue by GuillaumeGBzh** [benjaminkott/bootstrap_package#840]
# Feature Request

## Is your feature request related to a problem? Please describe

Currently, only .woff versions of Google Fonts are used.

WOFF2 is the most advanced font format. It offers the benefit of reducing file size by 30% on average and by over 50% in certain cases compared to the WOFF format.

## Describe the solution you'd like

Load the woff and woff2 versions to improve performance.
It is necessary to keep the woff format for old browsers (IE11 #751).

## Additional context

Google Font takes into account the User Agent to serve the CSS file.
It is therefore necessary to make a request by desired format.

Development tracks:
* https://stackoverflow.com/questions/10300143/how-to-download-multiple-formats-of-a-web-font-from-the-official-google-web-fo
* https://gist.github.com/nikoskip/bcf58106f728a3e7b7f9dcb6edaa1e82 reuse `parseCss()` ?

**Comment by cosmonoid** [comment]
I had the problem when using polish text that font is not rendered properly. So I changed User-Agent in GoogleFontService.php from 
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/6.0)
to
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:82.0) Gecko/20100101 Firefox/82.0
and it loads the .woff2 fonts and renders polish text correct.
