### ISSUE TITLE
How to define positon of top menu ?

### ISSUE THREAD

**Issue by ds2k5** [benjaminkott/bootstrap_package#841]
Hello,
need to know how to define the positon of the Menu.
The LOGO is on the left but the 1st Menu Point is far away.
How to define the menu starts left instead of right ?

![logo_menu](https://user-images.githubusercontent.com/11292286/72201642-874ca380-3456-11ea-9be4-a241fcc20a33.png)

Template:

page.theme.navigation.type = top

**Comment by gilbertsoft** [comment]
Hi @ds2k5 

You can insert a page of type divider which will split the menu into two parts. The first pages before the divider will be placed on the left, the rest on the right like in your screenshot.

Bigger changes you have to put into your SCSS files in your sitepackage.

Regards
Simon

**Comment by gilbertsoft** [comment]
Was you question answered and can we close this issue?

**Comment by ds2k5** [comment]
Can I got example please ?

**Comment by gilbertsoft** [comment]
Have you tried the introduction distribution already? The menu there is setup with a divider after the home link.

![grafik](https://user-images.githubusercontent.com/25326036/72345222-72307880-36d3-11ea-93da-8d617a43ba8c.png)

**Comment by ds2k5** [comment]
Did not have a "Divider" set

It can be that I had installed, but can no see it under installed extensions.

**Comment by ds2k5** [comment]
Ok now I understand!
Thanks!
