### ISSUE TITLE
How to remove the LINE between the Menu and the Content ?

### ISSUE THREAD

**Issue by ds2k5** [benjaminkott/bootstrap_package#842]
Hello,
how can I disable the LINE between the Menu an the Content ?

![line](https://user-images.githubusercontent.com/11292286/72201698-21ace700-3457-11ea-854f-ada974066c52.png)

**Comment by gilbertsoft** [comment]
You have to redefine the CSS part in your sitepackage to not to show this line, e.g.:

.navbar-mainnavigation {
	box-shadow: 0;
}

**Comment by ds2k5** [comment]
Thanks, is this possible to define in the Template ?

like:

page.theme.navbar-mainnavigation.box-shadow=0

**Comment by gilbertsoft** [comment]
No, you only can set values for variables e.g. https://github.com/benjaminkott/bootstrap_package/wiki/Customize-Footer-Colors. If you not already have go to https://www.sitepackagebuilder.com/ and create your sitepackage to adapt the theme.

**Comment by gilbertsoft** [comment]
Is your question answered now and can we close the issue?

**Comment by ds2k5** [comment]
yes, thanks

**Comment by ds2k5** [comment]
Tryed it in:

typo3conf/ext/bootstrap_package/Resources/Public/Css/bootstrap3-rte.css and
typo3conf/ext/bootstrap_package/Resources/Public/Css/bootstrap4-rte.css

but did not work, the LINE is still there...

**Comment by gilbertsoft** [comment]
Please never edit extension files. Your changes will be lost after an update. Instead create a sitepackage and make your changes there. See https://www.sitepackagebuilder.com/

The *-rte.css files are for the backend and not used in the frontend.

You can simply add the lines I've posted in my first comment to the theme.scss of your sitepackage (ext:sitepackage/Resources/Public/Scss/Theme/theme.scss).

**Comment by ds2k5** [comment]
can not install

        The extension bootstrap_package is installed in version 11.0.2 but needed in version 10.0.0 - 10.0.99

**Comment by gilbertsoft** [comment]
Yeah, we did not find the time to enable the creation of v11 compatible sitepackages so far. But as sitepackagebuilder is meant for the creation of a starting point for a sitepackage this is not a big issue: change the ext_emconf.php and composer.json to your versions and you should be done...

**Comment by gilbertsoft** [comment]
Fyi, the sitepackagebuilder should get updated shortly benjaminkott/packagebuilder#31

**Comment by gilbertsoft** [comment]
Changes are deployed, you are now able to create a compatible sitepackage by default.

**Comment by ds2k5** [comment]
Hi gilbertsoft,
thanks the new package from https://www.sitepackagebuilder.com can be imported without any errors.

But the LINE is still there.

Made on a SUBDomain a clean new side.
Installed: bootstrap_package 11.0.2 and the Package from sitepackagebuilder.com.
In the package I changed the file: 

Enabled the package in SiteTemplate

![template](https://user-images.githubusercontent.com/11292286/73045930-3d10ec80-3e70-11ea-86ad-d73baeb3a1d0.png)

In the file: Resources/Public/Scss/Theme/theme.scss

```
//
// Variables
//
@import "variables";

//
// Import needed Bootstrap Package Files
//
@import "../../../../../bootstrap_package/Resources/Public/Scss/Theme/theme";

.navbar-mainnavigation {
box-shadow: 0;
}

```

But he Line between the Menu and the Textarea is sill there.


![line](https://user-images.githubusercontent.com/11292286/73046609-16a08080-3e73-11ea-871b-7123135e4100.png)


What did I wrong ?

Thanks

**Comment by benjaminkott** [comment]
If you do not have your own sitepackage the easiest way to achieve this is to use this `typoscript` setup snipped.

```
page {
    cssInline {
        10 = TEXT
        10.value (
           .navbar-mainnavigation { box-shadow: none !important; }
        )
    }
}
```

**Comment by ds2k5** [comment]
Hi benjaminkott,
thanks that worked for me!
```
page {
    cssInline {
        10 = TEXT
        10.value (
           .navbar-mainnavigation { box-shadow: none !important; }
        )
    }
}

```
