### ISSUE TITLE
how to remove start banner (Bootstrap Logo before page is finnished loading)

### ISSUE THREAD

**Issue by lukasdoerr** [benjaminkott/bootstrap_package#843]

**Comment by gilbertsoft** [comment]
Hi @lukasdoerr 

I'm guessing you are talking about the preloader. Have a look at the TypoScript constants, there you can various options to set a preloader image or disable the preloader.

Regards
Simon

**Comment by lukasdoerr** [comment]
thank you. i didnt found the key now, but i think i will find it.

**Comment by n3amil** [comment]
should be page.preloader.enable = 0

**Comment by lukasdoerr** [comment]
> 
> 
> should be page.preloader.enable = 0

nope, sadly its not that easy :D - normally i could just write this in the setup but it doesnt work :(

**Comment by lukasdoerr** [comment]
![grafik](https://user-images.githubusercontent.com/54935227/72344725-3ea11e80-36d2-11ea-986a-a2c8eaaa2894.png)

thanks to @n3amil ;)

**Comment by gilbertsoft** [comment]
> 
> 
> > should be page.preloader.enable = 0
> 
> nope, sadly its not that easy :D - normally i could just write this in the setup but it doesnt work :(

It's a constant as I wrote in my first message, so setup won't work ;)
