### ISSUE TITLE
Feature: classes in body tag for CSS customization based on selected layout and other parameters

### ISSUE THREAD

**Issue by webian** [benjaminkott/bootstrap_package#85]
Hi @benjaminkott,
I'm implementing a Typoscript lib that edits the body tag adding some classes that can be useful to customize the CSS based on various parameters.
Example:
`<body class="uid3 treeLvl2 parentUid1 langUid1 bootstrap_package__default_subnavigation_right">`
This is a page:
* with uid=3
* in the 2nd level of the tree
* child of page with uid=1
* showing language with uid=1
* using "bootstrap_package__default_subnavigation_right" layout

If you think that this can be useful for EXT:bootstrap_package too then I can provide a patch.
Bye!

**Comment by benjaminkott** [comment]
I`ve implemented a variation of this so i can close this issue. Please have a look at the referenced commit to double check if this breaks your setup somehow.
