### ISSUE TITLE
Bug in the class 'accordion-title-link-state' - accordion

### ISSUE THREAD

**Issue by typo3ua** [benjaminkott/bootstrap_package#850]
![bs_accordions_icon_bug](https://user-images.githubusercontent.com/638022/73873100-a245e400-4859-11ea-98c1-b299d6390d47.png)

## Description

I can reproduce this only in Chrome (last version) as in my case it is the last line, so and  at yours, it is the third line "[Media Top](https://www.bootstrap-package.com/content-examples/interactive/accordion)"

**Comment by benjaminkott** [comment]
We changed the layout here, it should be resolved.
