### ISSUE TITLE
How to add Border around content element

### ISSUE THREAD

**Issue by JavierVelazquez** [benjaminkott/bootstrap_package#860]
Hello all, 
Does anyone know how to add a border to a content element (not on the "frame" drop down list in the appereance tab)
I am doing it using the content element's id and custom css but it is getting a long list of elements.
Maybe it is simple and I just can't find it. Thanks in advance.
Javier

**Comment by gilbertsoft** [comment]
What do you mean with `not on the "frame" drop down list in the appereance tab`, not using this select or currently not available in this select?

**Comment by JavierVelazquez** [comment]
Thanks for the answer!
It seems it used to be -correct me if I am wrong- one of the choices in the Appearance tab, Content Element Layout, in the drop down list under "Frame". But I would be happy to know any other way to make a border around a content element except custom css which is what I am using now because I have to add so many more. Will I have to add an extension or can the bootstrap border be used or made to appear in a menu.

**Comment by JavierVelazquez** [comment]
I got it done through PageTS config:
TCEFORM.tt_content.frame_class.addItems {
    custom-1 = Custom Border 1
    custom-2 = Custom Border 2
}
:)
