### ISSUE TITLE
Wrong require-dev entries

### ISSUE THREAD

**Issue by georgringer** [benjaminkott/bootstrap_package#878]
The following entries in `composer.json`

```
 "typo3/cms-felogin": "^9.5 || ^10.0 || 10.*@dev",
        "typo3/cms-form": "^9.5 || ^10.0 || 10.*@dev",
        "typo3/cms-indexed-search": "^9.5 || ^10.0 || 10.*@dev",
        "typo3/cms-info": "^9.5 || ^10.0 || 10.*@dev",
        "typo3/cms-lowlevel": "^9.5 || ^10.0 || 10.*@dev",
        "typo3/cms-tstemplate": "^9.5 || ^10.0 || 10.*@dev",
```

don't make sense. those are not dev dependendies. Either remove those entries or move to suggest section

**Comment by benjaminkott** [comment]
@georgringer that's not correct, these are used for local development

Also extensions are configured if loaded see, but not necessary to run the package:
https://github.com/benjaminkott/bootstrap_package/blob/master/Configuration/TypoScript/setup.typoscript#L18-L22

**Comment by gilbertsoft** [comment]
Agree, e.g. `typo3/cms-lowlevel` I have added because I often need it for debugging purposes during development.

**Comment by gilbertsoft** [comment]
@georgringer can we close this one?
