### ISSUE TITLE
Lost Backend Layouts after upgrade from 6.2.5 to 6.2.6

### ISSUE THREAD

**Issue by tuxstone** [benjaminkott/bootstrap_package#88]
Upgraded via Extension Manager, then the Layout selector and Page column layout are lost.
![captura de pantalla 2014-11-08 a las 10 43 31 a m](https://cloud.githubusercontent.com/assets/9626751/4964681/5d7c412a-6736-11e4-887c-b868b5b7e6d9.png)
![captura de pantalla 2014-11-08 a las 10 43 12 a m](https://cloud.githubusercontent.com/assets/9626751/4964683/60dac09e-6736-11e4-8c78-c8b8e42a0896.png)

Then solved edisabling and enabling again in the Extension Manager
![captura de pantalla 2014-11-08 a las 11 10 35 a m](https://cloud.githubusercontent.com/assets/9626751/4964714/f2b9d080-6737-11e4-92c3-61215508e2a4.png)

**Comment by benjaminkott** [comment]
There seems to be no more problems on that. I am closing this for now.
