### ISSUE TITLE
RTE styles broken for BP CTypes only

### ISSUE THREAD

**Issue by web2date** [benjaminkott/bootstrap_package#889]
# Bug Report

## Prerequisites

* [ ] Can you reproduce the problem on TYPO3 v8.7 LTS
* [ ] Can you reproduce the problem on TYPO3 v9.5 LTS
* [ ] Did you [perform a cursory search]

## Description

I can't add styles like Button, Lead, Primary... to bodytext field for Bootstrap Package Ctypes. The dropdown styles is missing as it shows only a default ckeditor configuration.

## Steps to Reproduce

Using BP with a sitepackage build with sitepackagebuilder.
 1. open a Ctype like text. You can add a for example a button style to a link. The dropdown “styles” is visible. 
2. Open for example a BP Ctype like textcolumn, textIcon or tab this dropdown isn’t available..
I think it is related to this changes https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.2/Important-88655-ChangedLoadingOrderOfRTEConfiguration.html

### Expected behavior

All predefined styles from BP RTE and from Sitepackage RTE should be available in all CTypes

### Actual behavior

Only default ckeditor configuration is available for BP CTypes

### Screenshots
1.
![image](https://user-images.githubusercontent.com/8898397/82357964-1ae64000-9a06-11ea-8ca3-058432be42af.png)
2.
![image](https://user-images.githubusercontent.com/8898397/82357924-11f56e80-9a06-11ea-9b74-9c7a2ee98c97.png)

## Versions

TYPO3 10.4.2 + 10.4.3 Bootstrap Package 11.0.2

**Comment by web2date** [comment]
I think I found a solution: remove 'richtextConfiguration' =>'default' from all BP Contentelements TCA

I tested it for example: line 214 => tx_bootstrappackage_accordion.php

**Comment by benjaminkott** [comment]
@web2date thx for reporting and figuring it out, pushed patches for it <3
