### ISSUE TITLE
Translated content element cannot be moved by drag'n'drop

### ISSUE THREAD

**Issue by olivermeckel** [benjaminkott/bootstrap_package#891]
# Bug Report

## Prerequisites

* [x] Can you reproduce the problem on TYPO3 v10.4 LTS
* [x] Can you reproduce the problem on TYPO3 v9.5 LTS
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package)
  to see if your bug or enhancement is already reported?

## Description

We created a multilingual website (for example: default language english, page translation to german).
We have made a translation of the pages. The content was translated and a direct relationship was established between the source language and the target language.

You can rearrange (change the order or move to other columns per drag'n'drop) content elements in the source language, but not in the target language.

### Expected behavior

Either the order is bound to the source language and the arrangements adapt automatically or you can change the arrangement in the target language.

## Versions

TYPO3 9.5 or 10.4 in the latest stable version, Bootstrap Package 11.0.2 and content by the introduction package

**Comment by gilbertsoft** [comment]
Thanks for your report. This issue is related to the TYPO3 Core and not the Bootstrap Package. But so far I thought it's only related to 10.4.x and not 9.5.x. Will have a look later for the related issues at https://forge.typo3.org or perhaps you are faster...

**Comment by olivermeckel** [comment]
Thank you for your feedback. You are absolutely right. And it's not a bug. I found the following for pages. I think it's the same for translated content elements.

`DataHandler: “sorting” and “pid” parameters of translations are always kept in sync one-to-one for translated pages. Translated pages cannot be moved themselves.`
