### ISSUE TITLE
External Links does not have "noopener" NOR "noreferrer"

### ISSUE THREAD

**Issue by MartinH0** [benjaminkott/bootstrap_package#895]
# Bug Report

## Prerequisites
* [X] Can you reproduce the problem on TYPO3 v10.4 LTS
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package)
  to see if your bug or enhancement is already reported?

## Description

When I check the Links on the right footer menu on bootstrap-package.com I can see `rel="noopener"` as its an external Link. This does not work for me. At least not for links which I created in the menu-tree as "external Link"

This may be a TYPO3 Core-Bug but how can this then work on the demo site?
Is the demo site on TYPO3 v9 and this Bug is just related to TYPO3 v10?

I'm using TYPO3 v10.4.3

### Expected behavior

Well. Especially "external Links" should have these parameters as google recommends this and marks my site (without these) as insecure.

### Screenshots
My Page:
![my Page](https://user-images.githubusercontent.com/17692860/83713863-8e549800-a629-11ea-8db3-03ac502a234a.png)

Demo Page:
![demo Page](https://user-images.githubusercontent.com/17692860/83713867-91e81f00-a629-11ea-8206-82bcc58ffebc.png)

## Versions

TYPO3 v10.4.3
BP 11.0.2 (also tested master)

**Comment by benjaminkott** [comment]
hey, the links on bootstrap-package.com were updated manually, so there is no automatic function for this. you can check https://github.com/b13/snipper for this.

**Comment by MartinH0** [comment]
Thanks! I will try this, even if I think this then is a TYPO3 Core Bug

**Comment by MartinH0** [comment]
Also this did not helped actually as I used a "menu" to display these links. Maybe I have to set manual links.
