### ISSUE TITLE
Timeline element: history too crowded

### ISSUE THREAD

**Issue by lisanoffke** [benjaminkott/bootstrap_package#898]
# Bug Report

## Prerequisites

* [ not tested ] Can you reproduce the problem on TYPO3 v8.7 LTS
* [ yes ] Can you reproduce the problem on TYPO3 v9.5 LTS
* [yes  ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package)
  to see if your bug or enhancement is already reported?

## Description

The timeline has been augmented by a single line and the resulting history is extremely long with items, that have not been touched. If I touch a single timeline item, that should be in the history, nothing else.

## Steps to Reproduce

1. Open a TYPO3 9.5.18.
2. Open an existing timeline element and change an existing timeline item.
3. Check page history.

### Expected behavior

1. Open a TYPO3 9.5.18.
2. Open an existing timeline element and change an existing timeline item.
3. Check page history: The changed timeline item is documented, nothing else.

### Actual behavior

1. Open a TYPO3 9.5.18.
2. Open an existing timeline element and change an existing timeline item.
3. Check page history: The changed timeline item is documented and all other timeline items as well which makes it quite messy.

### Screenshots

[If applicable, add screenshots to help explain your problem.]

## Versions

You can get this information from executing `composer show` at the command line
if your TYPO3 installation is composer based, otherwise the version number will
be shown in the extension manager.

**Comment by benjaminkott** [comment]
I´ve checked the behavior here are my observations:

1. I opened the record after a long time again and saved it, in this moment all child records got a new history entry.
2. After that i clicked on some elements and opened them and saved again. now only the opened elements got persisted.
3. I changed content at an entry, only that got persisted
4. I changed content again ant an entry, only that got persisted
5. I changed content at a different element, opened some others - only that  touched elements got a new history entry
6. Opened and closed some elements and saved - these elements got a new history entry.

![image](https://user-images.githubusercontent.com/3243119/83881522-17aabe00-a741-11ea-9b94-97824c251ec1.png)

Assumption:
Touched Elements will create a new history item, regardless of something changed or not.

I am not sure how to handle this on Bootstrap Package site, seems to be related to how the data handler in core handles history entries.
