### ISSUE TITLE
Concerning cleanup: is main.js a library?

### ISSUE THREAD

**Issue by rowild** [benjaminkott/bootstrap_package#90]
In EXT:bootstrap_package/Configuration/TypoScript/setup.ts, around line 409, where the Javascript footer libaries are included, I wonder, if main.js should really be listed there. According to my understanding, it would be a regular js-inclusion done with includeJSFooter. This would also reflect the folder structure.

**Comment by benjaminkott** [comment]
Solved in:
https://github.com/benjaminkott/bootstrap_package/commit/305139fc07461e754eb0691594a3ca7d2dfd81d2
https://github.com/benjaminkott/bootstrap_package/commit/f0bee9461ff57be924aa2886412481ed6ec75d28
