### ISSUE TITLE
Images in RTE

### ISSUE THREAD

**Issue by yurigoul** [benjaminkott/bootstrap_package#902]
At the moment I am trying to bring the ability to work with images in RTE using the rte_ckeditor_image plugin and it is not working - under typo3 9.5 at least even after turning off the boostrap RTE in the bootstrap_package settings. But I just found out that this might be by design: https://github.com/benjaminkott/bootstrap_package/issues/315#issuecomment-347880062_

I do not understand why a CMS should only have the option to place images separate from the text - to me this seems to be not editor friendly at all - for instance when working on larger journalistic pieces. 

So please tell me why and please tell me what the alternative is?

**Comment by gilbertsoft** [comment]
@yurigoul  Check the Text & Image content element instead. By placing images into RTE you will loose all configuration options for images.

**Comment by yurigoul** [comment]
I know that that exists, but text and images are separated from one another. One has to publish multiple text and images blocks on one page to mix text and images like in a magazine article. 

This is exactly what is not working for me as an editor.  The workflow and usabilty is terrible because one has to go back and forth constantly between one text block and the next when editing.

**Comment by yurigoul** [comment]
And I'll ad one to it: since the CSS Zen Garden and more modern HTML, the content of a webpage and layout are more and more seen as different aspects. The first aspect is that for instance a news article is constructed as a meaningful text in HTML using headers and paragraphs and other HTML elements as part of the text - including images at the right place in the text. 

This is then displayed to the user with aid of css so it will be adapted for their device. 

The text and images content element does not offer the possibility to use images as part of a text.

**Comment by gilbertsoft** [comment]
Then I guess the best would be to write new content element which fits your requirements or change the RTE's behavior...

**Comment by yurigoul** [comment]
See the first paragraph on this thread: 

> At the moment I am trying to bring the ability to work with images in RTE using the rte_ckeditor_image plugin and it is not working

Since not everybody can be programmer I have to rely on plugins - and this plugin is not working under the boot_strap package. If you have insight to share how this can be activated under the boostrap_package, please share and I will be grateful :-)

**Comment by gilbertsoft** [comment]
Sorry, RTE is not my specialty. I guess I saw you today at Slack, I would recommend you ask in #typo-cms or #random. I'm sure somebody is able to help here....

**Comment by prdt3e** [comment]
This is not a "boostrap_package" problem. Continued here: https://github.com/netresearch/t3x-rte_ckeditor_image/issues/87

**Comment by yurigoul** [comment]
I have now solved the issue - [see here](https://github.com/netresearch/t3x-rte_ckeditor_image/issues/87#issuecomment-647991910).

Sorry for implying it was a bootstrap_package issue - but my main point is still that it is strange one can not work with images in an RTE anno 2020. I can not understand it.

**Comment by gilbertsoft** [comment]
I'm closing this issue now, we will not add support for images in RTE as this is not the recommended way to handle images.
