### ISSUE TITLE
bootstrap element menu thumbnail view of subpages

### ISSUE THREAD

**Issue by deobokl** [benjaminkott/bootstrap_package#903]
# Support
since last update to version TYPO3 10.4.3 this menu type doesnt work anymore
## Description
You can choose menu type thumbnail view of the subpages but no menu will be generated
Other menu types as example cards of subpages works.
## Screenshots
page is empty – screenshot doesnt make sense ;)

**Comment by deobokl** [comment]
any idea someone?

**Comment by olivermeckel** [comment]
Have you added a thumbnail for each page in the page settings?
Pages without images  are not shown because of a condition in the template.

**Comment by deobokl** [comment]
Hi, yes for sure  – it was running perfectly under TYPO3 7.6 
<img width="705" alt="Bildschirmfoto 2020-06-26 um 17 59 43" src="https://user-images.githubusercontent.com/24987486/85877031-d5701c00-b7d6-11ea-92aa-444dc3e42fd5.png">

**Comment by olivermeckel** [comment]
there is a new field for thumbnails (references.fieldName = thumbnail)

<img width="1100" alt="Bildschirmfoto 2020-06-26 um 18 01 39" src="https://user-images.githubusercontent.com/9928953/85877376-57604500-b7d7-11ea-83b6-ee6af99851ac.png">

**Comment by deobokl** [comment]
ok didn't know that – thanks!

**Comment by deobokl** [comment]
just tried it – now a menu is beeing generated, but without image...

**Comment by deobokl** [comment]
on another installation a menu is being generated with thumbnails – it works. okay thanks.
