### ISSUE TITLE
Tables: table-condensed should be table-sm

### ISSUE THREAD

**Issue by osahner** [benjaminkott/bootstrap_package#907]
# Bug Report

## Prerequisites

* [ ] Can you reproduce the problem on TYPO3 v8.7 LTS
* [x] Can you reproduce the problem on TYPO3 v9.5 LTS
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package)
  to see if your bug or enhancement is already reported?

## Description

.table-condensed is .table-sm in Bootstrap 4

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior

[What you expected to happen]

### Actual behavior

[What actually happened]

### Screenshots

[If applicable, add screenshots to help explain your problem.]

## Versions

You can get this information from executing `composer show` at the command line
if your TYPO3 installation is composer based, otherwise the version number will
be shown in the extension manager.

**Comment by gilbertsoft** [comment]
Hi @osahner, thanks for reporting. I searched the sources for occurences of `table-condensed` but the only places I can find it was in BP3 less files with one exception, also in the RTE configuration see https://github.com/benjaminkott/bootstrap_package/blob/master/Configuration/RTE/Default.yaml#L28. Are you talking perhaps about this one?

**Comment by gilbertsoft** [comment]
See https://getbootstrap.com/docs/4.5/migration/#tables

**Comment by osahner** [comment]
Hi @gilbertsoft - faster than the speed of light! 😄 
In the Table content element there ist the option Appearance > Table style > "Condensed table" which adds .table-condensed to the .table div. Smallest possible fix (which I did) is to add 
```scss
.table-condensed {
  th,
  td {
    padding: $table-cell-padding-sm;
  }
}
```

**Comment by gilbertsoft** [comment]
Thanks, got it! Will think about a solution...

**Comment by gilbertsoft** [comment]
@osahner please have a look at my PR, this should solve your issue. It's similar to your approach. Once we remove Bootstrap 3.x support I will rename the setting in the CE to `sm` but we still need to keep compatibility to 3.x at the moment.
