### ISSUE TITLE
FE missing images 

### ISSUE THREAD

**Issue by gilas1959** [benjaminkott/bootstrap_package#91]
Hi there is many issues about the imaged not displayd into the FE.
I have put some galleries in many pages and noticed that some images are not displayed correctly, ie:

this is the title of the first gallery
IMAGE1 IMAGE2 IMAGE3 

this is the title of the 2nd gallery
box-without-any-image box-without-any-image box-without-any-image

and so on. Often one page do not displays any image.

Inspecting the HTML (Mozilla) I discovered that the tag <img is not displayed (code inspector: appears in light gray); for unknown reasons in the same page one gallery is displayed the other not.

I unistalled all +ext that can interfere with js (perfectlightbox, etc.) the result doesn't changes.

However to solve (temporarily) I put this code with web > Template:

tt_content.image.20.1 {
    layout {
        bootstrappackage {
            element (
                < 
![ctype_textwimages](https://cloud.githubusercontent.com/assets/6662802/4979445/13e8e50a-68f7-11e4-9946-fb0c546c69ec.jpg)
img src="###SRC###" class="lazyload"  ###SOURCECOLLECTION######PARAMS######ALTPARAMS######SELFCLOSINGTAGSLASH###>
                <noscript>
                    <img  src="###SRC###" />
                </noscript> 
            )
      }
}

forcing IMG src="###SRC###" the cType Text w/Images displays correctly any gallery.

Please investigate, this is very annoying and maybe the solution implemented it is not right.

The problem is *always* reproducible - TYPO3 v.6.2.6 - no js errors displayed.

thank you

ALEX

**Comment by benjaminkott** [comment]
@gilas1959 big sorry for delay, responsive images were refactored now - if the issue still exist please open again.
