### ISSUE TITLE
Question: SCSS not compiling

### ISSUE THREAD

**Issue by KirstenKK** [benjaminkott/bootstrap_package#915]
I set up a new project with Typo3 10.4.6 and bootstrap-package 11.0.2. As I understand it the bootstrap-package has an integrated SASS compiler, which should be working as soon as I edit and save an existing SCSS file in the Resources folder of the bootstrap-package and then click view in the backend. Is this assumption correct?

The compilation process is not started though. What am I missing?

I changed the Typo3_context to 'Development' to no avail. I'm on Windows and have given all users all rights to the files.

Sorry for the newbie question, but I've googled and cannot find any hint where to look. Thanks for your help!

**Comment by gilbertsoft** [comment]
First of all, never edit files of an extension, your changes will be lost on the next update!

The right place to provide your own settings is the Sitepackage. Please head to https://www.sitepackagebuilder.com/new/ and create your unique Sitepackage for your project. The current Bootstrap Package release has some restrictions regarding Sitepackages and local path repositories, so you better use the 11.0.x-dev branch which will be the next release. You can also find some more details how to include it with Composer https://quick-start.web02.opsone.core.gilbertsoft.net/QuickStart/Preparation/Sitepackage.html

And of course the complete guide is interesting for your how to setup a new project correctly https://quick-start.web02.opsone.core.gilbertsoft.net/QuickStart/Preparation/ProjectFolder.html. The guide is not finished yet but should help you anyway.

**Comment by KirstenKK** [comment]
Thanks for the quick response. Actually I wasn't going to do changes in the extension but create my own custom extension. I just thought to test the compilation this way, but you're right, that was the wrong way to go anyway. 

I now see that the SASS compiler kicks in on including a SCSS file in my extension. I'll take it from there.

By the way, I spent a few hours setting up ddev and the Sitepackage. The docker requires Windows 10 Version 2004 which isn't available on all computers yet. I got it working on my laptop, though.

**Comment by gilbertsoft** [comment]
@KirstenKK  AFAIK Docker only requires Win 10 2004 for WSL2 support. As long as you work on the host you should not have any issues with older versions (for profesional editions and higher). WSL2 give a big performance advantage but also changes things a little bit. BTW connect your TYPO3 account with Slack to get great support for DDEV and Docker at #ddev
