### ISSUE TITLE
Wrong RTE Config in many content elements

### ISSUE THREAD

**Issue by schorsch8878** [benjaminkott/bootstrap_package#917]
The Bootstrap Package RTE config doesn't work in the Contentelements delivered by Bootstrap Package e.g: Text with Icon oder Text with Teaser. In the default CE (Text, Text width Media ...  ) it works perfect. 

I use TYPO3 10.5.6 and BP 11.0.2

In 9.5.14 and BP 11.0.2 it works.

Look at my screeenshots.

![Bildschirmfoto 2020-08-05 um 12 08 53](https://user-images.githubusercontent.com/26795388/89413099-84820a80-d728-11ea-9dce-72b4ef1fd456.png)
![Bildschirmfoto 2020-08-05 um 12 08 01](https://user-images.githubusercontent.com/26795388/89413115-86e46480-d728-11ea-8089-f125a55f604c.png)

And no, pagets.disablePageTsRTE is not set ;-)

Thanks

**Comment by gilbertsoft** [comment]
@schorsch8878  Thanks for reporting, this is known and already fixed in the related branches which you should use instead see #889
