### ISSUE TITLE
Tab-Content: styles

### ISSUE THREAD

**Issue by criwe** [benjaminkott/bootstrap_package#918]
Hi,

when using the tab-element, the option for choosing styles (see image below) is not available. 

![Zwischenablage01](https://user-images.githubusercontent.com/7531138/89505004-383ad700-d7c9-11ea-8610-1a8b1d55a267.jpg)

Don´t know if on purpose. But seems a bit inconsistend.
Would be great, if one can set styles in tab-content too.

TYPO3 10.4.6
Bootstrap Package 11.0.2

Best
Christoph

**Comment by gilbertsoft** [comment]
@criwe Thanks for reporting, this is known and already fixed in the related branches which you should use instead see #889 and #917

**Comment by criwe** [comment]
Thanks a lot!
