### ISSUE TITLE
No CSS provided

### ISSUE THREAD

**Issue by prewal** [benjaminkott/bootstrap_package#921]
## Support

I manage a typo3 website of my sports club and want to make an upgrade from version 8 to 9. The upgrade already works and now I tried to change the template to the bootstrap_package. The bootstrap_package was not installed in version 8.
Typo3 9.5.x (php version 7.4) is not installed with the composer and the bootstrap_package was installed with the extension manager.
I deactivated the content styled and fluid styled templates and activate the full bootstrap_package and the content and sass template.
Different templates are assigned to the pages.
If I now show a page, there is no css used. The menus are shown each in one line and if I have a look into the code with the developer tools of firefox, there is no css shown.
Now to my questions:
- Do someone have the same behaviour and solved it?
- Have I to install something (e.g. the sass parser) extra?
- How can I debug, where the problem get started (webhoster, parser, typo3, ...)?

**Comment by gilbertsoft** [comment]
You should have a look at the error logs, seems like your scss files are not compiled at all. Also check the hints in the readme on how to setup see https://github.com/benjaminkott/bootstrap_package#quick-install-guide

**Comment by prewal** [comment]
Yes, I checked the hints and all should be set right.
And yes, as I described, there is no css loaded.
How can i check or test, if the scss compiler works well? And in which log files must I search for any errors?

**Comment by gilbertsoft** [comment]
If the scss compiler fails there should be entries in the backend log module (backend modules are the ones in the left menu in the backend)

![grafik](https://user-images.githubusercontent.com/25326036/91279772-363fb480-e786-11ea-8eac-71b97b80719a.png)

**Comment by gilbertsoft** [comment]
BTW you should create a TYPO3 account and join the community at Slack see https://my.typo3.org/

**Comment by prewal** [comment]
Thank you for your suggestions. I don't get a solution for installing the bootstrap_package without composer. I always have no css.

Now I installed a fresh typo3 with composer, copied my database and files and it's working.
But it's strange form me.
