### ISSUE TITLE
ddev start fails

### ISSUE THREAD

**Issue by prewal** [benjaminkott/bootstrap_package#922]
I'm working on Mac OS X and have installed a working ddev (newest system and newest ddev).
I clone the bootstrap_package, jumpe into the directory and do a 'ddev start'.
```Starting bootstrap-package... 
Building ddev-ssh-agent 
Recreating ddev-ssh-agent ... done
 
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys. 
Pushed mkcert rootca certs to ddev-global-cache 
Building db 
Building web 
Creating ddev-bootstrap-package-db ... done
Creating ddev-bootstrap-package-dba ... done
Creating ddev-bootstrap-package-web ... done
 
Creating ddev-router ... done
 
TYPO3 does not seem to have been set up yet, missing LocalConfiguration.php (/Users/typocompany/Documents/bootstrap_package/.build/web/typo3conf/LocalConfiguration.php) 
Generating AdditionalConfiguration.php file for database connection. 
Unable to create settings file '/Users/typocompany/Documents/bootstrap_package/.build/web/typo3conf/LocalConfiguration.php': failed to write TYPO3 AdditionalConfiguration.php file: mkdir /Users/typocompany/Documents/bootstrap_package/.build/web/typo3conf: no such file or directory 
Successfully started bootstrap-package 
Project can be reached at https://bootstrap-package.ddev.site https://127.0.0.1:32769
```
Is there any documentation how to do the setup and especially with typo3 version 9?

**Comment by Lefaux** [comment]
The bootstrap package is not a bootstrap for TYPO3 itself.
The recommended way to do it is to set up a project using composer.
So once ddev has started up, you should do:

* `ddev composer require typo3/minimal`
* `ddev composer require bk2k/bootstrap-package`
* `ddev composer require typo3/cms-tstemplate`
* `ddev composer require typo3/cms-rte-ckeditor`

After that you should be able to call the frontend website and TYPO3s installer should come up.

**Comment by Lefaux** [comment]
Just tested these exact commands for you.
I updated my initial answer (I had one duplicated dependency)

**Comment by gilbertsoft** [comment]
Also have a look at this draft https://quick-start.web02.opsone.core.gilbertsoft.net/QuickStart/Index.html

**Comment by prewal** [comment]
Thank you for your help. That works for me.
