### ISSUE TITLE
Customize site package with included bootstrap_package

### ISSUE THREAD

**Issue by prewal** [benjaminkott/bootstrap_package#923]
I have generated a site package (https://www.sitepackagebuilder.com/) with included bootstrap_package (typo3 v10).
The installation was successful and I see the bootstrap layout in the browser.

Now I want - in a simple case - to override some css settings from the bootstrap_package and in a complexer case to ad a new template with 3 columns and a subnavigation in it.

Is there any description or tutorial where this is described?

**Comment by gilbertsoft** [comment]
Some examples you can find in the wiki see https://github.com/benjaminkott/bootstrap_package/wiki

To change the theme have a look at Resources/Public/Scss, there you find the scss files which you can change and adapt to your needs.

An example to create a new backend layout is also included see Configuration/PageTS/Mod/WebLayout/BackendLayouts/example.txt.

**Comment by prewal** [comment]
Thank you for your hints. I can see the new backend layout and I have to customize it.

But changing css values in the site package don't work for me.

I thought, if I set values in sitepackage/Resources/Public/Scss/Theme/_variables.scss, that it should work for the site. E.g. I set the font-size for h3 to 50px, but nothing happens on the pages.

Also changing/setting values in the file sitepackage/Configuration/TypoScript/constants.typoscript take no effect.
E.g. I set there:
plugin.bootstrap_package.settings.scss {
    primary = #0000ff
    secondary = #013859

    ### header ###
    headings-color = $primary
}
But the color of the headings-color was already taken from the settings in the bootstrap_package.

Any thoughts about this behaviour?

**Comment by Godlike-Productions** [comment]
To modify or overwrite css in the site package, just type the css into /yoursitepackage/Resources/Public/Css/layout.min.css

Make sure that you have in your setup.typoscript file under includeCSS something like

yoursitepackage_layout = EXT:yoursitepackage/Resources/Public/Css/layout.min.css

This will put layout.min.css into your css stack.

For Backend Layout the best resource for implementing is this video - https://www.youtube.com/watch?v=RoHaeo4fq34

I added a couple of comments for naming in the new site package to get it to recognize the layouts.

Hope this helps

**Comment by gilbertsoft** [comment]
Looks like you did not add the static template of your sitepackage to the template record or not at the last position (BTW the bootstrap_package you can remove from the static includes because your sitepackage will import this settings automatically). Click the template backend module on the left and edit the template record. On the tab Include add your sitepackage to the last position.
No need to change something in the TypoScript setup like mentioned by Godlike-Productions. This will create another css which has to be downloaded by the browser.

**Comment by prewal** [comment]
If I don't include any bootstrap_package to the static templates, I get the following error:
`../../../../../bootstrap_package/Resources/Public/Scss/Theme/theme` file not found for @import: typo3conf/ext/tsv_niederviehbach_sitepackage/Resources/Public/Scss/Theme/theme.scss on line 9, at column 1 Call Stack: #0 import typo3conf/ext/tsv_niederviehbach_sitepackage/Resources/Public/Scss/Theme/theme.scss (unknown file) on line 1

BTW, the path ../../../../../bootstrap_package/Resources/Public/Scss/Theme/theme seems to be OK.

**Comment by prewal** [comment]
Yes, thank you. Now it works as expected.
