### ISSUE TITLE
Add icon sets to icon group items

### ISSUE THREAD

**Issue by andreheuer** [benjaminkott/bootstrap_package#924]
# Feature Request

## Is your feature request related to a problem? Please describe
I would like to use glypicons or ionicons sets in "icon groups" for icon group items as I can do for the "Text & Icon" content elements.

## Describe the solution you'd like
It would be great to have a possibility to select also icons from the pre-defined icon sets as for the "Text & Icon" content element.

## Describe alternatives you've considered
An alternative would be to upload the icon sets in specific folders and select icons therefrom. However, this would increase e.g. the use of space and processing as the icons would already be available.

## Additional context
![image](https://user-images.githubusercontent.com/10393020/93721096-e8a04700-fb8d-11ea-89d2-a1115ea00b54.png)

**Comment by benjaminkott** [comment]
All icon selection have been streamlined a while ago. So also text and icon use the selectors now.
You can register your own icon sets and they will be offered as set to pick from everywhere.

Example:
https://github.com/benjaminkott/ext-iconset-bootstrap/tree/main
