### ISSUE TITLE
Navbar underline color

### ISSUE THREAD

**Issue by eMPai-git** [benjaminkott/bootstrap_package#933]
# Feature Request

## Is your feature request related to a problem? Please describe

I needed a bit more flexibility coloring the navbar. I wanted both, the navbar background- and the `§primary` color to be the same. So I gave both `$dark` and `$primary` the same color value. Unfortunately the underlined `hover` or `active` state of the navbar items uses `$primary` too and is not visible with this configuration.

After a deep dive into many things I didn't know anything about I came up with this solution:

1. introduced a new variable `$navbar-underline` in the file `_variables.scss` of the Sitepackage
2. created the file `_navbar.scss` with the following content

```
.navbar-mainnavigation {
    .navbar-nav > li {
        > .nav-link:before {
            background: $navbar-underline;
        }
    }
}
```
3. imported the `_navbar.scss` in `theme.scss` of the Sitepackage

## Describe the solution you'd like

I'd like to have a variable, e.g. `$navbar-underline` like described above. The default value could be `$primary` as it is now.

## Describe alternatives you've considered

I considered changing the colors. But using a dark navbar background and a light `$primary` color gave me low contrast between other elements and the white `$body-bg`.

## Additional context

Another style without a variable using `$primary`:

* `.form-element-mandatory`

**Comment by gilbertsoft** [comment]
Thanks for your suggestion. I'm not sure if we really should introduce it because as you said you are able to solve this with some lines in your Sitepackage and imho that's the most important and sufficient.

**Comment by eMPai-git** [comment]
Thanks for your reply. Feel free to close this issue if it isn't important. If my steps described above are correct, I'm fine.
Part of my Feature Request was to contribute to this awesome project by publishing a possible solution for others to find.

**Comment by gilbertsoft** [comment]
Maybe you create a Wiki page about this or add it to an existing one see https://github.com/benjaminkott/bootstrap_package/wiki

And yes, what you describe is the way to go!

**Comment by eMPai-git** [comment]
Closing this issue because it is solved for me.
