### ISSUE TITLE
Unable to render Extbase plugin as CType content (PLUGIN_TYPE_CONTENT_ELEMENT)

### ISSUE THREAD

**Issue by Moongazer** [benjaminkott/bootstrap_package#938]
I've defined an extbase plugin as `PLUGIN_TYPE_CONTENT_ELEMENT`, which I can successfully select and place on pages in the backend. But its content is never shown in the frontend (except a header if I give it one), the CE body is empty and the controller-action is never called.

In TYPO3 sites running without `bootstrap_package` I define the custom content-element as `userFunc` with vendorName, pluginName etc. which works great (e.g. for JSON output), but with `bootstrap_package` this seems not to work.

## Setup to reproduce:

```
// ext_localconf.php
(function($extKey): void {
    \TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin(
        $extKey,
        'PluginTest',
        [\MyVendor\MyExt\Controller\PluginTestController::class => 'show'],
        [],
        \TYPO3\CMS\Extbase\Utility\ExtensionUtility::PLUGIN_TYPE_CONTENT_ELEMENT
    );
})('my_ext');
```

```
// TCA/Overrides/tt_content_plugintest.php
\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addTcaSelectItem(
    'tt_content',
    'CType',
    [
        'My Content-Plugin Test',
        'myext_plugintest',
        'myext-content-plugintest'
    ]
);
```

```
// page TS definition
mod.wizards.newContentElement.wizardItems.myvendor {
    elements {
        myext_plugintest {
            iconIdentifier = myext-content-plugintest
            title = My Content-Plugin Test
            description = My Content-Plugin Test Description
            tt_content_defValues {
                CType = myext_plugintest
                header = My Content-Plugin Test
            }
            saveAndClose = true
        }
    }
    show := addToList(myext_plugintest)
}
```

```
// TypoScript definition
tt_content.myext_plugintest >
tt_content.myext_plugintest =< lib.contentElement
tt_content.myext_plugintest {
    templateName = PluginTest
# Does something like this has to go somewhere?
#    1234 = USER
#    1234 {
#        userFunc = TYPO3\CMS\Extbase\Core\Bootstrap->run
#        vendorName = MyVendor
#        extensionName = MyExt
#        pluginName = PluginTest
#    }
}

```

As soon as I register the plugin as "typical" `list` Extbase plugin (removing `PLUGIN_TYPE_CONTENT_ELEMENT` and registering it with `ExtensionUtility::registerPlugin(...)`) the controller-action is called and everything works fine.

## System:
TYPO3: v10.4.9
PHP: 7.2
Server: Apache2

**Comment by gilbertsoft** [comment]
The problem here seems to be your TypoScript definition which should not be needed at all, it's done by configurePlugin. Perhaps you like to define `templateName` but the rest you should not alter normally. Also see https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/extbase/Classes/Utility/ExtensionUtility.php#L128-L140.
The main problem in your TypoScript is the first line `tt_content.myext_plugintest >` which will delete the definition made by configurePlugin before.

**Comment by Moongazer** [comment]
> The main problem in your TypoScript is the first line `tt_content.myext_plugintest >` which will delete the definition made by configurePlugin before.

You're right - damn such a waste of time again. I check everything 3 times before I open a bug-report, but this I've totally overseen (must have been a copy-paste mistake looking at the other CE definitions). Thanks for pointing it out and sorry for opening the issue -.-

**Comment by gilbertsoft** [comment]
Looks like an old code example before configurePlugin was introduced.
