### ISSUE TITLE
Wrong Line Numbers in SCSS Source Maps

### ISSUE THREAD

**Issue by cm-andrews** [benjaminkott/bootstrap_package#939]
# Bug Report

## Description

SCSS Source Maps present wrong line numbers to browsers.

## Steps to Reproduce

1. install typo3-base-distribution (composer)
2. install bootstrap package (composer)
3. install bootstrap-based sitepackage from sitepackagebuilder
4. enable source maps in typoscript
5. edit sitepackage theme.scss and add some scss rules at the end:

`//
// Variables
//
@import "variables";

//
// Import needed Bootstrap Package Files
//
@import "../../../../../bootstrap_package/Resources/Public/Scss/Theme/theme";

.footer-copyright {
    background-color: green;
}

.footer-copyright {
    background-color: yellow;
}`

### Expected behavior

Browser shows two rules for .footer-copyright in source map, one on line 11 and one on line 15

### Actual behavior

Browser shows both rules on line 15.

### Comments
This is a minimum repro. In a large project with many imports of other files into theme.scss the problem gets worse, with rules even showing in wrong files from time to time. Line numbers are correct if rules are added before importing the bootstrap package default theme. Line numbers in scss files provided by the bootstrap package are also correct it seems.

## Versions

Typo3 10.4 + Latest Bootstrap Package, installed via Composer + basic boostrap sitepackage from sitepackagebuilder.com

**Comment by cm-andrews** [comment]
Any update on this, can anyone repro or suffers from the same issue?

**Comment by benjaminkott** [comment]
source maps are updated in master and v13 - assets are not inlined in sourcemap i thin we can close the issue.
