### ISSUE TITLE
Tag new release?

### ISSUE THREAD

**Issue by pixelbrackets** [benjaminkott/bootstrap_package#940]
# Feature Request

Hey,

is there a roadmap for a new release? 

The last one was tagged in December 2019. The »master« Branch now has _110_ new commits since then.

https://github.com/benjaminkott/bootstrap_package/releases/tag/11.0.2

## Describe the solution you'd like

Tag a new release.

## Describe alternatives you've considered

Use `dev-master` as version constraint.

## Additional context

Thanks for maintaining the package :) :+1: :100:

**Comment by gilbertsoft** [comment]
I can't tell you a exact release date but we are on it.

In the meantime please use the BP_11-0 branch, master is a bad idea as it could contain breaking changes.

**Comment by SchoolGuy** [comment]
Any update on this one? The demo is showcasing the Gallery Content element and as far as I understand, this is not in a release yet. It cost me 2h to actually understand that my instance is not missing something but there is no release with this content element yet.

**Comment by sgrossberndt** [comment]
The last release was more than a year ago now [on 13 Dec 2019](https://github.com/benjaminkott/bootstrap_package/releases/tag/11.0.2)
It would be nice to finally get those pesky SQL error messages on PosgreSQL out of the way in a official release. Those were fixed back [in March 2020](https://github.com/benjaminkott/bootstrap_package/commit/c9928e34cb900029dfbce5dbcf5d2052020cbb01) ..

Please release! :-)

**Comment by sgrossberndt** [comment]
As https://github.com/benjaminkott/bootstrap_package/releases/tag/11.0.3 has finally been released this issue can be closed. Thanks! 🎉
