### ISSUE TITLE
language uid in class in body not shown

### ISSUE THREAD

**Issue by pixelina** [benjaminkott/bootstrap_package#942]
# Bug Report

## Prerequisites

* [x] Can you reproduce the problem on TYPO3 v10.4 LTS

* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package)
  to see if your bug or enhancement is already reported?

## Description

classname for language in body is not shown, because of a bug in PageClass.typoscript

PageClass.typoscript, line 21:
 // Language
    30 = TEXT
    30 {
        data = TSFE:sys_language_uid
        noTrimWrap = | language-||
    }

correct is: 

 // Language
    30 = TEXT
    30 {
        data = sitelanguage:languageId
        noTrimWrap = | language-||
    }

## Steps to Reproduce

1. create different languages for a page
2. check HTML code, you can see the class "language-" without any id in the body tag

### Expected behavior

The class should be rendered with id "language-0" or "language-1"

### Actual behavior

The class is rendered without any id => "language-"

### Screenshots

![screenshot_language](https://user-images.githubusercontent.com/47669331/97316718-5b29d400-186a-11eb-8f7c-e4705c0b995e.JPG)

## Versions

11.0.2
--

**Comment by gilbertsoft** [comment]
Thank you for your report. This issue is already known and fixed with the linked PR. You can use the branch BP_11-0 until the next release.
