### ISSUE TITLE
Path issues with scssphp 1.4

### ISSUE THREAD

**Issue by JohnNDK** [benjaminkott/bootstrap_package#947]
After updating scssphp package to 1.4, scss paths doesn't work correctly. Custom scss path from sitepackage typescript causes fatal errors.
Possible because of symlinks, haven't tested without symlink to public folder.

Same issue with 11.0.3 dev branch.

Not sure if this is a bug with scssphp compiler or bootstrap_package path detection.

Downgrading to scssphp 1.3 resolves the issues.

Apologies for the lack of details, currently very busy so figured it was more important to get the bug reported.

**Comment by gilbertsoft** [comment]
Thanks for reporting. I can confirm that behavior, our unit and funtional tests are failing here too.

**Comment by gilbertsoft** [comment]
Looks like this change https://github.com/scssphp/scssphp/commit/e525b857a7487ee8a14b452e5addbdb4c69a390f is breaking.

**Comment by gilbertsoft** [comment]
Can confirm that the change https://github.com/scssphp/scssphp/pull/244 is highly breaking.

**Comment by gilbertsoft** [comment]
@JohnNDK please check my fix in the linked PR

**Comment by JohnNDK** [comment]
@gilbertsoft Fix works on 11.0.2 with scssphp/scssphp 1.4.0
