### ISSUE TITLE
Maintain page layout image variants in structure elements

### ISSUE THREAD

**Issue by buepro** [benjaminkott/bootstrap_package#956]
# Feature Request

## Current situation

When using content elements with images inside a structure element (e.g. container, gridelements, flux) the image sizes fall back to default hence images are rendered too big.

This is due to the fact that the `colPos` value from content elements beeing used within structure elements doesn't necessarily refer to the page layout `colPos` hence the image variants retrieved aren't correct.

## Describe the solution you'd like

The `colPos` value from the page layout could be obtained by the register which is already set in `lib.dynamicContent`.

**Comment by benjaminkott** [comment]
@buepro we added support for ext:container with the latest release that also handles the size calculation for images.

please check https://github.com/benjaminkott/bootstrap_package/pull/1035 and open the issue again if this does not suit your needs.
