### ISSUE TITLE
Translation of text for screen reader

### ISSUE THREAD

**Issue by SventB** [benjaminkott/bootstrap_package#964]
This is an easy one ;)

The text "current", which is set to the currently opened page in navigations, isn't translated.
Just search for "(current)" to find the occurrences:

`<span class="sr-only">(current)</span>`

**Comment by benjaminkott** [comment]
https://github.com/benjaminkott/bootstrap_package/commit/f9daa32ca576a548dd1aa5f09d6f339c6a4d5504
