### ISSUE TITLE
How to resize the Footer ? - .footer-section-content { height: 110px !important; }

### ISSUE THREAD

**Issue by ds2k5** [benjaminkott/bootstrap_package#965]
Try to resize the footer but will not work.

           .footer-section-content { height: 110px !important; }

What do I wrong ?

```
page {
   ##Remove Line beteen Menu an Content
    cssInline {
        10 = TEXT
        10.value (
           .navbar-mainnavigation { box-shadow: none !important; }
           .navbar-mainnavigation .navbar-brand { height: 191px !important; }
           .frame { padding-top: 2rem !important;  padding-bottom: 2rem !important; }
           # footer
           .footer-section-content { height: 110px !important; }
        )
    }


```

**Comment by gilbertsoft** [comment]
Try to change the CSS with a sitepackage from https://www.sitepackagebuilder.com/ instead.

**Comment by ds2k5** [comment]
no other way possible ?

**Comment by rumpfwerk** [comment]
@ds2k5 
the error in your code is, that for some reasons the CSS-Code in the Browser after 
 # footer 
 is not used or interpreted as selector?
 
it is not an error in the context of the BTP.

**Comment by ds2k5** [comment]
Thanks,
can you tell me how to make it work please ?

**Comment by rumpfwerk** [comment]
Yes, 
delete the line 
`# footer`

This is not CSS. 


.

**Comment by ds2k5** [comment]
thanks I removed the " # " but the height is not changed
