### ISSUE TITLE
Missing buttons in CKEditor and css-classes in link-browser after updating from v9 LTS to v10 LTS

### ISSUE THREAD

**Issue by hsos-kneip** [benjaminkott/bootstrap_package#966]
## Prerequisites
TYPO3 v9.5 LTS: ok
TYPO3 v10.4 LTS: problem

## Description
When upgrading from TYPO3 9 LTS to 10 LTS some buttons in the CKEditor disappear in accordions / card groups / icon groups.
Missing buttons:
- block style
- box
- insert address
![9-Accordion](https://user-images.githubusercontent.com/77110585/103912217-4b026080-5107-11eb-8894-de4d30614480.png)
![10-Accordion](https://user-images.githubusercontent.com/77110585/103912228-4c338d80-5107-11eb-9133-d56f45d80a15.png)

Also it is not possible anymore to choose a CSS-class in the link browser.
![9-Link-browser](https://user-images.githubusercontent.com/77110585/103912231-4c338d80-5107-11eb-8411-740b1b6793fa.png)
![10-Link-browser](https://user-images.githubusercontent.com/77110585/103912232-4c338d80-5107-11eb-86f5-e4cca194efe5.png)

In standard text elements it is no problem, all CKEditor buttons and the link-browser classes are visible.
![10-standard-text](https://user-images.githubusercontent.com/77110585/103912234-4ccc2400-5107-11eb-879e-c1b93e58de57.png)

## Steps to Reproduce
I installed two fresh TYPO3 sites (9 and 10 LTS) and downloaded the introduction package (introduction 4.2.0, bootstrap_package 11.0.2).

## Question
How can I activate the missing CKEditor buttons and the link-browser-css-classes in accordions, card groups and icon groups again?

**Comment by rumpfwerk** [comment]
Thanks. This bug is known. Infos about fixing are found here.
https://github.com/benjaminkott/bootstrap_package/issues/889

Hope, it helps

**Comment by hsos-kneip** [comment]
Thanks @rumpfwerk!

**Comment by gilbertsoft** [comment]
Should be fixed now.
