### ISSUE TITLE
Navbar not loading all navbar-items

### ISSUE THREAD

**Issue by RhoKappa** [benjaminkott/bootstrap_package#968]
# Navbar not loading all navbar-items

## Prerequisites

* [ ] I had the same behaviour in an earlier (test) installation with Version 8.7
* [ ] same behaviour with version v9.5
* [ ] so far, I did not not find a bug report for this behaviour on github

## Description
The navbar-item "Home" is not being loaded on pages <> Home as well as the main logo AND the inverted logo are both loaded/displayed (instead of just one).
I tested all kind of settings in the template constants (especially "Bootstrap Package: Navigation" & "Logo"); however, without success.

## Steps to Reproduce

1. show the root page (home) in preview mode, check main navigation on top
2. show any other page in preview mode, check main navigation on top

### Expected behavior

An the root page (home) and especially on all other pages, the navbar-item "home" should be visible/selectable.
On all pages, the menu bar should display just one logo, either the normal logo or the inverted logo, but not both.

### Actual behavior

On the "Home" page, all navbar-items are loaded, but once another page is selected, "home" is missing in the navbar-items.
Furthermore, when any other page than "home" is selected/active, both the logo AND the inverted logo are both loaded/displayed (instead of just one).

## Versions
Typo3	9.5.24
Introduction Package 4.0.1
Bootstrap Package 10.0.9
using Firefox 85.0

**Comment by gilbertsoft** [comment]
I've checked the default behavior of ext:introduction using my demo https://github.com/GsTYPO3/typo3-introduction#typo3-cms-introduction-package-with-ddev-local and it works just fine.

So it's most probably related to a change you did. Without more information about your changes I'm not able to say more at the moment.

**Comment by RhoKappa** [comment]
Hi gilbertsoft,
thanks for checking. Attached is how my navbar looks on pages other than Home.
![T3_navbar_bug_01](https://user-images.githubusercontent.com/78322431/106506400-f4036780-64c9-11eb-849a-2cdd3023077b.JPG)
![T3_navbar_bug_02](https://user-images.githubusercontent.com/78322431/106506412-f82f8500-64c9-11eb-918b-c0a74f10142b.jpg)

Actually, the only steps I did before the error ocured were: installing the bootstrap package, installing the introduction package and the extension "dp_cookieconsent" (10.6.1), i.e. no other changes. But maybe it was caused by the cookieconsent extension. So, I'll try to re-install Typo3 just with the Bootstrap and Introduction Package. Let's see.

**Comment by rumpfwerk** [comment]
Hello RhoKappa, I think you do not to have to reinstall things. 
Just deinstall the cookie-Extension and clear all caches (for security, that this is done).

**Comment by RhoKappa** [comment]
Hello rumpfwerk & thanks for the tip.
I first deactivated "dp_cookieconsent" and then removed it, unfortunately with no effect, even after flushing all Typo 3 & PHP caches. Then I also cleared persistent database tables, again with no effect.
I guess re-installing v. 9.5 will also not help, since with the previous v. 8.7 I had the same issue.
I will upgrade my PHP version (7.2 > 7.4), re-install Typo3, Bootstrap and Introduction package and then we'll see what happens. Otherwise I'll probably have to learn Fluid and adapt the template (..\bootstrap_package\Resources\Private\Partials\Page\Navigation\main.html)...

**Comment by rumpfwerk** [comment]
Hello RhoKappa, 
I do not think, that it depends on the PHP-Version 
https://typo3.org/cms/roadmap

Learning Fluid is always a goog thing ;-), but the Bootstrap-Package should work "out of the box". 
I am only guessing: BTP has an integrated SASS-Compiler, that produces the css. 
It looks for me, that the error is related to css (and the inverted logo covers the home-button)
perhaps missing write-conditions somewhere

**Comment by RhoKappa** [comment]
OK, thanks. I've got a solution now without learning Fluid ;-)
I installed Typo3 10.4.11 with Bootstrap Package 11.0.2 and Introduction Package 4.2.0
Now it works :-)

**Comment by gilbertsoft** [comment]
This issue is related to CSS most probably. So it looks like you somehow have messed up your SCSS files. It's also very important if you are in composer mode or not. The SCSS compiler has some issues in composer mode and with a sitepackage.

**Comment by RhoKappa** [comment]
Hm, actually I did not touch the CSS itself, but maybe the template editor does not fill the CSS in the right way or sequence. I don't know whether I am in composer mode or not: how do I see or change that?

And unfortunately I was pleased too quickly after I installed Typo3 10.4.11 with Bootstrap Package 11.0.2 and Introduction Package 4.2.0: the error now occured again and I am not able to correct it. At least I can reproduce the error now
-  after the installaton (& changing the language to German)
  > navbar and logo are working fine
  
- then I installed an own (Google) font
  > navbar and logo are still working
  
- then I replaced the standard logo and the inverted logo with my own logo(s) in the same location via the Template constant editor; I used SVG files in the same size as the original logos: 68/244 pixels (and also tried with 68/68 pixels)
  > then the beaviour as described above occurred again, i.e. the navbar-item "home" is not visible on pages <> "home" and both logos are visible in the header as opposed to just one
  
- I reverted to the old settings, i.e. I changed the "Logo" and "Logo Inverted" back to the standard logos (introduction-package.svg; introduction-package-inverted.svg)
  > however, the same behaviour/error now occurs/stays although I changed back the settings that lead to the error

I am stuck now :-(
Any idea how the CSS is created correctly from the Template constants as in the pristine bootstrap/ introduction package?

**Comment by RhoKappa** [comment]
Checking the site with the Code Inspector, I found that this time the navbar is OK on the HOME page as well as on the FEATURES page and the CONTENT EXAMPLES pages, but not on the CUSTOMIZE page and the PAGES page.
It may also be an error in the fluid template, not (just) in the CSS (?). Last time the navbar error occured on all pages apart from HOME. Please see the code inspector screenshops from the
HOME page:
![Home](https://user-images.githubusercontent.com/78322431/107154513-995b8700-6973-11eb-8bd5-3fb7b18fd419.JPG)
FEATURES page:
![Features](https://user-images.githubusercontent.com/78322431/107154524-b09a7480-6973-11eb-9c2d-1dca15765b55.jpg)
CUSTOMIZE page (with error: not HOME page link):
![Customize](https://user-images.githubusercontent.com/78322431/107154542-c0b25400-6973-11eb-9400-de697930a03b.jpg)

**Comment by RhoKappa** [comment]
OK, flushing all Typo3 & PHP caches several (!) times lead to the desired behaviour - navbar loads properly now! :-)
Still, rendering the final page with navbar etc. seems to be quite erratic. Anyway, for the time being, I can cope with the result.
Thanks for your help!

**Comment by rumpfwerk** [comment]
@RhoKappa Do not know, if it causing you problems, but I hat some probs with the constant (BTP-config) 
[config.sendCacheHeaders]

It controls via http-header the caching behaviour of the browser and this feature under some circumstances causes old sites (from browser-cache) in your browser (refreshing is without "hard" refresh)
Thanks for the detailed sharing of your issues.
