### ISSUE TITLE
DB Export from https://www.bootstrap-package.com/

### ISSUE THREAD

**Issue by wow-solution** [benjaminkott/bootstrap_package#975]
Hi!

Is it possible to get a DB Export .sql or a TYPO3 Export .xml - .T3D from the following Mainpages with their Subpages and all their content to include them into my distribution for new customer projects and test and show the custom styles with all possible page and content options?

https://www.bootstrap-package.com/pages/
https://www.bootstrap-package.com/content-examples

Best regards

Wolfgang

**Comment by gilbertsoft** [comment]
See https://github.com/FriendsOfTYPO3/introduction.
