### ISSUE TITLE
Gallery Content Element is missing

### ISSUE THREAD

**Issue by twurmehl** [benjaminkott/bootstrap_package#986]
# Bug Report

## Prerequisites

* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package)
  to see if your bug or enhancement is already reported?

## Description

I cannot create the CE Gallery (https://www.bootstrap-package.com/content-examples/media/gallery). 
I am using a own sitapckage, created with the sitepackagebuilder. 

## Steps to Reproduce

1. Create New Content Element in TYPO3 BE
2. Navigate to the "Media" Tab

### Expected behavior

Seeing a List of the available Content Elements including "Gallery"

### Actual behavior

Seeing a List of some Content Elements but always without "Gallery"

### Screenshots

![image](https://user-images.githubusercontent.com/56545341/110205136-1137a700-7e77-11eb-917c-1a76201166bb.png)

## Versions

11.0.2

**Comment by mandrasch** [comment]
Stumbled upon this is as well. The demo example has css class "gallery-row", which is also used in "Images only" component.

I guess the demo page just calls it "Gallery", but "Images Only" / "Nur Bilder" is used?

**Comment by twurmehl** [comment]
> Stumbled upon this is as well. The demo example has css class "gallery-row", which is also used in "Images only" component.
> 
> I guess the demo page just calls it "Gallery", but "Images Only" / "Nur Bilder" is used?

I don't think so. In older versions there was a CE called "Gallery" and also in in the dev version you can find the gallery. 
In the meantime I found a thread on slack with this issue, where @gilbertsoft refers to a bug with the pagination in Typo3. I think, that's why the Gallery CE is temporarily removed. I hope, this will be fixed soon!

**Comment by mandrasch** [comment]
Ah, thanks very much for this information!

**Comment by gilbertsoft** [comment]
@twurmehl the Gallery is part of the 12.x release see https://github.com/benjaminkott/bootstrap_package/releases/tag/12.0.0 and will not be backported at the moment. So I'm going to close this issue.
