### ISSUE TITLE
Unit-Tests execution will end with error and failure

### ISSUE THREAD

**Issue by zenobio93** [benjaminkott/bootstrap_package#988]
# Bug Report

## Prerequisites

* [ ] Can you reproduce the problem on TYPO3 v8.7 LTS
* [ ] Can you reproduce the problem on TYPO3 v9.5 LTS
* [X] Can you reproduce the problem on TYPO3 v10.4 LTS
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package)
  to see if your bug or enhancement is already reported?

## Description

On running the Unit-Tests of bootstrap_packge in one of our TYPO3 Projects, one error and one failure occure:

```
> bin/phpunit web/typo3conf/ext/bootstrap_package/Tests
PHPUnit 9.5.2 by Sebastian Bergmann and contributors.

FE...............................................                 49 / 49 (100%)

Time: 00:00.042, Memory: 10.00 MB

There was 1 error:

1) BK2K\BootstrapPackage\Tests\Unit\Utility\ExternalMediaUtilityTest::getEmbedCode with data set "empty" ('', '', null)
Trying to access array offset on value of type bool

web/typo3conf/ext/bootstrap_package/Classes/Utility/ExternalMediaUtility.php:65
web/typo3conf/ext/bootstrap_package/Classes/Utility/ExternalMediaUtility.php:42
web/typo3conf/ext/bootstrap_package/Tests/Unit/Utility/ExternalMediaUtilityTest.php:29

--

There was 1 failure:

1) BK2K\BootstrapPackage\Tests\Unit\Parser\ScssTest::compile with data set "Calculation" ('Fixtures/Calculation.scss', 'Fixtures/Calculation.css')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
 '.case-without-variable {
-  border-radius: 0.5rem; }
-
+  border-radius: 0.5rem;
+}
 .case-with-variable {
-  border-radius: 0.5rem; }
-
+  border-radius: 0.5rem;
+}
 .case-precalculated-variable {
-  border-radius: 0.25rem; }
-
+  border-radius: 0.25rem;
+}
 button {
   width: 0.5rem;
-  border-radius: 0.5rem; }
+  border-radius: 0.5rem;
+}
 '

web/typo3conf/ext/bootstrap_package/Tests/Unit/Scss/ScssTest.php:31

ERRORS!
Tests: 49, Assertions: 195, Errors: 1, Failures: 1.
```

The error will occure, because `parse_url` return a false while url is empty on line bootstrap_package/Classes/Utility/ExternalMediaUtility.php:64 but it won't be checked and next it will be used as array on line 65.

The failure will occure due other formatted compare output.

## Steps to Reproduce

1. Execute phpunit for extension bootstrap_package.

### Expected behavior

No errors or failures occure on execute Unit-Tests.

### Actual behavior

One error and one failure occure

## Versions

* 11.0.2

**Comment by gilbertsoft** [comment]
Please check with the branch instead, this should be fixed IIRC.

**Comment by gilbertsoft** [comment]
I'm going to close this issue now as there is no answer.
