### ISSUE TITLE
"bk2k/bootstrap-package", does not define extension key in composer.json

### ISSUE THREAD

**Issue by kludikovsky** [benjaminkott/bootstrap_package#990]
# Bug Report

## Prerequisites

* [ ] Can you reproduce the problem on TYPO3 v8.7 LTS
* [ ] Can you reproduce the problem on TYPO3 v9.5 LTS
* [Y ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Abenjaminkott+repo%3Abenjaminkott%2Fbootstrap_package)
  to see if your bug or enhancement is already reported?

## Description

When executing `ddev composer install` or `ddev composer update` the following warding pop's up.

```
TYPO3 Extension Package "bk2k/bootstrap-package", does not define extension key in composer.json.
Specifying the extension key will be mandatory in future versions of TYPO3 (see: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ComposerJson/Index.html#extra)
```

## Steps to Reproduce

1. `ddev composer install`

### Expected behavior

Not this warning.

###  Actual Behaviour
'ddev composer install'
TYPO3 Extension Package "bk2k/bootstrap-package", does not define extension key in composer.json.
Specifying the extension key will be mandatory in future versions of TYPO3 (see: https://docs.typo3.org/                                m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ComposerJson/Index.html#extra)
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting ou                                tdated dependencies. It is recommended that you run `composer update` or `composer update <package name>                                `.
Nothing to install or update

[If applicable, add screenshots to help explain your problem.]

![image](https://user-images.githubusercontent.com/6077916/110949519-fb2c5980-8342-11eb-87b8-3f7d6c1c26bf.png)

## bk2k/bootstrap-package                     11.0.2

You can get this information from executing `composer show` at the command line
if your TYPO3 installation is composer based, otherwise the version number will
be shown in the extension manager.

**Comment by gilbertsoft** [comment]
Thanks for your report. This issue was already addressed with the PR #874 and will be part of the next release.
