### ISSUE TITLE
Add Bootstrap form validation Javascript

### ISSUE THREAD

**Issue by ste101** [benjaminkott/bootstrap_package#992]
I tried to use the bootstrap form validation and found out that the 'activiation code' is not included.

Is there a reason why?
If no please include this script:
```https://github.com/twbs/bootstrap/blob/v4.6.0/site/content/docs/4.6/examples/checkout/form-validation.js```

**Comment by Kephson** [comment]
It is super easy for you to use a custom site package and extend the site with the scripts you need.
If you're not using a site package have a look at https://sitepackagebuilder.com/ and build your own.
Then you can extend the configuration with the scripts and styles you need.

**Comment by ste101** [comment]
I did it like that but why not including it?

**Comment by Kephson** [comment]
Because I think there are a lot of form extensions with their own validation. By default you should include as few as possible scripts by default.

**Comment by ste101** [comment]
> 
> 
> And TYPO3 provides it own validators in the ext:form.

I couldn't find a client side validation for EXT:form. Any hints?
