### ISSUE TITLE
how to add multiple additional background colours?

### ISSUE THREAD

**Issue by chris299** [benjaminkott/bootstrap_package#999]
# Support

## Description

the instructions in https://github.com/benjaminkott/bootstrap_package/wiki/Add-additional-Background-Colors-to-Content-Elements
work fine for one additional colour (allthough it seems I olny need the PageTsConfig and TypoScript Constants) 

however, with more than one color I'm not able to make it work.

the code I tried:

```
TCEFORM {
    tt_content {
        background_color_class {
            addItems {
                red = Red
                white = White
                hblau = Herth-Blau
            }
        }
    }
}
```

and 

```
plugin.bootstrap_package.settings.scss {
    frame-backgrounds = ( hblau:(background: #0092d0, link-color: #e0efff, link-hover-color: #ffffff),
                          white:(background: #ffffff, link-color: #e0efff, link-hover-color: #ffffff),
                          red:(background: #ff0000, link-color: #ffeeee, link-hover-color: #ffffff)
     )
}
```

The PageTsConfig part actually seems to work, as I can see all three new options in the typo3 backend content element editor, but the css part does not...

What am I doing wrong here?

**Comment by gilbertsoft** [comment]
Did you clear all caches?

**Comment by chris299** [comment]
thanks for your help. the line break was the problem. now it works.
